### PR TITLE
ODSP: Sharing link redemption fall back during trees/latest call

### LINKED ISSUE #5994: ODSP: Sharing link redemption need to have fall back
Today, when we call TreesLatest, we support workflow where sharing link is provided such that ODSP could redeem it and return TreesLatest in one call.
Due to some issues, redeem portion of the process could fail and return 403, if person A who opened a document never opened any sharing link shared by user B who produced that link.
The ask is for 403 to always try old flow to redeem link ourselves and follow up with TreesLatest.
Once pair of B -> A sharing (of any document) happens, any future redeeming (including different documents) would work through existing single call mechanism.

We are following up if this is considered GA blocking and needs to be ported into 0.39

### PR DESCRIPTION
**Pull request by jatgarg**
Fixes: https://github.com/microsoft/FluidFramework/issues/5994
Sometimes the redemption within the trees/latest call fails due to some bug on server side. So we need to have a fallback where we do a redeem separately and then make the trees latest call.

I tested the redeem call by generating a share link in bohemia and then use the postman to make the redeem call.

### CODE REVIEW

File: packages/drivers/odsp-driver/src/fetchSnapshot.ts [hunk 1]
```diff
@@ -58,13 +64,71 @@ export async function fetchSnapshot(
...
 }
 
+export async function redeemSharingLink(
+    odspResolvedUrl: IOdspResolvedUrl,
+    storageTokenFetcher: (options: TokenFetchOptions, name: string) => Promise<string | null>,
+) {
+    await getWithRetryForTokenRefresh(async (tokenFetchOptions) => {
+        assert(odspResolvedUrl.sharingLinkToRedeem !== undefined, "Share link should be present");
+        const storageToken = await storageTokenFetcher(tokenFetchOptions, "TreesLatest");
+        const shareId = encodeShareUrl(odspResolvedUrl.sharingLinkToRedeem);
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/fetchSnapshot.ts:74]: if we are getting ID, then should API be called getEncodeShareId?

File: packages/drivers/odsp-driver/src/fetchSnapshot.ts [hunk 2]
```diff
@@ -58,13 +64,71 @@ export async function fetchSnapshot(
     );
 }
 
+export async function redeemSharingLink(
+    odspResolvedUrl: IOdspResolvedUrl,
+    storageTokenFetcher: (options: TokenFetchOptions, name: string) => Promise<string | null>,
+) {
+    await getWithRetryForTokenRefresh(async (tokenFetchOptions) => {
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/fetchSnapshot.ts:71]: Are we reporting perf metrics (i.e. wrapping with PerformanceEvent)?

File: packages/drivers/odsp-driver/src/fetchSnapshot.ts [hunk 3]
```diff
@@ -58,13 +64,71 @@ export async function fetchSnapshot(
     );
 }
 
+export async function redeemSharingLink(
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/fetchSnapshot.ts:67]: I think there is no need to export this function as it's used only in this file. Can you please check other places?

File: packages/drivers/odsp-driver/src/fetchSnapshot.ts [hunk 4]
```diff
@@ -58,13 +64,71 @@ export async function fetchSnapshot(
...
+            snapshotOptions,
+            logger,
+            snapshotDownloader,
+            putInCache,
+        );
+    } catch(error) {
+        if (isRedeemSharingLinkError(odspResolvedUrl, error)) {
+            await redeemSharingLink(odspResolvedUrl, storageTokenFetcher);
+            logger.sendErrorEvent({
+                eventName: "TreeLatest_SecondCall",
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/fetchSnapshot.ts:105]: I'd change the name to better reflect the flow ("ReddemFallback" ?), and put it before calling redeemSharingLink

File: packages/drivers/odsp-driver/src/fetchSnapshot.ts [hunk 5]
```diff
@@ -58,13 +64,71 @@ export async function fetchSnapshot(
...
+
+export async function fetchSnapshotWithRedeem(
+    odspResolvedUrl: IOdspResolvedUrl,
+    storageTokenFetcher: (options: TokenFetchOptions, name: string) => Promise<string | null>,
+    snapshotOptions: ISnapshotOptions | undefined,
+    logger: ITelemetryLogger,
+    snapshotDownloader: (url: string, fetchOptions: {[index: string]: any}) => Promise<IOdspResponse<IOdspSnapshot>>,
+    putInCache: (valueWithEpoch: IVersionedValueWithEpoch) => Promise<void>,
+): Promise<ISnapshotCacheValue> {
+    let odspSnapshot: ISnapshotCacheValue;
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/fetchSnapshot.ts:91]: You can remove odspSnapshot variable by simply returning results in-place

File: packages/drivers/odsp-driver/src/fetchSnapshot.ts (hunk 2 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver/src/fetchSnapshot.ts:71]: We can report. So we had a metric which report total time including fallbacks if any and then a metric  which measures just the core trees/latest, For now I can add one, just to measure how much this takes.

File: packages/drivers/odsp-driver/src/fetchSnapshot.ts (hunk 5 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver/src/fetchSnapshot.ts:91]: yeah, just to avoid 2 returns, I did it this way.

File: packages/drivers/odsp-driver/src/fetchSnapshot.ts [hunk 6]
```diff
@@ -58,13 +64,71 @@ export async function fetchSnapshot(
...
+}
+
 export async function fetchLatestSnapshotCore(
     odspResolvedUrl: IOdspResolvedUrl,
     storageTokenFetcher: (options: TokenFetchOptions, name: string) => Promise<string | null>,
     snapshotOptions: ISnapshotOptions | undefined,
     logger: ITelemetryLogger,
     snapshotDownloader: (url: string, fetchOptions: {[index: string]: any}) => Promise<IOdspResponse<IOdspSnapshot>>,
     putInCache: (valueWithEpoch: IVersionedValueWithEpoch) => Promise<void>,
+    redeemShareLinkIfPresent: boolean = true,
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/fetchSnapshot.ts:131]: Maybe redeemSharingLinkFallback?

Comment (vladsud) [inline packages/drivers/odsp-driver/src/fetchSnapshot.ts:131]: I feel like it's better not to add this new argument, but rather in places where redeeming is not needed, make a copy of odspResolvedUrl and clear odspResolvedUrl.sharingLinkToRedeem

Comment (vladsud) [reply packages/drivers/odsp-driver/src/fetchSnapshot.ts:131]: It would also make other flows more coherent, for example if other calls are added in the future to isRedeemSharingLinkError(), it would stay correct (vs. today it's possible that odspResolvedUrl.sharingLinkToRedeem was not used but we still use it as a pivot)

File: packages/drivers/odsp-driver/src/fetchSnapshot.ts [hunk 7]
```diff
@@ -263,3 +327,62 @@ export function evalBlobsAndTrees(snapshot: IOdspSnapshot) {
     }
     return { numTrees, numBlobs, encodedBlobsSize, decodedBlobsSize };
 }
+
+export function isRedeemSharingLinkError(odspResolvedUrl: IOdspResolvedUrl, error: any) {
+    const errorType = error.errorType;
+    if (odspResolvedUrl.sharingLinkToRedeem !== undefined
+        && (errorType === DriverErrorType.authorizationError
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/fetchSnapshot.ts:334]: Please add a test that typeof error === "object" && error !== null (there is some helper function somewhere)

File: packages/drivers/odsp-driver/src/fetchSnapshot.ts [hunk 8]
```diff
@@ -263,3 +327,62 @@ export function evalBlobsAndTrees(snapshot: IOdspSnapshot) {
...
+        || errorType === DriverErrorType.fileNotFoundOrAccessDeniedError)) {
+        return true;
+    }
+    return false;
+}
+
+function encodeShareUrl(url: string): string | undefined {
+    if (!url) {
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/fetchSnapshot.ts:342]: This needs to be an assert/exception, right?

File: packages/drivers/odsp-driver/src/fetchSnapshot.ts [hunk 9]
```diff
@@ -263,3 +327,62 @@ export function evalBlobsAndTrees(snapshot: IOdspSnapshot) {
...
+      .replace(/=+$/g, "")
+      .replace(/\//g, "_")
+      .replace(/\+/g, "-");
+    encodedUrl = "u!".concat(encodedUrl);
+
+    return encodedUrl;
+}
+
+function b64EncodeUnicode(str: string): string | undefined {
+    if (!str || typeof str !== "string") {
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/fetchSnapshot.ts:365]: same here - we should not test typeof - function signature is enough (otherwise we would need to do it on every line of our code base).

File: packages/drivers/odsp-driver/src/fetchSnapshot.ts [hunk 10]
```diff
@@ -263,3 +327,62 @@ export function evalBlobsAndTrees(snapshot: IOdspSnapshot) {
...
+    if (!url) {
+      return undefined;
+    }
+
+    /**
+     * Encode the url to accepted format by Sharepoint
+     * https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/shares_get
+     */
+    let encodedUrl = b64EncodeUnicode(url);
+    if (!encodedUrl) {
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/fetchSnapshot.ts:351]: I do not see a need to have this check. If you want to have it, convert to assert

File: packages/drivers/odsp-driver/src/fetchSnapshot.ts (hunk 9 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver/src/fetchSnapshot.ts:365]: I missed this. Took this code to get share id from Teams code.

File: packages/drivers/odsp-driver/src/fetchSnapshot.ts [hunk 11]
```diff
@@ -263,3 +327,62 @@ export function evalBlobsAndTrees(snapshot: IOdspSnapshot) {
...
+    if (!str || typeof str !== "string") {
+      return undefined;
+    }
+
+    // first we use encodeURIComponent to get percent-encoded UTF-8,
+    // then we convert the percent encodings into raw bytes which
+    // can be fed into btoa.
+    // Latin characters like # which are also special characters are not encoded.
+    // Hence we manually encode them with encodeHash method - This is a requirement from Vroom APIs
+    return btoa(
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/fetchSnapshot.ts:374]: Can you please describe what this sequence is supposed to do, not how it does it?
How is it different from what fromUtf8ToBase64(encodeURIComponent()) does?
Also you description suggests that # is one of the special characters, but there is only it getting handled.
If this sequence is correct, it would be great to 
- have a reference to some SPO doc describing expectations here.
- inline encodeHash (there is already call to .replace, you can simply chain them, not clear why one of the is a separate function).

File: packages/drivers/odsp-driver/src/fetchSnapshot.ts [hunk 12]
```diff
@@ -263,3 +327,62 @@ export function evalBlobsAndTrees(snapshot: IOdspSnapshot) {
...
+        encodeHash(
+            encodeURIComponent(str).replace(
+                /%([\dA-F]{2})/g,
+                function toSolidBytes(_: unknown, p1) {
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/fetchSnapshot.ts:378]: Use arrow function, no need to given it a name I believe

File: packages/drivers/odsp-driver/src/prefetchLatestSnapshot.ts [hunk 13]
```diff
@@ -80,5 +81,15 @@ export async function prefetchLatestSnapshot(
             assert(cacheP !== undefined, "caching was not performed!");
             await cacheP;
             return true;
-    }).catch((error) => false);
+    }).catch(async (error) => {
+        const errorType = error.errorType;
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/prefetchLatestSnapshot.ts:85]: can we share this code (same code exists in fetchSnapshot) by moving it into fetchSnapshotWithRedeem?
Also, in both places could you please add check for typeof & not null?

File: packages/drivers/odsp-driver/src/fetchSnapshot.ts (hunk 11 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver/src/fetchSnapshot.ts:374]: Removed this entire code and replaced it with much simpler. I was trying to use this "fromUtf8ToBase64(encodeURIComponent())" but was not able to get the correctly encoded one. Digging into it more I got it correct with using encodeUrl instead of encodeUriComponent and found there is difference in both. So replaced this code.

File: packages/drivers/odsp-driver/src/fetchSnapshot.ts (hunk 8 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver/src/fetchSnapshot.ts:349]: Exception was at caller place. Moved it here.

File: packages/drivers/odsp-driver/src/fetchSnapshot.ts (hunk 7 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver/src/fetchSnapshot.ts:351]: I don't think there is a helper function. But added the check.

File: packages/drivers/odsp-driver/src/fetchSnapshot.ts [hunk 14]
```diff
@@ -58,7 +64,83 @@ export async function fetchSnapshot(
...
+        } catch(error) {
+            if (isRedeemSharingLinkError(odspResolvedUrl, error)) {
+                logger.sendErrorEvent({
+                    eventName: "RedeemFallback",
+                    errorType: error.errorType,
+                });
+                await redeemSharingLink(odspResolvedUrl, storageTokenFetcher, logger);
+                const odspResolvedUrlWithoutShareLink: IOdspResolvedUrl =
+                    { ...odspResolvedUrl, sharingLinkToRedeem: undefined };
+                const odspSnapshot = await fetchLatestSnapshotCore(
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/fetchSnapshot.ts:96]: you do not need extra variable here and above, just do
return await fetchLatestSnapshotCore(...)

File: packages/drivers/odsp-driver/src/fetchSnapshot.ts [hunk 15]
```diff
@@ -58,7 +64,83 @@ export async function fetchSnapshot(
...
+    odspResolvedUrl: IOdspResolvedUrl,
+    storageTokenFetcher: (options: TokenFetchOptions, name: string) => Promise<string | null>,
+    snapshotOptions: ISnapshotOptions | undefined,
+    logger: ITelemetryLogger,
+    snapshotDownloader: (url: string, fetchOptions: {[index: string]: any}) => Promise<IOdspResponse<IOdspSnapshot>>,
+    putInCache: (valueWithEpoch: IVersionedValueWithEpoch) => Promise<void>,
+    removeEntries: () => Promise<void>,
+): Promise<ISnapshotCacheValue> {
+    try {
+        try {
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/fetchSnapshot.ts:77]: nested try's look a bit ugly :)
Would this be more readable?

```typescript
return fetchLatestSnapshotCore(...)
.catch((error) => {
    ...
}).catch ((error) => {
     ...
});
```

File: packages/drivers/odsp-driver/src/fetchSnapshot.ts [hunk 16]
```diff
@@ -58,7 +64,83 @@ export async function fetchSnapshot(
...
+        // snapshot from cache in the future.
+        if (typeof error === "object" && error !== null && error.errorType === DriverErrorType.authorizationError
+            || error.errorType === DriverErrorType.fileNotFoundOrAccessDeniedError) {
+            await removeEntries();
+        }
+        throw error;
+    }
+}
+
+async function redeemSharingLink(
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/fetchSnapshot.ts:120]: not used outside of this file, drop export

File: packages/drivers/odsp-driver/src/fetchSnapshot.ts [hunk 17]
```diff
@@ -58,7 +64,83 @@ export async function fetchSnapshot(
...
+    odspResolvedUrl: IOdspResolvedUrl,
+    storageTokenFetcher: (options: TokenFetchOptions, name: string) => Promise<string | null>,
+    logger: ITelemetryLogger,
+) {
+    return PerformanceEvent.timedExecAsync(
+        logger,
+        {
+            eventName: "RedeemShareLink",
+        },
+        async () => {
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/fetchSnapshot.ts:130]: nit - you do not need away of {} here, can do
async () => getWithRetryForTokenRefresh(.....)

File: packages/drivers/odsp-driver/src/fetchSnapshot.ts [hunk 18]
```diff
@@ -263,3 +345,29 @@ export function evalBlobsAndTrees(snapshot: IOdspSnapshot) {
     }
     return { numTrees, numBlobs, encodedBlobsSize, decodedBlobsSize };
 }
+
+export function isRedeemSharingLinkError(odspResolvedUrl: IOdspResolvedUrl, error: any) {
+    const errorType = error.errorType;
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/fetchSnapshot.ts:350]: there should be a check that typeof error == "object" &&  error !== null here (and bail out if it's not).
Comment says you add it, but it's not here :)

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts [hunk 19]
```diff
@@ -603,14 +602,18 @@ export class OdspDocumentStorageService implements IDocumentStorageService {
                 valueWithEpoch.value,
             );
         };
+        const removeEntries = async () => {
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:605]: This is sufficient:
const removeEntries = async () => this.cache.persistedCache.removeEntries();

File: packages/drivers/odsp-driver/src/odspDriverUrlResolverForShareLink.ts [hunk 20]
```diff
@@ -137,7 +137,7 @@ export class OdspDriverUrlResolverForShareLink implements IUrlResolver {
         const odspResolvedUrl = await new OdspDriverUrlResolver().resolve(requestToBeResolved);
 
         if (isSharingLinkToRedeem) {
-            odspResolvedUrl.sharingLinkToRedeem = request.url.split("?")[0];
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/odspDriverUrlResolverForShareLink.ts:140]: Is this intentional change? Do we pass query param to redeem process?

**Review by vladsud — APPROVED** [review]

File: packages/drivers/odsp-driver/src/fetchSnapshot.ts (hunk 14 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver/src/fetchSnapshot.ts]: await with return gives error.

File: packages/drivers/odsp-driver/src/odspDriverUrlResolverForShareLink.ts (hunk 20 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver/src/odspDriverUrlResolverForShareLink.ts:140]: Yes. We do need the whole link for making a redeem call as I figured out. I have asked William, that it should not affect the other single RT redeem during trees/latest even if we send the query params.

**Review by AndreiZe — COMMENTED** [review]
@jatgarg, I added a few comments after this PR was completed, can you take a look?

File: packages/drivers/odsp-driver/src/fetchSnapshot.ts [hunk 21]
```diff
@@ -65,7 +66,77 @@ export async function fetchSnapshot(
...
+            odspSnapshot = await fetchLatestSnapshotCore(
+                odspResolvedUrlWithoutShareLink,
+                storageTokenFetcher,
+                snapshotOptions,
+                logger,
+                snapshotDownloader,
+                putInCache,
+            );
+        }
+        throw error;
```
[the remark this answers is not in the document]
Comment (jatgarg) [reply packages/drivers/odsp-driver/src/fetchSnapshot.ts:103]: Changed
