### PR TITLE
Fixing runWithRetry with abort signal when container closes

### LINKED ISSUE #8309: Prod: fluid:telemetry:OdspDriver:createNewFile_cancel: Need better back off & progress reporting / cancelation.
There are a lot of fluid:telemetry:OdspDriver:createNewFile_cancel errors in telemetry.
Looking closer, I see that most of them are concentrated in 10 sessions, with top one probably have 30% of all events (2109 hits in that session alone!)

I believe it works as it was designed (i.e. we keep retrying if user is offline), but
- should it do so in such tight loop? It looks like there is no delay / back off, just straight retry
- should it do so long? I know we went back and forth on it, and allowed (before) to fail and do retry by host.
   - probably better question to ask - can we start propagating IProgress through API and use this flow as a first guinea pig  for flashing out cancelation / progress reporting API?

> union Office_Fluid_FluidRuntime_*
| where Data_containerId == "2316b2db-5472-454b-bc4e-a1138393a477"
| project Event_Sequence, Event_Time, Data_eventName, Data_errorType, Data_error, Data_reason
| order by Event_Time asc

### PR DESCRIPTION
**Pull request by chensixx**
Fixes #8309 
We found hundreds of `createNew_cancel` and `createNewFile_cancel` events in one session
It was not the backoff logic that was broken, but the cancellation. Container was already closed but it was still retrying. RunWithRetry was in an infinite loop. So we added cancel signal. If container is closed, signal will fire abort, and we will throw an error
Also changed IProgress.retry to `onRetry` since it could be a bit confusing.

### CODE REVIEW

File: packages/loader/container-loader/src/container.ts [hunk 1]
```diff
@@ -811,6 +811,8 @@ export class Container extends EventEmitterWithErrorHandling<IContainerEvents> i
                     this.context.notifyAttaching();
                 }
 
+                const abortController = new AbortController();
+                abortController.signal.addEventListener("abort", (event: Event) => { this.close(); });
```
Comment (vladsud) [inline packages/loader/container-loader/src/container.ts:815]: What this code does is closes container if someone cancelled this signal. But nobody will cancel it, so this code does nothing.
Instead (based on your description) what you suggest to do is to listen on "closed" event on container and in response to it cancel this abort controller.

File: packages/loader/driver-utils/src/runWithRetry.ts [hunk 2]
```diff
@@ -61,13 +64,23 @@ export async function runWithRetry<T>(
                 }, err);
                 throw err;
             }
+
+            if (progress.cancel?.aborted){
+                throw new NonRetryableError(
+                    "runWithRetryAborted",
+                    undefined,
+                    DriverErrorType.genericError,
+                    { driverVersion: pkgVersion },
```
Comment (vladsud) [inline packages/loader/driver-utils/src/runWithRetry.ts:73]: Useful to stick fetchCallName as a property on error object to know what call was actually cancelled.
in the past we did this by changing name of event, i.e. something like `runWirhRetryAborted_${fetchCallName}`.
I'd prefer that way, as it's easier to work with data in this format (then have separate property, though we can do both).

Comment (chensixx) [reply packages/loader/driver-utils/src/runWithRetry.ts:73]: ok, though I'm not sure how to change the eventName here, since I'm throwing an error. Can I add eventName as an error property?

File: packages/loader/container-loader/src/container.ts [hunk 3]
```diff
@@ -105,6 +105,7 @@ import { getSnapshotTreeFromSerializedContainer } from "./utils";
 import { QuorumProxy } from "./quorum";
 import { CollabWindowTracker } from "./collabWindowTracker";
 import { ConnectionManager } from "./connectionManager";
+import { abort } from "process";
```
Comment (vladsud) [inline packages/loader/container-loader/src/container.ts:108]: I'm not sure why you need this symbol.
But I believe you are missing this one:
> import { default as AbortController } from "abort-controller";

File: packages/loader/driver-utils/src/runWithRetry.ts [hunk 4]
```diff
@@ -61,13 +64,23 @@ export async function runWithRetry<T>(
                 }, err);
                 throw err;
             }
+
+            if (progress.cancel?.aborted === true) {
+                throw new NonRetryableError(
+                    "runWithRetryAborted",
+                    undefined,
+                    DriverErrorType.genericError,
```
Comment (vladsud) [inline packages/loader/driver-utils/src/runWithRetry.ts:72]: I'd not use generic error.
This is same as this code:
```ts
        if (error.name === "AbortError") {
            throw new RetryableError(
                "Fetch Timeout (AbortError)", OdspErrorType.fetchTimeout, { driverVersion });
        }
```

And you have https://github.com/microsoft/FluidFramework/issues/8488 that asks to introduce and start using new OdspErrorType.fetchAborted error.

I'd do it here, though it has back-compat considerations, so likely we have to start with OdspErrorType.fetchTimeout here and use this bug to move all usages to new code.
Also I think such codes should not be odsp-specific, so should be added in different enum

File: api-report/driver-utils.api.md [hunk 5]
```diff
@@ -226,7 +226,7 @@ export class InsecureUrlResolver implements IUrlResolver {
 // @public
 export interface IProgress {
     cancel?: AbortSignal;
-    retry?(delayInMs: number, error: any): void;
+    onRetry?(delayInMs: number, error: any): void;
```
Comment (vladsud) [inline api-report/driver-utils.api.md:229]: Please double-check that it has no back-compa considerations. I.e. this interface is not crossing loader to driver boundary, or runtime to loader/driver boundary.

Comment (chensixx) [reply api-report/driver-utils.api.md:217]: yes, this is the only place IProgress is used today

Comment (chensixx) [reply api-report/driver-utils.api.md:217]: yes all usages are in loader only

File: packages/loader/driver-utils/src/runWithRetry.ts (hunk 4 above)
Comment (chensixx) [reply packages/loader/driver-utils/src/runWithRetry.ts:72]: since it's not odsp specific, we would need to add to `DriverErrorType` in driver-definitions, which also has back-compat considerations, and requires pre-release etc. 
is it ok to use `OdspErrorType.fetchTimeout` here?

**Review by vladsud — APPROVED** [review]

File: packages/loader/driver-utils/src/runWithRetry.ts [hunk 6]
```diff
@@ -5,7 +5,10 @@
 
 import { ITelemetryLogger } from "@fluidframework/common-definitions";
 import { delay, performance } from "@fluidframework/common-utils";
+import { OdspErrorType } from "@fluidframework/odsp-driver-definitions";
```
Comment (markfields) [inline packages/loader/driver-utils/src/runWithRetry.ts:8]: @chensixx - We should follow up on this, I don't think it's right for driver-utils to have a dependency on ODSP-specific error type.  Instead we should probably promote the timeout error type to base driver definitions.

File: packages/loader/driver-utils/src/runWithRetry.ts [hunk 7]
```diff
@@ -61,13 +64,22 @@ export async function runWithRetry<T>(
                 }, err);
                 throw err;
             }
+
+            if (progress.cancel?.aborted === true) {
+                throw new NonRetryableError(
+                    "runWithRetryAborted",
```
Comment (markfields) [inline packages/loader/driver-utils/src/runWithRetry.ts:70]: This should be a short sentence not a pascaleCased term

File: packages/loader/driver-utils/src/runWithRetry.ts [hunk 8]
```diff
@@ -61,13 +64,22 @@ export async function runWithRetry<T>(
...
+                    OdspErrorType.fetchTimeout,
+                    { eventName: `runWithRetryAborted_${fetchCallName}`, driverVersion: pkgVersion },
```
Comment (markfields) [inline packages/loader/driver-utils/src/runWithRetry.ts:72]: This eventName will never make it to the logs :)  Whenever this error is logged, the event will have an eventName, and it won't be overwritten by this prop.  Maybe we want to combine this case with the case above, or at least mimic it.

The symmetry makes sense because if the api checks for the abort signal (notice it gets passed `progress.cancel`) then it will probably handle that by throwing an error and end up in the first block, whereas if it doesn't then we'll handle it here.  So would be nice for the logging to be the same I think.

File: packages/loader/driver-utils/src/runWithRetry.ts (hunk 6 above)
Comment (chensixx) [reply packages/loader/driver-utils/src/runWithRetry.ts:8]: will remember to fix with #8488
