### PR TITLE
Track total summarization attempts made by a given Summarizer

### LINKED ISSUE #8972: Summarization attempt data in telemetry is wrong
Fotking from https://github.com/microsoft/FluidFramework/issues/8963, which has much longer thread about why having this data is importatnt.

Query:
> union Office_Fluid_FluidRuntime_Generic
| where Data_eventName == "fluid:telemetry:Summarizer:Running:GenerateSummary"
| summarize count() by Data_summarizeTotalAttempts
| render linechart 

I get only 5 attempts max, which is too low.
Cross-checking it against this query suggests that indeed data above is wrong:

> union Office_Fluid_FluidRuntime_Generic
| where Data_eventName == "fluid:telemetry:Summarizer:Running:GenerateSummary"
| summarize count() by Data_containerId
| summarize count() by count_
| render linechart  

image

It gives me hundreds of summaries per same container session.
Data_summarizeTotalAttempts is supposed to track all attempts to summarize within a session, but it clearly does not. And we have other properties to track other counters like that:

```ts
                const summarizeProps: ITelemetryProperties = {
                    summarizeReason,
                    summarizeTotalAttempts: totalAttempts,
                    summarizeAttemptsPerPhase: attemptPerPhase,
                    summarizeAttemptPhase: attemptPhase + 1, // make everything 1-based
                    ...options,
                };
```

### PR DESCRIPTION
**Pull request by pleath**
Use RunningSummarizer.totalAttempts to do this. Also rename a couple of existing telemetry properties to make it more clear that they are per-summary counters, not per-summarizer.

### CODE REVIEW

File: packages/runtime/container-runtime/src/runningSummarizer.ts [hunk 1]
```diff
@@ -338,27 +339,29 @@ export class RunningSummarizer implements IDisposable {
...
 
-            for (let attemptPhase = 0; attemptPhase < attempts.length;) {
+            for (let summaryAttemptPhase = 0; summaryAttemptPhase < attempts.length;) {
                 if (this.cancellationToken.cancelled) {
                     return;
                 }
 
-                totalAttempts++;
-                attemptPerPhase++;
+                this.totalAttempts++;
```
Comment (vladsud) [inline packages/runtime/container-runtime/src/runningSummarizer.ts:352]: Unfortunately, no matter how we name these things, it will be confusing, and one would need to look at the code to understand what it tracks. So, I'm not sure my suggestion is helping, but....
I'd probably rename totalAttempts and would increment it outside of the loop only, to track successful attempts. I.e. I'd keep it = 1 for first 3 unsuccessful and first successful retries, and then move to 2. That way it tracks succeeded cases (I can tell how many summaries we actually produced per session), and I can drill into summaryAttempts if I want to see how many attempts it takes per successful summary.

**Review by vladsud — APPROVED** [review]

File: packages/runtime/container-runtime/src/runningSummarizer.ts (hunk 1 above)
Comment (pleath) [reply packages/runtime/container-runtime/src/runningSummarizer.ts:352]: I see. So something like "RuningSummarizer.totalSuccessfulAttempts."
