### PR TITLE
Remove deterministic crash in logging

### LINKED ISSUE #3779: TypeError: Cannot read property 'eventName' of undefined
## Describe the bug
`PerformanceEvent` in `packages/utils/telemetry-utils/src/logger.ts` contains this code:
``` ts
  public reportEvent(eventNameSuffix: string, props?: ITelemetryProperties, error?: any): void {
        if (!this.event) {
            this.logger.sendErrorEvent({
                eventName: "PerformanceEventAfterStop",
                perfEventName: this.event!.eventName,
                eventNameSuffix,
            });
```
This non-null assertion will always throw here since we know `this.event` isn't defined. I have seen this error in tests that are failing for other reasons.

### Expected behavior
This should either not throw in this case or throw a more useful error.

### Logs
```
(node:31699) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'eventName' of undefined
    at PerformanceEvent.reportEvent (/home/wes/fluid/packages/utils/telemetry-utils/dist/logger.js:411:43)
    at PerformanceEvent.end (/home/wes/fluid/packages/utils/telemetry-utils/dist/logger.js:394:14)
    at container.load.finally.then (/home/wes/fluid/packages/loader/container-loader/dist/container.js:139:27)
```

### PR DESCRIPTION
**Pull request by markfields**
Fixes #3779

### CODE REVIEW

File: packages/utils/telemetry-utils/src/logger.ts [hunk 1]
```diff
@@ -516,7 +519,6 @@ export class PerformanceEvent {
         if (!this.event) {
             this.logger.sendErrorEvent({
                 eventName: "PerformanceEventAfterStop",
-                perfEventName: this.event!.eventName,
```
Comment (markfields) [inline packages/utils/telemetry-utils/src/logger.ts:519]: This came from https://github.com/microsoft/FluidFramework/pull/2330, which is a massive PR so I didn't try to track it back through it.  Is there anything else we could put here instead to give a hint about what the logger's trying to log about? Some best-guess property from Props?

Comment (markfields) [reply packages/utils/telemetry-utils/src/logger.ts:519]: @Vladsud

Comment (vladsud) [reply packages/utils/telemetry-utils/src/logger.ts:519]: We can record name of even, but that's probably enough - it it happens, than stream of events will likely contain enough clues to figure it out

**Review by vladsud — APPROVED** [review]

File: packages/utils/telemetry-utils/src/logger.ts (hunk 1 above)
Comment (markfields) [reply packages/utils/telemetry-utils/src/logger.ts:519]: > We can record name of even[t], but that's probably enough

??? Where would we get that name?  That's the faulty code I'm deleting.

Also, how about `error.message` or something?

Comment (vladsud) [reply packages/utils/telemetry-utils/src/logger.ts:519]: In constructor - we do have event there, we just clear it after some event

File: packages/utils/telemetry-utils/src/logger.ts [hunk 2]
```diff
@@ -514,11 +519,11 @@ export class PerformanceEvent {
 
     public reportEvent(eventNameSuffix: string, props?: ITelemetryProperties, error?: any): void {
         if (!this.event) {
-            this.logger.sendErrorEvent({
-                eventName: "PerformanceEventAfterStop",
-                perfEventName: this.event!.eventName,
+            const errorEvent = {
+                eventName: `${this.eventName}_doubleReport`,
```
Comment (markfields) [inline packages/utils/telemetry-utils/src/logger.ts:523]: This new eventName will make this show up in queries with a clause like this:
```
| where Data_eventName has "RefreshLatestSummaryGetSnapshot"
```

Otherwise I fear we'll never proactively look for this event and won't notice when it's happening.

Comment (vladsud) [reply packages/utils/telemetry-utils/src/logger.ts:523]: I'd keep the old structure, i.e. single event and property to point to type of issue.
This will increase chances that someone will take a look - I usually look at errors via sorting by hit count - if error does not happen that often, it may not even get into my view.

**Review by vladsud — APPROVED** [review]

**Comment by wes-carlson** [comment]
@vladsud I think I've only seen this come from Container.load() (like the stack in #3779). Could this indicate that there's something wrong with the use of timedExecAsync() in load()?

**Comment by vladsud** [comment]
@wes-carlson - it's very hard to say. I do not see a reference to any query / session ID to poke around in telemetry to better understand the problem. That said, I'll add comment in a moment to the issue itself describing what I see from code inspection.

**Comment by markfields** [comment]
The catch block in `timedExec`/`timedExecAsync` doesn't check `this.event` for undefined, I'm assuming that's what's going on, but I couldn't find from quick code inspection the call site that is cleaning up inside the callback and then throwing.

**Comment by markfields** [comment]
I'm pondering whether or not to change the event name before merging, spending some time becoming more familiar with how the logs are structured and typically queried.

**Comment by vladsud** [comment]
@markfields, please take a look at my comment in  #3779), I describe what happens here.

File: packages/utils/telemetry-utils/src/logger.ts (hunk 2 above)
Comment (markfields) [reply packages/utils/telemetry-utils/src/logger.ts]: Reverted
