### PR TITLE
Add `eslint-plugin-unused-imports` package, add `no-unused-imports` rule and pre-fix violations

### LINKED ISSUE #10359: Enable `@typescript-eslint/no-unused-vars` eslint rule and pre-apply fixes
From the [rule documentation](https://typescript-eslint.io/rules/no-unused-vars/):

> Disallow unused variables.

### PR DESCRIPTION
**Pull request by Josmithr**
For more on the package, see [here](https://www.npmjs.com/package/eslint-plugin-unused-imports)

This change also removes existing unused imports detected by the rule.

### CODE REVIEW

File: server/routerlicious/packages/lambdas-driver/src/document-router/documentPartition.ts [hunk 1]
```diff
@@ -15,7 +15,6 @@ import {
 } from "@fluidframework/server-services-core";
 import { getLumberBaseProperties, Lumberjack } from "@fluidframework/server-services-telemetry";
 import { QueueObject, queue } from "async";
-import * as _ from "lodash";
```
Comment (tylerbutler) [inline server/routerlicious/packages/lambdas-driver/src/document-router/documentPartition.ts:18]: Weird! This is likely old code that was never cleaned up properly, but does lodash have side effects that execute on import? @znewton @hedasilv Not sure if this is your area of expertise, but since this is server code, want to make sure we're not inadvertently breaking something. Do you know if this import is relevant?

**Review by tylerbutler — APPROVED** [review]
Looks good. Thanks for doing this! For future PRs, consider splitting the config changes from the code changes. That is, do the package.json/dependency changes in one PR, then separately do the code changes. The dep updates only need expertise from infra folks, while the code changes usually need input from across the team, so this helps keep the PRs focused. That said, no need to split this one apart IMO since the code changes are straightforward.

File: server/routerlicious/packages/lambdas-driver/src/document-router/documentPartition.ts (hunk 1 above)
Comment (znewton) [reply server/routerlicious/packages/lambdas-driver/src/document-router/documentPartition.ts:18]: Thanks for the ping, Tyler! It's not my area of expertise, but I checked everything I could and it looks totally safe to remove the 2 "lodash" imports being removed here (this file and kafka-service/src/partition).

Comment (znewton) [reply server/routerlicious/packages/lambdas-driver/src/document-router/documentPartition.ts:18]: I also pinged @hedasilv to see if he knows about some weird global artifact from this import that is important

Comment (hedasilv) [reply server/routerlicious/packages/lambdas-driver/src/document-router/documentPartition.ts:18]: I agree with Zach, but just to be safe, we could try to run r11s locally in Docker and target it with a test app like clicker. Let me try to test that some time today and hopefully soon I can get back to you.

Comment (hedasilv) [reply server/routerlicious/packages/lambdas-driver/src/document-router/documentPartition.ts:18]: Actually, we might not even have to run r11s on Docker with Clicker. Looking into the code history, those imports of `lodash` were added so that we could use `_.cloneDeep()` as in here: https://github.com/microsoft/FluidFramework/commit/09e34b1942fe32792590cfc0062818615a26ebed and here: https://github.com/microsoft/FluidFramework/pull/1606/files

That code was added to partition.ts and documentPartition.ts a few years ago (2 and 4.5, specifically) and those files do not do `_.cloneDeep()`. So I think it's safe to remove lodash.

I will give the approval from the server side 😄

**Review by hedasilv — APPROVED** [review]

File: server/routerlicious/packages/lambdas-driver/src/document-router/documentPartition.ts (hunk 1 above)
Comment (tylerbutler) [reply server/routerlicious/packages/lambdas-driver/src/document-router/documentPartition.ts:18]: THanks, gentlemen! @Josmithr Merge away!
