### PR TITLE
Fix Routerlicious TokenProvider Abstraction

### LINKED ISSUE #4655: Improve E2E and Real Service Test Integration Abstraction
The current e2e test server abstraction is insufficient to cover a number of scenarios, and results in unnatural test design.

https://github.com/microsoft/FluidFramework/blob/f5b26b261ea123b98373b91b61914dee52a0a7c5/packages/test/end-to-end-tests/src/test/compatUtils.ts#L41

I propose we simplify this integration to the smallest set of necessary pieces to connect to a a fluid endpoint. This likely includes url resolver, document service factory, logger, and a function to create a create new request. We should create one of these object to odsp, frs, tinylicous, and local test server. Additionally, these object should be part of a discriminated union that can provide strongly types access, such that tests can specifically target features on a specific backend if necessary.

We should use the same pattern as the @fluidframework/mocha-test-setup package to inject the object object at runtime. Then these test can be written as normal mocha tests without the overly complex of generateTest tests. Rather for each backend a test project supports it would have a npm script target, which would configure the test setup package to output the appropriate driver abstraction. This will also increase the possibly of parallelism across our test.

This automation should expect secrets in environment variables that match those output by getkeys, so it can easily be run locally. I've already updated our automation to support providing the necessary secrets, so configuring these same environment variable should be trivial:
https://github.com/microsoft/FluidFramework/blob/f5b26b261ea123b98373b91b61914dee52a0a7c5/tools/pipelines/test-real-service.yml#L76

It should be relatively easy to re-base the existing automation on this abstraction, but provide us with more flexibility going forward.

### PR DESCRIPTION
**Pull request by anthony-murphy**
The routerlicious token provider abstraction was wrong in that it required knowledge of the tenant and document it will be used against at construction time, this goes against the url resolver pattern where that information should be discovered and passed to the token provider. This extends the interface to support the url resolver pattern

### CODE REVIEW

File: examples/utils/get-tinylicious-container/src/insecureTinyliciousTokenProvider.ts [hunk 1]
```diff
@@ -13,32 +13,32 @@ import { v4 as uuid } from "uuid";
...
+        ver: string = "1.0"): string {
         // Current time in seconds
         const now = Math.round((new Date()).getTime() / 1000);
 
         const claims: ITokenClaims = {
-            documentId: this.documentId,
+            documentId,
             scopes: [ScopeType.DocRead, ScopeType.DocWrite, ScopeType.SummaryWrite],
-            tenantId: "tinylicious",
+            tenantId,
```
Comment (heliocliu) [inline examples/utils/get-tinylicious-container/src/insecureTinyliciousTokenProvider.ts:41]: Does tinylicious require the tenantId to be "tinylicious"? Regardless it's probably worth documenting somewhere for this class that this value must be provided for the tenantId param, or ignore the provided value and always use "tinylicious" (and document it gets ignored).  Mainly because the implementation before this never allowed you to provide the tenantId and it doesn't look like there are currently any examples for this change so it seems like this info might get lost

**Review by heliocliu — APPROVED** [review]

**Review by tanviraumi — APPROVED** [review]
:shipit:

File: examples/utils/get-tinylicious-container/src/insecureTinyliciousTokenProvider.ts (hunk 1 above)
Comment (anthony-murphy) [reply examples/utils/get-tinylicious-container/src/insecureTinyliciousTokenProvider.ts:41]: the tinylicious url resolver hard codes the tenantId as tinylicious, which is how it should be, as the resolver gets the constituent parts from the url
