### PR TITLE
Fix strict mode exceptions when changing Interval properties

### LINKED ISSUE #9715: IIntervalCollection.changeIntervalPropertySet error during delta processing
## Describe the bug
IIntervalCollection.changeIntervalPropertySet causes error during delta processing

### To Reproduce
User A: create an interval
User A: call IIntervalCollection.changeIntervalPropertySet 
User B: hits error while processing the change delta

It appears that this is caused by the user attempting to set the reserved id property.

### Expected behavior
No Error

### Logs
`
ContainerClose {"category":"error","error":"Cannot assign to read only property 'intervalId' of object '[object Object]'","errorType":"dataProcessingError","fluidErrorCode":"-","canRetry":false,"untrustedOrigin":1,"innerErrorInstanceId":"574b40e3-430f-44e6-a08e-ef6894c348b5","dataProcessingError":1,"dataProcessingCodepath":"channelDeltaConnectionFailedToProcessMessage","messageClientId":"839010c8-d0b7-4a87-ba02-d6b8a50c27f8","messageSequenceNumber":12,"messageClientSequenceNumber":8,"messageReferenceSequenceNumber":11,"messageMinimumSequenceNumber":5,"messageTimestamp":1648844390207,"message":"Cannot assign to read only property 'intervalId' of object '[object Object]'","errorInstanceId":"574b40e3-430f-44e6-a08e-ef6894c348b5","clientType":"interactive","containerId":"256d1ee3-0860-4927-84b9-54b5402cdff7","docId":"document1","containerAttachState":"Attached","containerLifecycleState":"closing","containerConnectionState":"Disconnected","dmInitialSeqNumber":0,"dmLastProcessedSeqNumber":12,"dmLastKnownSeqNumber":12,"containerLoadedFromVersionId":"d2d481d1-b6d3-45ef-bfa5-fd4a259bb2f4","dmLastMsqSeqNumber":12,"dmLastMsqSeqTimestamp":1648844390207,"dmLastMsqSeqClientId":"839010c8-d0b7-4a87-ba02-d6b8a50c27f8","connectionStateDuration":2.5,"loaderId":"553f0011-568a-4dca-bece-c70a3f61c48e","loaderVersion":"0.58.2001"} tick=56415 Error    at PropertiesManager.addProperties (http://localhost:8080/dist/scriptorPad.js:73685:31)    at SequenceInterval.addProperties (http://localhost:8080/dist/scriptorPad.js:84585:37)    at IntervalCollection.changeInterval (http://localhost:8080/dist/scriptorPad.js:85229:45)    at Object.process (http://localhost:8080/dist/scriptorPad.js:84917:23)    at Object.process (http://localhost:8080/dist/scriptorPad.js:86082:25)    at MapKernel.tryProcessMessage (http://localhost:8080/dist/scriptorPad.js:85892:18)    at SharedString.processCore (http://localhost:8080/dist/scriptorPad.js:86579:52)    at SharedString.process (http://localhost:8080/dist/scriptorPad.js:104176:14)    at Object.process (http://localhost:8080/dist/scriptorPad.js:104125:22)    at ChannelDeltaConnection.process (http://localhost:8080/dist/scriptorPad.js:50786:26) +0ms
`

### PR DESCRIPTION
**Pull request by pleath**
Confirm that Interval properties are writable/configurable before trying to change/delete them.

### CODE REVIEW

File: packages/dds/merge-tree/src/segmentPropertiesManager.ts [hunk 1]
```diff
@@ -78,8 +78,11 @@ export class PropertiesManager {
                 if (!newProps[key] && shouldModifyKey(key)) {
                     deltas[key] = oldProps[key];
 
-                    // eslint-disable-next-line @typescript-eslint/no-dynamic-delete
-                    delete oldProps[key];
+                    const desc = Object.getOwnPropertyDescriptor(oldProps, key);
+                    if (desc?.configurable !== false) {
```
Comment (anthony-murphy) [inline packages/dds/merge-tree/src/segmentPropertiesManager.ts:82]: i don't really understand how this can happen. i also worry if it happens, we are not being eventually consistent. how do we ensure all clients reach the same state?

Comment (anthony-murphy) [reply packages/dds/merge-tree/src/segmentPropertiesManager.ts:82]: generally, we can't silently fail when trying write data

Comment (pleath) [reply packages/dds/merge-tree/src/segmentPropertiesManager.ts:82]: Yeah, I agree, I don't like this approach either.

**Review by anthony-murphy — APPROVED** [review]
