### PR TITLE
Remove deprecated inbound and outbound queues on IDeltaManager

### LINKED ISSUE #22843: Deprecated `IDeltaManager.inbound` and `IDeltaManager.outbound`
## Deprecated API

Deprecated `IDeltaManager.inbound` and `IDeltaManager.outbound`

**Context**

-   Deprecated `IDeltaManager.inbound` as it was not very useful to the customer and there are pieces of functionality that can break the core runtime if used improperly. For example, summarization and processing batches. Do not use the apis on this if possible. Data loss/corruption may occur in these scenarios in which
    `IDeltaManger.inbound.pause()` or `IDeltaManager.inbound.resume()` get called.
-   Deprecated `IDeltaManager.outbound` as it was not very useful to the customer and there are pieces of functionality that can break the core runtime if used improperly. For example, generation of batches and chunking. Op batching and chunking can be broken. Data loss/corruption may occur in these scenarios in which `IDeltaManger.inbound.pause()` or `IDeltaManager.inbound.resume()` get called.

**Alternatives**

-   Alternatives to `IDeltaManager.inbound.on("op", ...)` are `IDeltaManager.on("op", ...)`
-   Alternatives to calling `IDeltaManager.inbound.pause`, `IDeltaManager.outbound.pause` for `IContainer` disconnect use `IContainer.disconnect`.
-   Alternatives to calling `IDeltaManager.inbound.resume`, `IDeltaManager.outbound.resume` for `IContainer` reconnect use `IContainer.connect`.

### PR DESCRIPTION
**Pull request by jatgarg**
## Description

[AB#7202](https://dev.azure.com/fluidframework/internal/_workitems/edit/7202)

1.) Remove deprecated inbound and outbound queues on IDeltaManager.
2.) Move them to IDeltaManagerFull so that internal Fluid layers can still use it but not the apps.

### CODE REVIEW

File: packages/common/container-definitions/src/deltas.ts [hunk 1]
```diff
@@ -241,6 +227,25 @@ export interface IDeltaManager<T, U>
 	submitSignal(content: any, targetClientId?: string): void;
 }
 
+/**
+ * DeltaManager which is used internally by the Fluid layers and not exposed to the end users.
+ * @sealed
+ * @legacy
+ * @alpha
```
Comment (alexvy86) [inline packages/common/container-definitions/src/deltas.ts:234]: If it's only used internally shouldn't this be `@internal`?

File: packages/loader/container-loader/src/loadPaused.ts [hunk 2]
```diff
@@ -59,7 +60,7 @@ export async function loadContainerPaused(
 	// Force readonly mode - this will ensure we don't receive an error for the lack of join op
 	container.forceReadonly?.(true);
 
-	const dm = container.deltaManager;
+	const dm = container.deltaManager as IDeltaManagerInternal;
```
Comment (alexvy86) [inline packages/loader/container-loader/src/loadPaused.ts:63]: Feels like we should have a type-guard function that guarantees something is an `IDeltaManagerInternal` instead of the cast.

File: packages/common/container-definitions/src/deltas.ts (hunk 1 above)
Comment (alexvy86) [reply packages/common/container-definitions/src/deltas.ts:234]: Oh, I see the new type is used in an existing `@alpha` API `toDeltaManagerInternal()`. But then I don't quite get the point of this change. We're removing the queues from one alpha interface... to put them in another one where they are not marked as deprecated, which seems wrong?

**Review by alexvy86 — COMMENTED** [review]
Didn't go through the whole thing, just a couple of comments below, and a general comment that I thought we were still holding off on any breaking changes (including to `@alpha`/`@legacy` APIs).

File: packages/common/container-definitions/src/deltas.ts (hunk 1 above)
Comment (jatgarg) [reply packages/common/container-definitions/src/deltas.ts]: Fixed.

**Comment by jatgarg** [comment]
> Didn't go through the whole thing, just a couple of comments below, and a general comment that I thought we were still holding off on any breaking changes (including to `@alpha`/`@legacy` APIs).

Yeah, I am not going to merge it until it is allowed to make breaking changes, but want to get review/approval so that I can just merge when it is allowed and to know if it is ok to make this change.

File: packages/common/container-definitions/src/deltas.ts [hunk 3]
```diff
@@ -156,20 +156,6 @@ export interface IDeltaManagerEvents extends IEvent {
 export interface IDeltaManager<T, U>
 	extends IEventProvider<IDeltaManagerEvents>,
 		IDeltaSender {
-	/**
-	 * The queue of inbound delta messages
-	 * @deprecated Do not use, for internal use only. There are a lot of complications in core pieces of the runtime
-	 * may break if this is used directly. For example summarization and op processing.
-	 */
-	readonly inbound: IDeltaQueue<T>;
```
Comment (vladsud) [inline packages/common/container-definitions/src/deltas.ts:164]: Overall - that's a great change.
But there is usage in office-bohemia. It would be great if we could first go into their repo and figure out what needs to be done to get rid of it.

@tyler-cai-microsoft - FYI, as you were looking at it at some point

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 4]
```diff
@@ -1466,6 +1470,7 @@ export class ContainerRuntime
 			compressionAlgorithm: CompressionAlgorithms.lz4,
 		};
 
+		assert(isIDeltaManagerInternal(deltaManager), "Invalid delta manager");
```
Comment (vladsud) [inline packages/runtime/container-runtime/src/containerRuntime.ts:1473]: This pattern is Ok to hide internals, but it results in runtime failures in case internal interface is not implemented. It's harder to see contracts.

Would it be better for IContainerContext to have IDeltaManager & IDeltaMaagerInternal?
This exposes internals, but only on that one interface. 

IContainerContext is marked as legacy & alpha. It will always be some form of "public" API, so there is some risk of exposing internals, but I think it's fine to acknowledge that whoever implements instantiateRuntime has access to internals, but our stock implementation (ContainerRuntime, IContainerRuntime(Base)) will not expose internals to users. Same for Container & IContainer - they will not expose internals.

File: packages/common/container-definitions/src/deltas.ts (hunk 3 above)
Comment (tyler-cai-microsoft) [reply packages/common/container-definitions/src/deltas.ts:164]: Last time I checked, it was just being used for testing purposes, which can be replaced probably with disconnect and reconnect.

Comment (jatgarg) [reply packages/common/container-definitions/src/deltas.ts:164]: I check their repo. There are mostly using it in examples to mimic offline behaviour, that is to go offline and comeback. I think probably, container.disconnect could achieve that?

Comment (tyler-cai-microsoft) [reply packages/common/container-definitions/src/deltas.ts:164]: Yeah, container.disconnect is a better solution to achieving that

Comment (jatgarg) [reply packages/common/container-definitions/src/deltas.ts:164]: Its usage is now removed from their repo.

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 4 above)
Comment (jatgarg) [reply packages/runtime/container-runtime/src/containerRuntime.ts:1525]: Didn't want to expose the delta manager on the container context, since technically it will still be exposed. With this approach we are not exposing it anywhere. 
The container runtime implementor does not need to implement the IDeltaManagerInternal, our Deltamanager class implement both and if the runtime does not need the inbound/outbound queues, then they don't need to do any type checking and if they do, then they can look that the Delta manager implements it and they can assert that like we do here as an example. 
Not sure, if got you completely there.

File: packages/test/local-server-tests/src/test/opsOnReconnect.spec.ts [hunk 5]
```diff
@@ -654,7 +655,10 @@ describe("Ops on Reconnect", () => {
 			// At this point, the delta manager should have the messages
 			// in its buffer but not in its outbound queue,
 			// as ops have not been flushed yet
-			assert.strictEqual(container1.deltaManager.outbound.length, 0);
+			assert.strictEqual(
+				(container1.deltaManager as IDeltaManagerInternal).outbound.length,
```
Comment (jason-ha) [inline packages/test/local-server-tests/src/test/opsOnReconnect.spec.ts:659]: Please avoid use of `as` cast. It is very unsafe in many situations. Failing other ways to know this is internal version, I recommend having a helper that takes care of the cast. That helper can then ensure at least going from `IDeltaManager<...>`.

**Review by jason-ha — COMMENTED** [review]
For the future I would recommend staging the internal changes and fixups much earlier (introduce `IDeltaManagerInternal` earlier). Preference for the breaking changes is to have most things settled and the break change is mostly just deletions and needed type test changes.

File: packages/common/container-definitions/api-report/container-definitions.legacy.alpha.api.md [hunk 6]
```diff
@@ -204,17 +204,13 @@ export interface IDeltaManager<T, U> extends IEventProvider<IDeltaManagerEvents>
     readonly active: boolean;
     readonly clientDetails: IClientDetails;
     readonly hasCheckpointSequenceNumber: boolean;
-    // @deprecated
-    readonly inbound: IDeltaQueue<T>;
```
Comment (vladsud) [inline packages/common/container-definitions/api-report/container-definitions.legacy.alpha.api.md:208]: what is the impact on Loop here? I remember there was some usage.

File: packages/common/container-definitions/api-report/container-definitions.legacy.alpha.api.md [hunk 7]
```diff
@@ -204,17 +204,13 @@ export interface IDeltaManager<T, U> extends IEventProvider<IDeltaManagerEvents>
...
     readonly inboundSignal: IDeltaQueue<ISignalMessage>;
```
Comment (vladsud) [inline packages/common/container-definitions/api-report/container-definitions.legacy.alpha.api.md:207]: It's really weird that we are keeping inboundSignal here. Can we remove it as part of this change?
If not, can we mark it deprecated and open a task item to remove it in the future?

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 4 above)
Comment (vladsud) [reply packages/runtime/container-runtime/src/containerRuntime.ts:1528]: Take a look at IDeltaManagerErased, toDeltaManagerErased() & toDeltaManagerInternal()  and its usage.
We could expose IDeltaManagerInternalErased that way.

For example, IFluidDataStoreRuntime exposed IDeltaManagerErased.

That said, current pattern is fine too, and I'd probably rename toDeltaManagerInternal -> toDeltaManager in any case, to remove confusion on "internal" meaning.

File: packages/test/test-end-to-end-tests/src/test/containerDirtyFlag.spec.ts [hunk 8]
```diff
@@ -63,7 +66,10 @@ describeCompat("Container dirty flag", "NoCompat", (getTestObjectProvider, apis)
 
 		await args.ensureSynchronized();
 		await args.opProcessingController.pauseProcessing(container);
-		assert(toDeltaManagerInternal(dataStore.runtime.deltaManager).outbound.paused);
+		const deltaManagerInternal = toDeltaManagerInternal(dataStore.runtime.deltaManager);
+		if (isIDeltaManagerInternal(deltaManagerInternal)) {
```
Comment (vladsud) [inline packages/test/test-end-to-end-tests/src/test/containerDirtyFlag.spec.ts:70]: See my prior comment on naming. Usage of "internal" on these two lines does not make sense - we already sort of got "internal" object, why do we need to check that it's "internal"? In reality, first line does not return internal interface, even though it feels that way from the name of API

**Review by vladsud — APPROVED** [review]

File: packages/loader/container-loader/src/utils.ts [hunk 9]
```diff
@@ -424,3 +430,13 @@ export async function getDocumentAttributes(
 
 	return attributes;
 }
+
+/**
+ * Type guard to check if the given deltaManager is of type IDeltaManagerInternal.
```
Comment (Josmithr) [inline packages/loader/container-loader/src/utils.ts:435]: Nit
```suggestion
 * Type guard to check if the given deltaManager is of type {@link IDeltaManagerInternal}.
```

Comment (Josmithr) [reply packages/loader/container-loader/src/utils.ts:435]: Given that `IDeltaManagerInternal` lives in `container-definitions`, would it make more sense for this type-guard to live there as well?

File: packages/runtime/runtime-utils/src/deltaManager.ts [hunk 10]
```diff
@@ -31,3 +34,13 @@ export function toDeltaManagerErased(
 ): IDeltaManagerErased {
 	return deltaManager as unknown as IDeltaManagerErased;
 }
+
+/**
+ * Type guard to check if the given deltaManager is of type IDeltaManagerInternal.
+ * @internal
+ */
+export function isIDeltaManagerInternal(
```
Comment (Josmithr) [inline packages/runtime/runtime-utils/src/deltaManager.ts:42]: We defined this function elsewhere too. Can we deduplicate?

File: packages/test/local-server-tests/src/test/opsOnReconnect.spec.ts (hunk 5 above)
Comment (Josmithr) [reply packages/test/local-server-tests/src/test/opsOnReconnect.spec.ts:659]:
```suggestion
			assert(isDeltaManagerInternal(container1.deltaManager));
			assert.strictEqual(
				container1.deltaManager.outbound.length,
```

File: packages/loader/container-loader/src/utils.ts (hunk 9 above)
Comment (jason-ha) [reply packages/loader/container-loader/src/utils.ts:435]: I think `container-definitions` should remain types only as best we can. (darn enums) That said there are a few helpers there already and I don't know where such a util should live, if not here or there.

File: packages/runtime/runtime-utils/src/deltaManager.ts
Comment (jason-ha) [inline packages/runtime/runtime-utils/src/deltaManager.ts:1]: Should toDeltaManagerInternal be updated to return IDeltaManagerInternal?

File: packages/test/local-server-tests/src/test/opsOnReconnect.spec.ts (hunk 5 above)
Comment (jason-ha) [reply packages/test/local-server-tests/src/test/opsOnReconnect.spec.ts:659]: That should also work, but it will be a lot of extra lines compared to cast helper.

File: packages/test/test-end-to-end-tests/src/test/containerDirtyFlag.spec.ts (hunk 8 above)
Comment (jason-ha) [reply packages/test/test-end-to-end-tests/src/test/containerDirtyFlag.spec.ts:70]: Probably could be resolved by updating `toDeltaManagerInternal` to return `IDeltaManagerInternal`.

File: packages/common/container-definitions/api-report/container-definitions.legacy.alpha.api.md (hunk 6 above)
Comment (jatgarg) [reply packages/common/container-definitions/api-report/container-definitions.legacy.alpha.api.md:208]: They removed that usage already.

File: packages/common/container-definitions/api-report/container-definitions.legacy.alpha.api.md (hunk 7 above)
Comment (jatgarg) [reply packages/common/container-definitions/api-report/container-definitions.legacy.alpha.api.md:207]: We will follow up with a separate task for that.

File: packages/loader/container-loader/src/utils.ts (hunk 9 above)
Comment (jatgarg) [reply packages/loader/container-loader/src/utils.ts]: Yes, I am of the same opinion where I don't want to put helper functions into the definition's packages.

Comment (Josmithr) [reply packages/loader/container-loader/src/utils.ts]: Hmm. I guess a type-narrowing free function seems pretty appropriate for a types-focused package. I don't feel super strongly about this, but I do think we should avoid recreating the same function in a bunch of places. Is there a reasonable place we could share this function, if not in the same package as the type?

File: packages/test/test-end-to-end-tests/src/test/containerDirtyFlag.spec.ts (hunk 8 above)
Comment (jatgarg) [reply packages/test/test-end-to-end-tests/src/test/containerDirtyFlag.spec.ts:70]: Yeah, I didn't realized we already have a method name IDeltaManagerInternal which actually returns IDeltaManager and not IDeltaManagerInternal.
So, I don't think we can make toIDeltaManagerInternal return IDeltaManagerInternal as it actually wants to expose IDeltaManager. So, I think I should rename IDeltaManagerInternal to IDeltaManagerFull which sorts of represents that it is full interface exposing some other props as well.

File: packages/common/container-definitions/src/index.ts [hunk 11]
```diff
@@ -18,6 +18,7 @@ export { isFluidBrowserPackage } from "./browserPackage.js";
 export type {
 	IConnectionDetails,
 	IDeltaManager,
+	IDeltaManagerInternal,
 	IDeltaManagerEvents,
```
[the remark this answers is not in the document]
Comment (jatgarg) [reply packages/common/container-definitions/src/index.ts]: fixed.

File: packages/runtime/runtime-utils/src/deltaManager.ts (hunk 10 above)
Comment (jatgarg) [reply packages/runtime/runtime-utils/src/deltaManager.ts:42]: Moved it to container-definitions

File: packages/loader/container-loader/src/utils.ts (hunk 9 above)
Comment (jatgarg) [reply packages/loader/container-loader/src/utils.ts]: Moved it to container-definitions

File: packages/test/test-end-to-end-tests/src/test/containerDirtyFlag.spec.ts (hunk 8 above)
Comment (jatgarg) [reply packages/test/test-end-to-end-tests/src/test/containerDirtyFlag.spec.ts]: toDeltaManagerInternal is legacy and alpha. Also, I renamed IDeltaManagerInternal to IDeltaManagerFull
 which represents that it has all/extra props. IDeltaManagerInternal is expose publicly by shared Object.

File: packages/test/local-server-tests/src/test/opsOnReconnect.spec.ts (hunk 5 above)
Comment (jatgarg) [reply packages/test/local-server-tests/src/test/opsOnReconnect.spec.ts]: Fixed it.

File: packages/runtime/runtime-utils/src/deltaManager.ts
Comment (jatgarg) [reply packages/runtime/runtime-utils/src/deltaManager.ts:1]: No, it is alpha/legacy. I also renamed IDeltaManagerInternal  to IDeltaManagerFull, since it represents something else. You can take a look know once.

File: packages/test/test-utils/src/containerUtils.ts [hunk 12]
```diff
@@ -89,3 +97,16 @@ export async function getDataStoreEntryPointBackCompat<T>(dataStore: IDataStore)
 	assert(response.status === 200, "empty request should return data object");
 	return response.value as T;
 }
+
+/**
+ * @internal
+ */
+export function assertIsIDeltaManagerFull(
```
Comment (jason-ha) [inline packages/test/test-utils/src/containerUtils.ts:104]: naming nit: I would expect `assertIs*` to assert and return void.
An alternate name would be `toIDeltaManagerFullAsserted` though I think we'd also be fine with just `toIDeltaManagerFull`.

File: packages/test/test-utils/src/containerUtils.ts [hunk 13]
```diff
@@ -89,3 +97,16 @@ export async function getDataStoreEntryPointBackCompat<T>(dataStore: IDataStore)
...
+	deltaManager: IDeltaManager<ISequencedDocumentMessage, IDocumentMessage>,
+): IDeltaManagerFull {
+	assert(
+		"inbound" in deltaManager && "outbound" in deltaManager,
+		"Delta manager does not have inbound/outbound queues.",
+	);
+	return deltaManager as IDeltaManagerFull;
```
Comment (jason-ha) [inline packages/test/test-utils/src/containerUtils.ts:111]: Some use case could be simplified if this allowed `IDeltaManagerErased | IDeltaManager<ISequencedDocumentMessage, IDocumentMessage>`.
The return line could go with `deltaManager as unknown as IDeltaManagerFull` (or if you wanted to be extra careful `deltaManager as unknown as IDeltaManagerErased | IDeltaManager<ISequencedDocumentMessage, IDocumentMessage> as IDeltaManagerFull`).

File: packages/test/test-end-to-end-tests/src/test/containerDirtyFlag.spec.ts (hunk 8 above)
Comment (jason-ha) [reply packages/test/test-end-to-end-tests/src/test/containerDirtyFlag.spec.ts]: 👍I think I must have looked at toDeltaManagerErased tagging.

**Review by jason-ha — APPROVED** [review]
Be sure to update PR description - still says `IDeltaManagerInternal`

**Comment by jason-ha** [comment]
Two new notes:
1. We just had another break change break Loop. I would recommend running (rerunning) the [Loop integration tests](https://eng.ms/docs/experiences-devices/opg/office-shared/fluid-framework/fluid-framework-internal/fluid-framework/docs/dev/monitoring/ff-loop-testing) as due diligence.
2. Please add a change set. Tyler just added a "Legacy API Changes" section so the changeset can target that. (Set `"section"` to `legacy`)

**Review by anthony-murphy — APPROVED** [review]
api changes look good

**Comment by jatgarg** [comment]
Integration pipeline with Loop succeeded for the breaking change: https://dev.azure.com/office/OC/_build/results?buildId=32410848&view=results

File: packages/framework/fluid-static/package.json [hunk 14]
```diff
@@ -140,7 +140,11 @@
 		"typescript": "~5.4.5"
 	},
 	"typeValidation": {
-		"broken": {},
+		"broken": {
+			"Interface_IFluidContainerInternal": {
+				"backCompat": false
+			}
+		},
```
Comment (tylerbutler) [inline packages/framework/fluid-static/package.json:147]: I'm very naive - is this safe? cc: @ChumpChief

File: .changeset/nice-flies-brake.md [hunk 15]
```diff
@@ -0,0 +1,25 @@
...
+"@fluidframework/test-runtime-utils": minor
+"@fluidframework/test-utils": minor
+---
+---
+"section": legacy
+---
+
+The inbound and outbound properties have been removed from IDeltaManager
+
+The inbound and outbound properties were deprecated in a previous release and have been removed from IDeltaManager. Please check pull request [#19636](https://github.com/microsoft/FluidFramework/pull/19636) for alternative APIs.
```
Comment (Josmithr) [inline .changeset/nice-flies-brake.md:22]: I would recommend including the instructions directly here, rather than linking to a PR. That's a lot of navigation steps for our users to jump through to get the information they need.

**Review by Josmithr — APPROVED** [review]
Left a small changeset recommendation, but otherwise docs changes look good.

**Comment by jatgarg** [comment]
Will make the change in another PR. Auto merge was on, so it got merged.
