### PR TITLE
Fixed: loader.request not passing headers to the container

### LINKED ISSUE #6806: Loader.request does not propagate headers to container.request
Any headers as part of the request in loader.request are not passed to the container. The `externalRequest` header for instance is not passed to the container which results in the associated feature to not work.

### PR DESCRIPTION
**Pull request by agarwal-navin**
Fixes #6806
In loader.request, passed the original request with only the url modified to container.request. Added tests.

### CODE REVIEW

File: packages/loader/container-loader/src/loader.ts [hunk 1]
```diff
@@ -366,7 +366,10 @@ export class Loader implements IHostLoader {
     public async request(request: IRequest): Promise<IResponse> {
         return PerformanceEvent.timedExecAsync(this.logger, { eventName: "Request" }, async () => {
             const resolved = await this.resolveCore(request);
-            return resolved.container.request({ url: `${resolved.parsed.path}${resolved.parsed.query}` });
+            return resolved.container.request({
+                ...request,
```
Comment (markfields) [inline packages/loader/container-loader/src/loader.ts:370]: Opinion: This is probably ok, but I would lean towards more explicitly copying just the headers. As-is, if/when request gets additional stuff on it (whether via `IRequest` type or just patched on), it will be copied over, which may not be correct but won't be obvious.

Comment (agarwal-navin) [reply packages/loader/container-loader/src/loader.ts:370]: The idea is that only the url is updated by the loader since it has to remove the container specific part. The rest should be sent as-is to the container. The call to container.request should be no different than calling container.request directly with the request (minus the container id in the url part).

Comment (markfields) [reply packages/loader/container-loader/src/loader.ts:370]: Ok that makes sense. Thanks.

**Review by markfields — APPROVED** [review]
🎂 Makes sense to me but I'm no authority on this part of the code (yet...! 🕵️‍♂️)
