### PR TITLE
Fix for initial signals getting lost in local driver due to race condition

### LINKED ISSUE #5023: Audience doesn't have the updated current user info after it switches to write mode
## Describe the bug
The audience from the local server used in demo-host is not correctly updated and doesn't contain the current user information after switching from read to write mode.

The issue here looks like it comes from the local-driver; when the current user switches to 'write' mode, it seems that is inserted into a duplicate audience object and is not the one exposed through the container. Tested with Navin a quick fix using this [package](https://offnet.visualstudio.com/officenet/_packaging?_a=package&feed=prague&package=%40fluidframework-test%2Flocal-test-driver&version=0.1.0&protocolType=Npm) and it seems to work fine.

### To Reproduce
Steps to reproduce the behavior: in order to repro I used demo-host app from bohemia.
1. Insert a component.
2. Attach the component.
3. Write something (so that the client switches to 'write' mode).
4. Insert/Load the same component again.

### Expected behavior
I would expect that the UI would reflect the second coauthor and remove the Last Edited UI from the component ux.

### PR DESCRIPTION
**Pull request by agarwal-navin**
Fixes #5023.

**Root-cause:** Server emits the `clientJoin` signal right after `connect_document_success`.
`LocalDocumentDeltaConnection` removes the initial op and signal handlers immediately after getting `connect_document_success` event. It then returns the delta connection to delta manager which set ups its event handlers on the socket. There is a race condition in between this where the `clientJoin` signal can get lost.

**Fix:** This has already been solved by odsp and routerlicious drivers. They use `DocumentDeltaConnection` as the base class which handles this race condition. Updated `LocalDocumentDeltaConnection` to use this base class as well.

**Problem with this fix:** I added a cast from `LocalWebSocket` to `SocketIOClient.Socket` which is a little ugly. So if that seems like a problem, we can handle this race similar to how `DocumentDeltaConnection` does, i.e., by removing the initial op and signal handlers when delta manager requests for initial signals.

### CODE REVIEW

File: packages/drivers/local-driver/src/localDocumentDeltaConnection.ts [hunk 1]
```diff
@@ -42,130 +38,23 @@ export class LocalDocumentDeltaConnection
...
-                (error) => {
-                    if (error) {
-                        debug("Emit error", error);
-                    }
-                });
-        });
+    constructor(socket: LocalWebSocket, documentId: string) {
+        // Cast LocalWebSocket to SocketIOClient.Socket which is the socket that the base class needs. Doing this
+        // should be fine because this delta connection is used for local use only.
+        const socketWithListener = socket as unknown as SocketIOClient.Socket;
```
Comment (vladsud) [inline packages/drivers/local-driver/src/localDocumentDeltaConnection.ts:48]: Any chance we push these requirements / assumptions up the stack? I see caller does another cast, it would be great to push these casts out to consumers

**Review by vladsud — APPROVED** [review]

**Review by tanviraumi — APPROVED** [review]

File: packages/drivers/local-driver/src/localDocumentDeltaConnection.ts (hunk 1 above)
Comment (agarwal-navin) [reply packages/drivers/local-driver/src/localDocumentDeltaConnection.ts:48]: I can move it to the create function. But I don't think it can be moved up any further.
