### PR TITLE
Fix for 8995 - Number of times summarizer refreshes snapshot is too high

### LINKED ISSUE #8995: Number of times summarizer refreshes snapshot is too high
I do not know how urgent / important this issue is, leaving to Paul to triage and make decision if Feb is appropriate.

Marcelo brought to my attention, that empty meeting notes documents continuously summarize, without any user changes. This looks like FFX bug (tracked separately), so this issue is not about that.
But as it summarizes, it does a lot of fetches of not-latest snapshots.
Looking at sample session, I do see these events pointing to issue:
> fluid:telemetry:Summarizer:RefreshLatestSummaryGetSnapshot_end {"fetchLatest":false}
fluid:telemetry:OdspDriver:LastSummaryProposedHandleMismatch

Unfortunately meeting notes scenario does not send data to our Aria tenant.
But I see that many summaries hit the same issue - these are counts for 1 day across all scenarios that send data:

> fluid:telemetry:Summarizer:Running:SummaryOp	254132
fluid:telemetry:OdspDriver:LastSummaryProposedHandleMismatch	50648
fluid:telemetry:Summarizer:RefreshLatestSummaryGetSnapshot_end	19414

It's definitely not normal to see that many cases where we need to refresh snapshots. And it's not clear why driver complains that we are referencing wrong parent snapshot. It would be great to analyze why it happens, and if we see sessions where it happens all the time like in meeting notes scenario

Sample meeting note file that demonstrates the issue:
https://www.onenote.com/notes/c3BvOmh0dHBzOi8vbWljcm9zb2Z0LW15LnNoYXJlcG9pbnQtZGYuY29tL3BlcnNvbmFsL21hcmNtYXNfbnRkZXZfbWljcm9zb2Z0X2NvbQ==/b!lql55Wf6D0qBqgrMMcpaiDshzUolNf1DofbCZqkstIk8wHnov-bCQ6pHMry6gSbx/016K3AXJF6AK7FAKU6YZGZ5BGBIDNXWPFW

### PR DESCRIPTION
**Pull request by NicholasCouri**
Create a separate expiration for the summarizer first run. 

Note: I'm not sure if this is the best direction but I was thinking we might even propagate this timeout from the SummaryConfiguration through the hostPolicy ?? Or not ? 

I did the initial tests and it seems to work fine - will run the ci:test  but wanted to get feedbacks.

### CODE REVIEW

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts [hunk 1]
```diff
@@ -457,6 +460,21 @@ export class OdspDocumentStorageService implements IDocumentStorageService {
 
                         retrievedSnapshot = await cachedSnapshotP;
 
+                        // In order to decrease the number of times we have to execute a snapshot refresh,
+                        // if this is the summarizer and we have a cache entry but it is past the defaultFirstSummaryCacheExpiryTimeout,
+                        // force the network retrieval instead as there might be a more recent snapshot available.
+                        if (retrievedSnapshot !== undefined &&
+                            this.hostPolicy.summarizerClient &&
+                            this.lastCacheEntryTime !== undefined) {
+                            const cacheAge = Date.now() - this.lastCacheEntryTime;
```
Comment (tyler-cai-microsoft) [inline packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:469]: We are calculating cache age twice now. Note that if `snapshotCachedEntry.cacheEntryTime` is `undefined`, that means the snapshot is older than the code itself. 

Here's the other calculation.
`const age = Date.now() - (snapshotCachedEntry.cacheEntryTime ?? (Date.now() - 30 * 24 * 60 * 60 * 1000));`

Comment (NicholasCouri) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:469]: Yes, the idea is to forcibly update the cache if a summarizer kicks in and it has been more than 60 seconds the cache has been updated. 
Notice this will only happen if this.firstVersionCall && count === 1 && (blobid === null || blobid === this.documentId) + IsSummarizer  and we did retrieve a snapthot.

Comment (tyler-cai-microsoft) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:469]: We are already recording cacheAge `props["cacheEntryAge"] = age`

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts [hunk 2]
```diff
@@ -180,6 +180,7 @@ export class OdspDocumentStorageService implements IDocumentStorageService {
 
     private firstVersionCall = true;
     private _snapshotSequenceNumber: number | undefined;
+    private readonly defaultFirstSummaryCacheExpiryTimeout = 60 * 1000; // 60 seconds.
```
Comment (agarwal-navin) [inline packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:183]: nit: `defaultSummarizerCacheExpryTimeout`. Not sure what first summary signifies but it could be for both summarizer and non-summarizer clients.

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts [hunk 3]
```diff
@@ -413,6 +414,16 @@ export class OdspDocumentStorageService implements IDocumentStorageService {
                                     const age = Date.now() - (snapshotCachedEntry.cacheEntryTime ??
                                         (Date.now() - 30 * 24 * 60 * 60 * 1000));
 
+                                    // In order to decrease the number of times we have to execute a snapshot refresh,
+                                    // if this is the summarizer and we have a cache entry but it is past the defaultFirstSummaryCacheExpiryTimeout,
+                                    // force the network retrieval instead as there might be a more recent snapshot available.
+                                    if (this.hostPolicy.summarizerClient &&
+                                        age > this.defaultFirstSummaryCacheExpiryTimeout) {
+                                        // eslint-disable-next-line @typescript-eslint/dot-notation
+                                        props["cacheSummarizerExpired"] = 1;
```
Comment (agarwal-navin) [inline packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:423]: Is setting to `true` better?

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts [hunk 4]
```diff
@@ -413,6 +414,16 @@ export class OdspDocumentStorageService implements IDocumentStorageService {
                                     const age = Date.now() - (snapshotCachedEntry.cacheEntryTime ??
                                         (Date.now() - 30 * 24 * 60 * 60 * 1000));
 
+                                    // In order to decrease the number of times we have to execute a snapshot refresh,
+                                    // if this is the summarizer and we have a cache entry but it is past the defaultFirstSummaryCacheExpiryTimeout,
+                                    // force the network retrieval instead as there might be a more recent snapshot available.
+                                    if (this.hostPolicy.summarizerClient &&
```
Comment (agarwal-navin) [inline packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:420]: @vladsud Can you check / confirm that updating the code here is enough to fix this issue?

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts (hunk 3 above)
Comment (agarwal-navin) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:423]: nit: `summarizerCacheExpired` probably reads better.

**Comment by agarwal-navin** [comment]
Can we add tests that validate this? @tyler-cai-microsoft I don't remember how you tested the cache expiry for the GC work. Are there unit tests / end-to-end tests that can be written for this?

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts [hunk 5]
```diff
@@ -413,6 +414,16 @@ export class OdspDocumentStorageService implements IDocumentStorageService {
...
+                                        age > this.defaultFirstSummaryCacheExpiryTimeout) {
+                                        // eslint-disable-next-line @typescript-eslint/dot-notation
+                                        props["cacheSummarizerExpired"] = 1;
+                                        return undefined;
+                                    }
```
Comment (tyler-cai-microsoft) [inline packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:425]: This looks good, now that I think about this code, since it has to be done here, we have a few different cases in which we need to expire/not use the cache. It would be awesome to move this logic into one place, as we are just expiring the cache. It may be helpful to future engineers if we conglomerate this code into one place

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts (hunk 2 above)
Comment (tyler-cai-microsoft) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:183]: `defaultSummarizerCacheExpryTimeoutMs`

**Comment by tyler-cai-microsoft** [comment]
> Can we add tests that validate this? @tyler-cai-microsoft I don't remember how you tested the cache expiry for the GC work. Are there unit tests / end-to-end tests that can be written for this?

I made changes to the `getVersions.spec.ts` file in the tests folder.

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts (hunk 3 above)
Comment (NicholasCouri) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:423]: defaultSummarizerCacheExpryTimeout

**Review by agarwal-navin — APPROVED** [review]

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts (hunk 4 above)
Comment (vladsud) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:421]: It looks fine to me. That said, some feedback:
1. It's useful to put issue references in the code, as they have way more data about reasoning, stats, etc. Something that comes handy next time when we need to change it or question the decision
2. It would be great to have telemetry when we reject it, to be able to assess if we should tune the number upwards.
