### PR TITLE
Simplified the attach / bind states in data store runtime. Fixed bug #9127.

### LINKED ISSUE #9127: Adding handle to data store in detached container doesn't bind the data store
This bug prevents the removal of `bindToContext` API that is called on a data store after its creation. We need to remove this asap as that affects GC.

In detached container, when a handle to a data store is attached to a bound DDS (DDS in root data stores), the data store is not bound. So, requesting it via the `request` API hangs forever. See the test added by this PR for an example of this - https://github.com/microsoft/FluidFramework/pull/9129. This test should be enabled once this bug is fixed.

Expected behavior - When a data store's handle is added to a bound DDS, it should be reachable and returned via the `request` APIs irrespective of whether the container is attached or not.

### PR DESCRIPTION
**Pull request by agarwal-navin**
Fixes #9127. Note that this bug will still happen when using these bits with older bits of container runtime of data store runtime. Only when the versions of both of these are current or newer, this bug won't happen.

Added `VisibilityState` to data store runtime. It has 3 values:
1. not visible - Created for the first time.
2. locally visible - Visible and reachable within the container locally.
3. globally visible - Visible and reachable to all clients connected to the document.

A local data store transitions from not visible -> locally visible -> globally visible without exception. A remote data store is globally visible by default.

Here is when the state transition happens:
- In detached container
  - A root data store becomes immediately locally visible by calling `makeVisibleAndAttachGraph` on its runtime. All its bound handles also recursively become locally visible.
  - Non-root data stores become locally visible when their handles are added to a locally visible DDS. This calls `attachGraph` on the runtime. All their bound handles also recursively become locally visible.
  - When the container attaches, it makes all its locally visible data stores globally visible by emitting "attaching" event. The data store marks all its DDS channels globally visible as well.
- In attached container
  - A root data store becomes immediately locally visible by calling `makeVisibleAndAttachGraph` on its runtime. All its bound handles also recursively become locally visible. All the data stores in this graph are made globally visible as well by emitting "attaching" event on them and sending an attach op.
  - Non-root data stores become locally visible when their handles are added to a locally visible DDS. This calls `attachGraph` on the runtime. All their bound handles also recursively become locally visible. All the data stores in this graph are made globally visible as well by emitting "attaching" event on them and sending an attach op.

### CODE REVIEW

File: packages/runtime/datastore/src/fluidHandle.ts [hunk 1]
```diff
@@ -36,40 +49,41 @@ export class FluidObjectHandle<T extends FluidObject = IFluidObject> implements
         public readonly routeContext: IFluidHandleContext,
     ) {
         this.absolutePath = generateHandleContextPath(path, this.routeContext);
+        if (this.isAttached) {
```
Comment (agarwal-navin) [inline packages/runtime/datastore/src/fluidHandle.ts:52]: Tracking of visibility state (or graph attach state before) in handles is bound to have problems. There can be many handles to a data store or DDS.
For data stores, only the one stored in another DDS will have this state correctly updated. Other handles, if they were created before data store was visible (or attached) will not know this state.
For DDS, only the default handle will know this state. Any additional handles to it won't know this state.

It `bind` is called on these handles with another handle, the second one may not be bound even if the underlying object is locally visible.

Comment (agarwal-navin) [reply packages/runtime/datastore/src/fluidHandle.ts:52]: Also, since bind, attachGraph and isAttached are part of IFluidHandle, it defeats our model of using handles as light weight object for passing around within a container. For that purpose, handles don't need these APIs / properties and it only adds confusion.

These states are only ever interesting for the default DDS handle because it can bind other handles.  For other handles, like blob handle, these don't make sense. Tracking these states and `boundHandles` for data store handles don't make sense either because data store runtime already has these. So, this state is duplicated to all handles of a data store which makes its very hard to keep them in sync. Nobody should call bind on a data store's handle.

We should make a special purpose handle for DDSes and remove these from IFluidHandle.

Comment (agarwal-navin) [reply packages/runtime/datastore/src/fluidHandle.ts:52]: @vladsud @anthony-murphy

File: api-report/runtime-definitions.api.md [hunk 2]
```diff
@@ -378,6 +384,16 @@ export type NamedFluidDataStoreRegistryEntry = [string, Promise<FluidDataStoreRe
 // @public (undocumented)
 export type SummarizeInternalFn = (fullTree: boolean, trackState: boolean) => Promise<ISummarizeInternalResult>;
 
+// @public
+enum VisibilityState_2 {
+    GloballyVisible = "GloballyVisible",
```
Comment (tyler-cai-microsoft) [inline api-report/runtime-definitions.api.md:389]: How about Connected state - `GloballyConnected`, `LocallyConnected`, `Disconnected`

File: packages/runtime/container-runtime/src/dataStores.ts [hunk 3]
```diff
@@ -291,14 +290,20 @@ export class DataStores implements IDisposable {
...
     }
 
-    public bindFluidDataStore(fluidDataStoreRuntime: IFluidDataStoreChannel): void {
-        const id = fluidDataStoreRuntime.id;
+    /**
+     * Makes the data store with the given id visible in the container graph by moving the data store context from
+     * unbound to bound list. This data store can now be reached from the root.
+     * @param id - The id of the data store context to make visible.
+     */
+    public makeDataStoreVisible(id: string): void {
```
Comment (tyler-cai-microsoft) [inline packages/runtime/container-runtime/src/dataStores.ts:298]: Are we connecting globally or locally?

File: packages/runtime/datastore/src/dataStoreRuntime.ts [hunk 4]
```diff
@@ -377,38 +391,52 @@ IFluidDataStoreChannel, IFluidDataStoreRuntime, IFluidHandleContext {
...
+    public makeVisibleAndAttachGraph() {
+        if (this.visibilityState !== VisibilityState.NotVisible) {
             return;
         }
-        this.graphAttachState = AttachState.Attaching;
+        this.visibilityState = VisibilityState.LocallyVisible;
+
         if (this.boundhandles !== undefined) {
             this.boundhandles.forEach((handle) => {
                 handle.attachGraph();
```
Comment (tyler-cai-microsoft) [inline packages/runtime/datastore/src/dataStoreRuntime.ts:428]: Will there be a need to make each handle visible? I don't know exactly what boundhandles is (it should also probably be named `boundHandles`)

File: api-report/runtime-definitions.api.md (hunk 2 above)
Comment (agarwal-navin) [reply api-report/runtime-definitions.api.md:389]: We already have connected state which means something totally different. This is more about the data store being visible or reachable within a container and / or from all clients in the document.

File: packages/runtime/container-runtime/src/dataStores.ts (hunk 3 above)
Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/dataStores.ts:298]: Well, the data store calls here when it is ready to be locally visible. It may also become globally visible if the container is attached.
DataStores moves it from unbound to bound list essentially making it visible (or reachable) in this container. Basically, this data store can now be retrieved by calling `getDataStore`.

File: packages/runtime/datastore/src/dataStoreRuntime.ts (hunk 4 above)
Comment (agarwal-navin) [reply packages/runtime/datastore/src/dataStoreRuntime.ts:428]: Calling `attachGraph` will make them locally visible. Basically, it this results in calling attachGraph() on another data store, it will also become locally visible (see attachGraph()).
`boundHandles` are the handles for which `bind` method was called on this data store. If we were not visible then, these handles are added to a list called `boundHandles`.

What should also be named boundHandles?

**Comment by agarwal-navin** [comment]
@anthony-murphy @vladsud Ping. Can you please take a look :-).

File: packages/runtime/container-runtime/src/dataStores.ts (hunk 3 above)
Comment (tyler-cai-microsoft) [reply packages/runtime/container-runtime/src/dataStores.ts:298]: From what I understand, this method makes the datastore locally visible, and global visibility is a side effect of the container being attached. It would be cool if we call this `makeDataStoreLocallyVisible`; however, I'm not sure how we want to indicate this side effect.

File: packages/runtime/datastore/src/dataStoreRuntime.ts (hunk 4 above)
Comment (tyler-cai-microsoft) [reply packages/runtime/datastore/src/dataStoreRuntime.ts:428]: `boundhandles` -> `boundHandles` the `H` should be capitalized.

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 5]
```diff
@@ -1791,7 +1791,13 @@ export class ContainerRuntime extends TypedEventEmitter<IContainerRuntimeEvents>
...
     private async createRootDataStoreLegacy(pkg: string | string[], rootDataStoreId: string): Promise<IFluidRouter> {
         const fluidDataStore = await this._createDataStore(pkg, true /* isRoot */, rootDataStoreId);
-        fluidDataStore.bindToContext();
+        // back-compat 0.58.2000 - makeVisibleAndAttachGraph was added in this version to IFluidDataStoreChannel. For
+        // older versions, we still have to call bindToContext.
+        if (fluidDataStore.makeVisibleAndAttachGraph !== undefined) {
+            fluidDataStore.makeVisibleAndAttachGraph();
+        } else {
+            fluidDataStore.bindToContext();
+        }
```
Comment (tyler-cai-microsoft) [inline packages/runtime/container-runtime/src/containerRuntime.ts:1800]: Why would this be undefined? fluidDataStore.makeVisibleAndAttachGraph !== undefined, if the container runtime is in 58.2000, then the datastores it creates would have to have makeVisibileAndAttachGraph as defined right? Is this back compat for older documents?

File: packages/runtime/datastore/src/fluidHandle.ts [hunk 6]
```diff
@@ -24,6 +21,22 @@ export class FluidObjectHandle<T extends FluidObject = IFluidObject> implements
...
+     * Tells whether the object of this handle is visible in the container.
+     */
+    private get visible(): boolean {
+        /**
+         * If the object of this handle is attached, it is visible in the container. This is a work around the scenario
+         * where the object becomes visible but the handle does not get this notification. For example, handles to a DDS
+         * other than the default handle won't know if the DDS becomes visible after the handle was created.
+         */
+        if (this.isAttached) {
+            this._visible = true;
```
Comment (tyler-cai-microsoft) [inline packages/runtime/datastore/src/fluidHandle.ts:34]: could we use the this.visibilityState === locallyVisible || this.visibilityState === globallyVisible instead of a flag here?

File: packages/runtime/datastore/src/fluidHandle.ts [hunk 7]
```diff
@@ -36,40 +49,41 @@ export class FluidObjectHandle<T extends FluidObject = IFluidObject> implements
...
-            for (const handle of this.bound) {
+
+        this._visible = true;
+        if (this.boundHandles !== undefined) {
+            for (const handle of this.boundHandles) {
                 handle.attachGraph();
             }
 
-            this.bound = undefined;
+            this.boundHandles = undefined;
```
Comment (tyler-cai-microsoft) [inline packages/runtime/datastore/src/fluidHandle.ts:72]: why would we want to unbind all the bound handles?

File: packages/runtime/datastore/src/fluidHandle.ts [hunk 8]
```diff
@@ -36,40 +49,41 @@ export class FluidObjectHandle<T extends FluidObject = IFluidObject> implements
...
-        // If this handle is already in attaching state in the graph or attached, no need to attach again.
-        if (this.graphAttachState !== AttachState.Detached) {
+        if (this.visible) {
             return;
         }
-        this.graphAttachState = AttachState.Attaching;
-        if (this.bound !== undefined) {
-            for (const handle of this.bound) {
+
+        this._visible = true;
```
Comment (tyler-cai-microsoft) [inline packages/runtime/datastore/src/fluidHandle.ts:66]: I would prefer if we were setting the graph to locally or globally visible at this point.

File: packages/runtime/datastore/src/dataStoreRuntime.ts [hunk 9]
```diff
@@ -851,16 +884,34 @@ IFluidDataStoreChannel, IFluidDataStoreRuntime, IFluidHandleContext {
...
+             * 2) After attachGraph() is called - When a detached container is attached.
+             *
+             * The basic idea is that all local object should become locally visible before they are globally visible.
+             */
+            this.attachGraph();
+
             this._attachState = AttachState.Attaching;
+
+            assert(this.visibilityState === VisibilityState.LocallyVisible,
+                `Data store should not attach if is not locally visible - ${this.visibilityState}`);
```
Comment (tyler-cai-microsoft) [inline packages/runtime/datastore/src/dataStoreRuntime.ts:901]: Data store should only attach if it is locally visible? In my mind, if the visibilityState is globally visible also means it's locally visible.

File: packages/runtime/datastore/src/dataStoreRuntime.ts [hunk 10]
```diff
@@ -851,16 +884,34 @@ IFluidDataStoreChannel, IFluidDataStoreRuntime, IFluidHandleContext {
...
+                channel.makeVisible();
+            });
+            this.localChannelContextQueue.clear();
+
             // This promise resolution will be moved to attached event once we fix the scheduler.
             this.deferredAttached.resolve();
             this.emit("attaching");
         });
         this.dataStoreContext.once("attached", () => {
-            assert(this.bindState === BindState.Bound,
```
Comment (tyler-cai-microsoft) [inline packages/runtime/datastore/src/dataStoreRuntime.ts:862]: Should we be checking the visibilityState here?

File: packages/runtime/datastore/src/localChannelContext.ts [hunk 11]
```diff
@@ -38,7 +38,7 @@ import { ChannelStorageService } from "./channelStorageService";
  */
 export abstract class LocalChannelContextBase implements IChannelContext {
     public channel: IChannel | undefined;
-    private attached = false;
+    private globallyVisible = false;
```
Comment (tyler-cai-microsoft) [inline packages/runtime/datastore/src/localChannelContext.ts:41]: can we make this a getter and internally use VisibilityState somehow?

File: packages/runtime/container-runtime/src/dataStores.ts (hunk 3 above)
Comment (tyler-cai-microsoft) [reply packages/runtime/container-runtime/src/dataStores.ts:298]: Also, how much of this logic can we move to the datastore itself? I'd prefer we'd have as little logic here if all we're using it is in the datastore itself.

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 5 above)
Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/containerRuntime.ts:1800]: FluidDataStoreRuntime (data store runtime layer) is in a different layer than ContainerRuntime and DataStoreContext (container runtime layer) and they can have different versions. We have to support N-2 compat across these 2 layers.

File: packages/runtime/container-runtime/src/dataStoreContext.ts [hunk 12]
```diff
@@ -280,11 +282,23 @@ export abstract class FluidDataStoreContext extends TypedEventEmitter<IFluidData
...
             this.containerRuntime.attachState : AttachState.Detached;
 
+        /**
+         * The existing flag can be true in two conditions:
+         * 1. It's a local data store that is created when a detached container is rehydrated. In this case, the data
+         *    store is locally visible because the snapshot it is loaded from contains locally visible data stores only.
+         * 2. It's a remote data store that is created when an attached container is loaded is loaded from snapshot or
+         *    when an attach op comes in. In both these cases, the data store is already globally visible.
+         */
+        if (existing) {
```
[the remark this answers is not in the document]
Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/dataStoreContext.ts:292]: I don't think it existing vs this.existing matter in the constructor.
To pass in visibility state here, we need to teach visibility state to ContainerRuntime / DataStores. We can (and probably should) do that but I don't want to do it in this PR. The `existing` flag drives other things in layers below data store context as well so we cannot easily remove it.

File: packages/runtime/container-runtime/src/dataStoreContext.ts [hunk 13]
```diff
@@ -280,11 +282,23 @@ export abstract class FluidDataStoreContext extends TypedEventEmitter<IFluidData
...
+            this.visibilityState = this.containerRuntime.attachState === AttachState.Detached
+                ? VisibilityState.LocallyVisible : VisibilityState.GloballyVisible;
+        }
+
         this.bindToContext = () => {
```
[the remark this answers is not in the document]
Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/dataStoreContext.ts:297]: Not sure. Maybe it made sense to have it inline here in the past but I don't think it matters anymore.

File: packages/runtime/container-runtime/src/dataStoreContext.ts (hunk 12 above)
[the remark this answers is not in the document]
Comment (tyler-cai-microsoft) [reply packages/runtime/container-runtime/src/dataStoreContext.ts:292]: Here's a techdebt issue https://github.com/microsoft/FluidFramework/issues/9646

File: packages/runtime/container-runtime/src/dataStores.ts (hunk 3 above)
Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/dataStores.ts:298]: From data store's perspective, its ready to be visible (both locally and globally). Whether it becomes globally visible or not is up to the container runtime and it controls when the data store becomes globally visible.
Ideally I would want the data store to not even care about being globally visible but today it does.

File: packages/runtime/container-runtime/src/dataStoreContext.ts (hunk 12 above)
[the remark this answers is not in the document]
Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/dataStoreContext.ts:292]: You should add that you are talking about the data store context layer. This is because existing flag is in other layers too. Also, visibility state is added by this PR which isn't merged yet so you should mention that you are talking about the state as is being added by this PR.
Andrei had worked on removing existing state from a bunch of places so might be worth talking to him about this.

File: packages/runtime/datastore/src/dataStoreRuntime.ts [hunk 14]
```diff
@@ -377,38 +391,52 @@ IFluidDataStoreChannel, IFluidDataStoreRuntime, IFluidHandleContext {
...
 
-            // If our data store is local then add the channel to the queue
-            if (!this.localChannelContextQueue.has(channel.id)) {
-                this.localChannelContextQueue.set(channel.id, this.contexts.get(channel.id) as LocalChannelContextBase);
-            }
+        /**
+         * If this channel has already been bound, do nothing. This can happen during attachGraph() when a channel's
+         * graph is attached. It calls bindToContext on the shared object which will end up back here.
+         */
+        if (this.boundhandles !== undefined && this.boundhandles.has(channel.handle)) {
```
[the remark this answers is not in the document]
Comment (agarwal-navin) [reply packages/runtime/datastore/src/dataStoreRuntime.ts:400]: I am not sure what you mean. Can you please elaborate?

File: packages/runtime/datastore/src/dataStoreRuntime.ts [hunk 15]
```diff
@@ -377,38 +391,52 @@ IFluidDataStoreChannel, IFluidDataStoreRuntime, IFluidHandleContext {
...
+    /**
+     * This function is called when a data store becomes root. It does the following:
+     * 1. Marks the data store locally visible in the container.
+     * 2. Attaches the graph of all the handles bound to it.
+     * 3. Calls into the data store context to mark it visible in the container too. If the container is globally
+     *    visible, it will mark us globally visible. Otherwise, it will mark us globally visible when it becomes
+     *    globally visible.
+     */
+    public makeVisibleAndAttachGraph() {
+        if (this.visibilityState !== VisibilityState.NotVisible) {
```
[the remark this answers is not in the document]
Comment (agarwal-navin) [reply packages/runtime/datastore/src/dataStoreRuntime.ts:421]: no, data store runtime only cares about making itself locally visible. It will become globally visible if the container is attached and this is decided by the container runtime.

File: packages/runtime/datastore/src/fluidHandle.ts (hunk 6 above)
Comment (agarwal-navin) [reply packages/runtime/datastore/src/fluidHandle.ts:34]: I don't want to add visibility state here because it doesn't need it. Why add extra state if its not required?

File: packages/runtime/datastore/src/fluidHandle.ts (hunk 7 above)
Comment (agarwal-navin) [reply packages/runtime/datastore/src/fluidHandle.ts:72]: We already called attachGraph() on these handles. We are just emptying the boundHandles set now. We could explicitly clear the set but I don't think it matters.

File: packages/runtime/datastore/src/fluidHandle.ts (hunk 8 above)
Comment (agarwal-navin) [reply packages/runtime/datastore/src/fluidHandle.ts:66]: why?

File: packages/runtime/datastore/src/dataStoreRuntime.ts (hunk 9 above)
Comment (agarwal-navin) [reply packages/runtime/datastore/src/dataStoreRuntime.ts:901]: This should say `Data should store not become globally visible without being locally visible first`.
Do you mean someone attaches the listener after the data store is globally visible? This does happen for remote data stores. They are always globally visible. But for them, "attaching" event should never fire. If it does, its a bug and we want to fail fast.

File: packages/runtime/datastore/src/dataStoreRuntime.ts (hunk 10 above)
Comment (agarwal-navin) [reply packages/runtime/datastore/src/dataStoreRuntime.ts:862]: We could assert that visibility state is globally visible. I didn't add it because we don't care about "attached" event. We should eventually remove attachState. I will create an issue to do this when (or if) this PR is merged. A lot of state will have to be cleared once there aren't back-compat concerns.

File: packages/runtime/datastore/src/dataStoreRuntime.ts (hunk 14 above)
[the remark this answers is not in the document]
Comment (tyler-cai-microsoft) [reply packages/runtime/datastore/src/dataStoreRuntime.ts:400]: What would cause a handle to be bound before the `channel.handle` was bound? Someone makes a handle and stores it in a dds?

File: packages/runtime/datastore/src/localChannelContext.ts (hunk 11 above)
Comment (agarwal-navin) [reply packages/runtime/datastore/src/localChannelContext.ts:41]: We could but that means adding additional state to something that doesn't need it. We should be moving to the other direction where visibility state is essentially just a boolean - you are either visible or you or not. Unfortunately, the current limitations don't allow us to do it for data stores but I think that is how it should be.

File: packages/runtime/datastore/src/fluidHandle.ts (hunk 6 above)
Comment (tyler-cai-microsoft) [reply packages/runtime/datastore/src/fluidHandle.ts:34]: I just realized this was the handle

File: packages/runtime/datastore/src/fluidHandle.ts (hunk 7 above)
Comment (tyler-cai-microsoft) [reply packages/runtime/datastore/src/fluidHandle.ts:72]: Wouldn't we want to keep the boundHandles stored, so when we unbind, we unbind the boundHandles?

File: packages/runtime/datastore/src/fluidHandle.ts (hunk 8 above)
Comment (tyler-cai-microsoft) [reply packages/runtime/datastore/src/fluidHandle.ts:66]: I remember this is a handle

File: packages/runtime/datastore/src/fluidHandle.ts (hunk 7 above)
Comment (agarwal-navin) [reply packages/runtime/datastore/src/fluidHandle.ts:72]: We don't have the concept of unbind today. boundHandles is basically a temporary list that contains handles that are bound to the data store when it is not visible. We use this list to actually bind these handles when we become visible.
So, it isn't really a list of all handles that are bound to this data store. The name is misleading and so are the terms attach and bind. That's why I am trying to move to just visible.
Maybe we can call this `pendingHandlesToBind` or `pendingHandlesToMakeVisible`?

File: packages/runtime/datastore/src/dataStoreRuntime.ts (hunk 14 above)
[the remark this answers is not in the document]
Comment (agarwal-navin) [reply packages/runtime/datastore/src/dataStoreRuntime.ts:400]: When you create a DDS, you have to bind (or attach or whatever to call it) it to its parent to make it visible. This is similar to data stores - If its a root DDS, you do it by calling `bindToContext` on the DDS which will end up calling `bindChannel` on data store runtime. It its a non-root DDS, you store its handle in a DDS which also ends up calling `bindChannel`.

Binding the channel.handle is how you bind the channel.

File: packages/runtime/datastore/src/fluidHandle.ts (hunk 7 above)
Comment (tyler-cai-microsoft) [reply packages/runtime/datastore/src/fluidHandle.ts:72]: That would work, `pendingHandlesToMakeVisible`, since that's the method we're calling

File: api-report/datastore.api.md [hunk 16]
```diff
@@ -89,6 +88,7 @@ export class FluidDataStoreRuntime extends TypedEventEmitter<IFluidDataStoreRunt
     static load(context: IFluidDataStoreContext, sharedObjectRegistry: ISharedObjectRegistry, existing: boolean): FluidDataStoreRuntime;
     // (undocumented)
     readonly logger: ITelemetryLogger;
+    makeVisibleAndAttachGraph(): void;
```
Comment (anthony-murphy) [inline api-report/datastore.api.md:91]: this looks like a breaking change. does this need to be made in the next branch

Comment (anthony-murphy) [reply api-report/datastore.api.md:91]: or should this be and optional method?

Comment (agarwal-navin) [reply api-report/datastore.api.md:91]: It is optional on IFluidDataStoreChannel. This here is the class implementation.

File: packages/runtime/runtime-definitions/src/dataStoreContext.ts [hunk 17]
```diff
@@ -57,6 +57,31 @@ export enum FlushMode {
     TurnBased,
 }
 
+/**
+ * This tells the visibility state of a Fluid object. It basically tracks whether the object is not visible, visible
+ * locally within the container only or visible globally to all clients.
+ */
+export enum VisibilityState {
```
Comment (anthony-murphy) [inline packages/runtime/runtime-definitions/src/dataStoreContext.ts:64]: enums create all sorts of problems, could we use and object instead:  [VisibilityState](https://www.typescriptlang.org/docs/handbook/enums.html#objects-vs-enums)

File: packages/runtime/container-runtime/src/dataStoreContext.ts [hunk 18]
```diff
@@ -243,6 +244,7 @@ export abstract class FluidDataStoreContext extends TypedEventEmitter<IFluidData
     private readonly subLogger: ITelemetryLogger;
     private readonly thresholdOpsCounter: ThresholdCounter;
     private static readonly pendingOpsCountThreshold = 1000;
+    public visibilityState: VisibilityState = VisibilityState.NotVisible;
```
Comment (vladsud) [inline packages/runtime/container-runtime/src/dataStoreContext.ts:247]: I'd remove default value here, and make sure constructor assigns one always (and compiler checks that). That way all the code / values are in one place to review, easier (in the future) to review logic / see what values are assigned and when

File: packages/runtime/container-runtime/src/dataStoreContext.ts [hunk 19]
```diff
@@ -280,11 +282,23 @@ export abstract class FluidDataStoreContext extends TypedEventEmitter<IFluidData
...
 
+        /**
+         * The existing flag can be true in two conditions:
+         * 1. It's a local data store that is created when a detached container is rehydrated. In this case, the data
+         *    store is locally visible because the snapshot it is loaded from contains locally visible data stores only.
+         * 2. It's a remote data store that is created when an attached container is loaded is loaded from snapshot or
+         *    when an attach op comes in. In both these cases, the data store is already globally visible.
+         */
+        if (existing) {
+            this.visibilityState = this.containerRuntime.attachState === AttachState.Detached
```
Comment (vladsud) [inline packages/runtime/container-runtime/src/dataStoreContext.ts:293]: Is it worth adding validation function that can be called at various times and check some invariants? Like detached container can't have VisibilityState.GloballyVisible data store. Or bound/unbound lists in datastores class matches visibility of contexts. Maybe there are some other invariants that we can check, either locally (one data store / context) or globally (at root level for all nodes).

File: packages/runtime/container-runtime/src/dataStoreContext.ts [hunk 20]
```diff
@@ -280,11 +282,23 @@ export abstract class FluidDataStoreContext extends TypedEventEmitter<IFluidData
...
+                ? VisibilityState.LocallyVisible : VisibilityState.GloballyVisible;
+        }
+
         this.bindToContext = () => {
             assert(this.bindState === BindState.NotBound, 0x13b /* "datastore context is already in bound state" */);
             this.bindState = BindState.Binding;
             assert(this.channel !== undefined, 0x13c /* "undefined channel on datastore context" */);
-            bindChannelFn(this.channel);
+            makeVisibleFn();
```
Comment (vladsud) [inline packages/runtime/container-runtime/src/dataStoreContext.ts:301]: Some though on naming - should it be called makeVisibleLocallyFn()? It may go further, but I think that's what it actually does (everything else is fall out of that).

Comment (vladsud) [reply packages/runtime/container-runtime/src/dataStoreContext.ts:301]: And code below is very in line with that:
```ts
        this.visibilityState = VisibilityState.LocallyVisible;
        this.makeVisibleFn();
```

File: packages/runtime/container-runtime/src/dataStoreContext.ts [hunk 21]
```diff
@@ -879,6 +904,16 @@ export class LocalFluidDataStoreContextBase extends FluidDataStoreContext {
...
+                "Data store should not already be globally visible",
+            );
+            /**
+             * Once the data store moves to attaching state, its existence has been notified to the server which will
+             * notify all clients. The data store is now globally visible.
+             */
+            this.visibilityState = VisibilityState.GloballyVisible;
         });
         this.once("attached", () => {
             assert(this.attachState === AttachState.Attaching, 0x14e /* "Should move from attaching to attached" */);
```
Comment (vladsud) [inline packages/runtime/container-runtime/src/dataStoreContext.ts:919]: Maybe add assert here as well that this.visibilityState === VisibilityState.GloballyVisible ?

Comment (vladsud) [reply packages/runtime/container-runtime/src/dataStoreContext.ts:919]: I'd also consider adding similar invariant checks in public methods like generateAttachMessage()

File: packages/runtime/container-runtime/src/dataStoreContext.ts [hunk 22]
```diff
@@ -1009,10 +1044,16 @@ export class LocalDetachedFluidDataStoreContext
...
         this.channelDeferred = new Deferred<IFluidDataStoreChannel>();
 
-        super.bindRuntime(dataStoreRuntime);
+        super.bindRuntime(dataStoreChannel);
 
         if (await this.isRoot()) {
-            dataStoreRuntime.bindToContext();
+            // back-compat 0.58.2000 - makeVisibleAndAttachGraph was added in this version to IFluidDataStoreChannel.
+            // For older versions, we still have to call bindToContext.
+            if (dataStoreChannel.makeVisibleAndAttachGraph !== undefined) {
```
Comment (vladsud) [inline packages/runtime/container-runtime/src/dataStoreContext.ts:1052]: This kind of code repeats in many places, so maybe create a method on context object and call it from various places?
Assuming that we have access in all those places.

File: packages/runtime/container-runtime/src/dataStores.ts (hunk 3 above)
Comment (vladsud) [inline packages/runtime/container-runtime/src/dataStores.ts:298]: I think this API should be private, as there is no way to directly call it (i.e. container runtime does not call it, and that's the only class that has direct access to this class).

It's minor, but I think we should reduce usage of IDs across our code base, and use objects pretty much everywhere. Maybe other way to say it - other than serialization / deserialization (and thus usage of handles), the system can and should be similar to "raw" JS environment, where objects creates by JS engine do not have id / other kind of identification, it's just an object.
Main reason why I think it's good idea - if we do get to implementing ID compression schema, we would have 2 internal IDs (in addition to aliases). And while I hear there is strong type safety built into existing ID compression logic, it would still be a pain to reason about what ID is used where. Less IDs - better.

File: packages/runtime/datastore/src/dataStoreRuntime.ts [hunk 23]
```diff
@@ -224,11 +222,11 @@ IFluidDataStoreChannel, IFluidDataStoreRuntime, IFluidHandleContext {
...
                     // This is the case of rehydrating a detached container from snapshot. Now due to delay loading of
-                    // data store, if the data store is loaded after the container is attached, then we missed marking
-                    // the channel as attached. So mark it now. Otherwise add it to local channel context queue, so
-                    // that it can be mark attached later with the data store.
+                    // data store, if the data store is loaded after the container is attached, then we missed making
+                    // the channel visible. So do it now. Otherwise, add it to local channel context queue, so
+                    // that it can be make it visible later with the data store.
                     if (dataStoreContext.attachState !== AttachState.Detached) {
-                        (channelContext as LocalChannelContextBase).markAttached();
+                        (channelContext as LocalChannelContextBase).makeVisible();
```
Comment (vladsud) [inline packages/runtime/datastore/src/dataStoreRuntime.ts:229]: Isn't this breaking compat? context can be from N-2 version.
Also, we should figure out how not to need casting here.

File: packages/runtime/datastore/src/dataStoreRuntime.ts [hunk 24]
```diff
@@ -264,6 +262,22 @@ IFluidDataStoreChannel, IFluidDataStoreRuntime, IFluidHandleContext {
...
+        /**
+         * back-compat 0.58.2000 - visibility state was added in this version. For older versions, get the visibility
+         * state similar to the data store context:
+         * The existing flag can be true in two conditions:
+         * 1. It's a local data store that is created when a detached container is rehydrated. In this case, the data
+         *    store is locally visible because the snapshot it is loaded from contains locally visible data stores only.
+         * 2. It's a remote data store that is created when an attached container is loaded is loaded from snapshot or
+         *    when an attach op comes in. In both these cases, the data store is already globally visible.
+         */
+        if (dataStoreContext.visibilityState !== undefined) {
```
Comment (vladsud) [inline packages/runtime/datastore/src/dataStoreRuntime.ts:274]: Correct me if I got it wrong, but I believe we have two places where we track same thing - here and in context.
And that might be source of mismatches / bugs.
Should this be a calculated property, that always relies on state of context (basically this logic moved to getter and this.visibilityState is removed)?

File: packages/runtime/datastore/src/dataStoreRuntime.ts [hunk 25]
```diff
@@ -377,38 +391,52 @@ IFluidDataStoreChannel, IFluidDataStoreRuntime, IFluidHandleContext {
...
+         * graph is attached. It calls bindToContext on the shared object which will end up back here.
+         */
+        if (this.boundhandles !== undefined && this.boundhandles.has(channel.handle)) {
+            return;
+        }
+
+        this.bind(channel.handle);
+
+        // If our data store is local then add the channel to the queue
+        if (!this.localChannelContextQueue.has(channel.id)) {
```
Comment (vladsud) [inline packages/runtime/datastore/src/dataStoreRuntime.ts:407]: It's rather hard to understand the meaning of this.localChannelContextQueue. And looking at isChannelAttached(), I think what would help is to remove notBoundedChannelContextSet / localChannelContextQueue / pendingAttach and instead have a property on channel that returns one of those states (enum). And have only one list of all channels (not IDs :), and do filters on top of it to get needed subset).

The other thought - I believe there is no need to have extra state (to track that enum), as channel already has that info (i.e. it's calculatable from existing state). I might be wrong, but the fact that we call various methods on channel (like attachChannel) suggests that channel has that info

File: packages/runtime/datastore/src/dataStoreRuntime.ts [hunk 26]
```diff
@@ -377,38 +391,52 @@ IFluidDataStoreChannel, IFluidDataStoreRuntime, IFluidHandleContext {
...
-            this.bind(channel.handle);
+        }
 
-            // If our data store is local then add the channel to the queue
-            if (!this.localChannelContextQueue.has(channel.id)) {
-                this.localChannelContextQueue.set(channel.id, this.contexts.get(channel.id) as LocalChannelContextBase);
-            }
+        /**
+         * If this channel has already been bound, do nothing. This can happen during attachGraph() when a channel's
+         * graph is attached. It calls bindToContext on the shared object which will end up back here.
```
Comment (vladsud) [inline packages/runtime/datastore/src/dataStoreRuntime.ts:398]: Do we have test coverage for all cases like that?

File: packages/runtime/datastore/src/dataStoreRuntime.ts [hunk 27]
```diff
@@ -756,24 +792,21 @@ IFluidDataStoreChannel, IFluidDataStoreRuntime, IFluidHandleContext {
         channel.handle.attachGraph();
```
Comment (vladsud) [inline packages/runtime/datastore/src/dataStoreRuntime.ts:792]: Any chance you can add asserts here clearly articulating the state of this data store? I think it has to be globally visible / attached (latter is asserted, but former is not).
May that assert should be in isAttached() itself, when it returns true (and maybe more asserts to clearly spell out valid invariants)?

Other related question - can we have only one enum to track all the states? I.e. get rid of this._attachState, and everything else be a projection from that enum? To avoid even thinking about cases (if it's possible to get to them) like attached but not locally visible.
public isAttached(): boolean

File: packages/runtime/datastore/src/dataStoreRuntime.ts [hunk 28]
```diff
@@ -756,24 +792,21 @@ IFluidDataStoreChannel, IFluidDataStoreRuntime, IFluidHandleContext {
...
 
         assert(this.isAttached, 0x182 /* "Data store should be attached to attach the channel." */);
-        // Get the object snapshot only if the data store is Bound and its graph is attached too,
-        // because if the graph is attaching, then it would get included in the data store snapshot.
-        if (this.bindState === BindState.Bound && this.graphAttachState === AttachState.Attached) {
```
Comment (vladsud) [inline packages/runtime/datastore/src/dataStoreRuntime.ts:761]: Is making it unconditional a result of realizing that condition was always true, or changes in the flow where we never get here when condition was false in the past?

File: packages/runtime/datastore/src/dataStoreRuntime.ts (hunk 27 above)
Comment (vladsud) [inline packages/runtime/datastore/src/dataStoreRuntime.ts:792]: check on line 788 seems like should be assert, as the only caller (bindChannel()) checks that this channel is in this.notBoundedChannelContextSet - another example (I think) of same state duplicated (see my comment on removal of this.notBoundedChannelContextSet and other sets in favor of asking channels these questions).

File: packages/runtime/runtime-definitions/src/dataStoreContext.ts (hunk 17 above)
Comment (vladsud) [reply packages/runtime/runtime-definitions/src/dataStoreContext.ts:64]: We are using string unions in couple other places; I think that results in more compact code (compare to enums like below), and are better for telemetry readability.

File: packages/runtime/runtime-definitions/src/dataStoreContext.ts [hunk 29]
```diff
@@ -184,13 +209,20 @@ export interface IFluidDataStoreChannel extends
...
+     * @deprecated - This will be removed in favor of makeVisibleAndAttachGraph.
      * Runs through the graph and attaches the bound handles. Then binds this runtime to the container.
      */
     attachGraph(): void;
 
+    /**
+     * Makes the data store channel visible in the container. Also, runs through its graph and attaches all
+     * bound handles that represent its dependencies in the container's graph.
+     */
+    makeVisibleAndAttachGraph?(): void;
```
Comment (vladsud) [inline packages/runtime/runtime-definitions/src/dataStoreContext.ts:224]: It's really hard to follow all attachment code :)
I think one reason - it's hard to think about directionality of calls. I.e. I'd think that most binding flows (including creation flow) would have direction channel -> context and ideally would not need context -> channel communication. Container attachment flow needs context -> channel communication.

This API seems like includes both. Glancing at code, I think it's only needed for root data stores, and in future may be removed (I think, assuming we remove attachment flow in its current form).
Is that correct assessment?

**Review by vladsud — APPROVED** [review]
Could you please analyze all the interesting state transitions and make sure we have text coverage for all of them? Without that it's hard to see we can be successful at pushing it through :)

File: packages/runtime/container-runtime/src/dataStoreContext.ts (hunk 20 above)
Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/dataStoreContext.ts:301]: The idea is that data store is already locally visible by this time and telling its parent that I am ready to be fully visible now. The parent decides whether it should become globally visible or not. The sequence of steps are:
1. Data store is created and is not visible.
2. It becomes locally visible when some one call `makeVisibleAndAttachGraph` (for root data stores) or `attachGraph` (for non-root data stores) on it.
3. The data store now tells its parent that I am locally visible so you can make me globally visible when you think the time is right.

So, maybe this function should be called `readyToBeVisible` or `readyToBeGloballyVisible`.

File: packages/runtime/container-runtime/src/dataStoreContext.ts (hunk 21 above)
Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/dataStoreContext.ts:919]: Added a similar assert to the `getAttachSummary` method in data store runtime.

File: packages/runtime/container-runtime/src/dataStores.ts (hunk 3 above)
Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/dataStores.ts:298]: Yes, you are right. This should be private.

File: packages/runtime/datastore/src/dataStoreRuntime.ts (hunk 23 above)
Comment (agarwal-navin) [reply packages/runtime/datastore/src/dataStoreRuntime.ts:231]: No, this is calling down into the channel contexts for DDSs not up to the data store context.

File: packages/runtime/datastore/src/dataStoreRuntime.ts (hunk 25 above)
Comment (agarwal-navin) [reply packages/runtime/datastore/src/dataStoreRuntime.ts:409]: I agree that it's confusing but I would rather not do it as part of this PR. I can create an issue and do it separately as its mostly orthogonal to this change.

File: packages/runtime/datastore/src/dataStoreRuntime.ts (hunk 27 above)
Comment (agarwal-navin) [reply packages/runtime/datastore/src/dataStoreRuntime.ts:788]: The idea is that we can remove bind, graph attach and attach state and only use visibility state. We may still have to expose attachState because its on the public interfaces but we can derive that from the visibility state.
We can also remove attachState and replace it with visibility state but I think that is a bigger breaking change.

And yes, we can mostly assert that the state is globally visible here. Let me work on that.

File: packages/runtime/datastore/src/fluidHandle.ts [hunk 30]
```diff
@@ -24,6 +21,22 @@ export class FluidObjectHandle<T extends FluidObject = IFluidObject> implements
...
+    /**
+     * Tells whether the object of this handle is visible in the container.
+     */
+    private get visible(): boolean {
+        /**
+         * If the object of this handle is attached, it is visible in the container. This is a work around the scenario
+         * where the object becomes visible but the handle does not get this notification. For example, handles to a DDS
+         * other than the default handle won't know if the DDS becomes visible after the handle was created.
+         */
+        if (this.isAttached) {
```
[the remark this answers is not in the document]
Comment (agarwal-navin) [reply packages/runtime/datastore/src/fluidHandle.ts:33]: In fact, the handle for root data stores will always its visibility state as not visible. This is because attachGraph() will never be called on it. For non-root data stores, attachGraph() will be called when its handle is stored in a DDS.

Things work today because the handles of DDSes of root-data stores will update its visibility state. This happens when bindChannel() is called for the DDS which ends up calling handle.attachGraph().

File: packages/runtime/runtime-definitions/src/dataStoreContext.ts (hunk 29 above)
Comment (agarwal-navin) [reply packages/runtime/runtime-definitions/src/dataStoreContext.ts:224]: Yes, you are right. Making data store locally visible (binding) flow always happens from channel -> context. Making them globally visible (attaching) happens from context -> channel.
For root-data stores too, the making locally visible flow is the same where the container runtime calls the channel which then calls context. So, channel -> context is preserved. However, there is an additional call from the context layer to channel layer first.

Another way to remove this will be to make the alias map behave like a DDS. When aliasing a data store, store its handle in the alias map which calls attachGraph() on it. This will make the behavior similar to non-root data stores.

File: packages/runtime/datastore/src/dataStoreRuntime.ts (hunk 24 above)
Comment (agarwal-navin) [reply packages/runtime/datastore/src/dataStoreRuntime.ts:277]: It would have to be the other way around - Have the state here and context gets it from here. The reason is that this state propagates from the runtime to the context compared to something like connectivity state which propagates the other way around.
The runtime has to update all its dependencies before it can let the channel know of the new state so it has to update the state locally first.

File: packages/runtime/datastore/src/dataStoreRuntime.ts (hunk 26 above)
Comment (agarwal-navin) [reply packages/runtime/datastore/src/dataStoreRuntime.ts]: Yes, this is very common scenario and will happen for all DDSs that are created in detached container.

**Comment by agarwal-navin** [comment]
> Could you please analyze all the interesting state transitions and make sure we have text coverage for all of them? Without that it's hard to see we can be successful at pushing it through :)

I added tests for these scenarios and in fact I found bunch of issues during development because of tests failing :-). I will try to think of more test cases.

File: packages/runtime/container-runtime/src/dataStoreContext.ts (hunk 19 above)
Comment (vladsud) [reply packages/runtime/container-runtime/src/dataStoreContext.ts:294]: I think it's useful (in addition to what you describe) to have validate() function that can be called any time and that validates that invariants are not broken.

File: packages/runtime/datastore/src/dataStoreRuntime.ts (hunk 24 above)
Comment (vladsud) [reply packages/runtime/datastore/src/dataStoreRuntime.ts:277]: Sure, should we do so (tracking in one place)? That probably can be done only in 2 releases, I guess.

File: packages/runtime/datastore/src/dataStoreRuntime.ts (hunk 25 above)
Comment (vladsud) [reply packages/runtime/datastore/src/dataStoreRuntime.ts:412]: Sounds good - please create an issue

Comment (agarwal-navin) [reply packages/runtime/datastore/src/dataStoreRuntime.ts:412]: https://github.com/microsoft/FluidFramework/issues/9826

File: packages/runtime/runtime-definitions/src/dataStoreContext.ts (hunk 17 above)
Comment (agarwal-navin) [reply packages/runtime/runtime-definitions/src/dataStoreContext.ts:64]: Changed it to an object.

File: packages/runtime/datastore/src/dataStoreRuntime.ts (hunk 24 above)
Comment (agarwal-navin) [reply packages/runtime/datastore/src/dataStoreRuntime.ts]: Data store context doesn't need to track visibility state because it doesn't use it. I removed it from the context and added it to `IFluidDataStoreChannel` so that the context can access it if needed.
