### PR TITLE
getSnapshotTree is required on IChannelStorageService

### LINKED ISSUE #25178: Make "getSnapshotTree" required on "IChannelStorageService"
## Broken API or pattern

`getSnapshotTree` was added as optional on `IChannelStorageService` in 2.51.0. This work items tracks making it required.

**Preparation References**

https://github.com/microsoft/FluidFramework/releases/tag/client_v2.51.0#user-content-new-getsnapshottree-api-on-ichannelstorageservice-24970

### PR DESCRIPTION
**Pull request by agarwal-navin**
## Description
The property `getSnapshotTree` is now required on `IChannelStorageService`.

## Breaking Changes
This is a breaking change. This API was added and the upcoming break was announced in release 2.51.0 [here](https://github.com/microsoft/FluidFramework/releases/tag/client_v2.51.0#user-content-new-getsnapshottree-api-on-ichannelstorageservice-24970).

### CODE REVIEW

File: packages/runtime/test-runtime-utils/src/mocks.ts [hunk 1]
```diff
@@ -1248,6 +1253,10 @@ export class MockObjectStorageService implements IChannelStorageService {
 			(key) => key.startsWith(path) && key.split("/").length === pathPartsLength + 1,
 		);
 	}
+
+	public getSnapshotTree(): ISnapshotTree {
+		return this.snapshotTree;
+	}
```
Comment (jason-ha) [inline packages/runtime/test-runtime-utils/src/mocks.ts:1268]: This should have happen before now, right?

File: packages/runtime/datastore/src/localChannelStorageService.ts
Comment (jason-ha) [inline packages/runtime/datastore/src/localChannelStorageService.ts:1]: Appears to be required dead code removal (as opposed to fixing to conform to new requirements), right?

File: .changeset/heavy-mails-pay.md [hunk 2]
```diff
@@ -0,0 +1,8 @@
+---
+"@fluidframework/datastore-definitions": minor
+"@fluidframework/test-runtime-utils": minor
+"__section": breaking
+---
+getSnapshotTree is now required in IChannelStorageService
+
+The `getSnapshotTree` property was added as optional to `IChannelStorageService` in version [2.51.0](https://github.com/microsoft/FluidFramework/releases/tag/client_v2.51.0#user-content-new-getsnapshottree-api-on-ichannelstorageservice-24970). It is now a required property.
```
Comment (jason-ha) [inline .changeset/heavy-mails-pay.md]: Please reference related issue directly.

**Review by jason-ha — APPROVED** [review]
Approved with suggestion for changeset update to point to the issue.

File: packages/runtime/test-runtime-utils/src/mocks.ts (hunk 1 above)
Comment (agarwal-navin) [reply packages/runtime/test-runtime-utils/src/mocks.ts:1268]: This is a breaking change though right since it is adding a property to a @legacy @beta class. Shouldn't it follow the same process as the other breaking changes in this PR?

Comment (jason-ha) [reply packages/runtime/test-runtime-utils/src/mocks.ts:1268]: Additional properties can be breaking, but we generally don't hold those back. It is similar (not the same) if an implementation of an interface gets a member added.
Mocks should generally reflect the current expectations of the interface it is mocking. If the main implementation of interface has it, then the mock should have it.

**Review by noencke — APPROVED** [review]

File: packages/runtime/datastore/src/localChannelStorageService.ts
Comment (agarwal-navin) [reply packages/runtime/datastore/src/localChannelStorageService.ts:1]: Moved this to a separate PR. This one now only contains breaking changes.

**Review by Josmithr — APPROVED** [review]
Docs changes look good
