### PR TITLE
Remove localStorage reference for disabling SummarizerNode

### LINKED ISSUE #3843: Fluid Framework throws a local storage access exception when third party cookies are blocked
There is a usage of local storage in containerRuntime https://github.com/microsoft/FluidFramework/blob/4c5738cd28e243d482069bd5f1e26ec74f1b71a7/packages/runtime/container-runtime/src/containerRuntime.ts#L711

Chromium based browsers will throw an exception when attempting to access local storage when third party cookies are disabled. Full repro steps in Chromium Edge:

1. Open the settings pane
2. Search for " lock third-party cookies" in the settings and set it to true
3. Open a fluid document on office.com

Expected: page should load
Actual: Error dialog, with the following error in the console: Error: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

We have worked around this issue in other repos by having a utility called safeLocalStorage that puts all local storage access behind a try/catch and ensuring all usages of local storage can function in this case where we are not able to read or write values from local storage.

### PR DESCRIPTION
**Pull request by arinwt**
Fixes #3843

Since it wasn't properly checking for errors thrown on global `localStorage` getter, it could throw when disabled by browser.

Removed this reference altogether, since it wasn't being used.

### CODE REVIEW

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 1]
```diff
@@ -707,9 +707,8 @@ export class ContainerRuntime extends EventEmitter
 
         const loadedFromSequenceNumber = this.deltaManager.initialSequenceNumber;
         const isSummarizerClient = this.clientDetails.type === summarizerClientType;
-        // Use runtimeOptions if provided, otherwise check localStorage, defaulting to true/enabled.
-        const enableSummarizerNode = this.runtimeOptions.enableSummarizerNode
-            ?? (typeof localStorage === "object" && localStorage?.fluidDisableSummarizerNode ? false : true);
+        // Use runtimeOptions if provided, otherwise default to true/enabled.
+        const enableSummarizerNode = this.runtimeOptions.enableSummarizerNode ?? true;
```
Comment (leeviana) [inline packages/runtime/container-runtime/src/containerRuntime.ts:711]: fyi for future booleans, for user usage consistency usually, you want to default to false for these sort of settings. So in this case, the setting probably could have been this.runtimeOptions.disableSummarizerNode and this check would be simply "enableSummarizerNode = !this.runtimeOptions.disableSummarizerNode" or "disableSummarizerNode = this.runtimeOptions.disableSummarizerNode" :P

**Review by leeviana — APPROVED** [review]

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 1 above)
Comment (arinwt) [reply packages/runtime/container-runtime/src/containerRuntime.ts:711]: Generally agree, that's why the localStorage was `fluidDisableSummarizerNode`. I decided to just be consistent with the rest of runtime options this time though, which were all `true` to enable.

**Review by vladsud — APPROVED** [review]

**Review by christiango — APPROVED** [review]
