### PR TITLE
Fixed some data corruption not logging needed information

### LINKED ISSUE #4669: Custom error properties in Container.close's error are not getting logged
For example, `message1` and `message2` in the following error from delta manager is not getting logged:
const message1 = this.comparableMessagePayload(this.previouslyProcessedMessage);
const message2 = this.comparableMessagePayload(message);
if (message1 !== message2) {
  const error = {
    errorType: ContainerErrorType.dataCorruption,
    message: "Two messages with same seq# and different payload!",
    clientId: this.connection?.clientId,
    sequenceNumber: message.sequenceNumber,
    message1,
    message2,
    };
  this.close(error);
}

### PR DESCRIPTION
**Pull request by agarwal-navin**
Fixes #4669.

Renamed CustomErrorWithProps -> LoggingError. It indicates that this error should be used when logging it to telemetry.
Updated couple of errors in delta manager and data stores to DataCorruptionError so that the additional properties are logged.

### CODE REVIEW

File: packages/utils/telemetry-utils/src/logger.ts [hunk 1]
```diff
@@ -66,12 +66,12 @@ export abstract class TelemetryLogger implements ITelemetryLogger {
...
             event.error = errorAsObject.message;
 
-            // Error message can container PII information.
+            // Error message can contain PII information.
             // If we know for sure it does, we have to not log it.
             if (error.containsPII) {
                 event.error = "Error message was removed as it contained PII";
-            } else if (error.getCustomProperties) {
-                const customProps: ITelemetryProperties = error.getCustomProperties();
+            } else if (error.getProperties) {
```
Comment (vladsud) [inline packages/utils/telemetry-utils/src/logger.ts:73]: getProperties is too generic name that can have collision with some other object that has nothing to do with LoggingError, and thus we will record potential PII data.
We either need more unique name here, or move away from such naming at all, and rather do (error instanceof LoggingError) test. With later, we do not care about having this method, we could just do { ...error } (though that has an impact of enumerating all keys, whereas having method theoretically allows us to filter).

**Review by vladsud — APPROVED** [review]
Please address the comment about potential PII leaking through

File: packages/utils/telemetry-utils/src/logger.ts (hunk 1 above)
Comment (agarwal-navin) [reply packages/utils/telemetry-utils/src/logger.ts]: Renamed it to getTelemetryProperties.
