### PR TITLE
start Logging readBlob errors 

### LINKED ISSUE #8504: We have no coverage in telemetry for readBlob failures
I do not think we have good telemetry story to track blob read errors.
I do see them in earlier releases through fluid:telemetry:Container:ContainerWarning events, but they are gone in latest build, and none of the errors show up any more in error table. One can still see issues as non-error events (via fluid:telemetry:OdspDriver:readDataBlob_cancel & fluid:telemetry:DeltaManager:WrapError), but we should not relay on latter, and former will be noisy (including reliable errors).

Note that both implementations of runWithRetry() (one in drivers, one in retriable layer in container) do not report non-retryable errors. I made this change because it was duplicating errors for container/snapshot loading, and I made a decision that scenario (i.e., high-level API) should be concerned with logging error.

If we continue on this path, then I think the following things need to happen:
1. BlobManager should report errors:
```typescript
    public async getBlob(blobId: string): Promise<IFluidHandle<ArrayBufferLike>> {
        const storageId = this.redirectTable?.get(blobId) ?? blobId;
        assert(this.hasBlob(storageId), 0x11f /* "requesting unknown blobs" */);

        return new BlobHandle(
            `${BlobManager.basePath}/${storageId}`,
            this.routeContext,
            async () => this.getStorage().readBlob(storageId),
        );
```
2. I worry a bit about DDS reading blobs and that failing. Usually, failures on that path report as DDS or Data store realization error, and that likely best way to report these errors, but I'm willing to have extra logging there as (at least in ODSP case) we should never fail there. I believe we have single bottleneck - ChannelStorageService.readBlob(). There are some calls that do not go through it - see usage like readAndParse in container runtime. We can go further and build adapter that wraps storage to capture every call - it would cover # 1 above as well, but it will be harder to see where we failed (i.e., is it user image, or core blob of DDS). Maybe here it's fine to go overboard and have double telemetry as errors here are rare and we need to pay attention.

### PR DESCRIPTION
**Pull request by chensixx**
Fixes #8504 
start logging readBlob errors in BlobManager and ChannelStorageService.readBlob()
for the latter, we are adding logger to RehydratedLocalChannelContext, LocalChannelContext, passed in from dataStoreRuntime

### CODE REVIEW

File: packages/runtime/container-runtime/src/blobManager.ts [hunk 1]
```diff
@@ -93,6 +93,11 @@ export class BlobManager {
         const storageId = this.redirectTable?.get(blobId) ?? blobId;
         assert(this.hasBlob(storageId), 0x11f /* "requesting unknown blobs" */);
 
+        // logging readBlob error if there is any
+        const readBlobP = this.getStorage().readBlob(storageId);
+        readBlobP.catch(
+            (error) => this.logger.sendErrorEvent({ eventName:"storageService_readBlobError" }, error));
```
Comment (vladsud) [inline packages/runtime/container-runtime/src/blobManager.ts:99]: This seems wrong. Why do we read blob here? This extra call is unnecessary, and logging added does not represent what actually happens when handle is resolve, as it might succeed here, and fail when BlobHandle is resolved below.
Any telemetry should be added where we actually load blobs today.

File: packages/runtime/container-runtime/src/blobManager.ts [hunk 2]
```diff
@@ -93,6 +93,11 @@ export class BlobManager {
         const storageId = this.redirectTable?.get(blobId) ?? blobId;
```
Comment (vladsud) [inline packages/runtime/container-runtime/src/blobManager.ts:93]: Unrelated to Si's changes: @wes-carlson, I'm a bit confused by code in ContainerRuntime.resolveHandle() around blobs.
Shouldn't there be an await here, where we return value?
```ts
                if (handle) {
                    return {
                        status: 200,
                        mimeType: "fluid/object",
                        value: handle.get(),
                    };
                } else {
```

File: packages/runtime/datastore/src/channelStorageService.ts [hunk 3]
```diff
@@ -48,7 +50,10 @@ export class ChannelStorageService implements IChannelStorageService {
         if (blob !== undefined) {
             return blob;
         }
-        return this.storage.readBlob(id);
+        const blobP = this.storage.readBlob(id);
+        blobP.catch((error) => this.logger.sendErrorEvent({ eventName: "readBlobError"}, error));
```
Comment (vladsud) [inline packages/runtime/datastore/src/channelStorageService.ts:54]: It would be great for name of even reflect what type of code issues it. I.e. maybe ChannelStorageBlobError, or something like that?
For context - we expect no failures here to ever happen, vs. the code in BlobManager - this one will hit errors because lifetime of those blobs is less well defined.

Comment (vladsud) [reply packages/runtime/datastore/src/channelStorageService.ts:54]: That said, if all code paths add some reasonable prefix to events (like you have below with "RemoteChannelContext"), then shorter name is likely fine

File: packages/runtime/datastore/src/test/channelStorageService.spec.ts [hunk 4]
```diff
@@ -21,7 +21,7 @@ describe("ChannelStorageService", () => {
                 throw new Error("not implemented");
             },
         };
-        const ss = new ChannelStorageService(tree, storage);
```
Comment (vladsud) [inline packages/runtime/datastore/src/test/channelStorageService.spec.ts:24]: Consider using TelemetryUTLogger in UTs - I believe it should fail the test if any error event is issueed

File: packages/runtime/container-runtime/src/blobManager.ts (hunk 1 above)
Comment (vladsud) [reply packages/runtime/container-runtime/src/blobManager.ts:99]: That said, consider adding storageId property as "id" to event - that way we can see if it's same blob or not across many sessions.

File: packages/runtime/container-runtime/src/blobManager.ts (hunk 2 above)
Comment (wes-carlson) [reply packages/runtime/container-runtime/src/blobManager.ts:93]: I don't think it functionally makes a difference since RemoteFluidObjectHandle.get() is async, so awaiting it will await this promise too. Is there a reason we should await here?

Comment (vladsud) [reply packages/runtime/container-runtime/src/blobManager.ts:93]: It works the way code is structured today. if get() were to interrogate FluidObject, then it would likely fail, as it works with promise:
```ts
                    if (response.mimeType === "fluid/object") {
                        const fluidObject: FluidObject = response.value;
                        return fluidObject;
                    }
```
It's not a big deal, but it feels wrong - requests should return results, not promises for results (as request pattern itself is async). It's equivalent to returning Promise<Promise<T>> - valid, but not useful construct.

File: packages/runtime/container-runtime/src/blobManager.ts [hunk 5]
```diff
@@ -96,7 +96,17 @@ export class BlobManager {
         return new BlobHandle(
             `${BlobManager.basePath}/${storageId}`,
             this.routeContext,
-            async () => this.getStorage().readBlob(storageId),
+            async () => {
```
Comment (vladsud) [inline packages/runtime/container-runtime/src/blobManager.ts:99]: You are missing return statement and rethrow, plus comma after error:

```ts
                return this.getStorage().readBlob(storageId).catch((error) => {
                    this.logger.sendErrorEvent(
                        {
                            eventName:"DocumentStorageBlobError",
                            id: storageId,
                        },
                        error,
                    );
                    throw error;
                })
```

Comment (vladsud) [reply packages/runtime/container-runtime/src/blobManager.ts:99]: I'd also rename DocumentStorageBlobError to something more on point, like AttachmentReadBlob (error is imposed from category, and it's about attachment blobs, DocumentStorage is implementation detail so it's less interesting here)

File: packages/runtime/datastore/src/channelStorageService.ts [hunk 6]
```diff
@@ -48,7 +50,13 @@ export class ChannelStorageService implements IChannelStorageService {
         if (blob !== undefined) {
             return blob;
         }
-        return this.storage.readBlob(id);
+        const blobP = this.storage.readBlob(id);
+        blobP.catch((error) => {
+            this.logger.sendErrorEvent({ eventName: "ChannelStorageBlobError"}, error);
+            throw error;
```
Comment (vladsud) [inline packages/runtime/datastore/src/channelStorageService.ts:56]: This will result in unhandled exceptions, because nobody observes the new promise created by blobP.catch() block.
So best way - remove throw from here, that's a dead-end promise fork (it's easier to think about promises as a tree, every time you add .then or .catch you create a child in that tree)

Alternatively, this function could return blobP.catch((eror) => {}...);
This way you would need to rethrow, as otherwise this function would return Promise<ArrayBufferLike | undefined> and eat exceptions.

**Review by vladsud — APPROVED** [review]
