### PR TITLE
Fix URL substring sanitization

### LINKED ISSUE #9395: build-tools: Fix URL parsing in lockfile parsing
Tracking issue for:
- [ ] https://github.com/microsoft/FluidFramework/security/code-scanning/31

### PR DESCRIPTION
**Pull request by tylerbutler**
Fixes #9395.

### CODE REVIEW

File: tools/build-tools/src/repoPolicyCheck/handlers/lockfiles.ts [hunk 1]
```diff
@@ -23,7 +22,8 @@ export const handlers: Handler[] = [
             if (matches !== null) {
                 const results: string[] = [];
                 const containsBadUrl = matches.some((value) => {
-                    if (value.startsWith(`https://registry.npmjs.org`)) {
+                    const url = new URL(value);
+                    if (url.hostname !== `registry.npmjs.org` || url.protocol !== `https:`) {
```
Comment (heliocliu) [inline tools/build-tools/src/repoPolicyCheck/handlers/lockfiles.ts:26]: is this supposed to reverse the logic?  it wasn't obvious to me what the problem was from the linked issue

Comment (tylerbutler) [reply tools/build-tools/src/repoPolicyCheck/handlers/lockfiles.ts]: You're totally right. 🤦🏻 Fixed in the latest iteration.

**Review by heliocliu — APPROVED** [review]
