### PR TITLE
Fallback to non blob request if size too big or timeout in snapshot fetch call

### LINKED ISSUE #4005: Fallback for big snapshot download failures
Observing behavior of this file (see below), I believe we need to make changes to how we download snapshot in SPO driver. The issue is that we fail with really large files / snapshots, and we need to have a strategy (even if not perf-optimized) to recover in such cases.
We should put some timeout / limit (baked into driver, in addition to any limits that SPO has on their side - see ISnapshotOptions.mds) and if it fails, report error to telemetry and switch to mode without blobs.

Currently this is blocking issue - we can't open 

[Chapter 1](https://fluidpreview.office.net/p/c3BvOmh0dHBzOi8vbWljcm9zb2Z0LnNoYXJlcG9pbnQtZGYuY29tL3RlYW1zL09mZmljZU9ubGluZVByYWd1ZQ%3D%3D/b!BOyJN6Bkykm_L66EicZFaDKnQ_cydFFLqph8D-t_9vqaMsGC4Tm9RYec9Rh5aw3l/01N5X4JN6S6ARYASACENCKCD7KFOSCXJIK/Chapter-1-Collaborative-Components-Status)
[Teams thread](https://teams.microsoft.com/l/message/19:53328301da384b33bcc81111124e3ab4@thread.skype/1603252323204?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=422665a0-7ad3-4d0d-9171-e8881d0397d9&parentMessageId=1603252323204&teamName=FFX%20(Fluid%20Framework%20and%20Experiences)&channelName=Bugs%20%F0%9F%90%9B&createdTime=1603252323204)

### PR DESCRIPTION
**Pull request by jatgarg**
Fixes: https://github.com/microsoft/FluidFramework/issues/4005
1.) If either the snapshot size is bigger than specified policy or it took more time to fetch snapshot then specified, then fallback to fetch snapshot without blobs.
2.) Take policy of host or driver whichever is min.
The non blob snapshot requests fetches the skeleton of the snapshot(without blobs), which causes the size of snapshot to become small. Later the blobs are fetched as per the requirement.

### CODE REVIEW

File: packages/drivers/odsp-driver/src/contracts.ts [hunk 1]
```diff
@@ -202,6 +202,13 @@ export interface ISnapshotOptions {
      * if snapshot is bigger in size than specified limit.
      */
     mds?: number;
+
+    /*
+     * Maximum time limit to fetch snapshot (in seconds)
+     * If specified, client will timeout the fetch request if it exceeds the time limit and
+     * will try to fetch the snapshot without blobs.
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/contracts.ts:209]: I like the way you described it, but what if host already is asking for snapshot without blobs?
I feel like there should be no fall over in such case (i.e. if it fails, it fails)

Comment (jatgarg) [reply packages/drivers/odsp-driver/src/contracts.ts:209]: But in trees latest we always fetch with blobs.

Comment (jatgarg) [reply packages/drivers/odsp-driver/src/contracts.ts:209]: But I think I can remove from description here because that will be driver internal behavior?

**Comment by anthony-murphy** [comment]
i don't understand blob vs. non-blob or how that is controlled here? can you point it out with PR comments

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts [hunk 2]
```diff
@@ -509,28 +512,51 @@ export class OdspDocumentStorageService implements IDocumentStorageService {
...
-                return this.fetchSnapshotCore(snapshotOptions, tokenFetchOptions, false);
+                return this.fetchSnapshotWithTimeout(snapshotOptions, tokenFetchOptions, false);
             }
         } else {
-            return this.fetchSnapshotCore(snapshotOptions, tokenFetchOptions, false);
+            return this.fetchSnapshotWithTimeout(snapshotOptions, tokenFetchOptions, false);
+        }
+    }
+
+    private async fetchSnapshotWithTimeout(snapshotOptions: ISnapshotOptions, tokenFetchOptions: TokenFetchOptions, usePost: boolean) {
```
Comment (anthony-murphy) [inline packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:530]: is  `usePost` what controls blob vs non-blob? seems weird.

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts [hunk 3]
```diff
@@ -509,28 +512,51 @@ export class OdspDocumentStorageService implements IDocumentStorageService {
...
                 if ((errorType === DriverErrorType.authorizationError || errorType === DriverErrorType.incorrectServerResponse) && tokenFetchOptions.refresh === false) {
                     throw error;
                 }
                 this.logger.sendErrorEvent({ eventName: "TreeLatest_FallBackToGetRequest" }, error);
-                return this.fetchSnapshotCore(snapshotOptions, tokenFetchOptions, false);
+                return this.fetchSnapshotWithTimeout(snapshotOptions, tokenFetchOptions, false);
             }
         } else {
-            return this.fetchSnapshotCore(snapshotOptions, tokenFetchOptions, false);
+            return this.fetchSnapshotWithTimeout(snapshotOptions, tokenFetchOptions, false);
```
Comment (anthony-murphy) [inline packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:526]: is this the fallback? should timeout and size be nulled out, what if the spine is HUGE

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts (hunk 2 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:530]: No, usePost is another feature where we use POST network request to fetch snapshot instead of GET.

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts [hunk 4]
```diff
@@ -509,28 +512,51 @@ export class OdspDocumentStorageService implements IDocumentStorageService {
...
+                abortController.abort();
+            },
+            snapshotOptions.timeout,
+        );
+        try {
+            const odspSnapshot = await this.fetchSnapshotCore(snapshotOptions, tokenFetchOptions, usePost, abortController);
+            return odspSnapshot;
+        } catch (error) {
+            if (error.errorType === OdspErrorType.snapshotTooBig || error.errorType === OdspErrorType.fetchTimeout) {
+                snapshotOptions.blobs = undefined;
```
Comment (anthony-murphy) [inline packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:544]: ahhh. here it is. should we shallow clone before changing the options, as this will change the object, and modify the behavior of the retry above, as this is nested

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts (hunk 2 above)
Comment (anthony-murphy) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:530]: found it

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts (hunk 3 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:526]: This is fallback for post feature. It depends upon host policy which is not enabled yet. So it will always go to else as usePost would be false.

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts [hunk 5]
```diff
@@ -509,28 +512,51 @@ export class OdspDocumentStorageService implements IDocumentStorageService {
...
+            () => {
+                abortController.abort();
+            },
+            snapshotOptions.timeout,
+        );
+        try {
+            const odspSnapshot = await this.fetchSnapshotCore(snapshotOptions, tokenFetchOptions, usePost, abortController);
+            return odspSnapshot;
+        } catch (error) {
+            if (error.errorType === OdspErrorType.snapshotTooBig || error.errorType === OdspErrorType.fetchTimeout) {
```
Comment (jatgarg) [inline packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:543]: This is fallback to non blob snapshot. I don't think we can fetch some spine. It needs to fetched as whole.

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts [hunk 6]
```diff
@@ -340,10 +342,11 @@ export class OdspDocumentStorageService implements IDocumentStorageService {
                     ...this.hostPolicy.snapshotOptions,
                 };
 
-                // No limit on size of snapshot, as otherwise we fail all clients to summarize
-                if (this.hostPolicy.summarizerClient) {
-                    snapshotOptions.mds = undefined;
-                }
+                const maxSnapshotSizeLimit = 25000000; // 25 MB
+                const maxSnapshotFetchTimeout = 30000; // 30 sec
```
Comment (anthony-murphy) [inline packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:346]: move these inline above

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts (hunk 5 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:543]: Also, I am nulling out the time but not the snapshot size. IS it ok fetch such huge snapshot, won't it create the problem again? Size is currently 25 MB.

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts (hunk 6 above)
Comment (anthony-murphy) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:346]: const snapshotOptions: ISnapshotOptions = {
                    deltas: 1,
                    channels: 1,
                    blobs: 2,
                    ...this.hostPolicy.snapshotOptions,
                   mds: snapshotOptions.mds ? Math.min(snapshotOptions.mds, maxSnapshotSizeLimit) : maxSnapshotSizeLimit,
                   timeout:  snapshotOptions.timeout ? Math.min(snapshotOptions.timeout, maxSnapshotFetchTimeout) : maxSnapshotFetchTimeout
                };

---
In reply to: [509818589](https://github.com/microsoft/FluidFramework/pull/4026#discussion_r509818589) [](ancestors = 509818589)

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts (hunk 4 above)
Comment (anthony-murphy) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:544]: should timeout and size be nulled out, what if the spine is HUGE

---
In reply to: [509817789](https://github.com/microsoft/FluidFramework/pull/4026#discussion_r509817789) [](ancestors = 509817789)

Comment (anthony-murphy) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:544]: my worry is we have a block somewhere over 25MB, especially once we have blob support. this code can never download it, but maybe that is ok

---
In reply to: [509819764](https://github.com/microsoft/FluidFramework/pull/4026#discussion_r509819764) [](ancestors = 509819764,509817789)

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts (hunk 2 above)
Comment (skylerjokiel) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:530]: +1 I haven't looked at this code before but I think it's generally a good principal to reflect what you expect the caller cares about.

Ie. they probably don't care if the request uses post vs get but they might want blob or non-blob.

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts [hunk 7]
```diff
@@ -340,10 +342,11 @@ export class OdspDocumentStorageService implements IDocumentStorageService {
...
+                // Choose min of host specified limits or driver specified limits.
+                snapshotOptions.mds = snapshotOptions.mds ? Math.min(snapshotOptions.mds, maxSnapshotSizeLimit) : maxSnapshotSizeLimit;
+                snapshotOptions.timeout = snapshotOptions.timeout ? Math.min(snapshotOptions.timeout, maxSnapshotFetchTimeout) : maxSnapshotFetchTimeout;
```
Comment (skylerjokiel) [inline packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:349]: This will always override if the host specifies a snapshot limit. Do we generally want to defer to the server for setting the size or are there scenarios where the client might care more? (IE. Mobile might want smaller limits)

Non-block. Just food for thought.

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts (hunk 2 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:530]: Actually this is trees latest call and only the driver decides currently whether to fetch with blobs or not. So it is internal to driver. Maybe in future we add a policy to specify that also.

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts (hunk 7 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:349]: I think it should depend on client side because if the client can handle large snapshot or wait for long time, then server should not care.

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts (hunk 6 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts]: done.

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts (hunk 7 above)
Comment (anthony-murphy) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts]: i don't think it will anyway if  snapshotOptions.mds is set, it came from the host via shallow clone, i think moving this above will make that clearer

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts (hunk 4 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts]: Did the cloning. Also these limits will be tuned based on telemetry. So we can change this in future.

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts (hunk 5 above)
Comment (anthony-murphy) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:542]: seems fine for now.

**Review by anthony-murphy — APPROVED** [review]

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts [hunk 8]
```diff
@@ -333,18 +335,18 @@ export class OdspDocumentStorageService implements IDocumentStorageService {
...
                     deltas: 1,
                     channels: 1,
                     blobs: 2,
                     ...this.hostPolicy.snapshotOptions,
+                    mds: this.hostPolicy.snapshotOptions?.mds ? Math.min(this.hostPolicy.snapshotOptions.mds, maxSnapshotSizeLimit) : maxSnapshotSizeLimit,
+                    timeout: this.hostPolicy.snapshotOptions?.timeout ? Math.min(this.hostPolicy.snapshotOptions.timeout, maxSnapshotFetchTimeout) : maxSnapshotFetchTimeout,
                 };
 
-                // No limit on size of snapshot, as otherwise we fail all clients to summarize
-                if (this.hostPolicy.summarizerClient) {
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:344]: This does not look right. The limits client applied to original snapshot can't be applied to summarizer client in the same way. Otherwise we can easily run into situation where client started with 999K snapshot, but summarizer failed to load at 1001K snapshot, and now client keeps going pushing a ton of ops without any chance to summarize.
It's a balancing act between ignoring host requirements (summarizer can join much later when file is bigger) and not summarizing file at all.

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts [hunk 9]
```diff
@@ -509,28 +511,51 @@ export class OdspDocumentStorageService implements IDocumentStorageService {
...
+                abortController.abort();
+            },
+            snapshotOptions.timeout,
+        );
+        try {
+            const odspSnapshot = await this.fetchSnapshotCore(snapshotOptions, tokenFetchOptions, usePost, abortController);
+            return odspSnapshot;
+        } catch (error) {
+            if (error.errorType === OdspErrorType.snapshotTooBig || error.errorType === OdspErrorType.fetchTimeout) {
+                const snapshotOptionsWithoutBlobs: ISnapshotOptions = { ...snapshotOptions, blobs: undefined };
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:543]: It would be great to clear timeout here.
But more important - clear snapshot size restriction:
1. if it came from driver, not from host - clear it, we should try to load skeleton, even if it's bigger what driver thinks is reasonable (as otherwise we fail at all). Alternatively, we can proceed with such restrictions, but we need to ensure that on failure we can fall back to load file by reading tree by tree (how r11s workflow does it) 
2. If restriction came from host (Teams), we have to fail right here, not to proceed. Restriction is due to worries about bandwidth impact, not perf, so we have to respect that choice, not try circumvent that choice.

File: packages/drivers/odsp-driver/src/contracts.ts (hunk 1 above)
Comment (vladsud) [reply packages/drivers/odsp-driver/src/contracts.ts:209]: Not really, if the host says no blobs, then we do no blobs. At least that's the case today in the product - this allows host to optimize behavior...

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts [hunk 10]
```diff
@@ -333,18 +335,18 @@ export class OdspDocumentStorageService implements IDocumentStorageService {
...
                 }
 
+                // Choose min of host specified limits or driver specified limits.
+                const maxSnapshotSizeLimit = 25000000; // 25 MB
+                const maxSnapshotFetchTimeout = 30000; // 30 sec
                 const snapshotOptions: ISnapshotOptions = {
                     deltas: 1,
                     channels: 1,
                     blobs: 2,
                     ...this.hostPolicy.snapshotOptions,
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:345]: Please note that user settings overwrite defaults (above). I'll refer to it later.

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts (hunk 9 above)
Comment (vladsud) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:543]: Please see my comment earlier about user settings - we need to respect user settings (blobs, mds, etc.).
It's fine to put lower limits to fallback to other method of loading (no blobs), because driver believes not enough limitation is in place. But we neither can fail end-to-end process if driver put smaller limits above (rmd), neither we can circumvent total bandwidth restriction

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts (hunk 10 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:345]: We are choosing the minimum of user and driver.

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts (hunk 8 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:344]: How come this is a special situation for summarizer? If a normal client failed to load a big snapshot, then the summarizer client would also fail? (as you said you ran out of memory). But I agree that snapshot client needs to download the full snapshot.

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts (hunk 10 above)
Comment (vladsud) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:345]: My comment was to bring attention to other settings, like blobs=2. If user specifies other setting, then it takes over (that said, we should double check that there is a setting that client can supply, like 0, as undefined will not cut it - we will overwrite it).
I.e. user specifying blobs = 0 is preserved here, and thus falling back to trees later (if we timed out) may not make sense because we already were not asking for trees,

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts (hunk 8 above)
Comment (vladsud) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:344]: Note that summarizer client can boot 20 hours later because some other client (who was summarizer) left.
So not, it's possible that main client succeeded to load at 999K (with limit of 1M), but summarizer would fail at 1001K if limits are there. Unfortunately we have no choice other than let summarizer in, but we can clearly optimize bandwidth over speed for summarizer (i..e not load it with blobs in such case). But we can't fail it
