### PR TITLE
Fix stress tests for Tinylicious

### LINKED ISSUE #8721: Stress tests can't be run locally using Tinylicious
Found during validation of #8717

`initialize()` from test-service-load assumes it can pass an ID in the attach call and have it honored by the service.  Tinylicious/Routerlicious don't do this (they generate a GUID and respond to the attach call with it).  Probably this should instead pull the `resolvedUrl` from the container after attach, similar to what we do in `getTinyliciousContainer()`.  Need to verify that this approach is compatible with ODSP which may work a little differently.

Probably also would be good to audit the test drivers to see if they are stale in their approach (e.g. is `createContainerUrl()` a sensible thing for them to have)

### PR DESCRIPTION
**Pull request by ChumpChief**
Resolves #8721 

Currently the stress tests assume the created container ID will match the requested ID.  This is not true for Routerlicious/Tinylicious, which generate a GUID and ignore the requested ID.  As a result, the stress tests can't run currently on Tinylicious.

Instead, retrieve the ID from the resolved URL after attach.

### CODE REVIEW

File: packages/test/test-service-load/src/utils.ts [hunk 1]
```diff
@@ -154,14 +154,17 @@ export async function initialize(testDriver: ITestDriver, seed: number, testConf
...
+    const containerId = container.resolvedUrl.id;
     container.close();
 
     if ((testConfig.detachedBlobCount ?? 0) > 0) {
         // TODO: #7684 this should be driver-agnostic
         const url = (testDriver as OdspTestDriver).getUrlFromItemId((container.resolvedUrl as any).itemId);
         return url;
     }
-    return testDriver.createContainerUrl(testId);
+    return testDriver.createContainerUrl(containerId);
```
Comment (anthony-murphy) [inline packages/test/test-service-load/src/utils.ts:167]: i do not believe this is the correct fix. it will not work for odsp.

Comment (anthony-murphy) [reply packages/test/test-service-load/src/utils.ts:167]: elsewhere it is done like this:
```suggestion
    return testDriver.createContainerUrl(testId, container..resolvedUrl);
```

**Review by ssimic2 — APPROVED** [review]
