### PR TITLE
Verify runtime sequence number matches protocol sequence number

### LINKED ISSUE #7002: Runtime should verify its sequence number matches protocol sequence number from summary
We should fail faster, by recording the reference sequence number of the runtime in the .metadata blob and failing immediately on load if that doesn't match the one in the .protocol tree.

It might be nice to be able to override this check with a runtimeOption for troubleshooting/correction. So when the runtime option is enabled, we post a telemetry error, but still load. By default, I think we should fail immediately with the error logged.

### PR DESCRIPTION
**Pull request by arinwt**
Fixes #7002 by storing the sequenceNumber in .metadata blob within the runtime-generated summary. Then comparing this to the one that the server generated in the .protocol tree.

If they don't match, close the container with a critical error by default. Allow this behavior to be overridden with a new runtimeOption: "loadSequenceNumberVerification", which defaults to "close". If set to "log", instead just log an error to telemetry on mismatch, and if set to "bypass", do not even perform the check.

~~This bumps the summaryFormatVersion of the .metadata blob from 1 to 2 with the sequenceNumber being required. It would be possible to do this without bumping the version by either: (1) making the sequenceNumber property optional, but always writing it anyway. This has the drawback that .metadata blob writers could miss doing this, which can be mitigated by making it explicit: i.e. typing it `sequenceNumber: number | undefined` instead of `sequenceNumber?: number`, which requires writers to actually include the property even if it's undefined. Or (2) splitting into 2 types, a "Read" type which has the property as optional, and a "Write" type which has it as required. If a reviewer prefers not to bump the format version over this change, I'm happy to revert it, and go with either option (1) or (2); I think I prefer option (1).~~ _Edit: went with option 2_

Split IContainerRuntimeMetadata into a separate ReadContainerRuntimeMetadata (which unions with `undefined` and has `sequenceNumber` as required) type and WriteContainerRuntimeMetadata (which has `sequenceNumber` required).

This PR also removes the `getBackCompatRuntimeOptions` function, which was used to handle compatibility when the format of the runtimeOptions changed from a flat list of properties.

### CODE REVIEW

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 1]
```diff
@@ -114,9 +119,11 @@ import {
     chunksBlobName,
     electedSummarizerBlobName,
     gcFeature,
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/containerRuntime.ts:121]: Can we rename this to getGCVersion (or something similar)? The result of this is called GC version in this file. It's confusing to see two different things with the same name.

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 2]
```diff
@@ -300,6 +316,22 @@ export function unpackRuntimeMessage(message: ISequencedDocumentMessage) {
     return message;
 }
 
+class LoadSequenceNumberMismatchError extends Error implements ICriticalContainerError, ILoggingError {
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/containerRuntime.ts:319]: Do we really need a separate error type? Can this be logged as a data corruption error instead?

**Review by pleath — APPROVED** [review]

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 3]
```diff
@@ -1116,11 +1137,12 @@ export class ContainerRuntime extends TypedEventEmitter<IContainerRuntimeEvents>
         return !this.disableIsolatedChannels || this.gcEnabled;
     }
 
-    private formMetadata(): IContainerRuntimeMetadata {
+    private formMetadata(): WriteContainerRuntimeMetadata {
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/containerRuntime.ts:1140]: The PR description says `summaryFormatVersion` is updated to 2. But I think you went with option (2) mentioned in the description?

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 4]
```diff
@@ -1116,11 +1137,12 @@ export class ContainerRuntime extends TypedEventEmitter<IContainerRuntimeEvents>
...
         return {
             summaryFormatVersion: 1,
             disableIsolatedChannels: this.disableIsolatedChannels || undefined,
-            gcFeature: this.summaryGCVersion, // retain value, this is unchangeable for nown
+            gcFeature: this.summaryGCVersion, // retain value, this is unchangeable for now
+            sequenceNumber: this.deltaManager.lastSequenceNumber,
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/containerRuntime.ts:1145]: Is it guaranteed that this will match the `referenceSequenceNumber` in the summary? We do pause the delta queues when summarizing but we should assert when writing this in the summary that this matches the `referenceSequenceNumber`.

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 5]
```diff
@@ -255,6 +262,15 @@ export interface ISummaryRuntimeOptions {
...
     gcOptions?: IGCRuntimeOptions;
+    /**
+     * Affects the behavior while loading the runtime when the data verification check which
+     * compares the DeltaManager sequence number (obtained from protocol in summary) to the
+     * runtime sequence number (obtained from runtime metadata in summary) finds a mismatch.
+     * 1. "close" (default) will close the container with an assertion.
+     * 2. "log" will log an error event to telemetry, but still continue to load.
+     * 3. "bypass" will skip the check entirely. This is not recommended.
+     */
+    loadSequenceNumberVerification?: "close" | "log" | "bypass";
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/containerRuntime.ts:273]: I am wondering if we need this. If the sequenceNumbers do not match, its a critical bug right. Even if we proceed and load the container, things will definitely break or we would have missing data.

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 1 above)
Comment (arinwt) [reply packages/runtime/container-runtime/src/containerRuntime.ts:121]: Yeah, I was actually debating renaming it too.

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 3 above)
Comment (arinwt) [reply packages/runtime/container-runtime/src/containerRuntime.ts:1140]: Oh yes, I forgot to update the description afterwards, I did go with option (2).

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 5 above)
Comment (arinwt) [reply packages/runtime/container-runtime/src/containerRuntime.ts:273]: Yeah I was just thinking of troubleshooting/recovery scenarios, or future change in assumptions. I don't think we need to really advertise this option.

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 4 above)
Comment (arinwt) [reply packages/runtime/container-runtime/src/containerRuntime.ts:1145]: I was thinking about this too.

We could parameterize `formMetadataBlob(sequenceNumber: number)` and pass in `this.deltaManager.lastSequenceNumber` from the summarize call. This is functionally equivalent, and it _might_ guard for future changes, but we already are **heavily** assuming that DeltaManager remains paused throughout the summarize process. We already assert between each async step in the outer `submitSummary` call. So that's why I opted to leave it as-is. What do you think? I am sort of against adding a new assert, but I'd be open to parameterizing it.

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 2 above)
Comment (arinwt) [reply packages/runtime/container-runtime/src/containerRuntime.ts:319]: Good call, yes I changed it.

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 4 above)
Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/containerRuntime.ts:1145]: If we are already validating this, then its fine; we don't need to add another assert.

File: server/routerlicious/packages/lambdas/src/scribe/lambda.ts [hunk 6]
```diff
@@ -521,28 +521,28 @@ export class ScribeLambda implements IPartitionLambda {
         this.protocolHead = protocolHead;
     }
 
-    private async sendSummaryAck(contents: ISummaryAck) {
+    private async sendResponse({ type, contents }: {
```
Comment (agarwal-navin) [inline server/routerlicious/packages/lambdas/src/scribe/lambda.ts:524]: This looks unrelated. Did this file get added accidentally?

File: packages/test/test-service-load/src/optionsMatrix.ts [hunk 7]
```diff
@@ -50,6 +50,7 @@ export function generateRuntimeOptions(seed: number) {
     const runtimeOptionsMatrix: OptionsMatrix<IContainerRuntimeOptions> = {
         gcOptions: [undefined, ...generatePairwiseOptions(gcOptionsMatrix, seed)],
         summaryOptions: [undefined, ...generatePairwiseOptions(summaryOptionsMatrix, seed)],
+        loadSequenceNumberVerification: [undefined],
```
Comment (agarwal-navin) [inline packages/test/test-service-load/src/optionsMatrix.ts:53]: We can add the expected values here right? I don't see any harm in testing these. Infact, stress tests are what found this issue in the first place so might be worth adding coverage.

File: server/routerlicious/packages/lambdas/src/scribe/lambda.ts (hunk 6 above)
Comment (arinwt) [reply server/routerlicious/packages/lambdas/src/scribe/lambda.ts:524]: Yes!! Whoops.

File: packages/test/test-service-load/src/optionsMatrix.ts (hunk 7 above)
Comment (arinwt) [reply packages/test/test-service-load/src/optionsMatrix.ts:53]: We can, but I'm not sure that it adds much value/coverage, since it just means testing this small if statement of what to do depending on that value.

I assume the cost of adding various options to this matrix is multiplicative? i.e. I think it's really important and good to add all possible runtime options here, but knowing that the cost is nontrivial- and perhaps choosing not to for such a few lines of code & impact. @anthony-murphy thoughts? I could be wrong about the cost, but definitely it is either impacting performance of these tests _or_ decreasing number of unique cases.

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 1 above)
Comment (arinwt) [reply packages/runtime/container-runtime/src/containerRuntime.ts]: Changed it.

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 3 above)
Comment (arinwt) [reply packages/runtime/container-runtime/src/containerRuntime.ts:1122]: Updated the description to match.

**Review by agarwal-navin — APPROVED** [review]
