### PR TITLE
Providing tenant info for InsecureTokenProvider to support Tinylicious

### LINKED ISSUE #4299: Tinylicious not working in webpack-fluid-loader
## Describe the bug

I was trying to run `Todo` data object in `tinylicious` and it looked like this:
image

Url does not have document id; todo item can't open in new tab; and console is not so helpful

### Solution
After debugging, Navin found that the error was because of this PR #4126 
The new token provider did not handle the case of tinylicious where `tenantId` and `tenantSecret` are undefined
Navin already has a solution in mind and he also explained it to me.

### PR DESCRIPTION
**Pull request by chensixx**
Fixed #4299 
Provided tenant info of Tinylicious to InsecureTokenProvider.
Curtis suggested this quick fix which is adding tenant info in options. The other solution would be creating multiTokenProvider file and handle different cases there, which I can do later. Thanks to Navin who quickly found the solution.

### CODE REVIEW

File: packages/tools/webpack-fluid-loader/src/loader.ts [hunk 1]
```diff
@@ -66,6 +66,8 @@ export interface IRouterliciousRouteOptions extends IBaseRouteOptions {
 
 export interface ITinyliciousRouteOptions extends IBaseRouteOptions {
     mode: "tinylicious";
+    tenantId?: string;
+    tenantSecret?: string;
```
Comment (agarwal-navin) [inline packages/tools/webpack-fluid-loader/src/loader.ts:70]: I would rather not add these here. You can instead directly provide the tenantId and secret to the InsecureTokenProvider for tinylicious.

File: packages/tools/webpack-fluid-loader/src/multiDocumentServiceFactory.ts [hunk 2]
```diff
@@ -26,6 +26,10 @@ export function getDocumentServiceFactory(documentId: string, options: RouteOpti
         name: getRandomName(),
     });
 
+    if (options.mode === "tinylicious") {
```
Comment (agarwal-navin) [inline packages/tools/webpack-fluid-loader/src/multiDocumentServiceFactory.ts:29]: Don't add these to options. You can probably create local variables for tenantId and tenantSecret and give them values based on the mode. Then pass those to the InsecureTokenProvider.

**Comment by agarwal-navin** [comment]
This looks good for the time being to unblock testing tinylicious. Can you please create a work item for the long term fix?

File: packages/tools/webpack-fluid-loader/src/loader.ts (hunk 1 above)
Comment (tanviraumi) [reply packages/tools/webpack-fluid-loader/src/loader.ts:70]: Ditto

File: packages/tools/webpack-fluid-loader/src/multiDocumentServiceFactory.ts (hunk 2 above)
Comment (tanviraumi) [reply packages/tools/webpack-fluid-loader/src/multiDocumentServiceFactory.ts:29]: Ditto

File: packages/tools/webpack-fluid-loader/src/loader.ts (hunk 1 above)
Comment (agarwal-navin) [reply packages/tools/webpack-fluid-loader/src/loader.ts:70]: Long term, we don't want these as part of options. If you are planning to work on the long term solution soon, then its fine to keep it here :-).
Otherwise, if someone starts using these options, it will just become harder to remove.

File: packages/tools/webpack-fluid-loader/src/multiDocumentServiceFactory.ts [hunk 3]
```diff
@@ -13,6 +13,7 @@ import { InsecureTokenProvider } from "@fluidframework/test-runtime-utils";
 // eslint-disable-next-line import/no-internal-modules
 import uuid from "uuid/v4";
 import { IDevServerUser, IRouterliciousRouteOptions, RouteOptions } from "./loader";
+import { getuid } from "process";
```
Comment (agarwal-navin) [inline packages/tools/webpack-fluid-loader/src/multiDocumentServiceFactory.ts:16]: Looks like this got added accidentally?

File: packages/tools/webpack-fluid-loader/src/multiDocumentServiceFactory.ts [hunk 4]
```diff
@@ -26,12 +27,15 @@ export function getDocumentServiceFactory(documentId: string, options: RouteOpti
...
     });
 
-    const routerliciousTokenProvider = new InsecureTokenProvider(
+    let routerliciousTokenProvider = new InsecureTokenProvider(
         (options as IRouterliciousRouteOptions).tenantId ,
         documentId,
         (options as IRouterliciousRouteOptions).tenantSecret,
         getUser());
 
+        if (options.mode === "tinylicious") {
```
Comment (agarwal-navin) [inline packages/tools/webpack-fluid-loader/src/multiDocumentServiceFactory.ts:36]: This should be formatted to the left.

Comment (agarwal-navin) [reply packages/tools/webpack-fluid-loader/src/multiDocumentServiceFactory.ts:35]: The formatting still looks wrong to me. Could be a github issue though!
Also, you should create the InsecureTokenProvider above as an else clause to this.
```
if (options.mode === "tinylicious") {
   // create the tinylicious one.
} else {
   // create the routerlicious one.
}
```

Comment (agarwal-navin) [reply packages/tools/webpack-fluid-loader/src/multiDocumentServiceFactory.ts:35]: Can you also add a comment here saying that the token provider and the routerlicious document service will not be called for local server and spo.

**Review by agarwal-navin — APPROVED** [review]
