### PR TITLE
[BREAKING IN 2.20] Added assert for compression ON grouping OFF

### LINKED ISSUE #23618: Removal of op compression without op grouping in v2.20
## Broken API or pattern

'IContainerRuntimeOptions.enableGroupedBatching' with false and `IContainerRuntimeOptions.compressionOptions` enabled

`IContainerRuntimeOptions.enableGroupedBatching` was deprecated in 2.12 (see [release notes](https://github.com/microsoft/FluidFramework/releases/tag/client_v2.12.0#user-content-icontainerruntimeoptionsenablegroupedbatching-is-now-deprecated-23260)).
While this option is not yet removed (and still defaults to `true`), disabling it (by setting to `false`) is not supported
if compression is enabled (by passing a finite value for `IContainerRuntimeOptions.compressionOptions.minimumBatchSizeInBytes`).

**Packages**

@fluidframework/container-runtime

**Expected Timeline**

We expect the ability to disable grouped batching to be fully removed by the 2.30 version.

### PR DESCRIPTION
**Pull request by MarioJGMsoft**
## Description

We no longer want to make it possible to create a container that has grouping off and compression on, so we will throw an error if we detect that it has been created that way.

## Acceptance Criteria

A container throws an error when it is configured with compression on and grouping off.

## Execution Plan

Add code to container runtime 
Update related tests to make sure that they expect an error to be thrown.

## Reviewer Guidance

Please let me know if there's something that I'm missing or that I should know about. Thanks!

Fixes: [AB#28625](https://dev.azure.com/fluidframework/235294da-091d-4c29-84fc-cdfc3d90890b/_workitems/edit/28625)

### CODE REVIEW

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 1]
```diff
@@ -1100,6 +1100,10 @@ export class ContainerRuntime
 				runtime.onSchemaChange(schema);
 			},
 		);
+		assert(
```
Comment (markfields) [inline packages/runtime/container-runtime/src/containerRuntime.ts:1103]: @MarioJGMsoft we need to update this to a simple if check and then throw a `UsageError`.  We reserve asserts for only codepaths that we believe are impossible to hit no matter the inputs to the system.

**Comment by markfields** [comment]
@dannimad -- Marking this as release-blocking.  The removal of this deprecated option was reverted, but we still need to make this breaking _behavior_ change in 2.20.

cc @jzaffiro for docs review. Thanks!

File: packages/test/test-version-utils/src/compatUtils.ts [hunk 2]
```diff
@@ -102,7 +103,7 @@ function filterRuntimeOptionsForVersion(
 	if (version.startsWith("1.")) {
 		options = {
 			// None of these features are supported by 1.3
-			compressionOptions: undefined,
+			compressionOptions: disabledCompressionConfig,
```
Comment (markfields) [inline packages/test/test-version-utils/src/compatUtils.ts:106]: @vladsud -- FYI, to disable compression pass this not undefined

File: packages/runtime/container-runtime/src/test/containerRuntime.spec.ts [hunk 3]
```diff
@@ -1456,10 +1458,7 @@ describe("Runtime", () => {
 				gcOptions: {},
 				loadSequenceNumberVerification: "close",
 				flushMode: FlushMode.TurnBased,
-				compressionOptions: {
-					minimumBatchSizeInBytes: 614400,
-					compressionAlgorithm: CompressionAlgorithms.lz4,
-				},
+				compressionOptions: disabledCompressionConfig,
```
Comment (markfields) [inline packages/runtime/container-runtime/src/test/containerRuntime.spec.ts:1461]: expand down to see `enableGroupedBatching: false`

File: packages/test/test-end-to-end-tests/src/test/blobs.spec.ts [hunk 4]
```diff
@@ -231,7 +231,7 @@ describeCompat("blobs", "FullCompat", (getTestObjectProvider, apis) => {
 		]);
 	});
 
-	[false, true].forEach((enableGroupedBatching) => {
+	[true].forEach((enableGroupedBatching) => {
```
Comment (markfields) [inline packages/test/test-end-to-end-tests/src/test/blobs.spec.ts:234]: We should revisit the test matrix here - may want to ensure coverage with grouping and compression both disabled?

File: packages/test/test-end-to-end-tests/src/test/messageSize.spec.ts [hunk 5]
```diff
@@ -257,7 +255,7 @@ describeCompat("Message size", "NoCompat", (getTestObjectProvider, apis) => {
 
 	const chunkingBatchesTimeoutMs = 200000;
 
-	[false, true].forEach((enableGroupedBatching) => {
+	[true].forEach((enableGroupedBatching) => {
```
Comment (markfields) [inline packages/test/test-end-to-end-tests/src/test/messageSize.spec.ts:258]: Same as above, for future - what about both disabled?

**Review by markfields — APPROVED** [review]

File: packages/test/test-version-utils/src/compatUtils.ts (hunk 2 above)
Comment (anthony-murphy) [reply packages/test/test-version-utils/src/compatUtils.ts:106]: why do we need to do this? why can't we just handle this internally?

Comment (anthony-murphy) [reply packages/test/test-version-utils/src/compatUtils.ts:106]: as this will be a breaking change for partners, and AFIK this was not called out anywhere before now

Comment (markfields) [reply packages/test/test-version-utils/src/compatUtils.ts:106]: We were queued up to remove the option altogether.  Pivoting to make the behavior change the break.

Comment (markfields) [reply packages/test/test-version-utils/src/compatUtils.ts:106]: > why can't we just handle this internally?

You mean just not compress even if it's requested via options?

**Review by jzaffiro — APPROVED** [review]
Approved for docs!

File: packages/test/test-version-utils/src/compatUtils.ts (hunk 2 above)
Comment (anthony-murphy) [reply packages/test/test-version-utils/src/compatUtils.ts:106]: i just don't understand this change and why it is necessary?

Comment (markfields) [reply packages/test/test-version-utils/src/compatUtils.ts:106]: > as this will be a breaking change for partners

This is for compat testing, not sure who this will break.  The function is `@internal` too

Comment (anthony-murphy) [reply packages/test/test-version-utils/src/compatUtils.ts:106]: so i only replied here, but  i see a bunch of changes that do the same thing? did the tests just not work? i'm just confused why we need any other changes besides just adding an error for the case we are explicitly disallowing, and i worry we are doing something that necessitates the other changes, and i don't know for certain it is safe to do

Comment (anthony-murphy) [reply packages/test/test-version-utils/src/compatUtils.ts:106]: to me, i think enableGroupBatching == false + undefined compressionOptions should just work, and compression should just be disabled. only explicit enableGroupBatching === false and defined compressionOptions  should fail

Comment (markfields) [reply packages/test/test-version-utils/src/compatUtils.ts:106]: Thanks for the suggestion, I agree that will be better.  Updating as applicable throughout, but leaving this one explicitly disabling.

File: packages/test/test-end-to-end-tests/src/test/containerRuntime.spec.ts [hunk 6]
```diff
@@ -120,6 +120,7 @@ describeCompat(
 						minimumBatchSizeInBytes: compression ? 1000 : Infinity,
 						compressionAlgorithm: CompressionAlgorithms.lz4,
 					},
+					enableGroupedBatching: compression, // Compression w/o grouping is not supported
```
Comment (markfields) [inline packages/test/test-end-to-end-tests/src/test/containerRuntime.spec.ts:123]: @MarioJGMsoft I think we need to revisit this too - I think there's an existing gap in test coverage where "Grouping Disabled" isn't covered

**Comment by jason-ha** [comment]
> @dannimad -- Marking this as release-blocking. The removal of this deprecated option was reverted, but we still need to make this breaking _behavior_ change in 2.20. (cc @jason-ha as FYI)
> 
> cc @jzaffiro for docs review. Thanks!

@MarioJGMsoft / @markfields, since the API change was moved out to 2.30, can you backfill with a replacement breaking change issue under [2.20 list](https://github.com/microsoft/FluidFramework/issues/22835)?

@anthony-murphy, I think you spotted the Word incompatibility. Are you able to confirm that this doesn't similarly impact Word (as the API change did)?

**Comment by MarioJGMsoft** [comment]
> > @dannimad -- Marking this as release-blocking. The removal of this deprecated option was reverted, but we still need to make this breaking _behavior_ change in 2.20. (cc @jason-ha as FYI)
> > cc @jzaffiro for docs review. Thanks!
> 
> @MarioJGMsoft / @markfields, since the API change was moved out to 2.30, can you backfill with a replacement breaking change issue under [2.20 list](https://github.com/microsoft/FluidFramework/issues/22835)?
> 
> @anthony-murphy, I think you spotted the Word incompatibility. Are you able to confirm that this doesn't similarly impact Word (as the API change did)?

I added an issue to the breaking change list, let me know what you think about it.

File: packages/test/test-end-to-end-tests/src/test/containerRuntime.spec.ts (hunk 6 above)
Comment (markfields) [reply packages/test/test-end-to-end-tests/src/test/containerRuntime.spec.ts:123]: I think this coverage is better placed in compression.spec.ts actually.  See AB#6287. those tests are disabled for cross-version compat, but we can reenable them with some work.
