### PR TITLE
Fix removed type test case generation

### LINKED ISSUE #8822: Type validation fails when removing an interface, unable to disable checks with broken types
## Describe the bug
If you completely remove an interface from a package, type validation will fail as it is unable to reference `current.<RemovedInterface>`.

### To Reproduce
1. Remove an interface from a definitions package (i.e. `@fluidframework/driver-definitions`).
2. Run `npm run build` for the modified package
3. See error (unable to resolve)

### Expected behavior
You should be able to disable this check by adding the interface to the broken types in `package.json` for the modified package.

### PR DESCRIPTION
**Pull request by scottn12**
This PR fixes type validation test generation for removed types.

Closes https://github.com/microsoft/FluidFramework/issues/8822

### CODE REVIEW

File: tools/build-tools/src/typeValidator/testGeneration.ts [hunk 1]
```diff
@@ -87,14 +87,25 @@ interface TestCaseTypeData extends TypeData{
 function buildTestCase(getAsType:TestCaseTypeData, useType:TestCaseTypeData, isCompatible: boolean){
     const getSig =`get_${getAsType.prefix}_${getFullTypeName(getAsType).replace(".","_")}`;
     const useSig =`use_${useType.prefix}_${getFullTypeName(useType).replace(".","_")}`;
+    const getIsRemoved = getAsType.kind.startsWith("Removed");
```
Comment (anthony-murphy) [inline tools/build-tools/src/typeValidator/testGeneration.ts:90]: can we avoid the string parse here and just add an `removed:boolean` field to TestCaseTypeData that will be true when it is removed

File: tools/build-tools/src/typeValidator/testGeneration.ts [hunk 2]
```diff
@@ -87,14 +87,25 @@ interface TestCaseTypeData extends TypeData{
...
+    }
+    testString.push(`    ${toTypeString(getAsType.prefix, getAsType)};`);
+    testString.push(`declare function ${useSig}(`);
+    if (!isCompatible && useIsRemoved) {
+        testString.push(`    // @ts-expect-error compatibility expected to be broken`);
+    }
+    testString.push(`    use: ${toTypeString(useType.prefix, useType)});`);
     testString.push(`${useSig}(`);
-    if(!isCompatible){
+    if(!isCompatible && !getIsRemoved && !useIsRemoved) {
```
Comment (anthony-murphy) [inline tools/build-tools/src/typeValidator/testGeneration.ts:105]: i don't think we care about removed in this case. if it is not compatible, we should always comment it out

File: tools/build-tools/src/typeValidator/testGeneration.ts [hunk 3]
```diff
@@ -87,14 +87,25 @@ interface TestCaseTypeData extends TypeData{
...
     const useSig =`use_${useType.prefix}_${getFullTypeName(useType).replace(".","_")}`;
+    const getIsRemoved = getAsType.kind.startsWith("Removed");
+    const useIsRemoved = useType.kind.startsWith("Removed");
     const testString: string[] =[];
-    testString.push(`declare function ${getSig}():\n    ${toTypeString(getAsType.prefix, getAsType)};`);
-    testString.push(`declare function ${useSig}(\n    use: ${toTypeString(useType.prefix, useType)});`);
+
+    testString.push(`declare function ${getSig}():`);
+    if (!isCompatible && getIsRemoved) {
+        testString.push(`    // @ts-expect-error compatibility expected to be broken`);
```
Comment (anthony-murphy) [inline tools/build-tools/src/typeValidator/testGeneration.ts:96]: can you add a better message to the comment here

Comment (anthony-murphy) [inline tools/build-tools/src/typeValidator/testGeneration.ts:96]: it we reused the same comment string its worth it to put it in a constant somewhere

File: tools/build-tools/src/typeValidator/testGeneration.ts (hunk 2 above)
Comment (scottn12) [reply tools/build-tools/src/typeValidator/testGeneration.ts:105]: I wasn't sure about this either, but I had noticed that the compiler would complain about the ts directive being unused. It seems like in this scenario `getSig()` does not produce any compilation errors (which does seem strange).

**Comment by anthony-murphy** [comment]
have you tested this? you can build and run the package directly against the repo:

1. cd tools\build-tools
2. npm install
3. npm run build
4. node dist/typeValidator/typeValidator.js -d d:\code\fluid\common\lib\driver-definitions

**Comment by scottn12** [comment]
Yes, I have tested it with `driver-definitions` on my PR branch (see https://github.com/microsoft/FluidFramework/pull/8827). However, I used `npm link` and then `fluid-type-validator -d .` from the driver-definitions directory.

File: tools/build-tools/src/typeValidator/testGeneration.ts (hunk 2 above)
Comment (anthony-murphy) [reply tools/build-tools/src/typeValidator/testGeneration.ts:105]: or does that create a problem due to the next this line not having an error, so the comment creates an error? if that's the case, can you add a commend to the code about what it is necessary

Comment (anthony-murphy) [reply tools/build-tools/src/typeValidator/testGeneration.ts:105]: missed your comment. i think i get it. since we say we know the declaration has an error, typescript probably just treats it as an `any` that make the below code valid, as typescript doesn't really check anything with an any.

File: tools/build-tools/src/typeValidator/testGeneration.ts (hunk 1 above)
Comment (scottn12) [reply tools/build-tools/src/typeValidator/testGeneration.ts:90]: The only issue is that we need to know if `currentType` is passed in as `getAsType` or `useType`. So, we may have to pass in two fields to this function, but that is probably still better than the string parse.

File: tools/build-tools/src/typeValidator/testGeneration.ts [hunk 4]
```diff
@@ -56,7 +56,7 @@ import * as current from "${indexPath}/index";
             testString.push(`* If breaking change required, add in package.json under typeValidation.broken.${oldProjectData.packageDetails.version}:`);
             testString.push(`* "${getFullTypeName(currentType)}": {"forwardCompat": false}`);
             testString.push("*/");
-            testString.push(...  buildTestCase(oldType, currentType, brokenData?.forwardCompat ?? true));
+            testString.push(...  buildTestCase(oldType, currentType, brokenData?.forwardCompat ?? true, false, currentTypeData === undefined));
```
Comment (anthony-murphy) [inline tools/build-tools/src/typeValidator/testGeneration.ts:59]: i think we should literally add a removed field to the type TestCaseTypeData, and set it when we create it above. only the current data type will be removed, the old type will never be removed

Comment (anthony-murphy) [reply tools/build-tools/src/typeValidator/testGeneration.ts:59]: after this, you will not need to modify the function signature, just check the remove field on the TestCaseTypeData's passing in

File: tools/build-tools/src/typeValidator/testGeneration.ts [hunk 5]
```diff
@@ -84,18 +84,28 @@ interface TestCaseTypeData extends TypeData{
     prefix: "old" | "current"
```
Comment (anthony-murphy) [inline tools/build-tools/src/typeValidator/testGeneration.ts:84]: like this:
```suggestion
    prefix: "old" | "current",
    removed: boolean,
```

**Review by anthony-murphy — APPROVED** [review]
