### PR TITLE
Fix fetch tool snapshot fetch problem.

### LINKED ISSUE #3541: Fetch tool fails to download snapshots
I've opened a bunch of issues with fluid-fetch failing to retrieve tokens, failing to get content using office.com links
But even if I can work-around all these issues, and it actually downloads ops for file on fluid preview, it fails to download snapshot with not much explanaiton:

ERROR: Error: Failed to load snapshot tree
    at fetchBlobsFromVersion (E:\FluidFramework\packages\tools\fetch-tool\dist\fluidFetchSnapshot.js:156:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.fluidFetchSnapshot (E:\FluidFramework\packages\tools\fetch-tool\dist\fluidFetchSnapshot.js:209:31)
    at async fluidFetchOneFile (E:\FluidFramework\packages\tools\fetch-tool\dist\fluidFetch.js:33:5)

We should
1. Expose better error message (sounds like we eat exception)
2, Fix the actual underlying problem.

### PR DESCRIPTION
**Pull request by jatgarg**
Fixes: https://github.com/microsoft/FluidFramework/issues/3541
1.) The id used to fetch from cache was wrong.
2.) Save the refreshed token in cache so that we don't refresh the token again and again.

### CODE REVIEW

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts [hunk 1]
```diff
@@ -571,16 +571,21 @@ export class OdspDocumentStorageService implements IDocumentStorageService {
 
                 const response = await fetchSnapshot(this.snapshotUrl!, storageToken, id, this.fetchFullSnapshot, this.logger);
                 const odspSnapshot: IOdspSnapshot = response.content;
-                // OdspSnapshot contain "trees" when the request is made for latest or the root of the tree, for all other cases it will contain "tree" which is the fetched tree with the id
```
Comment (jatgarg) [inline packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:574]: This comment is not valid anymore.

**Review by anthony-murphy — APPROVED** [review]
