### PR TITLE
Handle ServiceReadOnly error in odsp driver

### LINKED ISSUE #7241: ODSP driver: special handling for data center fall over / read-only farm
SPO can occasionally return 403 for r/w operations on document when there is a fail over to another data center.
The intention here is that data is read-only for a while, while fail over happens, to preserve integrity of the data.
While the process can take arbitrary time, we observe that this happens often in SPDF where new features are tested, and tenant is in this state for very short amount of time.

So it's proposed that SPO driver would understand that situation and would retry couple times with some exponential back-off logic and bail out after some number of retries. When it actually fails, it should return unique error code such that host app can reason about it and show reasonable message to user.

Client can differentiate such state vs. other 403 cases by looking at returned header “X-SP-SERVERSTATE : ReadOnly=1” 

Jatin - it would be great to implement this soonish, maybe even port it to 0.46 if change is relatively safe.
I think it should be generic enough (and impact all fetches), but file creation (posting initial snapshot) is the one that is the most impacted. If it does not fit in August, it should be moved to September

Please work with Ben (Teams) & Edmund Wong (SPO) if you need help here.

### PR DESCRIPTION
**Pull request by jatgarg**
Fixes: https://github.com/microsoft/FluidFramework/issues/7241
SPO can occasionally return 403 for r/w operations on document when there is a fail over to another data center.
The intention here is that data is read-only for a while, while fail over happens, to preserve integrity of the data. 
So when this error occurs, handle it and retry and then throw ServiceReadOnly error if it keeps occuring.

### CODE REVIEW

File: packages/drivers/odsp-driver/src/epochTracker.ts [hunk 1]
```diff
@@ -143,9 +144,11 @@ export class EpochTracker implements IPersistedFileCache {
         const request = this.addEpochInRequest(url, fetchOptions, addInBody);
         let epochFromResponse: string | undefined;
         try {
-            const response = await this.rateLimiter.schedule(
+            const response = await handleReadOnlyServerState(async () => this.rateLimiter.schedule(
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/epochTracker.ts:147]: I'm not sure I like it being here. Can it be incorporated into getWithRetryForTokenRefresh?
Is the concern that we only want to apply it to few calls, not to all SPO calls? It feels like it should be fine for it to apply to all calls that can fall into this bucket.

Comment (vladsud) [reply packages/drivers/odsp-driver/src/epochTracker.ts:147]: The other alternative - RetryCoherencyErrorsStorageAdapter that I've added to handle 409 errors. But it feels like it might be well suited for this case too (might want to rename class, or follow similar pattern and add another adapter on top of it - I'd prefer single class if code composes well).

File: packages/utils/odsp-doclib-utils/src/odspErrorUtils.ts [hunk 2]
```diff
@@ -124,15 +126,36 @@ export function createOdspNetworkError(
...
         case 401:
         case 403:
-            const claims = response?.headers ? parseAuthErrorClaims(response.headers) : undefined;
-            const tenantId = response?.headers ? parseAuthErrorTenant(response.headers) : undefined;
-            error = new AuthorizationError(errorMessage, claims, tenantId, { statusCode });
+            if (innerMostErrorCode === OdspErrorType.serviceReadOnly) {
+                error = new RetryableError(
+                    errorMessage,
+                    OdspErrorType.serviceReadOnly,
+                    { statusCode: serviceReadOnlyErrorCode },
```
Comment (vladsud) [inline packages/utils/odsp-doclib-utils/src/odspErrorUtils.ts:152]: I do not see a need to define status code and add it here. My preference would be to not have status codes at all (with driver doing projection to driver errors), but it's useful thing for logging where real code is returned by service (to validate that we mapped it correctly). Here - there is no code from service, so no need to invent one.

File: packages/utils/odsp-doclib-utils/src/odspErrorUtils.ts [hunk 3]
```diff
@@ -124,15 +126,36 @@ export function createOdspNetworkError(
...
     switch (statusCode) {
         case 400:
             error = new GenericNetworkError(errorMessage, false, { statusCode });
             break;
         case 401:
         case 403:
-            const claims = response?.headers ? parseAuthErrorClaims(response.headers) : undefined;
-            const tenantId = response?.headers ? parseAuthErrorTenant(response.headers) : undefined;
-            error = new AuthorizationError(errorMessage, claims, tenantId, { statusCode });
+            if (innerMostErrorCode === OdspErrorType.serviceReadOnly) {
```
Comment (vladsud) [inline packages/utils/odsp-doclib-utils/src/odspErrorUtils.ts:148]: I find it odd to use same type / name for ODSP internal errors and for our public API surface. I'd prefer these to be two different things. I.e. 

const OdspServiceReadOnlyErrorCode = "...";

enum OdspErrorType {
... 
serviceReadOnly = "";
}

Their values could be the same, but I'd rather not collide them to remove temptation to leverage one where the other one needs to be used.

That said, I thought initial messaging was to use headers to detect it, no? Maybe guidance changed...

**Comment by vladsud** [comment]
Tagging issue https://github.com/microsoft/FluidFramework/issues/7241

File: packages/drivers/odsp-driver-definitions/src/errors.ts [hunk 4]
```diff
@@ -42,6 +42,11 @@ export enum OdspErrorType {
     // This condition will result in any local changes being lost (i.e. only way to save state is by user
     // copying it over manually)
     cannotCatchUp = "cannotCatchUp",
+
+    // SPO can occasionally return 403 for r/w operations on document when there is a fail over to another data center.
```
Comment (jvoels) [inline packages/drivers/odsp-driver-definitions/src/errors.ts:46]: Do we have feedback for ODSP on how they're handling these scenarios? Sometimes I feel like there are a lot of problems packed underneath 403. Is this even the right status code from the service? At a glance I would have expected the service to 405. We should consider proposing this feedback to ODSP whenever we come across it, in addition to adapting.

Comment (jvoels) [inline packages/drivers/odsp-driver-definitions/src/errors.ts:46]: The code comment here is too detailed about inner workings and speculating the state of ODSP's service. We should simply understand the response and handling prescribed. 

"Why" makes for great code comments, but only up until the point the commentary is dependent on private details of something else.

File: api-report/odsp-driver-definitions.api.md [hunk 5]
```diff
@@ -157,6 +157,8 @@ export enum OdspErrorType {
     fluidNotEnabled = "fluidNotEnabled",
     invalidFileNameError = "invalidFileNameError",
     outOfStorageError = "outOfStorageError",
+    // (undocumented)
+    serviceReadOnly = "serviceReadOnly",
```
Comment (jvoels) [inline api-report/odsp-driver-definitions.api.md:161]: Consider "server" not "service"

The communication from ODSP in this case is specifically that you ended up on read only server. The reason why it is retryable is because the server is readonly not because the actual resource/document/data or entire 'service' is read only.

0.02, feel free to push back on that notion. 

The header appears to be X-SP-SERVERSTATE : ReadOnly=1

**Comment by jvoels** [comment]
>     return stack;

As a part of this review we should include (compliantly) a sample response that demonstrates what this facet looks like in the response and why this is a stable/viable process for detecting this state.

That would also bring some clarity as to why we are able to look here and nothing in this change directly connect to the header (as Vlad inquires about elsewhere)

---
Refers to: packages/utils/odsp-doclib-utils/src/odspErrorUtils.ts:117 in 7750fbd. [](commit_id = 7750fbd5cc3dbdc208518686073f9a78eea1c4d8, deletion_comment = False)

File: packages/drivers/odsp-driver/src/handleReadonlyServerState.ts [hunk 6]
```diff
@@ -0,0 +1,56 @@
...
+            // If the innerMostError is not "ServiceReadonly" error or we have retried the max times, then just
+            // give up.
+            if (error?.innerMostErrorCode !== OdspErrorType.serviceReadOnly || numRetries >= maxRetries) {
+                break;
+            }
+            numRetries++;
+            // If the error is about server becoming readonly for sometime, then wait for the specified time
+            // before retrying. If the waitTime is not specified, then we start with retrying immediately
+            // to max of 8s.
+            retryAfterMs = getRetryDelayFromError(error) ?? Math.min(retryAfterMs, 8000);
```
Comment (jvoels) [inline packages/drivers/odsp-driver/src/handleReadonlyServerState.ts:38]: >getRetryDelayFromError [](http://example.com/codeflow?start=27&length=22)

Does there happen to be "canRetry" in their response?
I'm curious if we need to bake the idea that this facet is retriable on our own and specifically, or if we should be respecting an existing and more generic marker.

This could be more clear if some sample response(s) for the sceanrio were included as a part of the review.

File: packages/drivers/odsp-driver-definitions/src/errors.ts (hunk 4 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver-definitions/src/errors.ts:46]: Currently they return 403 code with this response: { "code": "accessDenied", "innerError": { "code": "serviceReadOnly" }, "message": "Database Is Read Only" }
Current suggestion is to read the innerMostCode. For now we need to go with this and then I will talk with them about returning another status code but maybe they have this code for such scenarios for vroom apis.

File: packages/drivers/odsp-driver/src/handleReadonlyServerState.ts (hunk 6 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver/src/handleReadonlyServerState.ts:38]: Sorry I failed the mention the issue link in the description. You can take a look. 
The error that we are evaluating here is generated by driver code by looking at the server response. So this checks if that error has any wait time baked in the error. Their response for this specific error does not have any wait time.

File: packages/drivers/odsp-driver/src/epochTracker.ts (hunk 1 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver/src/epochTracker.ts:147]: I added this in epochTracker because that is the choke point for all the storage calls even those made outside of storage service like ops and create new. This will enable this feature for all calls.

Comment (jatgarg) [reply packages/drivers/odsp-driver/src/epochTracker.ts:147]: I don't think "getWithRetryForTokenRefresh" is right place because that is for token refresh.

File: packages/drivers/odsp-driver-definitions/src/errors.ts (hunk 4 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver-definitions/src/errors.ts:46]: Shortened the comment a bit. Just wanted a bit why it becomes r/w.

File: packages/utils/odsp-doclib-utils/src/odspErrorUtils.ts (hunk 3 above)
Comment (jatgarg) [reply packages/utils/odsp-doclib-utils/src/odspErrorUtils.ts]: Yes, the guidance changed on how to detect the error. No headers now.

File: packages/drivers/odsp-driver/src/epochTracker.ts (hunk 1 above)
Comment (vladsud) [reply packages/drivers/odsp-driver/src/epochTracker.ts:147]: Yes, RetryCoherencyErrorsStorageAdapter will not capture file creation (as an example)

Is it for all calls, or only calls that write (modify) file?
Glancing through usage of getWithRetryForTokenRefresh, do we have problems in any of these flows?
- I assume it should not apply to flows like getFileLinkCore and similar, right?
- What about connectToDeltaStream - can joinSession or PUSH connection return with same error? Should we handle it there too?
- readTree -> fetchSnapshot

File: packages/drivers/odsp-driver/src/epochTracker.ts [hunk 7]
```diff
@@ -177,9 +180,11 @@ export class EpochTracker implements IPersistedFileCache {
...
                 async () => fetchArray(request.url, request.fetchOptions),
-            );
+            ),
+            this.logger,
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/epochTracker.ts:186]: indent - arguments should be not inline with statements that follow

File: packages/utils/odsp-doclib-utils/src/odspErrorUtils.ts (hunk 3 above)
Comment (vladsud) [reply packages/utils/odsp-doclib-utils/src/odspErrorUtils.ts]: That's fine, but we should not compare innerMostErrorCode  to OdspErrorType.serviceReadOnly. Developer should be free to change OdspErrorType enums and the code should continue to work as expected (minus host changes). There should be clearly defined constant for this value with a comment that the value is defined by ODSP and can't be changed.

Comment (jatgarg) [reply packages/utils/odsp-doclib-utils/src/odspErrorUtils.ts]: I added that constant in this change. Will add this comment too.

File: packages/drivers/odsp-driver/src/handleReadonlyServerState.ts [hunk 8]
```diff
@@ -0,0 +1,56 @@
...
+export async function handleReadOnlyServerState<T>(
+    api: () => Promise<T>,
+    logger: ITelemetryLogger,
+    fetchType: FetchType,
+) {
+    let result: T | undefined;
+    let success = false;
+    let retryAfterMs = 1000; // has to be positive!
+    let numRetries = 0;
+    const maxRetries = 5;
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/handleReadonlyServerState.ts:21]: I think we should follow up here (with an issue to consider in the future).
These retries multiplex in non-easily trackable shape. I.e. here we have 5 retries, 409 has its own retries. This makes it hard to control end user experience, as in the worst case we could have 5*3 retries. Usually it's better to have a single place where overall policy RE retries is implemented.

File: packages/drivers/odsp-driver/src/handleReadonlyServerState.ts [hunk 9]
```diff
@@ -0,0 +1,56 @@
...
+    let lastError: any;
+    do {
+        try {
+            result = await api();
+            success = true;
+        } catch (error) {
+            lastError = error;
+            // If the innerMostError is not "ServiceReadonly" error or we have retried the max times, then just
+            // give up.
+            if (error?.innerMostErrorCode !== OdspErrorType.serviceReadOnly || numRetries >= maxRetries) {
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/handleReadonlyServerState.ts:31]: I do not think this code should work with innerMostErrorCode, instead it should use resolved errorType from createOdspNetworkError() and thus have logic on what is OdspErrorType.serviceReadOnly in one place.

File: packages/drivers/odsp-driver/src/handleReadonlyServerState.ts [hunk 10]
```diff
@@ -0,0 +1,56 @@
...
+            // If the error is about server becoming readonly for sometime, then wait for the specified time
+            // before retrying. If the waitTime is not specified, then we start with retrying immediately
+            // to max of 8s.
+            retryAfterMs = getRetryDelayFromError(error) ?? Math.min(retryAfterMs, 8000);
+            await delay(retryAfterMs);
+            retryAfterMs *= 2;
+        }
+    } while (!success);
+    if (numRetries > 0) {
+        logger.sendTelemetryEvent({
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/handleReadonlyServerState.ts:44]: This error is a bit hard to consume as one needs to look at retry property to determine if it was an actual error (propagated through) or not.
I'd rather simplify and say we log a generic error every failed attempt, and then log one error event if we are propagating error down.

File: packages/drivers/odsp-driver/src/epochTracker.ts (hunk 1 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver/src/epochTracker.ts:147]: Yes, join session can have this issue as I have been told. But not the fetch snapshot and getblobs apis as those are purely read apis.

File: packages/drivers/odsp-driver/src/createFile.ts [hunk 11]
```diff
@@ -115,14 +116,19 @@ export async function createNewEmptyFluidFile(
...
 
-                const fetchResponse = await epochTracker.fetchAndParseAsJSON<ICreateFileResponse>(
-                    url,
-                    {
-                        body: undefined,
-                        headers,
-                        method: "PUT",
-                    },
-                    "createFile");
+                const fetchResponse = await runWithRetry(
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/createFile.ts:119]: Please rename runWithRetry to include at least some hints in the name why retry is needed / type of retry it does
runWithRetryForServiceRecovery or something like that

**Review by jatgarg — COMMENTED** [review]
.

File: packages/drivers/odsp-driver/src/retryUtils.ts [hunk 12]
```diff
@@ -0,0 +1,60 @@
...
+    checkRetry?: () => void,
+): Promise<T> {
+    let retryAfter = 1000;
+    const start = performance.now();
+    for (let retry = 1; ; retry++) {
+        try
+        {
+            return await api();
+        } catch (error) {
+            if (checkRetry !== undefined) {
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/retryUtils.ts:28]: Should this check be before actual call to api()? Maybe in both places?

File: packages/utils/odsp-doclib-utils/src/odspErrorUtils.ts [hunk 13]
```diff
@@ -124,15 +127,35 @@ export function createOdspNetworkError(
...
     switch (statusCode) {
         case 400:
             error = new GenericNetworkError(errorMessage, false, { statusCode });
             break;
         case 401:
         case 403:
-            const claims = response?.headers ? parseAuthErrorClaims(response.headers) : undefined;
-            const tenantId = response?.headers ? parseAuthErrorTenant(response.headers) : undefined;
-            error = new AuthorizationError(errorMessage, claims, tenantId, { statusCode });
+            if (innerMostErrorCode === OdspServiceReadOnlyErrorCode) {
```
Comment (vladsud) [inline packages/utils/odsp-doclib-utils/src/odspErrorUtils.ts:149]: Maybe add some comment here on why we differentiate this case and how it's handled in the code base, to help next engineer :)

**Review by vladsud — APPROVED** [review]

File: api-report/odsp-driver-definitions.api.md (hunk 5 above)
Comment (vladsud) [reply api-report/odsp-driver-definitions.api.md:161]: I like service more than server. Server is a particular box to me, while whole service is down for this tenant (no matter what box one connects to).

Comment (jvoels) [reply api-report/odsp-driver-definitions.api.md:161]: Makes sense, thanks for clarifying.

File: packages/drivers/odsp-driver/src/retryUtils.ts (hunk 12 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver/src/retryUtils.ts:28]: I think just before is fine.

File: packages/drivers/odsp-driver/src/handleReadonlyServerState.ts (hunk 9 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver/src/handleReadonlyServerState.ts]: Removed this code and merged with storage adapter for retry.
