### PR TITLE
Request parser handle pathing

### LINKED ISSUE #2677: Request Parser should handle pathing correctly when createSubRequest is called
## Describe the bug
Today RequestParser handles createSubRequest pathing by joining subparts with '/' and returning undefined when it does not see valid path parts beyond the subrequest. This introduces a few bugs detailed below. Note that this issue has so far hidden another bug in ComponentHandles in the Fluid repo so the component handle issue might want to be fixed first before fixing this issue. @skylerjokiel is there an issue for the componenthandle bug?

### To Reproduce
Call RequestParser.createSubRequest(1) on several paths which exposes several (all related) bugs in the createSubRequest logic

Bug 1: leading slash (and trailing slash where needed?) is dropped:
Setup: Request URL is "/id/id2/"
Expected: "/id2" or "/id2/"
Actual: "id2"

Bug 2: Returned value for final sub request is undefined instead of '/'
Setup: Request URL is "/"
Expected: "/"
Actual: ""

Bug 3: Returned value for sub request is undefined and does not include query params
Setup: request url is "/?queryParams
Expected: "/?queryParams"
Actual: undefined

### PR DESCRIPTION
**Pull request by chensixx**
Fixed #2677 
Changed createSubRequest and the output request url will always have a leading slash, as well as always including the query parameters at the end.

### CODE REVIEW

File: packages/runtime/runtime-utils/src/requestParser.ts [hunk 1]
```diff
@@ -13,6 +13,9 @@ export class RequestParser implements IRequest {
      * @param url - the url to get path parts of
      */
     public static getPathParts(url: string): readonly string[] {
+        if (url.split("/")[0] === "" && url.split("/").length === 2) {
```
Comment (vladsud) [inline packages/runtime/runtime-utils/src/requestParser.ts:16]: That's pretty expensive piece of code! Parsing and allocating array twice, just to do trivial test?
Also not sure why /a is special here. i.e. /a -> [a], but /a/b -> ["", a, b].
Don't we want to fix seconds case as well?

File: packages/runtime/runtime-utils/src/requestParser.ts [hunk 2]
```diff
@@ -41,7 +44,7 @@ export class RequestParser implements IRequest {
     protected constructor(private readonly request: Readonly<IRequest>) {
         const queryStartIndex = this.request.url.indexOf("?");
         if (queryStartIndex >= 0) {
-            this.query = this.request.url.substring(queryStartIndex);
+            this.query = `/` + `${this.request.url.substring(queryStartIndex)}`;
```
Comment (vladsud) [inline packages/runtime/runtime-utils/src/requestParser.ts:47]: why do we need this trailing slash?

Comment (vladsud) [reply packages/runtime/runtime-utils/src/requestParser.ts:47]: Maybe it's right (looking at UT examples), I'm not sure.

File: packages/runtime/runtime-utils/src/test/requestParser.spec.ts [hunk 3]
```diff
@@ -47,20 +48,57 @@ describe("RequestParser", () => {
...
+    describe(".createSubRequest with query params", () => {
+        let requestParser2: RequestParser;
+        beforeEach(() => {
+            requestParser2 = RequestParser.create({ url: "/dataStoreId/some/route/?queryparams" });
+        });
+        it("Create request from part 0", () => {
+            assert.strictEqual(requestParser2.createSubRequest(0)?.url, "/dataStoreId/some/route/?queryparams");
+        });
+        it("Create request from part 1", () => {
+            assert.strictEqual(requestParser2.createSubRequest(1)?.url, "/some/route/?queryparams");
```
Comment (vladsud) [inline packages/runtime/runtime-utils/src/test/requestParser.spec.ts:76]: I think all these question marks should be removed - API never returns undefined.

File: packages/runtime/runtime-utils/src/test/requestParser.spec.ts [hunk 4]
```diff
@@ -47,20 +48,57 @@ describe("RequestParser", () => {
...
+            assert.throws(() => requestParser2.createSubRequest(4));
+            assert.throws(() => requestParser2.createSubRequest(-1));
+        });
+    });
+    describe(".createSubRequest with special urls", () => {
+        beforeEach(() => {
+        });
+        it("Create request for `/`", () => {
+            const testRequestParser = RequestParser.create({ url: "/" });
+            assert.strictEqual(testRequestParser.createSubRequest(1)?.url, "/");
```
Comment (vladsud) [inline packages/runtime/runtime-utils/src/test/requestParser.spec.ts:94]: I think it should fail. testRequestParser.createSubRequest(0) should return "/", (1) should throw,

Comment (vladsud) [reply packages/runtime/runtime-utils/src/test/requestParser.spec.ts:94]: I'd add testing for (0) & (1) into next it() test as well.

File: packages/runtime/runtime-utils/src/test/requestParser.spec.ts [hunk 5]
```diff
@@ -47,20 +48,57 @@ describe("RequestParser", () => {
...
         it("Create request from parts length ", () => {
-            assert.equal(requestParser.createSubRequest(3)?.url, "");
+            assert.strictEqual(requestParser.createSubRequest(3)?.url, "/");
         });
         it("Create request from invalid part ", () => {
             assert.throws(() => requestParser.createSubRequest(4));
             assert.throws(() => requestParser.createSubRequest(-1));
         });
     });
+    describe(".createSubRequest with query params", () => {
```
Comment (vladsud) [inline packages/runtime/runtime-utils/src/test/requestParser.spec.ts:67]: Any chance you can refactor this code (everything in describe() behind test(url) function, and call test() twice:
test("/dataStoreId/some/route/?queryparams");
test("dataStoreId/some/route/?queryparams");

all the it() methods should result in exactly same outcome!

**Comment by vladsud** [comment]
+@leeviana , given that area popped up today in discussion :)

File: packages/runtime/runtime-utils/src/requestParser.ts (hunk 1 above)
Comment (chensixx) [reply packages/runtime/runtime-utils/src/requestParser.ts:16]: I just deleted this part and I will push later

**Review by vladsud — APPROVED** [review]

**Comment by chensixx** [comment]
THANK GOD

File: packages/runtime/runtime-utils/src/requestParser.ts [hunk 6]
```diff
@@ -75,16 +75,30 @@ export class RequestParser implements IRequest {
...
             throw new Error("incorrect sub-request");
         }
-        const path = this.pathParts.slice(startingPathIndex).join("/");
+        if (startingPathIndex === pathLen && this.url.includes("?")) {
+            return {
+                url:`${this.query}`,
+                headers: this.headers,
+            };
+        }
+        const path = `/` + `${this.pathParts.slice(startingPathIndex).join("/")}`;
```
Comment (ChumpChief) [inline packages/runtime/runtime-utils/src/requestParser.ts:99]:
```suggestion
        const path = `/${this.pathParts.slice(startingPathIndex).join("/")}`;
```

File: packages/runtime/runtime-utils/src/requestParser.ts [hunk 7]
```diff
@@ -75,16 +75,30 @@ export class RequestParser implements IRequest {
...
         return {
-            url: path + this.query,
+            url: `${path}` + `${this.query}`,
```
Comment (ChumpChief) [inline packages/runtime/runtime-utils/src/requestParser.ts:101]:
```suggestion
            url: `${path}${this.query}`,
```

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 8]
```diff
@@ -988,6 +988,7 @@ export class ContainerRuntime extends TypedEventEmitter<IContainerRuntimeEvents>
 
             const dataStore = await this.getDataStore(id, wait);
             const subRequest = requestParser.createSubRequest(1);
+            subRequest.url = subRequest.url.slice(1);
```
Comment (ChumpChief) [inline packages/runtime/container-runtime/src/containerRuntime.ts:991]: Chatted with Si about this - I'd like to see us be consistent in request format throughout our repo (i.e. always have a leading slash if we believe that is the right behavior), so I suggested to remove this `slice()` and instead handle the leading slash in the request handler, which may require adding some back-compat support.

File: packages/runtime/runtime-utils/src/requestParser.ts [hunk 9]
```diff
@@ -41,7 +41,7 @@ export class RequestParser implements IRequest {
     protected constructor(private readonly request: Readonly<IRequest>) {
         const queryStartIndex = this.request.url.indexOf("?");
         if (queryStartIndex >= 0) {
-            this.query = this.request.url.substring(queryStartIndex);
+            this.query = `/` + `${this.request.url.substring(queryStartIndex)}`;
```
Comment (ChumpChief) [inline packages/runtime/runtime-utils/src/requestParser.ts:44]:
```suggestion
            this.query = `/${this.request.url.substring(queryStartIndex)}`;
```

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 8 above)
Comment (vladsud) [reply packages/runtime/container-runtime/src/containerRuntime.ts:991]: I believe request handlers should be able to handle request with or without slash, but all our code that generates URIs should be consistent and always use leading slash. Note that this partially will go away with https://github.com/microsoft/FluidFramework/pull/4351, as request handling (for most part) will be by product of registering routing paths.

Comment (chensixx) [reply packages/runtime/container-runtime/src/containerRuntime.ts:991]: Keeping this part for now. If we remove this line, it will break 2 tests in `packages\test\end-to-end-tests\src\test\primedComponent.spec.ts` : new loader, old runtime and new ContainerRuntime, old DataStoreRuntime. These two tests call the old version of request which doesn't handle the case of leading slash.

File: packages/framework/aqueduct/src/data-objects/dataObject.ts [hunk 10]
```diff
@@ -40,10 +41,20 @@ export abstract class DataObject<O extends IFluidObject = object, S = undefined,
...
+            let value = this.root.get<string>(url);
             if (value === undefined) {
-                return { mimeType: "text/plain", status: 404, value: `request ${url} not found` };
+                const value2 = this.root.get<string>(url.slice(1));
+                if (value2 === undefined) {
+                    return { mimeType: "text/plain", status: 404, value: `request ${url} not found` };
+                }
+                else {
+                    this.root.set(url.slice(1),value2);
+                    this.root.delete(url);
```
Comment (ChumpChief) [inline packages/framework/aqueduct/src/data-objects/dataObject.ts:55]: I know I suggested this change, but after more thought I don't think there's value in converting the format here -- I don't think there's really a benefit from having the key format exactly match the URL (even though it currently does today).

This way you can just join the path parts with '/' to get the key, and thereby avoid the slice calls, something like

```typescript
if (requestParser.pathParts[0] === this.bigBlobs) {
    const value = this.root.get<string>(requestParser.pathParts.join("/"));
    // ... the rest
}
```

File: packages/framework/aqueduct/src/test/defaultRoute.spec.ts [hunk 11]
```diff
@@ -65,16 +65,17 @@ describe("defaultRouteRequestHandler", () => {
         const handler = defaultRouteRequestHandler("objectId");
 
         const requestParser = RequestParser.create({ url: "", headers: {} });
+        console.log(requestParser);
```
Comment (ChumpChief) [inline packages/framework/aqueduct/src/test/defaultRoute.spec.ts:68]: Remove console.log calls before checking in

File: packages/runtime/runtime-utils/src/requestParser.ts [hunk 12]
```diff
@@ -41,7 +41,7 @@ export class RequestParser implements IRequest {
     protected constructor(private readonly request: Readonly<IRequest>) {
         const queryStartIndex = this.request.url.indexOf("?");
         if (queryStartIndex >= 0) {
-            this.query = this.request.url.substring(queryStartIndex);
+            this.query = `/${this.request.url.substring(queryStartIndex)}`;
```
Comment (ChumpChief) [inline packages/runtime/runtime-utils/src/requestParser.ts:44]: The query should not include the slash - instead add it in createSubRequest if necessary.

**Review by ChumpChief — APPROVED** [review]
