### PR TITLE
Change elected summarizer when not summarizing for too long

### LINKED ISSUE #1791: Protect from lingering inactive summarizers
Currently, summarizer clients can outlive their parent containers for just long enough to summarize one more time.  This means that when other clients are deciding whether or not to spawn a summarizer, they also verify that there are no other summarizer clients in the quorum.

It might be nice to protect against the error case where a bad/inactive summarizer client remains in the quorum indefinitely, preventing other clients from spawning summarizers.

### LINKED ISSUE #5222: Spawn summarizer when elected client is not summarizing
This is a draft proposal for improving summarizer resiliency in cases where either elected client fails to spawn summarizer client, or spawned summarizer client fails to summarize for too long. Usually clients will get booted from the quorum if they sit too long, but there are exceptions: recently we have seen issues with clients sticking around in the quorum even after they have disconnected. There can always be problems with a specific client preventing it from summarizing as well.

All clients already have a summarizer running which tracks summary ops. It might be good to have this raise some event if enough ops/time pass without a summary attempt (ack?). If this heuristic is deterministic/consistent enough, then clients could unanimously elect a new summarizer client. I think the approach for this can be to pick off clients 1-by-1 from oldest to newest in the quorum.

Ideally it would be aware of which clients are submitting the summaries, so it can handle the case where the originally elected summarizer comes back online.

This requires some current checks to be bypassed/modified:
- We only allow one summarizer client in the quorum at a time. However, if the summarizer client connected isn't summarizing, we need to bypass this check. I think this goes hand-in-hand with specifically marking clients as "bad", so we only allow one non-bad summarizer client in quorum at once.
- It would be more robust if other clients could know who the parent clients are of the summarizer clients. This way, all clients can determine "bad" client pairs.

### PR DESCRIPTION
**Pull request by arinwt**
Fixes #5222
Fixes #1791

The goal of the change is to have all clients unanimously and deterministically change their elected summarizer client whenever too many ops pass without a summary ack. In order to ensure eventual consistency here, the decision is purely based on inbound op processing: we use the sequence numbers of summary acks and other ops to figure it out.

The current behavior is that the oldest interactive client is responsible for summarizing. If 3000 inbound ops are seen since the last summary ack, that client will be marked as invalid, and the next oldest client will be elected. If no summary ack is seen since that client is elected, we use the first inbound op since they were elected as the baseline for the sequence number comparison.

## Implementation Details
**OrderedClientCollection** - doubly linked list which tracks all the clients in the Quorum, sorted by their join sequence number.
**OrderedClientElection** - this is an adapter over the OrderedClientCollection which allows the caller to specify an `isEligibleFn` function to filter out non-interactive clients (or other criteria) and track a client as an "elected" client. It provides APIs to increment and reset the elected client. The rule is that the oldest eligible client is the elected client, and when increment is called the next oldest eligible client is elected instead (which means it should only be called deterministically for all clients to achieve eventual consistency). At any point, the elected client can be reset back to the oldest eligible client again, which should also be deterministically called.

The above 2 classes achieve something similar to the old leader election or task picking, but without requiring any additional ops or signals to be used. This is because the information is based on other ops already being passed around: join op sequence numbers, summaryAck sequence numbers, and other op sequence numbers.

**ElectedSummarizerManager** - this is a helper class used by SummaryManager to handle electing which client is responsible for generating summaries. It leverages the above OrderedClientElection to achieve this, and decides to reelect after some number of ops have passed since the last successful summary. If all clients are elected, it directly resets and goes back to electing the oldest client again.

Added tests for all 3 above classes.

### CODE REVIEW

File: packages/runtime/container-runtime/src/throttler.ts [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+ */
+ export class Throttler {
+    private startTimes: number[] = [];
+    constructor(
+        private readonly delayWindowMs: number,
+        private readonly maxDelayMs: number,
+        private readonly delayFunction: (n: number) => number,
+    ) { }
+
+    public get attempts() {
```
Comment (anthony-murphy) [inline packages/runtime/container-runtime/src/throttler.ts:18]: this looks wrong. won't the shift below affect the length and loose attempts?

File: packages/runtime/container-runtime/src/throttler.ts [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+        return this.startTimes.length;
+    }
+
+    public getDelay() {
+        const now = Date.now();
+        this.startTimes = this.startTimes.filter((t) => now - t < this.delayWindowMs);
+        const delayMs = Math.min(this.delayFunction(this.startTimes.length), this.maxDelayMs);
+        this.startTimes.push(now);
+        this.startTimes = this.startTimes.map((t) => t + delayMs); // account for delay time
+        if (delayMs === this.maxDelayMs) {
```
Comment (anthony-murphy) [inline packages/runtime/container-runtime/src/throttler.ts:28]: i don't understand why all start times are shifted

File: packages/runtime/container-runtime/src/throttler.ts [hunk 3]
```diff
@@ -0,0 +1,36 @@
+/*!
+ * Copyright (c) Microsoft Corporation and contributors. All rights reserved.
+ * Licensed under the MIT License.
+ */
+
+/**
+ * Used to give increasing delay times for throttling a single functionality.
+ * Delay is based on previous attempts within specified time window, ignoring actual delay time.
+ */
+ export class Throttler {
```
Comment (anthony-murphy) [inline packages/runtime/container-runtime/src/throttler.ts:10]: would be good to have unit tests for this, as the behaviors are non obvious, and could easily be broken

File: packages/runtime/container-runtime/src/summaryManager.ts [hunk 4]
```diff
@@ -200,20 +257,14 @@ export class SummaryManager extends EventEmitter implements IDisposable {
             return { shouldSummarize: false, stopReason: "parentShouldNotSummarize" };
         } else if (this.disposed) {
             return { shouldSummarize: false, stopReason: "disposed" };
-        } else if (this.orderedClients.getSummarizerCount() > 0) {
```
Comment (anthony-murphy) [inline packages/runtime/container-runtime/src/summaryManager.ts:203]: based on the comment i get why we need to remove shouldStart, but is the case handled elsewhere?

Comment (anthony-murphy) [reply packages/runtime/container-runtime/src/summaryManager.ts:203]: is it that now refreshSummarizer will detect this state based on this.electedSummarizerManager.electedClientId, so while getShouldSummarizeState will return true, it won't be electect so it it won't run? if so, i wonder if we should rename getShouldSummarizeState to canSummarizeState, or supportsSumarizingState, as whether it should or not is really controlled by election

Comment (anthony-murphy) [reply packages/runtime/container-runtime/src/summaryManager.ts:203]: or you could move the newSummarizerClientId logic and event emitting from refreshSummarizer to getShouldSummarizeState

**Comment by anthony-murphy** [comment]
>         // computed summarizer client id

this comment is no longer accurate given the above

---
Refers to: packages/runtime/container-runtime/src/summaryManager.ts:275 in a46ce7a. [](commit_id = a46ce7a5ab7ff8aa070415c9fe3cc32fab488e1d, deletion_comment = False)

File: packages/runtime/container-runtime/src/summaryManager.ts [hunk 5]
```diff
@@ -320,7 +371,7 @@ export class SummaryManager extends EventEmitter implements IDisposable {
 
     private tryRestart(): void {
         const shouldSummarizeState = this.getShouldSummarizeState();
-        if (shouldSummarizeState.shouldSummarize && shouldSummarizeState.shouldStart) {
+        if (shouldSummarizeState.shouldSummarize) {
```
Comment (anthony-murphy) [inline packages/runtime/container-runtime/src/summaryManager.ts:374]: >( [](http://example.com/codeflow?start=11&length=1)

this check is no longer complete, as it doesn't valid the client is actuall the client that should summarize. does that matter here?

File: packages/runtime/container-runtime/src/summaryManager.ts [hunk 6]
```diff
@@ -45,12 +52,103 @@ enum SummaryManagerState {
...
+        private readonly refreshSummarizer: () => void,
+    ) {
+        // On every inbound op, if enough ops pass without seeing a summary ack (per elected client),
+        // elect a new client and log to telemetry.
+        this.summaryCollection.on("default", (op) => {
+            if (this.lastSummaryAckSeqForClient === undefined) {
+                // We don't have enough information to know if a client is not summarizing yet.
+                if (this.electedClientId !== undefined) {
+                    this.lastSummaryAckSeqForClient = op.sequenceNumber;
+                }
```
Comment (anthony-murphy) [inline packages/runtime/container-runtime/src/summaryManager.ts:94]: why store the seq of some random op?

Comment (anthony-murphy) [reply packages/runtime/container-runtime/src/summaryManager.ts:94]: i think i get it, but it could use more comment describing why this ok, and why it makes the math work, even when each client could have a different initial value here

File: packages/runtime/container-runtime/src/summaryManager.ts [hunk 7]
```diff
@@ -45,12 +52,103 @@ enum SummaryManagerState {
...
+                this.invalidClientId = electedClientId;
+
+                // Elect a new summarizer client.
+                this.clientElection.incrementElectedClient();
+            }
+        });
+
+        // When a summary ack comes in, reset our op seq counter.
+        this.summaryCollection.on(MessageType.SummaryAck, (op) => {
+            this.invalidClientId = undefined;
```
Comment (anthony-murphy) [inline packages/runtime/container-runtime/src/summaryManager.ts:119]: should we also reset our electedClientId if needed as given the above we might not even know who he summarizer should be right now

**Comment by anthony-murphy** [comment]
Still reviewing, but it think we should wait and check this in after the 0.41 release, so it has the full amount of time to bake in our stress runs. also sorry it took sooooo long to review here, been having trouble finding a solid chuck of time to really dig in here

File: packages/runtime/container-runtime/src/orderedClientElection.ts [hunk 8]
```diff
@@ -110,154 +136,173 @@ export class OrderedClientElection extends TypedEventEmitter<IOrderedClientElect
...
-        this.eligibleCount++;
+        this.clientMap.set(clientId, newClient);
         return newClient;
     }
 
-    private deleteEligibleClient(removeClient: Readonly<IEligibleClient>) {
+    private removeClient(clientId: string): ITrackedClient | undefined {
+        const removeClient = this.clientMap.get(clientId);
+        if (removeClient === undefined) {
+            return;
```
[the remark this answers is not in the document]
Comment (anthony-murphy) [reply packages/runtime/container-runtime/src/orderedClientElection.ts:152]: as we should populate from initial quorum, and then see consistent join/leaves

File: packages/runtime/container-runtime/src/orderedClientElection.ts [hunk 9]
```diff
@@ -110,154 +136,173 @@ export class OrderedClientElection extends TypedEventEmitter<IOrderedClientElect
...
- export class Throttler {
-    private startTimes: number[] = [];
-    constructor(
-        private readonly delayWindowMs: number,
-        private readonly maxDelayMs: number,
-        private readonly delayFunction: (n: number) => number,
-    ) { }
+    public getAllEligibleClients(): ITrackedClient[] {
+        return this.orderedClientCollection.getAllClients().filter(this.isEligibleFn);
+    }
```
Comment (anthony-murphy) [inline packages/runtime/container-runtime/src/orderedClientElection.ts:295]: i wonder if it would be easier to just keep a map in this class as well as it will also remove the need for this._eligibleCount. i tend to dislike any kind of ref counting, as it's easy to break

**Review by anthony-murphy — DISMISSED** [review]
Looks good. I have some question comments, but no major concerns. Please don't merge until after 0.41 cuts to ensure this has time to bake in stress.

File: packages/runtime/container-runtime/src/throttler.ts (hunk 3 above)
Comment (arinwt) [reply packages/runtime/container-runtime/src/throttler.ts:10]: I opened a separate issue #6472 for Throttler related comments, since this PR just moved them to a separate file.

File: packages/runtime/container-runtime/src/throttler.ts (hunk 2 above)
Comment (arinwt) [reply packages/runtime/container-runtime/src/throttler.ts:28]: opened #6472 - to add testing & comments

File: packages/runtime/container-runtime/src/throttler.ts (hunk 1 above)
Comment (arinwt) [reply packages/runtime/container-runtime/src/throttler.ts:18]: opened #6472 - to add testing & comments

File: packages/runtime/container-runtime/src/summaryManager.ts (hunk 5 above)
Comment (arinwt) [reply packages/runtime/container-runtime/src/summaryManager.ts:374]: `shouldSummarize` is only true if it is the client that should summarize (i.e. it is elected). So this still holds the same as before. Previously `shouldStart` could be false if waiting for the previous lingering summarizer client to leave the quorum.

File: packages/runtime/container-runtime/src/summaryManager.ts (hunk 6 above)
Comment (arinwt) [reply packages/runtime/container-runtime/src/summaryManager.ts:94]: This actually brings up a good point.. in response to this comment, I was trying to tighten it up so that the sequence number that actually triggers the election change would be for-sure set here (i.e. the join op or leave op seq#). But when doing so I realized that we can never get it exactly right without adding the seq# that triggered the most recent election to the summary. So I can get it right for all except the one we initially loaded from: i.e. clients that just connected will have a different value than clients who have been connected since before the election change.

Let me think about this some more.. If we go this route (and care about this being exact), we would need to store a number in the summary per `OrderedClientElection` object- which is just the one used for SummaryManager right now.

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 10]
```diff
@@ -604,11 +606,13 @@ export class ContainerRuntime extends TypedEventEmitter<IContainerRuntimeEvents>
         };
         const chunks = await tryFetchBlob<[string, string[]][]>(chunksBlobName) ?? [];
         const metadata = await tryFetchBlob<IContainerRuntimeMetadata>(metadataBlobName);
+        const electedSummarizer = await tryFetchBlob<ISerializedElection>(electedSummarizerBlobName);
```
Comment (anthony-murphy) [inline packages/runtime/container-runtime/src/containerRuntime.ts:609]: do we want a new blob here? would it make sense in metadata? is it fine due to aggregation?

Comment (arinwt) [reply packages/runtime/container-runtime/src/containerRuntime.ts:609]: This is a good question. I've done it both ways for now (in a separate commit).. open to suggestions. @vladsud

File: packages/runtime/container-runtime/src/summaryManager.ts (hunk 6 above)
Comment (arinwt) [reply packages/runtime/container-runtime/src/summaryManager.ts]: Okay with serialization, now we keep track of `electionSequenceNumber`, which is just the sequence number at which the currently elected client was elected. This allows us to have a deterministic point in time to work with as our baseline when no summary acks have been observed.

File: packages/runtime/container-runtime/src/summaryManager.ts (hunk 4 above)
Comment (arinwt) [reply packages/runtime/container-runtime/src/summaryManager.ts:204]: We just no longer wait for the summarizer client(s) to leave the quorum.

File: packages/runtime/container-runtime/src/summarizerClientElection.ts [hunk 11]
```diff
@@ -6,88 +6,120 @@
...
+                return;
             }
-            this.emit("shouldSummarizeStateChanged");
+            // Election can trigger a change in SummaryManager state.
+            this.emit("electedSummarizerChanged");
         });
-        this._hasAnySummarizersInQuorum = this.clientElection.getSummarizerCount() > 0;
+    }
+
+    public serialize(): ISerializedElection {
```
Comment (anthony-murphy) [inline packages/runtime/container-runtime/src/summarizerClientElection.ts:109]: the whole serialize/deserialize flow seems over complicated with deserialization decoupled in orderedClientElection and loadOrderedClients. can we just add a static create funciton to this class that takes the serialize form, and whatever else is needed, rather than spreading across muliple classes and funcitons

File: packages/runtime/container-runtime/src/summarizerClientElection.ts [hunk 12]
```diff
@@ -6,88 +6,120 @@
...
+                if (this.clientElection.eligibleCount > 0) {
+                    this.clientElection.resetElectedClient(sequenceNumber);
+                }
+                return;
+            }
+            let electionSequenceNumber = this.clientElection.electionSequenceNumber;
+            const opsWithoutSummary = sequenceNumber - (this.lastSummaryAckSeqForClient ?? electionSequenceNumber);
+            if (opsWithoutSummary > this.maxOpsSinceLastSummary) {
+                // Log and elect a new summarizer client.
                 this.logger.sendErrorEvent({
```
Comment (anthony-murphy) [inline packages/runtime/container-runtime/src/summarizerClientElection.ts:61]: i'm worried this could emit alot of logs as once we pass the threshold it will emit for every op until new election or summary succeeds

File: packages/runtime/container-runtime/src/summarizerClientElection.ts [hunk 13]
```diff
@@ -6,88 +6,120 @@
...
+                this.clientElection.incrementElectedClient(sequenceNumber);
 
-                this.hasLoggedTelemetry = true;
+                // Verify that we will not be reentrant. This should be reliable,
+                // since all of OrderedClientElection is synchronous.
+                electionSequenceNumber = this.clientElection.electionSequenceNumber;
+                if (sequenceNumber > (this.lastSummaryAckSeqForClient ?? electionSequenceNumber)) {
+                    this.logger.sendErrorEvent({
+                        eventName: "UnexpectedElectionSequenceNumber",
+                        sequenceNumber,
```
Comment (anthony-murphy) [inline packages/runtime/container-runtime/src/summarizerClientElection.ts:77]: >sequenceNumber [](http://example.com/codeflow?start=24&length=14)

this is too generic of a name, and is already logged at the contianer level

File: packages/runtime/container-runtime/src/orderedClientElection.ts [hunk 14]
```diff
@@ -110,122 +146,260 @@ export class OrderedClientElection extends TypedEventEmitter<IOrderedClientElect
...
+    public get electionSequenceNumber() {
+        return this._electionSequenceNumber;
+    }
+
+    constructor(
+        logger: ITelemetryLogger,
+        private readonly orderedClientCollection: IOrderedClientCollection,
+        /** Serialized state from summary or current sequence number at time of load if new. */
+        initialState: ISerializedElection | number,
```
Comment (anthony-murphy) [inline packages/runtime/container-runtime/src/orderedClientElection.ts:260]: >ISerializedElection | number [](http://example.com/codeflow?start=22&length=28)

why do we need to support number only?

File: packages/runtime/container-runtime/src/summarizerClientElection.ts (hunk 13 above)
Comment (arinwt) [reply packages/runtime/container-runtime/src/summarizerClientElection.ts:77]: Removed it, good call.

File: packages/runtime/container-runtime/src/summarizerClientElection.ts (hunk 12 above)
Comment (arinwt) [reply packages/runtime/container-runtime/src/summarizerClientElection.ts:61]: This is prevented by all the code being synchronous. If you look below, I added an event to detect where this scenario could appear. It might be better to add an extra layer of protection against this though...

The intended flow on receiving an op is this:
1. Use op sequence number (`N`) to calculate `opsWithoutSummary`
2. If `opsWithoutSummary` > threshold, then send ElectedClientNotSummarizing event
3. Also increment elected client- this is synchronous
    1. Should set `electionSequenceNumber` to the op sequence number (`N`)
    2. Should emit an "election" event
4. We handle the "election" event synchronously
    1. Should unset `lastSummaryAckSeqForClient` to undefined
    2. If it was the last client in the quorum, we reset but still update `electionSequenceNumber`
5. Now resuming our op handler, we essentially recalculate `opsWithoutSummary` like so:
    1. `= op sequence number - (lastSummaryAckSeqForClient ?? electionSequenceNumber)`
    2. `= N - (undefined ?? N)`
    3. `= 0` Otherwise we throw an "UnexpectedElectionSequenceNumber" error.

I think this intended flow is okay, but I will add an extra safeguard such that in case it does not work as intended, instead of just logging an error message, we will also prevent excessive per-op telemetry logs.

Comment (arinwt) [reply packages/runtime/container-runtime/src/summarizerClientElection.ts]: I made a change to help prevent excess logging. Let me know if it seems okay.

File: packages/runtime/container-runtime/src/orderedClientElection.ts (hunk 14 above)
Comment (arinwt) [reply packages/runtime/container-runtime/src/orderedClientElection.ts:260]: When this is first rolled out we won't have an initial state to load from. So we pass the initial sequence number as a baseline.

**Review by anthony-murphy — APPROVED** [review]
i'd still like the deserialization code cleaned up, but otherwise looks good.

File: packages/runtime/container-runtime/src/summarizerClientElection.ts (hunk 11 above)
Comment (arinwt) [reply packages/runtime/container-runtime/src/summarizerClientElection.ts:120]: So I can simplify it, which will probably make it easier to understand, but the intention in creating & loading both the OrderedClientCollection and all OrderedClientElections in a separate function is that it ensures they are instantiated together. It is important that they are created synchronously together, and this gives that direction via code.

Comment (arinwt) [reply packages/runtime/container-runtime/src/summarizerClientElection.ts:120]: I changed it to just call all the constructors plainly in ContainerRuntime to show the difference, but I think it makes more sense to have the separate load function. The comparison is easy to see by looking at only this commit: https://github.com/microsoft/FluidFramework/pull/6335/commits/2a1dfb27952bc5e43bd10e9d2fbef7bbf7b6a45f

**Comment by vladsud** [comment]
Some high level thoughts:
1. 3K ops is too small of a number. Please take a look at some of the recent numbers of TAP40 simulation - we continuously hit 3K, and even 10K in this run. There are a lot of questions on workload being representative, proper feedback to client, and throttling being not balanced (i.e. ideally it happens earlier and not allow that many ops to be submitted, if we can't summarize it). BUT even with all these ifs and pending investigations, we should assume that hitting 3K limit in production will be routine, and switching summarizer at that boundary will create more pressure on SPO (more calls to load container, more posted summaries), and it will also increase chances of two summarizers working in parallel. So I feel like this kind of switch should be really action of last resort.
2. Is this mostly to address client misbehaving, or service misbehaving? Have we considered it driven from service side, in a form of forceful disconnect of lingering summarizer?
3. I worry about summarization process becoming more and more complex.
