### PR TITLE
Include driverVersion telemetry prop on errors raised from the driver layer

### LINKED ISSUE #8069: Suggest adding driverVersion property on events emitted by driver
Example:

 Office_Fluid_FluidRuntime_Error
| where Data_error contains "TooManyRetries"
| summarize count() by Data_driverVersion, Data_eventName

This emits fluid:telemetry:DeltaManager:GetDeltas_Exception but very hard to say what version of driver was used to generate this error, as event comes from loader.
We can do joins with other events from same session to get this data, but I wonder if driver should just stamp version on all errors it raises?

See createOdspLogger() how we do it for all driver events today.

### PR DESCRIPTION
**Pull request by markfields**
Fixes #8069 

* Update all driver classes in driver-utils to take `driverVersion` as a constructor param
* Update all callsites from odsp/r11s driver packages to pass `pkgVersion`
* Update all callsites from loader package to pass `""`.  Interesting to consider if these errors should be used from here.  Or if this code (connectionManager) should move to driver layer.
* Updated all callsites in driver-utils (where `pkgVersion` may not match) to plumb through the proper `pkgVersion`.

### CODE REVIEW

File: packages/drivers/driver-base/src/documentDeltaConnection.ts [hunk 1]
```diff
@@ -106,11 +106,14 @@ export class DocumentDeltaConnection
...
      * @param socket - websocket to be used
      * @param documentId - ID of the document
+     * @param logger - for reporting telemetry events
+     * @param driverVersion - driverVersion to use when raising errors
      */
     protected constructor(
         protected readonly socket: SocketIOClient.Socket,
         public documentId: string,
         logger: ITelemetryLogger,
+        private driverVersion: string,
```
Comment (markfields) [inline packages/drivers/driver-base/src/documentDeltaConnection.ts:116]: I'm sneaking `driverVersion` onto the `logger` as well in `createOdspLogger`, I could remove this param and just pull it off the logger if that's better, like I do for parallel requests code (where it was too awkward to plumb "honestly")

File: packages/loader/driver-utils/src/network.ts [hunk 2]
```diff
@@ -29,19 +29,33 @@ export function isOnline(): OnlineStatus {
     return OnlineStatus.Unknown;
 }
 
+/** Base class for driver errors that standardizes adding driverVersion for logging */
+export abstract class DriverErrorWithVersion extends LoggingError {
```
Comment (markfields) [inline packages/loader/driver-utils/src/network.ts:33]: Alternative approach if we don't want to export this class:

```
function addDriverVersion(error: IFluidErrorBase, driverVersion: string) {
    error.addTelemetryProperties({ driverVersion });
}
```
And then just call `addDriverVersions(this, driverVersion)` after the `super` call in each constructor.  🤷‍♂️

File: packages/loader/driver-utils/src/network.ts [hunk 3]
```diff
@@ -29,19 +29,33 @@ export function isOnline(): OnlineStatus {
     return OnlineStatus.Unknown;
 }
 
+/** Base class for driver errors that standardizes adding driverVersion for logging */
```
Comment (markfields) [inline packages/loader/driver-utils/src/network.ts:32]: Alternative approach if we don't want to export this class is a function like this:

```
function addDriverVersion(error: IFluidErrorBase, driverVersion: string) {
    error.addTelemetryProperties({ driverVersion });
}
```
And then just call `addDriverVersions(this, driverVersion)` after the `super` call in each constructor.  🤷‍♂️

File: packages/loader/driver-utils/src/parallelRequests.ts [hunk 4]
```diff
@@ -402,8 +402,8 @@ async function getSingleOpBatch(
                 throw createGenericNetworkError(
                     "failedToRetrieveOpsFromStorage:TooManyRetries",
                     undefined,
-                    false /* canRetry */,
-                    undefined /* retryAfterSeconds */,
+                    { canRetry: false },
+                    (logger as any).driverVersion ?? "", // createOdspLogger stashes driverVersion on the logger
```
Comment (markfields) [inline packages/loader/driver-utils/src/parallelRequests.ts:406]: I don't love this, but it was better to me than plumbing `driverVersion` through several functions with already large signatures.

Future improvements to consider here (low-pri, I think):
* Add an `IDriverTelemetryLogger` interface with `driverVersion` on it, and pass that around the driver
* Add a `props` field to `MonitoringContext`, and pass the mc around instead of the logger, and then read `props.driverVersion` here (wouldn't be as strongly typed, but better that `as any`)

**Comment by markfields** [comment]
> but loader maybe older

Doh, forgot about that boundary.  Hmmmm and no compat tests on these constructors to warn me...

File: api-report/driver-utils.api.md [hunk 5]
```diff
@@ -365,8 +373,8 @@ export function streamFromMessages(messagesArg: Promise<ISequencedDocumentMessag
 export function streamObserver<T>(stream: IStream<T>, handler: (value: IStreamResult<T>) => void): IStream<T>;
 
 // @public
-export class ThrottlingError extends LoggingError implements IThrottlingWarning, IFluidErrorBase {
-    constructor(fluidErrorCode: string, message: string, retryAfterSeconds: number, props?: ITelemetryProperties);
+export class ThrottlingError extends DriverErrorWithVersion implements IThrottlingWarning, IFluidErrorBase {
+    constructor(fluidErrorCode: string, message: string, retryAfterSeconds: number, driverVersion: string, props?: ITelemetryProperties);
```
Comment (anthony-murphy) [inline api-report/driver-utils.api.md:377]: why can't we just reuse the props and add those to exceptions?

**Comment by markfields** [comment]
@anthony-murphy - Looking into Jatin's concern about compatibility - I'm wondering if we're actually ok.  I'm guessing driver-utils gets bundled with loader and driver bundles, so they each have their own copy at the version they were compiled against. As opposed to the loader somehow calling across to the driver to get at driver-utils, when they're not bundled together.  Right?

File: api-report/driver-utils.api.md (hunk 5 above)
Comment (markfields) [reply api-report/driver-utils.api.md:377]: I want each type's constructor to require the driver version, rather than counting on callers to remember to add it to props (this is where I started but then realized it was impossible to enforce)

File: packages/drivers/driver-base/src/documentDeltaConnection.ts (hunk 1 above)
Comment (markfields) [reply packages/drivers/driver-base/src/documentDeltaConnection.ts]: Nope no duplicate logging.  Also I switched this and just using the snuck in version on the logger.

File: packages/loader/driver-utils/src/parallelRequests.ts (hunk 4 above)
Comment (markfields) [reply packages/loader/driver-utils/src/parallelRequests.ts]: Tony had a good idea which is to expose `getTelemetryProperties` on the logger to expose the props it stamps on logs, so then I could get it properly from there instead of casting to `any`.  Will try that in a follow-up PR or open an issue if it's not as trivial as it sounds

File: api-report/driver-utils.api.md [hunk 6]
```diff
@@ -116,14 +116,17 @@ export function combineAppAndProtocolSummary(appSummary: ISummaryTree, protocolS
 export function configurableUrlResolver(resolversList: IUrlResolver[], request: IRequest): Promise<IResolvedUrl | undefined>;
 
 // @public (undocumented)
-export function createGenericNetworkError(fluidErrorCode: string, message: string | undefined, canRetry: boolean, retryAfterMs?: number, props?: ITelemetryProperties): ThrottlingError | GenericNetworkError;
+export function createGenericNetworkError(fluidErrorCode: string, message: string | undefined, retryInfo: {
+    canRetry: boolean;
+    retryAfterMs?: number;
```
Comment (markfields) [inline api-report/driver-utils.api.md:121]: @anthony-murphy - How do I think through if this breaking change is a risk in terms of backwards compatibility?  My assumption is that if a package has a build dependency on another package (like driver-utils), then at runtime it will have the code it's built against.  You only have a compat boundary at runtime if you're building against interfaces (i.e. depending on definitions packages).

So, I can feel free to make this breaking change to switch to `retryInfo`, right?  And I have another breaking change coming next (basically reverting PR #7788, which didn't seem to break anything itself).

cc @jatgarg

File: packages/drivers/routerlicious-driver/src/documentServiceFactory.ts [hunk 7]
```diff
@@ -147,7 +148,9 @@ export class RouterliciousDocumentServiceFactory implements IDocumentServiceFact
                 `Couldn't parse documentId and/or tenantId. [documentId:${documentId}][tenantId:${tenantId}]`);
         }
 
-        const logger2 = ChildLogger.create(logger, "RouterliciousDriver");
+        const logger2 = ChildLogger.create(logger, "RouterliciousDriver", { all: { driverVersion }});
+        // Stash driverVersion here for adding to errors thrown from shared driver code
+        (logger2 as any).driverVersion = driverVersion;
```
Comment (anthony-murphy) [inline packages/drivers/routerlicious-driver/src/documentServiceFactory.ts:153]: this is pretty nasty. can we remove this stuff from this pr. the rest is looking pretty good, but i'd really like to avoid this

File: packages/drivers/routerlicious-driver/src/errorUtils.ts [hunk 8]
```diff
@@ -58,21 +59,22 @@ export function createR11sNetworkError(
             // a network error with no status code (e.g. err:ERR_CONN_REFUSED or err:ERR_FAILED) and
             // the error message will start with NetworkError as defined in restWrapper.ts
             return new GenericNetworkError(
-                fluidErrorCode, errorMessage, errorMessage.startsWith("NetworkError"), { statusCode });
+                fluidErrorCode, errorMessage, errorMessage.startsWith("NetworkError"), { statusCode, driverVersion });
```
Comment (anthony-murphy) [inline packages/drivers/routerlicious-driver/src/errorUtils.ts:62]: make just create the props object at the top, and reuse in all the calls

File: packages/loader/container-loader/src/connectionManager.ts [hunk 9]
```diff
@@ -72,13 +72,17 @@ function getNackReconnectInfo(nackContent: INackContent) {
     const canRetry = nackContent.code !== 403;
     const retryAfterMs = nackContent.retryAfter !== undefined ? nackContent.retryAfter * 1000 : undefined;
     return createGenericNetworkError(
-        `nack [${nackContent.code}]`, message, canRetry, retryAfterMs, { statusCode: nackContent.code });
+        `nack [${nackContent.code}]`,
+        message,
+        { canRetry, retryAfterMs },
+        { statusCode: nackContent.code, driverVersion: "" });
```
Comment (anthony-murphy) [inline packages/loader/container-loader/src/connectionManager.ts:78]: i don't really like empty string here, could driverVersion be defined as `driverVersion: string | undefined` to enforce explicit undefined.

File: packages/loader/driver-utils/src/network.ts [hunk 10]
```diff
@@ -57,7 +59,7 @@ export class DeltaStreamConnectionForbiddenError extends LoggingError implements
     readonly errorType: string = DeltaStreamConnectionForbiddenError.errorType;
     readonly canRetry = false;
 
-    constructor(readonly fluidErrorCode: string) {
+    constructor(readonly fluidErrorCode: string, props: DriverErrorTelemetryProps) {
         super(fluidErrorCode, { statusCode: 400 });
```
Comment (anthony-murphy) [inline packages/loader/driver-utils/src/network.ts:63]:
```suggestion
        super(fluidErrorCode, { ...props, statusCode: 400 });
```

File: packages/drivers/routerlicious-driver/src/documentServiceFactory.ts (hunk 7 above)
Comment (anthony-murphy) [reply packages/drivers/routerlicious-driver/src/documentServiceFactory.ts:153]: also, today the version across these packages will align, we could also continue to ship drivers as a unit in the future, in which case these packages will always be consistently versioned, so today it is safe to just always use pacakge version

File: api-report/driver-utils.api.md [hunk 11]
```diff
@@ -40,7 +40,7 @@ import { LoggingError } from '@fluidframework/telemetry-utils';
 
 // @public (undocumented)
 export class AuthorizationError extends LoggingError implements IAuthorizationError, IFluidErrorBase {
-    constructor(fluidErrorCode: string, message: string, claims: string | undefined, tenantId: string | undefined, props?: ITelemetryProperties);
+    constructor(fluidErrorCode: string, message: string, claims: string | undefined, tenantId: string | undefined, props: DriverErrorTelemetryProps);
```
Comment (anthony-murphy) [inline api-report/driver-utils.api.md:43]: this needs a breaking.md addition

File: packages/loader/driver-utils/src/network.ts (hunk 10 above)
Comment (markfields) [reply packages/loader/driver-utils/src/network.ts:63]: Yikes, thanks for catching this.

File: packages/drivers/routerlicious-driver/src/documentServiceFactory.ts (hunk 7 above)
Comment (markfields) [reply packages/drivers/routerlicious-driver/src/documentServiceFactory.ts:153]: > this is pretty nasty

Can't argue with you on that ;)

Good point that it will work to just use pkgVersion today.  I'll follow up with Helio to make sure that whenever we stop releasing all client packages together, that we audit the use of pkgVersion throughout the code.

File: BREAKING.md [hunk 12]
```diff
@@ -32,7 +33,7 @@ The unused `url` property of `ICreateBlobResponse` in `@fluidframework/protocol-
 The `readonly` property was deprecated and has now been removed from `IDeltaManager` from `container-definitions`. Additionally, `readonly` has been removed from the implementations in `DeltaManager` and `DeltaManagerProxy` from `container-loader`. To replace its functionality, use `readOnlyInfo.readonly` instead.
 
 ### Synthesize Decoupled from IFluidObject and Deprecations Removed
-DependencyContainer now takes a generic argument, as it is no longer directly couple to IFluidObject. The ideal pattern here would be directly pass the provider or FluidObject interfaces you will register. As a short term solution you could also pass IFluidObject, but IFluidObject is deprecated, so will need to be removed if used here. 
+DependencyContainer now takes a generic argument, as it is no longer directly couple to IFluidObject. The ideal pattern here would be directly pass the provider or FluidObject interfaces you will register. As a short term solution you could also pass IFluidObject, but IFluidObject is deprecated, so will need to be removed if used here.
```
Comment (markfields) [inline BREAKING.md:36]:
```suggestion
DependencyContainer now takes a generic argument, as it is no longer directly couple to IFluidObject. The ideal pattern here would be directly pass the provider or FluidObject interfaces you will register. As a short term solution you could also pass IFluidObject, but IFluidObject is deprecated, so will need to be removed if used here.

```

**Review by anthony-murphy — APPROVED** [review]

**Comment by vladsud** [comment]
Would it be simpler, and somewhat aligned with future direction of not using exceptions for normal flows, to simply identify driver API boundary (couple interfaces) and ensure that any exception thrown on that boundary has code that annotates error with driverVersion? This can likely be done through adapters, i.e., implementation that wraps existing object, implements same interface and basically has try/catch for each method.
It would be pretty scoped (i.e. not spread out across all of the driver & driver-utils) and it would be very trivial to review it and ensure that indeed all code paths.
Not ideal in any way, but it feels like any solution here sucks.
