### PR TITLE
Handle null tokens in odsp driver.

### LINKED ISSUE #4858: If token retrievals in the odsp driver return null, don't attempt the ODSP request
In the odsp driver, when token callbacks like getStorageToken() fail, often we will continue on to make a request to odsp that we should know beforehand to fail. Instead we should try to fail fast and report failure before making the API calls.

### PR DESCRIPTION
**Pull request by jatgarg**
Fixes: https://github.com/microsoft/FluidFramework/issues/4858

### CODE REVIEW

**Comment by markfields** [comment]
Removing the milestone marker on this PR since it's linked to an issue, to avoid duplicate items on the project board.

File: packages/drivers/odsp-driver/src/odspSummaryUploadManager.ts [hunk 1]
```diff
@@ -207,7 +209,9 @@ export class OdspSummaryUploadManager {
 
         return getWithRetryForTokenRefresh(async (options) => {
             const storageToken = await this.getStorageToken(options, "WriteSummaryTree");
-
+            if (storageToken === null) {
```
Comment (curtisman) [inline packages/drivers/odsp-driver/src/odspSummaryUploadManager.ts:212]: Should we wrap the getStorageToken function to make it throw instead of having it to check everywhere?

Comment (jatgarg) [reply packages/drivers/odsp-driver/src/odspSummaryUploadManager.ts:212]: Yes, I thought of that but then I thought maybe every call does need to throw if token is null. But in that case caller may catch the error. So I think I will wrap it up in another function which will throw in case of null token.

**Review by curtisman — APPROVED** [review]
:shipit:
