### PR TITLE
Strip query string from error response object

### LINKED ISSUE #5326: Redact error message in responseToException
Please see https://github.com/microsoft/FluidFramework/pull/5215
and responseToException() that adds URI to message (and stack) that could result in PII info leaking to telemetry if we are running in container with 3rd party code.

The goal here should be holistic approach - any error could container PII. So likely case like that should be automatically covered by not collecting message / stack unless error happens in internal (dogfood) rings.
If we want to address this particular case (without addressing more generic problem), we could drop URI if we are running in container with 3rd party code.
Dropping URI all the time will reduce our ability to diagnose problems.

Related issuds:
https://github.com/microsoft/FluidFramework/issues/4908
https://github.com/microsoft/FluidFramework/issues/1920

### PR DESCRIPTION
**Pull request by markfields**
Doesn't fully fix #5326 but does ameliorate the more concerning user personal data case.  We can wait for more clarity on 3P-in-1P scenarios before fully addressing that issue.

### CODE REVIEW

File: packages/runtime/runtime-utils/src/dataStoreHelpers.ts [hunk 1]
```diff
@@ -88,10 +88,12 @@ export const create404Response = (request: IRequest) => createResponseError(404,
 
 export function createResponseError(status: number, value: string, request: IRequest): IResponse {
```
Comment (anthony-murphy) [inline packages/runtime/runtime-utils/src/dataStoreHelpers.ts:89]: unit test to make sure no body breaks it again?

**Review by vladsud — APPROVED** [review]
