### PR TITLE
Cache containers by default and add default loader options

### LINKED ISSUE #4489: Loader should return cached container
When something like Loader.request() is called, it does not utilized the cached container feature because of various design problems. This means we cannot rely on the Loader to reliably give us back the same instance of a loaded container which causes performance issues (multiple trees/latest calls etc.) if we want to use Loader.resolve() to get a container and Loader.request() to get a component or any other flow that may use the Loader multiple times.

More details from Vlad:
Unfortunately it is pretty broken, as Container exposes a bunch of state (forceReadOnly, paused, etc.) that different users may not agree on. This is known, and we plan to look into it in some future, but no concrete plans for now. As result, I believe right now we are not caching containers, so two calls will result in two containers loaded (at least when they are paused, not sure what happens next).

@vladsud, @anthony-murphy, @agarwal-navin

### PR DESCRIPTION
**Pull request by heliocliu**
Fixes #4489
Currently the loader does not cache containers it returns by default because of how other options are handled. We can ignore those options with regard to caching because they should apply to all consumers of that container.
- Decouple reconnect and pause flags from container caching, so callers will need to explicitly specify no caching to get a new instance if they previously provided those flags
- Add closed event hook to evict closed containers from the cache
- Move some existing request header options into loader options to guide default loader behavior, while still allowing individual requests to override that behavior
- Add a test to ensure expected caching behavior

### CODE REVIEW

File: packages/loader/container-loader/src/loader.ts [hunk 1]
```diff
@@ -392,6 +399,11 @@ export class Loader extends EventEmitter implements ILoader {
                     resolvedAsFluid);
         }
 
+        if (newlyLoaded && this.services.options.readonly === true) {
+            // Don't re-force readonly when returning an existing container
```
Comment (vladsud) [inline packages/loader/container-loader/src/loader.ts:403]: It should be no-op if container is already read-only.
Note that if someone is manipulating this container and reset its read-only state, and now someone else is asking for container and expects it to be read-only, then we are breaking that promise.

I think the only way to make it work correctly is by
- providing a logic (interface/callback/...) to loader instance at loader creation
- This logic control all containers in the loader in terms of things like read-only, potentially pausing, etc.
In other words there is agreed upfront policy that applies to all containers in loader.

This works well with read-only, and clients use it to disallow user from making changes on loss of connection. So that logic is host policy for all containers.

Note that "all containers' here is very important. If we have guest components in container (that is component that is coming from another container), then first container will load second container. Host is not aware about it, and first container is not aware of host policies. When host says - container should be read-only, it really means - this container and all nested containers as well. Today there is no way to represent that logic, thus my point about it being a policy (expressed in code provided to loader) and applicable to all containers in loader.
If someone wants to escape that policy, it creates new loader with new policy (might be applicable for summarizer, for example).

This can't be solved with options.
I think (though I have not had enough time to think deeply about it) that pausing container is in the same bucket - it's a policy on how we load stuff. It likely as important for nested containers as well.

File: packages/loader/container-loader/src/loader.ts [hunk 2]
```diff
@@ -408,17 +420,21 @@ export class Loader extends EventEmitter implements ILoader {
         return { container, parsed };
     }
 
+    private mergeHeaderOptions(headers: IRequestHeader): IRequestHeader {
+        const loaderDefaults = {
+            [LoaderHeader.cache]: this.services.options.cache,
+            [LoaderHeader.pause]: this.services.options.pause,
+            [LoaderHeader.reconnect]: this.services.options.reconnect,
+        };
+        return { ...loaderDefaults, ...headers };
```
Comment (vladsud) [inline packages/loader/container-loader/src/loader.ts:429]: I think there should be only one way of specifying these things. I.e. LoaderHeader.pause should be deleted and host should be forced to use options and have no way to override it for an instance of the container. As otherwise loader options are meaningless - they are supposed to represent constant things about all containers in loader.

File: packages/loader/container-loader/src/loader.ts (hunk 1 above)
Comment (vladsud) [reply packages/loader/container-loader/src/loader.ts:403]: To clarify, I believe that
1. policy should be applicable to all containers in loader, with no way to override it per container request.
2. Some policies can be expressed as boolean, but most can't. forceReadonly and paused are two examples - their initial state is not interesting, what's interesting is that policy is applied uniformly through lifetime of containers, and requesting an instance of container from loader at any moment gives expected result (i.e. using Bohemia policy - if container still did not load fully - it is paused, if it already loaded and rendered, it's no longer paused).

Comment (heliocliu) [reply packages/loader/container-loader/src/loader.ts]: I opened a new issue #4880 to track migrating the non-cache policy into the loader and remove it from the request and captured your thoughts there.  That work involves some changes with how we handle creating the scheduler and summarizer and potentially has implications for decoupling Loader from container, so I think it probably reaches too far beyond the caching issue

File: packages/loader/container-loader/src/loader.ts [hunk 3]
```diff
@@ -381,8 +375,16 @@ export class Loader extends EventEmitter implements ILoader {
                         parsed.id,
                         request,
                         resolvedAsFluid);
-                this.containers.set(key, containerP);
                 container = await containerP;
+
+                if (!container.closed) {
+                    // Don't cache already closed containers because won't know when to evict
+                    this.containers.set(key, containerP);
+                    container.on("closed", () => {
```
Comment (anthony-murphy) [inline packages/loader/container-loader/src/loader.ts:383]:
```suggestion
                    container.once("closed", () => {
```

**Review by anthony-murphy — APPROVED** [review]
