### PR TITLE
Fix FluidObject Corner Case and Improve Errors

### LINKED ISSUE #8294: FluidObject corner case is too permissive
Consider this interface. `z` shows up in `FluidObjectKeys<IFoo>`:

```typescript
interface IFoo {
  z: { z: boolean };
}
```

Feel free to WF, but wanted to mention it.  It can be fixed by adding this condition*:

```typescript
T[TProp] extends T[TProp][TProp]
```

or just `T extends T[TProp]` if you are willing to preclude doing `FluidObject<IProvideFoo>`.

* Really you need to use `Required` or `Exclude<..., undefined`> as discussed in the original PR, just keeping it simple for illustrative purposes

### PR DESCRIPTION
**Pull request by anthony-murphy**
This change fixes a missed corner case in FluidObject.

It also changes from `Partial<Pick` to it's own implementation of the same thing. This improves error messages 
from `Property 'z' does not exist on type 'Partial<Pick<IFoo, never>>'` 
to `Property 'z' does not exist on type 'FluidObject<IFoo>'`
functionally the behavior is the same.

fixes #8294

### CODE REVIEW

**Comment by anthony-murphy** [comment]
@leeviana this shouldn't break anything, but now all know issues should be fixed

**Comment by leeviana** [comment]
> @leeviana this shouldn't break anything, but now all known issues should be fixed

Nice, thank you! I'll update the prebump task we have to wait for this change, pick it up on our end to match and remove the workarounds. (do you think we have to wait for your change to come in or can we just copy it now since it's not a breaking change?)

File: common/lib/core-interfaces/src/provider.ts [hunk 1]
```diff
@@ -25,8 +25,11 @@
  export type FluidObjectProviderKeys<T, TProp extends keyof T = keyof T> =
     string extends TProp ? never : number extends TProp? never : // exclude indexers [key:string |number]: any
     TProp extends keyof Exclude<T[TProp], undefined> // TProp is a property of T, and T[TProp]
-        ? TProp
-        :never;
+        ? TProp extends
```
Comment (markfields) [inline common/lib/core-interfaces/src/provider.ts:28]: My suggestion was to do `T[TProp] extends Required< Required<T>[TProp] >[TProp]`, to make sure the type itself matches, not just the keys.

Your way accepts this (event more contrived!) example but mine doesn't:  `z: { z: { z: boolean } };`

PS - I think using `Required` is slightly more readable since it doesn't need the other type param

**Review by markfields — APPROVED** [review]
🎂
