### PR TITLE
ODSP: Clear joinSessionCache on "server_disconnect" with 401/403

### LINKED ISSUE #8106: ODSP: server_disconnect with code = 401/403 should clear joinSession cache
Today, any disconnect (for any reason) results in attempt to reconnect to PUSH using cached joinSession results.
And only when it fails (let's say with 401/403 code), we remove joinSession cache and try over full cycle.
Gary is asking to optimize that flow and remove joinSession cache on 401/403 disconnect reasons (through server_disconnect flow) to ensure we do not waste time (and latency) on useless reconnect attempt.

Note that duration of session is controlled by storage token provided to joinSession.
websocket token is checked at connection time for validity (I assume that includes duration), but does not controls duration of connection - storage token provided in joinSession does.

### PR DESCRIPTION
**Pull request by jatgarg**
Fixes: https://github.com/microsoft/FluidFramework/issues/8106
Remove joinSession cache on 401/403 disconnect reasons (through server_disconnect flow) to ensure we do not waste time (and latency) on useless reconnect attempt.

### CODE REVIEW

File: packages/drivers/odsp-driver/src/odspDocumentDeltaConnection.ts [hunk 1]
```diff
@@ -203,7 +204,10 @@ export class OdspDocumentDeltaConnection extends DocumentDeltaConnection {
         telemetryLogger: ITelemetryLogger,
         timeoutMs: number,
         epochTracker: EpochTracker,
-        socketReferenceKeyPrefix: string | undefined): Promise<OdspDocumentDeltaConnection> {
+        socketReferenceKeyPrefix: string | undefined,
+        sessionJoinCache: PromiseCacheWithOneHourSlidingExpiry<ISocketStorageDiscovery>,
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/odspDocumentDeltaConnection.ts:208]: If possible, this should be PromiseCache<string, ISocketStorageDiscovery>, not to encode implementation details here, only interface.
I'd go even further, and abstract away sessionJoinCache & joinSessionCacheKey via

joinCacheRemoveCallback: () =>void,

There is just no need to have that kind of implementation leakage that far. Maybe go even further and provide more general callback:

onDisconnect: (error: OdspError) => error,

And let the caller encode specialness of DriverErrorType.authorizationError

Comment (vladsud) [reply packages/drivers/odsp-driver/src/odspDocumentDeltaConnection.ts:208]: I think it would be better for this logic not to be here at all, but rather be in connectToDeltaStream().
Similar how we already subscribe to "op" vent there, we can subscribe to "disconnect" event and test error for right condition to remove join session cache. It would be broader check, but I think it's Ok (I do not see cases where it would cause trouble) and it would be in the right place, without polluting lower levels.

File: packages/drivers/odsp-driver/src/odspDocumentService.ts [hunk 2]
```diff
@@ -281,6 +283,13 @@ export class OdspDocumentService implements IDocumentService {
                 connection.on("op", (documentId, ops: ISequencedDocumentMessage[]) => {
                     this.opsReceived(ops);
                 });
+                // On disconnect with 401/403 error code, we can just clear the joinSession cache as we will again
+                // get the auth error on reconnecting and face latency.
+                connection.on("disconnect", (error: OdspError) => {
+                    if (error.errorType === DriverErrorType.authorizationError) {
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/odspDocumentService.ts:289]: Do we guarantee that it's an object (OdspError)? If not, consider having error?.errorType check instead

**Review by vladsud — APPROVED** [review]

File: packages/drivers/odsp-driver/src/odspDocumentService.ts (hunk 2 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver/src/odspDocumentService.ts]: It seems it throws OdspError but it is not typed in the event. So replacing it with any and testing for object/null/errorType now.
