### PR TITLE
Stop handle expansion due to missing unreferenced flag in summary

### LINKED ISSUE #5055: Deleted data stores are not marked as unreferenced in summary sent to SPO
There is a regression in the odsp driver due to which deleted data stores are not marked as unreferenced. This will happen in the following scenario:

- User deletes a data store and we mark it as unreferenced in the summary send to server.
- The data store never changes after this. Basically the user does not bring this data store back by undo.
- If the user refreshes the page or reopens the document (basically if a new summarizer client is chosen), this data store will be send to the server as referenced.

The root-cause is because of the following blob de-duping optimization:
- The new summarizer client downloads latest snapshot from server and updates the dedup cache from it.
- The snapshot from the server does not contain the unreferenced flag for deleted data stores.
- Since the deleted data store did not change, runtime sends handle with path to previous summary.
- The driver gets the previous summary tree for this data store from the dedup cache. This does not have the unreferenced flag.
- We send a tree for this data store without the unreferenced flag which essentially marks it as referenced.

### PR DESCRIPTION
**Pull request by jatgarg**
Fixes: https://github.com/microsoft/FluidFramework/issues/5055
1.) The server does not return unreferenced flag in the summary returned, currently. However this may change in future.
2.) So when we expand the handle with the cached summary tree, we are not able to set the unreferenced flag in the expanded tree.
3.) So disable the handle expansion for now.

### CODE REVIEW

File: packages/drivers/odsp-driver/src/odspSummaryUploadManager.ts [hunk 1]
```diff
@@ -390,9 +390,11 @@ export class OdspSummaryUploadManager {
                         reusedBlobs += result.reusedBlobs;
                         blobs += result.blobs;
                     } else {
-                        // Ideally we should not come here as we should have found it in cache. But in order to successfully upload the summary
```
Comment (agarwal-navin) [inline packages/drivers/odsp-driver/src/odspSummaryUploadManager.ts:393]: We should not even try to get the summary tree from the cache is `allowHandleExpansion` is false. Only if its true, we should try to get it and log if its not available.

**Comment by agarwal-navin** [comment]
This should be tested to make sure that the unreferenced flag is not lost anymore.

File: packages/drivers/odsp-driver/src/odspSummaryUploadManager.ts (hunk 1 above)
Comment (vladsud) [reply packages/drivers/odsp-driver/src/odspSummaryUploadManager.ts:393]: I think getting it from cache is fine, as long as cache contains referenced flag.
I believe the issue is that it does not round trip, i.e. TreesLatest does not contain it (but we are fine with incremental summaries). If so, should we push more pressure on SPO folks to round trip it to make whole system work?

File: packages/drivers/odsp-driver/src/odspSummaryUploadManager.ts [hunk 2]
```diff
@@ -198,7 +198,7 @@ export class OdspSummaryUploadManager {
             cloneDeep(tree),
             blobTreeDedupCachesLatest,
             ".app",
-            true,
+            false /* Stop handle expansion due to missing unreferenced flag in summary returned from server */,
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/odspSummaryUploadManager.ts:201]: It would be great to add a reference to an issue or some other description that tells why and potential next steps.
I.e. next developer reading code should be able to reason on whys and how he/she can improve it further.

**Review by vladsud — APPROVED** [review]

File: packages/drivers/odsp-driver/src/odspSummaryUploadManager.ts (hunk 1 above)
Comment (agarwal-navin) [reply packages/drivers/odsp-driver/src/odspSummaryUploadManager.ts:393]: I mean if allowHandleExpansion is false, then we don't need to get the tree from cache irrespective of whether we have this bug or not.
Yep, the issue is that the tree sent back by the server does not have the unreferenced flag. If we had that, this would work just fine. If we are planning to use cache in this fashion (after your blob aggregation changes as well), then we should push them to send the unreferenced flag back.

Comment (agarwal-navin) [reply packages/drivers/odsp-driver/src/odspSummaryUploadManager.ts:393]: I think even without this cache requirement, it would be a good idea to get the unreferenced flag. So, we should push them for it.

Comment (jatgarg) [reply packages/drivers/odsp-driver/src/odspSummaryUploadManager.ts:393]: I think we can keep this getting from cache thing as it is not a big op. Otherwise code would become ugly as we would have 2 if-else rather than 1.

File: packages/drivers/odsp-driver/src/odspSummaryUploadManager.ts (hunk 2 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver/src/odspSummaryUploadManager.ts]: Added.

**Comment by jatgarg** [comment]
> This should be tested to make sure that the unreferenced flag is not lost anymore.
Actually this is more of server side operation as they mark the tree as referenced if we expand the handle. So if we don't expand the handle server would not be marking them as referenced. So lets see when the FFX takes this change.
