### PR TITLE
SharedMatrix: fix #5805 and #5809

### LINKED ISSUE #5805: SharedMatrix: Should not re-emit revertibles during reconnection
## Describe the bug
On reconnection, the 'setCell()' op is re-emitted by SharedMatrix as the op is replayed.  (i.e., the subscriber sees the IRevertible twice: once for the original 'setCell()' call and again when it's replayed.)

### To Reproduce
Perform a 'setCell()' operation while in a disconnected state.
Reconnect.

### Expected behavior
IRevertible is emitted for original 'setCell()' operation only.

### More info
Simple bug due to code sharing.  (Only setCell is affected.  Does not occur with row/col mutation ops.)

### PR DESCRIPTION
**Pull request by DLehenbauer**
Fixes two bugs caused by the same code-reuse issue.

In both cases, the issue is calling `setCellCore()` instead of `sendSetCellOp()` when resubmitting ops during reconnection.

The problems with calling `setCellCore()` are that:

1. It (re-)emits events for the undo manager which were already emitted when the cell was set. (#5805).
2. It writes the value to the storage, which would be benign, except that 'op.value' has had handles encoded for serialization (#5809).

### CODE REVIEW

File: packages/dds/matrix/src/matrix.ts [hunk 1]
```diff
@@ -505,7 +505,7 @@ export class SharedMatrix<T extends Serializable = Serializable>
                     const col = this.cols.handleToPosition(colHandle, localSeq);
 
                     if (row >= 0 && col >= 0) {
-                        this.setCellCore(
+                        this.sendSetCellOp(
                             row,
```
Comment (DLehenbauer) [inline packages/dds/matrix/src/matrix.ts:509]: This 1 line is the actual fix.

**Review by anthony-murphy — APPROVED** [review]

**Comment by DLehenbauer** [comment]
Thanks, @anthony-murphy !
