### PR TITLE
Fix for data stores resummarized without changes.

### LINKED ISSUE #8963: Summaries are large: We summarize data stores that did not have changes
These numbers are not great:

> union Office_Fluid_FluidRuntime_Performance
| where Data_eventName == "fluid:telemetry:OdspDriver:uploadSummary_end"
| summarize percentile(Data_blobs, 50), percentile(Data_blobs, 90), percentile(Data_blobs, 95), percentile(Data_blobs, 99)

| percentile_blobs_50 | percentile_blobs_90 | percentile_blobs_95 | percentile_blobs_99 |
|-|-|-|-|
| 16 | 191 | 361 | 962 |

Part of that - I disabled incremental summaries at data store level, to allow blob aggregation to work correctly (but given it was not enabled ever, we should reconsider it).
That said, it does not (alone, or in big part) explains the tail - it's just too many blobs!

I believe that's primary driving force (in addition to Sequence not having efficient differential summaries) to large summaries:

| percentile_size_50 | percentile_size_90 | percentile_size_95 | percentile_size_99 |
|-|-|-|-|
| 29,352 | 475,858 | 1,142,372 | 5,781,269 |

That's a lot of bytes! 314K on average, to be exact!

### PR DESCRIPTION
**Pull request by agarwal-navin**
Fixes https://github.com/microsoft/FluidFramework/issues/8963.

**Issue**
When a container is loaded, garbage collector reads the GC blobs for data stores from the base snapshot and passes it to data stores during creation. However, it does not sort the used routes before passing it to the data stores. These used routes become `referenceUsedRoutes` for the data stores, i.e., used routes in the previous summary.
During summarize, the current used routes are compared with the `referenceUsedRoutes` to determine if the reference state of the data store changed.  The used routes must be sorted so that they can be compared correctly.

**Fix**
Data stores sort the used routes passed by the container runtime before saving it as `referenceUsedRoutes`.

The tests added in https://github.com/microsoft/FluidFramework/pull/8983 now pass with this change.

### CODE REVIEW

File: packages/runtime/container-runtime/src/summaryGenerator.ts [hunk 1]
```diff
@@ -276,6 +277,26 @@ export class SummaryGenerator {
...
+             * - Its reference state changed, i.e., it went from referenced to unreferenced or vice-versa.
+             *
+             * Since an op in a data store can change the reference state of another data store, each op can potentially
+             * result in two data stores being summarized. So, the number of summarized data stores should not exceed
+             * twice the number of ops since last summary.
+             */
+            if (!fullTree
+                && !summaryData.forcedFullTree
+                && summaryData.summaryStats.summarizedDataStoreCount <= 2 * opsSinceLastSummary) {
+                logger.sendErrorEvent({
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/summaryGenerator.ts:293]: @vladsud - I logged an error here instead of an assert for 2 reasons:
1. It's possible that the bug fixed by this PR isn't the only one resulting in large number of summarized data stores. So, we should monitor telemetry before converting this to an assert.
2. Theoretically, multiple handles can be added to a DDS via an object. This would result in one op changing multiple data stores. Although, practically this check shouldn't get violated as we have of buffer. But being safe for now.

Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/summaryGenerator.ts:293]: Actually, there a 3rd reason why we cannot do this as pointed out in the issue https://github.com/microsoft/FluidFramework/issues/8963#issuecomment-1029427346.

**Review by vladsud — APPROVED** [review]

**Comment by vladsud** [comment]
if you consider it not too risky, maybe worth creating hot fix (especially that we just cut release and it likely is not picked up yet by anyone)?

**Comment by agarwal-navin** [comment]
> if you consider it not too risky, maybe worth creating hot fix (especially that we just cut release and it likely is not picked up yet by anyone)?

Yeah, I was also thinking that we should hot fix this. It shouldn't be risky except for the error log. What do you think of the comment here - https://github.com/microsoft/FluidFramework/issues/8963#issuecomment-1029427346?

**Comment by vladsud** [comment]
I've replies to comment in there. Your call really how to proceed (to keep it or not, and what multiplier to use) - I'd naturally want more from here (more in a sense of more performant system, and sooner :)), but reality might not allow all at once :)

**Comment by agarwal-navin** [comment]
> I've replies to comment in there. Your call really how to proceed (to keep it or not, and what multiplier to use) - I'd naturally want more from here (more in a sense of more performant system, and sooner :)), but reality might not allow all at once :)

I removed the telemetry. I opened [this issue](https://github.com/microsoft/FluidFramework/issues/9017) and after its fixed we can accurately identify when this bug happens again. I intend to fix it before the next release and add an assert to validate this case.
