### PR TITLE
Matrix: Fix incorrect row/col adjustment w/multiple reconnections

### LINKED ISSUE #5808: SharedMatrix: Ops transmitted during reconnection phase are adjusted incorrectly
## Describe the bug
The row/col targets of 'setCell()' ops are adjusted incorrectly on the 2nd reconnection attempt leading to data loss.

## More Info
The cause of the issue is that SharedMatrix previously advanced 'localSeq' when resubmitting ops. If the initial submission fails, and the 1st reconnection also fails, the 2nd reconnection attempt replays the ops that were resubmitted during the 1st attempt (as opposed to the originally submitted ops.)

This causes incorrect row/col adjustment when MergeTree compares with the 'localSeqs' stored on the segments when they were originally inserted.

### PR DESCRIPTION
**Pull request by DLehenbauer**
This fixes a data loss issue during reconnection that reproduces when the initial submission fails and the 1st reconnection attempt also fails.  (Fixes #5808).

The cause of the issue is that SharedMatrix previously advanced 'localSeq' when resubmitting ops the 1st time.  During the 2nd reconnection attempt, the runtime replays the ops that were resubmitted during the 1st attempt (as opposed to the originally submitted ops), which now have higher 'localSeq' than those stored in the MergeTree segments.

This results in incorrect adjustment of row/col when resubmitting 'setCell()' ops, as the higher 'localSeqs' cause adjustment to behave as if all 'setCell()' calls occurred after all row/col insertions and removals (i.e., no adjustment takes place.)

### CODE REVIEW

File: packages/dds/matrix/src/matrix.ts [hunk 1]
```diff
@@ -230,32 +230,36 @@ export class SharedMatrix<T extends Serializable = Serializable>
...
-    }
-
-    private sendSetCellOp(row: number, col: number, value: T, rowHandle: Handle, colHandle: Handle) {
-        // If the SharedMatrix is local, it will by synchronized via a Snapshot when initially connected.
-        // Do not queue a message or track the pending op, as there will never be an ACK, etc.
         if (this.isAttached()) {
-            const localSeq = this.nextLocalSeq();
+            this.sendSetCellOp(row, col, value, rowHandle, colHandle);
+        }
+    }
```
Comment (DLehenbauer) [inline packages/dds/matrix/src/matrix.ts:236]: Ugh.  What an awful diff for a simple change:

1.  The 'isAttached()' check is hoisted from 'sendSetCellOp()' to the caller.  (above ---^)
2.  'sendSetCellOp()' now takes 'localSeq' as an argument.   (below ----v)
3.  ...which forced me to reformat the signature due to line length (below ---v)

The motivation for #1 is to pedantically avoid advancing 'nextLocalSeq' when no op will be sent.
The motivation for #2 is to enable 'reSubmitCore' to preserve the 'localSeq' from the original op.

File: packages/dds/matrix/src/matrix.ts [hunk 2]
```diff
@@ -511,6 +515,7 @@ export class SharedMatrix<T extends Serializable = Serializable>
                             setOp.value,
                             rowHandle,
                             colHandle,
+                            localSeq,
```
Comment (DLehenbauer) [inline packages/dds/matrix/src/matrix.ts:518]: ...and here's the only "real" change: preserving 'localSeq' during resubmission.

File: packages/dds/matrix/src/test/matrix.spec.ts [hunk 3]
```diff
@@ -705,6 +705,42 @@ describe("Matrix", () => {
...
+            containerRuntime1.connected = false;
+            containerRuntime1.connected = true;
+
+            // Verify that the 'setCells()' op targeted the original position of (0,0),
+            // not the current local position of (0,3).
+            await expect([
+                [undefined, undefined, undefined, "A"],
+            ]);
+        });
+
```
Comment (DLehenbauer) [inline packages/dds/matrix/src/test/matrix.spec.ts:743]: New test case to cover the missing multiple reconnection case.

File: packages/dds/matrix/src/test/matrix.stress.spec.ts [hunk 4]
```diff
@@ -234,7 +234,14 @@ describe("Matrix", () => {
...
-                    if (runtimes[matrixIndex].connected && float64() < disconnectProbability) {
+                    if (float64() < disconnectProbability) {
+                        // If the client is already disconnected, first reconnect it to cover the case where
+                        // multiple reconnections are required.
+                        if (!runtimes[matrixIndex].connected) {
+                            trace?.push(`containerRuntime${matrixIndex + 1}.connected = true;`);
+                            runtimes[matrixIndex].connected = true;
+                        }
+
                         trace?.push(`containerRuntime${matrixIndex + 1}.connected = false;`);
```
Comment (DLehenbauer) [inline packages/dds/matrix/src/test/matrix.stress.spec.ts:245]: Change to stress to cover multiple reconnections as well.

File: packages/dds/matrix/src/test/matrix.stress.spec.ts [hunk 5]
```diff
@@ -269,7 +276,7 @@ describe("Matrix", () => {
             { numClients: 2, numOps: 200, syncProbability: 0.3, disconnectProbability: 0, seed: 0x84d43a0a },
             { numClients: 3, numOps: 200, syncProbability: 0.1, disconnectProbability: 0, seed: 0x655c763b },
             { numClients: 5, numOps: 200, syncProbability: 0.0, disconnectProbability: 0, seed: 0x2f98736d },
-            { numClients: 2, numOps: 200, syncProbability: 0.3, disconnectProbability: 1, seed: 0x84d43a0a },
+            { numClients: 2, numOps: 200, syncProbability: 0.2, disconnectProbability: 0.4, seed: 0x84d43a0a },
```
Comment (DLehenbauer) [inline packages/dds/matrix/src/test/matrix.stress.spec.ts:279]: Adjusted the mix a bit.  Previously, this stress config would force reconnection after every op, but it's more interesting to have a handful of ops pending during resubmission.

(There's also a pre-existing "long haul" stress that hits reconnection with hundreds of ops pending, but I only run that on my box.)

File: packages/dds/matrix/src/test/matrix.spec.ts [hunk 6]
```diff
@@ -705,6 +705,42 @@ describe("Matrix", () => {
...
+            // Disconnect and reconnect the client.
+            containerRuntime1.connected = false;
+            containerRuntime1.connected = true;
+
+            // Disconnect and reconnect the client a second time to catch bugs caused by not preserving
+            // the original 'localSeq' or caused by state mutations during reconnection.
+            containerRuntime1.connected = false;
+            containerRuntime1.connected = true;
+
```
Comment (DLehenbauer) [inline packages/dds/matrix/src/test/matrix.spec.ts:736]: ^--- Reconnecting twice is the secret to repro'ing this bug.

File: packages/dds/matrix/src/test/matrix.stress.spec.ts [hunk 7]
```diff
@@ -301,9 +308,13 @@ describe("Matrix", () => {
...
-                    // console.log(matrices[0].toString());
-                    // eslint-disable-next-line max-len
-                    console.log(`Stress loop: ${++iterations} iterations completed - Total Elapsed: ${((Date.now() - start) / 1000).toFixed(2)}s`);
+                    // Note: Mocha reporter intercepts 'console.log()' so use 'process.stdout.write' instead.
+                    process.stdout.write(matrices[0].toString());
+
+                    process.stdout.write(
+                        `Stress loop: ${++iterations} iterations completed - Total Elapsed: ${
+                            ((Date.now() - start) / 1000).toFixed(2)
+                        }s\n`);
```
Comment (DLehenbauer) [inline packages/dds/matrix/src/test/matrix.stress.spec.ts:317]: ^-- The above console output only appears in the "long haul" stress.  (i.e., not during 'npm t', in the lab, etc.)

**Review by anthony-murphy — APPROVED** [review]
:shipit:

**Comment by anthony-murphy** [comment]
should this get back ported to release 0.38?

**Comment by DLehenbauer** [comment]
Thanks, @anthony-murphy!

We're okay waiting for 0.39 to release.  The issue was found by refreshing a document while pasting.  That scenario is a bit fringe and the app has already mitigated by changing the row/col insertion order during paste.
