### PR TITLE
fix blobManager assert tripped after serialization/rehydration

### LINKED ISSUE #6989: Rehydrating board with offline blobs fails to load blobs
Similar to #6828, however after https://github.com/microsoft/FluidFramework/pull/6864/files, while the container data itself can be rehydrated, it doesn't actually load blobs from IDetachedBlobStorage.

### To Reproduce
1. Instantiate loader with IDetachedBlobStorage
2. Create detached container from loader
3. While container is detached, upload blob via runtime
4. Serialize detached container, and rehydrate
5. Request blob previously uploaded via runtime

### Expected behavior
Expect that IDetachedBlobStorage.readBlob() will be called

### Actual behavior
IDetachedBlobStorage.readBlob() not called, no blob is fetched

### Additional Info
Based on debugging--the culprit is the failure of [this assertion](https://github.com/microsoft/FluidFramework/blob/9ecfe01c4224649a8da64912d72f7971537d0bff/packages/runtime/container-runtime/src/blobManager.ts#L74), since on rehydration, blobIds and detachedBlobIds are both empty.  Removing the assertion seems to resolve the issue.

### PR DESCRIPTION
**Pull request by wes-carlson**
fixes #6989

Include detached blob IDs in snapshot returned by serialize() and load them upon rehydration.

### CODE REVIEW

File: packages/runtime/container-runtime/src/blobManager.ts [hunk 1]
```diff
@@ -131,17 +135,19 @@ export class BlobManager {
...
             count = values.length;
-            values.map((entry) => this.blobIds.add(entry));
+            values.map((entry) => detached ? this.detachedBlobIds.add(entry) : this.blobIds.add(entry));
         }
         this.logger.sendTelemetryEvent({ eventName: "ExternalBlobsInSnapshot", count });
     }
 
     public snapshot(): ITree {
-        const entries = [...this.blobIds].map((id) => new AttachmentTreeEntry(id, id));
+        const blobIds = this.runtime.attachState === AttachState.Detached ? this.detachedBlobIds : this.blobIds;
```
Comment (andre4i) [inline packages/runtime/container-runtime/src/blobManager.ts:149]: what do you think about a private method that just returns the blobids and encapsulates the whole  `this.runtime.attachState === AttachState.Detached` thing?

File: packages/loader/container-loader/src/utils.ts [hunk 2]
```diff
@@ -85,7 +88,7 @@ function convertSummaryToSnapshotWithEmbeddedBlobContents(
                 throw new Error("No handles should be there in summary in detached container!!");
                 break;
             default: {
-                throw new Error(`Unknown tree type ${summaryObject.type}`);
+                unreachableCase(summaryObject, `Unknown tree type ${(summaryObject as any).type}`);
```
[the remark this answers is not in the document]
Comment (wes-carlson) [reply packages/loader/container-loader/src/utils.ts:91]: The addition of `SummaryType.Attachment` makes the switch exhaustive, so the type of `summaryObject` here is `never`, which results in a compilation error when accessing `type` without the type assertion.

File: packages/runtime/container-runtime/src/blobManager.ts (hunk 1 above)
Comment (wes-carlson) [reply packages/runtime/container-runtime/src/blobManager.ts:149]: That's not a bad idea but I would like to keep this PR simple since it's a bugfix and also it somewhat overlaps with #6762. I will keep this idea in mind though.

File: packages/runtime/container-runtime/src/blobManager.ts [hunk 3]
```diff
@@ -69,8 +68,12 @@ export class BlobManager {
         });
     }
 
+    private hasBlob(id: string): boolean {
+        return this.blobIds.has(id) || this.detachedBlobIds.has(id);
+    }
+
     public async getBlob(blobId: string): Promise<IFluidHandle<ArrayBufferLike>> {
-        assert(this.blobIds.has(blobId) || this.pendingBlobIds.has(blobId), 0x11f /* "requesting unknown blobs" */);
+        assert(this.hasBlob(blobId), 0x11f /* "requesting unknown blobs" */);
```
Comment (markfields) [inline packages/runtime/container-runtime/src/blobManager.ts:76]: This is an example of where we should replace this assert with an if and throw a more user-friendly error. I'm adding a new container error type "UsageError" for this purpose, but I haven't merged it. You could do new GenericError or leave it as-is for now.

File: packages/runtime/container-runtime/src/blobManager.ts [hunk 4]
```diff
@@ -131,17 +135,19 @@ export class BlobManager {
      * attachment types returned in snapshot() with blobs.
      */
     public load(blobsTree?: ISnapshotTree): void {
+        const detached = this.runtime.attachState === AttachState.Detached;
```
Comment (markfields) [inline packages/runtime/container-runtime/src/blobManager.ts:138]: Subjective Nit: I prefer a name like isDetached for booleans

File: packages/runtime/container-runtime/src/blobManager.ts [hunk 5]
```diff
@@ -69,8 +68,12 @@ export class BlobManager {
         });
     }
 
+    private hasBlob(id: string): boolean {
+        return this.blobIds.has(id) || this.detachedBlobIds.has(id);
+    }
+
     public async getBlob(blobId: string): Promise<IFluidHandle<ArrayBufferLike>> {
-        assert(this.blobIds.has(blobId) || this.pendingBlobIds.has(blobId), 0x11f /* "requesting unknown blobs" */);
```
Comment (markfields) [inline packages/runtime/container-runtime/src/blobManager.ts:73]: What happened to the pendingBlobIds check here?

File: packages/loader/container-loader/src/utils.ts [hunk 6]
```diff
@@ -70,6 +70,9 @@ function convertSummaryToSnapshotWithEmbeddedBlobContents(
                 treeNode.trees[key] = convertSummaryToSnapshotWithEmbeddedBlobContents(summaryObject);
                 break;
             }
+            case SummaryType.Attachment:
```
Comment (markfields) [inline packages/loader/container-loader/src/utils.ts:73]: How is this related to the rest of the change?

**Review by markfields — APPROVED** [review]
Left some questions and general comments. I like that your wrote a test presumably that simulates the bug you're fixing, so with that passing you're good to go.

File: packages/runtime/container-runtime/src/blobManager.ts (hunk 3 above)
Comment (wes-carlson) [reply packages/runtime/container-runtime/src/blobManager.ts:76]: I would argue that an assert is appropriate here. For context, this is not really a public-facing API. `getBlob()` is used by `ContainerRuntime` to route blob handles. This assert being tripped would most likely indicate data loss.

File: packages/runtime/container-runtime/src/blobManager.ts (hunk 5 above)
Comment (wes-carlson) [reply packages/runtime/container-runtime/src/blobManager.ts:73]: This is the result of a previous change which made it impossible for blobs to be requested while pending (see `createBlob()`/`processBlobAttachOp()`)

File: packages/loader/container-loader/src/utils.ts (hunk 6 above)
Comment (wes-carlson) [reply packages/loader/container-loader/src/utils.ts:73]: This function is used during rehydration from snapshot. Since only BlobManager uses the attachment type and previously, blobs were not supported in detached containers, there wouldn't ever be attachment types in the snapshot. This is covered in the unit test added in this PR as part of container serialization/rehydration.
