### PR TITLE
fix r11s driver issue

### LINKED ISSUE #9163: Fix and re-enable disabled stashedOps tests
A lot of `stashedOps` tests from the end-to-end tests are failing when run under t9s or r11s-frs because they are timing out consistently. A few of them have been disabled to help clean up CI runs and should be fixed and re-enabled (deemed to not be release-blocking).
A few of them are also failing for odsp occasionally mostly due to [this change](https://github.com/microsoft/FluidFramework/pull/8702) which changed map.wait -> map.set.

Flaky tests:
```
doesn't resend successful chunked op
doesn't resend a lot of successful ops
doesn't resend successful op
successful map clear no resend
resends op
resends a lot of ops
```

Related - https://github.com/microsoft/FluidFramework/issues/9309 which are also flaky mostly due to the same root-cause.

### PR DESCRIPTION
**Pull request by wes-carlson**
fix #9163
Fix hang in r11s driver caused by response.clone()

### CODE REVIEW

**Comment by anthony-murphy** [comment]
please do check this minimal test in eventually. regression tests like this are usually great bug finders, as if something breaks once, it's more likely to break again

**Comment by wes-carlson** [comment]
#9164

Looks like the issue was that response.clone() will hang if the response is too big

**Comment by wes-carlson** [comment]
#9163

**Comment by vladsud** [comment]
Curious, why did it hang?

File: packages/drivers/routerlicious-driver/src/restWrapper.ts [hunk 1]
```diff
@@ -82,7 +82,9 @@ export class RouterliciousRestWrapper extends RestWrapper {
                     isNetworkError ? `NetworkError: ${error.message}` : safeStringify(error));
             }));
 
-        const responseBody: any = await response.clone().json().catch(async () => response.text());
+        const responseBody: any = response.headers.get("content-type")?.includes("application/json")
```
Comment (vladsud) [inline packages/drivers/routerlicious-driver/src/restWrapper.ts:85]: Is this logic applicable both to success & failure paths?
I do not know, (and not sure if ODSP gets it right), but glanced at ODSP - we never check content-type:
- on success the caller describes what to expect (it's either JSON or binary)
- on failure, we always use text.

Comment (znewton) [reply packages/drivers/routerlicious-driver/src/restWrapper.ts:85]: Took a quick look at the R11s APIs. Content-Type header _should_ be accurate, including for error paths. However, on line 110 here it looks like we're stringifying JSON errors anyways, so errors end up being strings no matter what. Probably safest bet would be to put this logic within the Success `if()` block, then parse the body stream as `.text()` around line 109 instead of stringifying an object.

**Comment by znewton** [comment]
Thanks for this fix, @wes-carlson!

File: packages/test/test-end-to-end-tests/src/test/t9sregressiontest.spec.ts [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+        summaryOptions: {
+            // currently these tests will break if we load from a summary that was too recent
+            disableSummaries: true,
+        },
+    },
+};
+
+// This is a regression test for #9163
+describeNoCompat("t9s issue regression test", (getTestObjectProvider) => {
+    it("test which fails", async function() {
```
Comment (anthony-murphy) [inline packages/test/test-end-to-end-tests/src/test/t9sregressiontest.spec.ts:33]: can you update the scenario name to be a bit more specific

File: packages/drivers/routerlicious-driver/src/restWrapper.ts (hunk 1 above)
Comment (wes-carlson) [reply packages/drivers/routerlicious-driver/src/restWrapper.ts:85]: It looks like it checks `responseBody.retryAfter` if it's a 429

Comment (markfields) [reply packages/drivers/routerlicious-driver/src/restWrapper.ts:85]: Side note - can we add a real type annotation rather than settling for `any`?  It can serve as documentation for what we expect (and depend on) over the wire all in one place.  I think it'd be `const responseBody: string | { retryAfter?: number }`.  Even safer would be to write a helper to extract the response body, and have it do additional runtime type checking before returning a thing of that type.  But I fully accept that these additiona runtime checks may be overkill and it works without it.  But I always love getting rid of `any`.

**Comment by znewton** [comment]
@wes-carlson we're seeing this problem coming up for FRS. Are you able to push this past the finish line or can/should I take over to help get it there?

**Comment by wes-carlson** [comment]
@znewton feel free to reassign #9163 if the fix is not right

File: packages/drivers/routerlicious-driver/src/restWrapper.ts (hunk 1 above)
Comment (znewton) [reply packages/drivers/routerlicious-driver/src/restWrapper.ts:85]: I think it would be `T | { retryAfter?: number }`

**Review by znewton — APPROVED** [review]
