### PR TITLE
Integrate OpProcessingController functionality into LoaderContainerTracker

### LINKED ISSUE #5572: Asserts in leader end-to-end tests do not fail tests
In `leader.spec.ts`, asserts are thrown in response to unexpected `"leader"` and `"notleader"` events, however these do not result in a test failure. This can be confirmed by changing `true` to `false` for an expected event. The assert will trip but the test will still pass.

In addition, the asserts trip during test teardown, resulting in errors displayed when run in verbose mode (but not test failure for the above reason) like this:
```
 fluid:telemetry RaiseConnectedEventError {"category":"error","error":"notleader event not expected in dataObject1","clientType":"interactive","loaderVersion":"0.37.0","containerId":"b663759d-0a9e-4dc8-a440-d7fe38e9c353","docId":"ab70ad6a-216e-4ce5-b0ce-a5bb9d38ab46","containerAttachState":"Attached","containerLoaded":true,"runtimeVersion":"0.37.0","dataStoreId":"9a9d180e-edc8-4e9b-8be1-ee397dec543b","loaderId":"38d247bb-a504-457a-8cdd-096d691e5717"} tick=3423 AssertionError [ERR_ASSERTION]: notleader event not expected in dataObject1
  fluid:telemetry     at RuntimeWithRequestHandler.<anonymous> (/home/wes/fluid/packages/test/test-end-to-end-tests/dist/test/leader.spec.js:52:22)
  fluid:telemetry     at RuntimeWithRequestHandler.emit (events.js:315:20)
  fluid:telemetry     at LocalFluidDataStoreContext.<anonymous> (/home/wes/fluid/packages/runtime/datastore/dist/dataStoreRuntime.js:655:18)
  fluid:telemetry     at LocalFluidDataStoreContext.emit (events.js:315:20)
  fluid:telemetry     at LocalFluidDataStoreContext.updateLeader (/home/wes/fluid/packages/runtime/container-runtime/dist/dataStoreContext.js:356:18)
  fluid:telemetry     at DataStores.updateLeader (/home/wes/fluid/packages/runtime/container-runtime/dist/dataStores.js:152:21)
  fluid:telemetry     at ContainerRuntime.updateLeader (/home/wes/fluid/packages/runtime/container-runtime/dist/containerRuntime.js:1283:25)
  fluid:telemetry     at AgentScheduler.<anonymous> (/home/wes/fluid/packages/runtime/container-runtime/dist/containerRuntime.js:1250:30)
  fluid:telemetry     at AgentScheduler.emit (events.js:315:20)
  fluid:telemetry     at AgentScheduler.clearRunningTasks (/home/wes/fluid/packages/runtime/agent-scheduler/dist/scheduler.js:308:18)
  fluid:telemetry     at AgentSchedulerRuntime.<anonymous> (/home/wes/fluid/packages/runtime/agent-scheduler/dist/scheduler.js:221:22)
  fluid:telemetry     at AgentSchedulerRuntime.emit (events.js:315:20)
  fluid:telemetry     at Object.raiseConnectedEvent (/home/wes/fluid/packages/utils/telemetry-utils/dist/events.js:25:21)
  fluid:telemetry     at AgentSchedulerRuntime.setConnectionState (/home/wes/fluid/packages/runtime/datastore/dist/dataStoreRuntime.js:309:27)
  fluid:telemetry     at LocalFluidDataStoreContext.setConnectionState (/home/wes/fluid/packages/runtime/container-runtime/dist/dataStoreContext.js:187:22)
  fluid:telemetry     at DataStores.setConnectionState (/home/wes/fluid/packages/runtime/container-runtime/dist/dataStores.js:204:25)
  fluid:telemetry     at ContainerRuntime.setConnectionState (/home/wes/fluid/packages/runtime/container-runtime/dist/containerRuntime.js:702:25)
  fluid:telemetry     at ContainerContext.setConnectionState (/home/wes/fluid/packages/loader/container-loader/dist/containerContext.js:142:17)
  fluid:telemetry     at Container.propagateConnectionState (/home/wes/fluid/packages/loader/container-loader/dist/container.js:1217:26)
  fluid:telemetry     at Object.propagateConnectionState (/home/wes/fluid/packages/loader/container-loader/dist/container.js:200:50)
  fluid:telemetry     at ConnectionStateHandler.setConnectionState (/home/wes/fluid/packages/loader/container-loader/dist/connectionStateHandler.js:86:26)
  fluid:telemetry     at ConnectionStateHandler.receivedDisconnectEvent (/home/wes/fluid/packages/loader/container-loader/dist/connectionStateHandler.js:36:14)
  fluid:telemetry     at DeltaManager.<anonymous> (/home/wes/fluid/packages/loader/container-loader/dist/container.js:1120:41)
  fluid:telemetry     at DeltaManager.emit (events.js:327:22)
  fluid:telemetry     at DeltaManager.disconnectFromDeltaStream (/home/wes/fluid/packages/loader/container-loader/dist/deltaManager.js:943:14)
  fluid:telemetry     at DeltaManager.close (/home/wes/fluid/packages/loader/container-loader/dist/deltaManager.js:803:14)
  fluid:telemetry     at Container.close (/home/wes/fluid/packages/loader/container-loader/dist/container.js:455:28)
  fluid:telemetry     at LoaderContainerTracker.reset (/home/wes/fluid/packages/test/test-utils/dist/loaderContainerTracker.js:30:23)
  fluid:telemetry     at TestObjectProvider.reset (/home/wes/fluid/packages/test/test-utils/dist/testObjectProvider.js:136:38)
  fluid:telemetry     at Context.<anonymous> (/home/wes/fluid/packages/test/test-end-to-end-tests/dist/test/leader.spec.js:27:14)
  fluid:telemetry     at callFn (/home/wes/fluid/node_modules/mocha/lib/runnable.js:366:21)
  fluid:telemetry     at Hook.Runnable.run (/home/wes/fluid/node_modules/mocha/lib/runnable.js:354:5)
  fluid:telemetry     at next (/home/wes/fluid/node_modules/mocha/lib/runner.js:510:10)
  fluid:telemetry     at Immediate._onImmediate (/home/wes/fluid/node_modules/mocha/lib/runner.js:572:5)
  fluid:telemetry     at processImmediate (internal/timers.js:456:21) +0ms

```

### PR DESCRIPTION
**Pull request by curtisman**
Fully replace usage of `OpProcessingController` with `LoaderContainerTracker`
  - Container created by Loader added to it will be automatically tracked, removing explicity `addDeltaManager`
  - `OpProcessingController` manually track op outbound and inbound to keep track of inflight ops.  `LoaderContainerTracker` do less tracking, instead it use the follow condition to tell if the containers are in sync
    - No `isDirty` containers
    - No extra `clientId` in quorum of any container that is not tracked and still opened.
      - i.e. no pending Join/Leave message.
    - No unresolved proposal (`minSeqNum >= lastProposalSeqNum`)  [New in`LoaderContainerTracker`]
    - `lastSequenceNumber` of all container is the same
    - `clientSequenceNumberObserved` is the same as `clientSequenceNumber` sent
        - This overlaps with `!isDirty`, but include task scheduler ops that `isDirty` doesn't cover
        - Trailing `NoOp` is tracked and don't count as pending ops. See Issue #5629 

This fixes `pendingOps.spec.ts` test where there is a bad interaction between `OpProcessingController` and `LoaderContainerTracker` where `OpProcessingController` paused the `DeltaManager` while `LoaderContainerTracker` is waiting.

`OpProcessingController` is mark as deprecated and will be remove on the next release to allow a grace period for migration

Also:
- Using the debug package to trace ops and wait for debugging (set env DEBUG to `fluid:test-utils:ops` or `fluid:test-utils:wait`)
- Fixes #5572: listener with assert should be unregister after test in `leader.spec.ts`, as those condition would not be true .
- Convert more test to create and load containers with `TestObjectProvider` to get automatic tracking
- Quorum Proposal should throw a Error instead of a string when disconnected.

### CODE REVIEW

File: packages/test/test-utils/src/loaderContainerTracker.ts [hunk 1]
```diff
@@ -3,17 +3,46 @@
...
+export class LoaderContainerTracker implements IOpProcessingController {
+    private readonly containers = new Map<IContainer, ContainerRecord>();
+    private lastProposalSeqNum: number = 0;
+
+    /**
+     * Add a loader to start to track any container created from them
+     * @param loader - loader to start tracking any container created.
+     */
     public add<LoaderType extends IHostLoader>(loader: LoaderType) {
+        // TODO: Expose Loader API to able to intercept container creation
```
Comment (anthony-murphy) [inline packages/test/test-utils/src/loaderContainerTracker.ts:40]: #5114

File: packages/test/test-utils/src/loaderContainerTracker.ts [hunk 2]
```diff
@@ -25,36 +54,470 @@ export class LoaderContainerTracker {
...
+                    record.startTrailingNoOps = 0;
+                    record.trailingNoOps = 0;
+                }
+            }
+        });
+
+        container.deltaManager.inbound.on("push", (message) => {
+            // Received the no op back, update the record.
+            if (message.type === MessageType.NoOp
+                && message.clientId === (container as Container).clientId
```
Comment (anthony-murphy) [inline packages/test/test-utils/src/loaderContainerTracker.ts:109]: I really dislike how we always need to cast to container. we should consider #1707

File: packages/test/test-utils/src/loaderContainerTracker.ts [hunk 3]
```diff
@@ -25,36 +54,470 @@ export class LoaderContainerTracker {
...
+
+        container.on("disconnected", () => {
+            // reset on disconnect.
+            record.startTrailingNoOps = 0;
+            record.trailingNoOps = 0;
+        });
+    }
+
+    private trackLastProposal(container: IContainer) {
+        container.deltaManager.inbound.on("op", (message) => {
```
Comment (anthony-murphy) [inline packages/test/test-utils/src/loaderContainerTracker.ts:124]: use container.on("codeDetailsProposed"

File: packages/test/test-utils/src/loaderContainerTracker.ts [hunk 4]
```diff
@@ -25,36 +54,470 @@ export class LoaderContainerTracker {
...
+     */
     public reset() {
-        for (const container of this.containers) {
+        this.lastProposalSeqNum = 0;
+        for (const container of this.containers.keys()) {
             container.close();
         }
         this.containers.clear();
+
+        // REVIEW: do we need to unpatch the loaders?
```
Comment (anthony-murphy) [inline packages/test/test-utils/src/loaderContainerTracker.ts:141]: probably wise. should be easy if you encapsulate the function you patch with, that function could be stored somewhere on this class, and then you can just shutdown that function somehow, so the loader is still patched, but now the patch does nothing.

Comment (anthony-murphy) [reply packages/test/test-utils/src/loaderContainerTracker.ts:141]: would also be easier if we had the event, so this could be a follow up

File: packages/test/test-utils/src/loaderContainerTracker.ts [hunk 5]
```diff
@@ -25,36 +54,470 @@ export class LoaderContainerTracker {
...
+            const { trailingNoOps } = this.containers.get(container)!;
+            return deltaManager.clientSequenceNumber ===
+                (deltaManager.clientSequenceNumberObserved as number) + trailingNoOps;
+        });
+
+        if (!isClientSequenceNumberSynchronized) {
+            return false;
         }
+
+        const minSeqNum = containersToApply[0].deltaManager.minimumSequenceNumber;
```
Comment (anthony-murphy) [inline packages/test/test-utils/src/loaderContainerTracker.ts:268]: it's a bit weird we need to special case the quorum, won't other consensus structures have the same issue? i'd rather make the test wait if the side effect it cares about, approve or reject in this case

**Review by anthony-murphy — APPROVED** [review]

File: packages/test/test-utils/src/loaderContainerTracker.ts (hunk 2 above)
Comment (curtisman) [reply packages/test/test-utils/src/loaderContainerTracker.ts:109]: I am trying not to lump that into this PR.

File: packages/test/test-utils/src/loaderContainerTracker.ts (hunk 4 above)
Comment (curtisman) [reply packages/test/test-utils/src/loaderContainerTracker.ts:141]: Yep... That's why I just left it a comment here, because we might just have the event.

File: packages/test/test-utils/src/loaderContainerTracker.ts (hunk 5 above)
Comment (curtisman) [reply packages/test/test-utils/src/loaderContainerTracker.ts:268]: All the consensus data structure only need the round trip.   The quorum proposal is unique in that  it allow other client to reject, thus needs to wait until minSeqNumber to catch up.

It is debatable that whether we should have the test wait for proposal accepted or not and just let op resume in the mean time.   But I do see a benefit to basically ensure the system has completely "settled".

File: packages/test/test-utils/src/loaderContainerTracker.ts (hunk 3 above)
Comment (curtisman) [reply packages/test/test-utils/src/loaderContainerTracker.ts:124]: But there are other proposal too, not just code details?   I think I should change it to container.quorum.on("addProposal") instead.

File: packages/test/test-utils/src/loaderContainerTracker.ts (hunk 1 above)
Comment (curtisman) [reply packages/test/test-utils/src/loaderContainerTracker.ts:40]: Yep.  adding a comment here.  I will add issue number
