### PR TITLE
Fix datastore reference validation for GC

### LINKED ISSUE #9426: Fix GC Outbound Reference Validation
GC outbound reference validation does not catch the bug in this issue #8859 

Essentially references from child nodes to parents are added to explicitReferences when they should not be. Thus, the explicitReferences contain references that were not explicitly added.

### PR DESCRIPTION
**Pull request by tyler-cai-microsoft**
Resolves #9426 

* Adds the logUnknownOutboundRoutes feature flag
* Fixes outboundRoute validation

### CODE REVIEW

File: packages/runtime/container-runtime/src/garbageCollection.ts [hunk 1]
```diff
@@ -816,13 +818,17 @@ export class GarbageCollector implements IGarbageCollector {
      */
     private updateStateSinceLastRun(currentGCData: IGarbageCollectionData) {
         // If we haven't run GC before or no references were added since the last run, there is nothing to do.
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/garbageCollection.ts:820]: This comment needs to be updated now.

File: packages/runtime/container-runtime/src/garbageCollection.ts [hunk 2]
```diff
@@ -878,44 +887,52 @@ export class GarbageCollector implements IGarbageCollector {
...
 
-        // Get a list of outbound routes (or references) from the last run's GC data plus references added since the
-        // last run that were notified via `referenceAdded`.
-        const explicitReferences: string[] = [];
-        for (const [, outboundRoutes] of Object.entries(this.gcDataFromLastRun.gcNodes)) {
-            explicitReferences.push(...outboundRoutes);
+        // Get a list of references (or outbound routes) from the previous run's GC data plus new references added since
+        // the last run that were notified via `addedOutboundReference`.
+        const previousAndNewReferences: string[] = [];
+        const previousGraph = Object.entries(this.gcDataFromLastRun.gcNodes);
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/garbageCollection.ts:908]: We should probably rename `gcDataFromLastRun` -> `previousGCData` or `previousRunGCData` to make it clearer.

File: packages/runtime/container-runtime/src/garbageCollection.ts [hunk 3]
```diff
@@ -865,59 +877,92 @@ export class GarbageCollector implements IGarbageCollector {
...
-            /**
-             * Remove routes from a child node to its parent which is added implicitly by the runtime. For instance,
-             * each adds its data store as an outbound route to mark it as referenced if the DDS is referenced.
-             * We won't get any explicit notification for these references so they must be removed before validation.
-             */
-            const explicitRoutes = outboundRoutes.filter((route) => !nodeId.startsWith(route));
-            currentReferences.push(...explicitRoutes);
-        }
+        const getOutboundReferences = (nodeId: string, references: string[]): string[] => {
+            if (references === undefined) {
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/garbageCollection.ts:909]: This check is not needed because the type of references is `string[]` so it won't be undefined.

File: packages/runtime/container-runtime/src/garbageCollection.ts [hunk 4]
```diff
@@ -865,59 +877,92 @@ export class GarbageCollector implements IGarbageCollector {
...
+                return [];
+            }
+            return references.filter((reference) => !nodeId.startsWith(reference) && isDataStoreNode(reference));
+        };
+
+        const getOutboundGraph = (routes: [string, string[]][]) => {
+            const outboundGraph: [string, string[]][] = [];
+            for (const [nodeId, references] of routes) {
+                const outboundReferences: string[] = getOutboundReferences(nodeId, references);
+                if (outboundReferences.length > 0) {
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/garbageCollection.ts:919]: This check should be removed. When building the outbound graph, you want to include nodes that don't have outbound routes.

File: packages/runtime/container-runtime/src/garbageCollection.ts [hunk 5]
```diff
@@ -865,59 +877,92 @@ export class GarbageCollector implements IGarbageCollector {
...
-        // last run that were notified via `referenceAdded`.
-        const explicitReferences: string[] = [];
-        for (const [, outboundRoutes] of Object.entries(this.gcDataFromLastRun.gcNodes)) {
-            explicitReferences.push(...outboundRoutes);
+        // Get Current and Previous graphs
+        const currentGraph = getOutboundGraph(Object.entries(currentGCData.gcNodes));
+        const previousGraph = previousGCData.gcNodes;
+
+        // Expected Routes = Routes in the Current Graph and not in the Previous Graph
+        const expectedRoutes: [string, string[]][] = [];
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/garbageCollection.ts:931]: `expectedRoutes` does not seem like the right term for this. This is new references between previous and current run deteremined by generating the reference graph. You want to compare this with explicit references between previous and current run.

File: packages/runtime/container-runtime/src/garbageCollection.ts [hunk 6]
```diff
@@ -865,59 +877,92 @@ export class GarbageCollector implements IGarbageCollector {
     }
 
     /**
-     * Validates that all new references are correctly identified and processed. The basic principle for validation is
-     * that we should not have new references in the reference graph (GC data) that have not been notified to the
-     * garbage collector via `referenceAdded`.
-     * We validate that the references in the current reference graph should be a subset of the references in the last
-     * run's reference graph + references since the last run.
+     * Finds Missing Routes and logs a Performance event everytime a missing route is found
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/garbageCollection.ts:880]: This comment needs to be updated to add more details to better reflect what this function is going. "Finds Missing Routes" is very generic and doesn't convey any meaningful information. This function finds references that were added between the previous run and the current one by comparing the two reference graphs. From these references, it finds and returns the ones that were not explicitly notified to GC.

File: packages/runtime/container-runtime/src/garbageCollection.ts [hunk 7]
```diff
@@ -865,59 +877,92 @@ export class GarbageCollector implements IGarbageCollector {
...
+     *
+     * Expected Routes = Routes in Current datastore graph and not in Previous datastore graph
+     * New Routes = New routes added by GC when a handle was added or root datastores
+     * Missing Routes = Expected Routes not in New Routes
+     *
+     * Node - represented as nodeId, it's a node on the GC graph
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/garbageCollection.ts:886]: The distinction between these terms is a good one to add. I think we should add this to the class description as its applicable to the entire class and will help explain what each of these mean.

File: packages/runtime/container-runtime/src/garbageCollection.ts [hunk 8]
```diff
@@ -865,59 +877,92 @@ export class GarbageCollector implements IGarbageCollector {
...
+     * Route - a reference with a parent, think `nodeId` & `reference`
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/garbageCollection.ts:887]: The definitions of route, reference and outbound is not correct. Infact, I think its incorrectly used in a lot of places in this file and in other places.
An "outbound route" and a "reference" mean the same thing. They represent a link from one node to another. For example, consider the following reference graph: A -> B -> C. Here, the arrows represent reference or outbound route. Basically, there is a reference or outbound route from A to B and from B to C. So, essentially the source node, destination node and the link between together mean a reference or an outbound route.

File: packages/runtime/container-runtime/src/garbageCollection.ts [hunk 9]
```diff
@@ -865,59 +877,92 @@ export class GarbageCollector implements IGarbageCollector {
...
-                // We should ideally throw a data corruption error here. However, send an error for now until we have
-                // implemented sweep and have reasonable confidence in the sweep process.
-                // this.mc.logger.sendErrorEvent({
-                //     eventName: "gcUnknownOutboundRoute",
-                //     route,
-                // });
+        // Missing Routes = Expected Routes not in New Routes
+        const missingRoutes: [string, string[]][] = [];
+        for (const [nodeId, expectedReferences] of expectedRoutes) {
+            const newReferences = newRoutes.get(nodeId);
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/garbageCollection.ts:944]: You can do newReferences = newRoutes.get(nodeId) ?? []. Then you don't have to check for it being unreferenced below.

File: packages/runtime/container-runtime/src/garbageCollection.ts [hunk 10]
```diff
@@ -865,59 +877,92 @@ export class GarbageCollector implements IGarbageCollector {
...
+            const missingReferences: string[] = [];
+            expectedReferences.forEach((expectedRef) => {
+                // Every time an expected route is found, there should be a log of the error.
+                // Eventually a data corruption assert should be thrown and the client should fail fast
+                if (newReferences === undefined || !newReferences.includes(expectedRef)) {
+                    this.mc.logger.sendPerformanceEvent({
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/garbageCollection.ts:950]: We cannot log this error yet because of the bug mentioned in the comment that was here before. You should only do it for testing behind a feature flag.

File: packages/runtime/container-runtime/src/garbageCollection.ts [hunk 11]
```diff
@@ -865,59 +903,60 @@ export class GarbageCollector implements IGarbageCollector {
...
-        // Get a list of outbound routes (or references) from the last run's GC data plus references added since the
-        // last run that were notified via `referenceAdded`.
-        const explicitReferences: string[] = [];
-        for (const [, outboundRoutes] of Object.entries(this.gcDataFromLastRun.gcNodes)) {
-            explicitReferences.push(...outboundRoutes);
-        }
-        this.referencesSinceLastRun.forEach((outboundRoutes: string[]) => {
-            explicitReferences.push(...outboundRoutes);
-        });
+        const getOutboundRoutes = (nodeId: string, routes: string[]): string[] => {
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/garbageCollection.ts:929]: This is only used in convertGraphToOutounndReferences and so making this a function does not add any value. You can make this inline in convertGraphToOutounndReferences.

File: packages/runtime/container-runtime/src/garbageCollection.ts [hunk 12]
```diff
@@ -97,6 +99,11 @@ interface IUnreferencedEvent {
     viaHandle?: boolean;
 }
 
+interface IGCReference {
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/garbageCollection.ts:102]: We already have a node -> outboundRoutes structure. Adding another for each node -> route combination doesn't add any value.

File: packages/runtime/container-runtime/src/garbageCollection.ts [hunk 13]
```diff
@@ -865,59 +903,60 @@ export class GarbageCollector implements IGarbageCollector {
...
-                 * The following log will be enabled once this issue is resolved:
-                 * https://github.com/microsoft/FluidFramework/issues/8878.
-                 */
-                // We should ideally throw a data corruption error here. However, send an error for now until we have
-                // implemented sweep and have reasonable confidence in the sweep process.
-                // this.mc.logger.sendErrorEvent({
-                //     eventName: "gcUnknownOutboundRoute",
-                //     route,
-                // });
+        const convertGraphToOutboundReferences = (graph: [string, string[]][]) => {
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/garbageCollection.ts:935]: I don't see any value in converting this graph from a list of `node -> set of routes` to `node -> individual route`. It only adds another data structure and another concept we have to deal with. Plus, making this conversion in not necessary and adds overheads.

File: packages/runtime/container-runtime/src/garbageCollection.ts [hunk 14]
```diff
@@ -865,59 +903,60 @@ export class GarbageCollector implements IGarbageCollector {
...
+                outboundReferences.push(...outboundReferencesForNode);
             }
+            return outboundReferences;
+        };
+
+        const currentReferences = convertGraphToOutboundReferences(Object.entries(currentGCData.gcNodes));
+
+        // Missing Explicit References str Current References not in the previous graph and not in explicit references
+        const missingExplicitReferences: IGCReference[] = currentReferences.filter((reference) => {
+            const previousReferences = previousGCData.gcNodes[reference.parent] ?? [];
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/garbageCollection.ts:951]: This is complicated than it needs to be because of so many conversions. We already have a structure in the format `node -> set of outbound routes` and we can just that here.
This can become something like -
currentGCData.filter(([nodeId, currentOutboundRoutes]) => {
    const previousRoutes = previousGCData.gcNodes[nodeId] ?? [];
    const explicitRoutes = explicitReferences.get(nodeId) ?? [];
    let found = false;
    currentOutboundRoutes.forEach((route) => {
         found = previousRoutes.includes(route) || explicitRoutes.include(route);
    });
    return found;
});

File: packages/runtime/container-runtime/src/garbageCollection.ts [hunk 15]
```diff
@@ -204,6 +211,12 @@ class UnreferencedStateTracker {
 /**
  * The garbage collector for the container runtime. It consolidates the garbage collection functionality and maintains
  * its state across summaries.
+ *
+ * Node - represented as nodeId, it's a node on the GC graph
+ * Reference - a route with a parent, think `nodeId` & `Route`
+ * Route - a node that is reachable from another node, think `nodeId`
+ * Outbound - a route or reference going from parent to child
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/garbageCollection.ts:218]: There is no parent child relationship in a graph. Its just a set of nodes and dependencies.

Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/garbageCollection.ts:218]: So, only node, outbound route and graph are the only terms we need. You can correlate them to vertices and directed edges in a directed graph. Maybe even write an example here and show what the different terms look like w.r.t. graph

Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/garbageCollection.ts:218]: A comment with a diagram like this - https://github.com/microsoft/FluidFramework/blob/b84ea277bad1d7133df989c8e5cd64973b3d6bc9/packages/runtime/container-runtime/src/test/dataStoreCreation.spec.ts#L29

File: packages/runtime/container-runtime/src/garbageCollection.ts [hunk 16]
```diff
@@ -865,59 +903,60 @@ export class GarbageCollector implements IGarbageCollector {
...
-     * garbage collector via `referenceAdded`.
-     * We validate that the references in the current reference graph should be a subset of the references in the last
-     * run's reference graph + references since the last run.
+     * Finds outbound references to datastores in the current GC graph that aren't in the previous GC graph and returns
+     * them if they are not added by GC's `addedOutboundReference`.
+     *
+     * In more simple terms:
+     * Missing Explicit References = Current References - Previous References - Explicitly Added References;
+     *
+     * Currently outbound references are references from a parent node to child datastore node
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/garbageCollection.ts:912]: This line is incorrect. outbound references do not have parent child relationship. Its just from one node to another where a node doesn't have to be a data store.

File: packages/runtime/container-runtime/src/garbageCollection.ts [hunk 17]
```diff
@@ -865,59 +903,60 @@ export class GarbageCollector implements IGarbageCollector {
     }
 
     /**
-     * Validates that all new references are correctly identified and processed. The basic principle for validation is
-     * that we should not have new references in the reference graph (GC data) that have not been notified to the
-     * garbage collector via `referenceAdded`.
-     * We validate that the references in the current reference graph should be a subset of the references in the last
-     * run's reference graph + references since the last run.
+     * Finds outbound references to datastores in the current GC graph that aren't in the previous GC graph and returns
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/garbageCollection.ts:906]: This line is tied to the specific implementation that is done. It should provide a high level view of what this function is doing and then you can mention the current implementation if needed. Or, a better approach is that the implementation part of the comment can move inside the function. Similarly, the part about only doing this for data stores currently is implementation detail. We do this because we haven't implemented GC in layers other than data stores. You should mention this where you filter out other nodes and not here.


So, this function finds all new references or outbound routes in the current graph that haven't been explicitly notified to GC. The principle is that every new reference or outbound route must be notified to GC via the addedOutboundReference method. It it hasn't, its a bug and we want to identify these scenarios.

File: packages/runtime/container-runtime/src/garbageCollection.ts [hunk 18]
```diff
@@ -865,59 +903,60 @@ export class GarbageCollector implements IGarbageCollector {
...
+     * them if they are not added by GC's `addedOutboundReference`.
+     *
+     * In more simple terms:
+     * Missing Explicit References = Current References - Previous References - Explicitly Added References;
+     *
+     * Currently outbound references are references from a parent node to child datastore node
+     *
      * @param currentGCData - The GC data (reference graph) from the current GC run.
+     * @param previousGCData - The GC data (reference graph) from the previous GC run.
+     * @param explicitReferences - New references added by GC explicity between the previous and the current run.
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/garbageCollection.ts:916]: remove "by GC" here. The references are not added by GC. GC is only notified of these.

File: packages/runtime/container-runtime/src/garbageCollection.ts (hunk 14 above)
Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/garbageCollection.ts:951]: The return type of the findMissingExplicitReferences function should be IGarbageCollectionData or a map of node -> outbound routes similar to this.newReferencesSinceLastRun.

File: packages/runtime/container-runtime/src/garbageCollection.ts (hunk 13 above)
Comment (tyler-cai-microsoft) [reply packages/runtime/container-runtime/src/garbageCollection.ts:935]: How would you want to log the node -> set of routes? There needs to be some sort of conversion

Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/garbageCollection.ts:935]: You will have a list of `node -> routes`. You can either JSON.stringify the whole list. Or you can JSON.stringify every `node -> routes` combination and log it separately. I think logging them separately will be better because otherwise the string can become very large and may cause problems.

I didn't look at it before but with the way you are logging here, it will be difficult to look at this data in kusto. We need to log against unique keys and not a list of numbers. If the list of missing references is very large, we will have to add Data_0, Data_1 and so on which is not convenient or scalable.

File: packages/runtime/container-runtime/src/garbageCollection.ts [hunk 19]
```diff
@@ -826,13 +841,36 @@ export class GarbageCollector implements IGarbageCollector {
...
+        );
+
+        // The following log will be enabled once this issue is resolved:
+        // https://github.com/microsoft/FluidFramework/issues/8878.
+        if(this.mc.config.getBoolean(logUnknownOutboundReferencesKey) === true
+            && missingExplicitReferences.length > 0) {
+            missingExplicitReferences.forEach((missingExplicitReference) => {
+                const event: ITelemetryPerformanceEvent = {
+                    eventName: "gcUnknownOutboundReferences",
+                    gcNode: missingExplicitReference[0],
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/garbageCollection.ts:863]: nit: gcNodeId

File: packages/runtime/container-runtime/src/garbageCollection.ts [hunk 20]
```diff
@@ -826,13 +841,36 @@ export class GarbageCollector implements IGarbageCollector {
...
+                    gcRoutes: JSON.stringify(missingExplicitReference[1]),
+                };
+                this.mc.logger.sendPerformanceEvent(event);
+            });
+        }
+
+        // No references were added since the last run so we don't need to run garbage collection
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/garbageCollection.ts:870]: Instead of "we don't to run gc", this should say something like "we don't have to update reference states of any unreferenced nodes"

File: packages/runtime/container-runtime/src/garbageCollection.ts [hunk 21]
```diff
@@ -876,59 +914,41 @@ export class GarbageCollector implements IGarbageCollector {
...
-        // Get a list of outbound routes (or references) from the last run's GC data plus references added since the
-        // last run that were notified via `referenceAdded`.
-        const explicitReferences: string[] = [];
-        for (const [, outboundRoutes] of Object.entries(this.gcDataFromLastRun.gcNodes)) {
-            explicitReferences.push(...outboundRoutes);
-        }
-        this.referencesSinceLastRun.forEach((outboundRoutes: string[]) => {
-            explicitReferences.push(...outboundRoutes);
+        const currentGraph = Object.entries(currentGCData.gcNodes);
+        const missingExplicitReferences = currentGraph.filter(([nodeId, currentOutboundRoutes]) => {
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/garbageCollection.ts:940]: nit: You could do Object.entries(currentGCData.gcNodes).filter

File: packages/runtime/container-runtime/src/garbageCollection.ts [hunk 22]
```diff
@@ -876,59 +914,41 @@ export class GarbageCollector implements IGarbageCollector {
...
+            const previousRoutes = previousGCData.gcNodes[nodeId] ?? [];
+            const explicitRoutes = explicitReferences.get(nodeId) ?? [];
+            let found = false;
+            currentOutboundRoutes.forEach((route) => {
+                 found = previousRoutes.includes(route) || explicitRoutes.includes(route);
+            });
+            return found;
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/garbageCollection.ts:947]: Shouldn't this be reverted? You want to filter out routes that are not found. So, you should return !found.

Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/garbageCollection.ts:947]: I think that's why the test you added also doesn't get the new routes added between the two GC runs as unknown.

File: packages/runtime/container-runtime/src/test/garbageCollection.spec.ts [hunk 23]
```diff
@@ -751,27 +757,36 @@ describe("Garbage Collection Tests", () => {
...
-            // Validate that we got the "gcUnknownOutboundRoute" error.
-            mockLogger.matchEvents([
-                { eventName: unknownRouteEvent, route: nodeB },
-            ]);
+            // Validate that we got the "gcUnknownOutboundReferences" error.
+            const unknownReferencesEvent = "GarbageCollector:gcUnknownOutboundReferences";
+            const eventsFound = mockLogger.matchEvents([{
+                    eventName: unknownReferencesEvent,
+                    gcNode: "/",
+                    gcRoutes: JSON.stringify(["/A", "/D"]),
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/test/garbageCollection.spec.ts:787]: This should have A -> B, A -> C and D -> C since those were added between the two GC runs without notifying GC.

File: packages/runtime/container-runtime/src/garbageCollection.ts [hunk 24]
```diff
@@ -876,59 +914,41 @@ export class GarbageCollector implements IGarbageCollector {
...
-            explicitReferences.push(...outboundRoutes);
-        }
-        this.referencesSinceLastRun.forEach((outboundRoutes: string[]) => {
-            explicitReferences.push(...outboundRoutes);
+        const currentGraph = Object.entries(currentGCData.gcNodes);
+        const missingExplicitReferences = currentGraph.filter(([nodeId, currentOutboundRoutes]) => {
+            const previousRoutes = previousGCData.gcNodes[nodeId] ?? [];
+            const explicitRoutes = explicitReferences.get(nodeId) ?? [];
+            let found = false;
+            currentOutboundRoutes.forEach((route) => {
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/garbageCollection.ts:944]: I don't think returning a single boolean flag for all the outbound routes for a node will work. A node can have multiple outbound routes and some of them may not have been explicitly notified. We want to only add those.

File: packages/runtime/container-runtime/src/garbageCollection.ts [hunk 25]
```diff
@@ -876,59 +914,41 @@ export class GarbageCollector implements IGarbageCollector {
...
+                 found = previousRoutes.includes(route) || explicitRoutes.includes(route);
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/garbageCollection.ts:945]: You will need to filter out DDS routes and implicit route from DDS -> Data store here. We don't enforce the explicit reference to GC for DDS and the back route from DDS to Data store should not be notified as an unknown reference.

File: packages/runtime/container-runtime/src/garbageCollection.ts (hunk 21 above)
Comment (tyler-cai-microsoft) [reply packages/runtime/container-runtime/src/garbageCollection.ts:940]: The only reason I had the two split out was for readability sake.

File: packages/runtime/container-runtime/src/garbageCollection.ts [hunk 26]
```diff
@@ -876,59 +915,53 @@ export class GarbageCollector implements IGarbageCollector {
...
-                //     route,
-                // });
+        const currentGraph = Object.entries(currentGCData.gcNodes);
+        const missingExplicitReferences: [string, string[]][] = [];
+        currentGraph.forEach(([nodeId, currentOutboundRoutes]) => {
+            const previousRoutes = previousGCData.gcNodes[nodeId] ?? [];
+            const explicitRoutes = explicitReferences.get(nodeId) ?? [];
+            const missingExplicitRoutes: string[] = [];
+            currentOutboundRoutes.forEach((route) => {
+                const isBlobOrDataStoreRoute = this.runtime.getNodeType(route) !== GCNodeType.Other;
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/garbageCollection.ts:947]: This should explicitly use this.runtime.getNodeType(route) === GCNodeType.DataStore || this.runtime.getNodeType(route) === GCNodeType.Blob. If other types are added, it could break this.

File: packages/runtime/container-runtime/src/garbageCollection.ts [hunk 27]
```diff
@@ -876,59 +915,53 @@ export class GarbageCollector implements IGarbageCollector {
...
+                const notRouteFromDDSToParentDataStore = !nodeId.startsWith(route);
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/garbageCollection.ts:948]: Maybe adding a comment why this is removed would be helpful as its not obvious.

File: packages/runtime/container-runtime/src/garbageCollection.ts [hunk 28]
```diff
@@ -876,59 +915,53 @@ export class GarbageCollector implements IGarbageCollector {
...
+                const routeNotFound = !previousRoutes.includes(route) && !explicitRoutes.includes(route);
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/garbageCollection.ts:949]: nit: This step can be skipped if any of the two flags above are false. Since this is searching in two arrays, its not that cheap.

File: packages/runtime/container-runtime/src/test/garbageCollection.spec.ts [hunk 29]
```diff
@@ -751,27 +761,48 @@ describe("Garbage Collection Tests", () => {
...
+            assert(timestamps1.get(nodeD) === undefined, "D should be referenced");
 
-            // 2. Create node B. E = [].
+            // 2. Create nodes B & C. E = [].
             defaultGCData.gcNodes[nodeB] = [];
+            defaultGCData.gcNodes[nodeC] = [];
 
-            // 3. Add reference from A to B without calling addedOutboundReference. E = [A -> B].
-            defaultGCData.gcNodes[nodeA] = [ nodeB ];
+            // 3. Add reference from A to B, A to C, and D to C without calling addedOutboundReference.
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/test/garbageCollection.spec.ts:778]: This should include E to A.

File: packages/runtime/container-runtime/src/test/garbageCollection.spec.ts [hunk 30]
```diff
@@ -751,27 +761,48 @@ describe("Garbage Collection Tests", () => {
...
+            defaultGCData.gcNodes[nodeA] = [ nodeB, nodeC, nodeE ];
+            defaultGCData.gcNodes[nodeD] = [ nodeC ];
+            defaultGCData.gcNodes[nodeE] = [ nodeA ];
+
+            // 4. Add reference from A to D with calling addedOutboundReference
+            defaultGCData.gcNodes[nodeA].push(nodeD);
+            garbageCollector.addedOutboundReference(nodeA, nodeD);
 
-            // 4. Run GC and generate summary 2. E = [A -> B].
+            // 5. Run GC and generate summary 2. E = [A -> B, A -> C, D -> C].
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/test/garbageCollection.spec.ts:788]: This should include E -> A.

File: packages/runtime/container-runtime/src/garbageCollection.ts [hunk 31]
```diff
@@ -66,6 +66,8 @@ const runSweepKey = "Fluid.GarbageCollection.RunSweep";
 const writeAtRootKey = "Fluid.GarbageCollection.WriteDataAtRoot";
 // Feature gate key to expire a session after a set period of time.
 const runSessionExpiry = "Fluid.GarbageCollection.RunSessionExpiry";
+// Feature gate key to log error messages if gc route validation fails.
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/garbageCollection.ts:69]: "gc reference validation"

File: packages/runtime/container-runtime/src/garbageCollection.ts [hunk 32]
```diff
@@ -227,6 +229,19 @@ class UnreferencedStateTracker {
 /**
  * The garbage collector for the container runtime. It consolidates the garbage collection functionality and maintains
  * its state across summaries.
+ *
+ * Node - represented as nodeId, it's a node on the GC graph
+ * Outbound Route - a node that is reachable from another node, think `nodeId`
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/garbageCollection.ts:234]: Route is not a node. It's a reference from one node to another node.

**Review by agarwal-navin — APPROVED** [review]
LGTM. Please take a look at the comments before merging :-).
