### PR TITLE
fixes for #8755 Dubious switch fallthrough case in undo-redo

### LINKED ISSUE #8755: Dubious switch fallthrough case in undo-redo
> This looks like it found a bug, like there should be a `break` statement above...?  @anthony-murphy, @wes-carlson what do you think?

_Originally posted by @markfields in https://github.com/microsoft/FluidFramework/pull/8685#discussion_r781673019_

### PR DESCRIPTION
**Pull request by manaliraut**
break statement was missing before fall through / default in case for MergeTreeDeltaType.ANNOTATE

### CODE REVIEW

**Comment by tylerbutler** [comment]
@anthony-murphy Can you take a look at this?

File: packages/framework/undo-redo/src/sequenceHandler.ts [hunk 1]
```diff
@@ -124,6 +124,7 @@ export class SharedSegmentSequenceRevertible implements IRevertible {
                                     tracked.propertyDelta,
                                     undefined);
                             }
+			    break;
```
Comment (anthony-murphy) [inline packages/framework/undo-redo/src/sequenceHandler.ts:127]:
```suggestion
                            break;
```

**Review by anthony-murphy — APPROVED** [review]

**Comment by anthony-murphy** [comment]
fixes #8755

**Comment by anthony-murphy** [comment]
looks good. going to merge. thanks!
