### PR TITLE
Deprecate submitAsync

### LINKED ISSUE #2039: creationDocumentDeltaConnection improperly implements submitAsync
## Describe the bug
The Promise created [here ](https://github.com/microsoft/FluidFramework/blob/master/packages/drivers/create-new-driver/src/creationDocumentDeltaConnection.ts#L168-L170) may be intending to defer execution of the call to `this.serverMessagesHandler.submitMessage` until the microtask queue is flushed, but it will run immediately.

Instead it should probably do this:

```typescript
    public async submitAsync(messages: IDocumentMessage[]): Promise<void> {
       await Promise.resolve();
       this.serverMessagesHandler.submitMessage(messages, this.clientId);
    }
```

See [this demo](https://www.typescriptlang.org/play/?ts=3.7.5#code/MYewdgzgLgBANiA5jAvDUkRwKYDoGIDcAsAFBkCGEAnmMDAGYCudUAluDGNgO4AKAJxABbNhGwAKAJQwA3mRiKYA7FCYCwXXjEEixkiSogyUAPjkKlVghIBEAQVtSSpK1aMSAjM8uKAvj6kfmSUNHSMLMDsnEZYAG7YAGJsAtDSFq5KKmoaWjw6QqLiEobYxqjm8pluymUSAEyBNYo2tgBCTi5WAS7B5KRUtPTMrByaAFZM0ADCFHBwAJJQ6VXWSHbTnb61OZoAzL0hA2HDkdGaAI5M2NcAsmzAQlBUANYr2xQ8FGywukV4sTgCWkXSUrQAIltqjt1JoACyHfoSQbhdJmDJrRB2ewAIxATFgUBA6DmcBgUAAFtgIqNwBAodsMNAYAAHTyoPJ-fQgxl02As+ocwEJZKpZZNJRM-l7DmTGakpY86FS1lwjlXG7Ye6PEDPCBvQLbVq4-GE4mfb5QBnQmwWn6s7yglrrO38xpO+Aur72ll7CXOrGu1WGm3rWzg8DU11sMCIKEBJVkVqmiBsAAm2CcQA) of different forms on TS Playground.  Only the 4th one does the right thing.

### PR DESCRIPTION
**Pull request by curtisman**
submitAsync was implemented initially to allow larger message content payload to be uploaded/downloaded asynchronously from the op message itself.    Now that we have blob API, that should serve the same purpose.

The functionality isn't being used for a long time now, and shouldn't have back-compat concern.
Clean up most of the client code and also the server support.   Will clean up the IConnected.initialContents in the next PR once the server changes in this PR are committed.

Fix #2039

### CODE REVIEW

File: packages/drivers/iframe-driver/src/outerDocumentServiceFactory.ts [hunk 1]
```diff
@@ -208,7 +208,7 @@ export class DocumentServiceFactoryProxy implements IDocumentServiceFactoryProxy
             clientId: deltaStream.clientId,
             existing: deltaStream.existing,
             get initialClients() { return deltaStream.initialClients; },
-            get initialContents() { return deltaStream.initialContents; },
+            get initialContents() { return [] as IContentMessage[]; },
```
Comment (vladsud) [inline packages/drivers/iframe-driver/src/outerDocumentServiceFactory.ts:211]: Why not delete it from here?

File: packages/test/end-to-end-tests/src/test/compatUtils.ts [hunk 2]
```diff
@@ -186,17 +186,17 @@ export function createOldLoader(
 }
 
 export const createContainer = async (
-    loader: ILoader | old.ILoader,
```
Comment (vladsud) [inline packages/test/end-to-end-tests/src/test/compatUtils.ts:189]: FYI - Wes just merged that change, pull should resolve it to noop

**Review by vladsud — APPROVED** [review]

File: packages/drivers/iframe-driver/src/outerDocumentServiceFactory.ts (hunk 1 above)
Comment (curtisman) [reply packages/drivers/iframe-driver/src/outerDocumentServiceFactory.ts:211]: Because I need to build an updated server package and publish that first so the IConnected interface doesn't require initialContents

**Review by vladsud — APPROVED** [review]

**Review by tanviraumi — APPROVED** [review]
