### PR TITLE
Make isRootDataStore boolean and undefined

### LINKED ISSUE #9355: isRootDataStore in FluidDataStoreContext may not return correct value if getInitialSnapshotDetails isn't called
With the introduction of aliasing in data stores, the "rootiness" of a data store is not defined when its created but when it is aliased. Basically, a non-root data store can become root later on.
However, for compatibility, we need to support root data stores that are created via the old API where it is a "root" at creation time. This makes determining whether a data store is a root or not a little complicated because there are 2 ways for it to become root:
1. Based on the base snapshot from which a data store is loaded.
2. Based on the `isRootDataStore` flag updated via aliasing.

The following PR fixed a bug where this value would be incorrect - https://github.com/microsoft/FluidFramework/pull/9312. However, there is still a change where the value may be incorrect when `isRootDataStore` is read as mentioned here - https://github.com/microsoft/FluidFramework/pull/9338#discussion_r819708868. This needs to be fixed.

When aliasing is used everywhere, the determination of "rootiness" becomes simple - An aliased data store is a root data store and this can be done synchronously at the container runtime layer.

### PR DESCRIPTION
**Pull request by tyler-cai-microsoft**
Resolves #9355 

Prevent improper usage of `isRootDataStore` in children of  `FluidDataStoreContext`

### CODE REVIEW

File: packages/runtime/container-runtime/src/dataStoreContext.ts [hunk 1]
```diff
@@ -450,7 +454,8 @@ export abstract class FluidDataStoreContext extends TypedEventEmitter<IFluidData
 
         // Add data store's attributes to the summary.
         const { pkg } = await this.getInitialSnapshotDetails();
-        const attributes = createAttributes(pkg, this.isRootDataStore, this.disableIsolatedChannels);
+        const isRootOrAliasedDataStore = await this.isRoot();
```
Comment (vladsud) [inline packages/runtime/container-runtime/src/dataStoreContext.ts:457]: I'd use isRoot for name of variable here.
If you feel like some semantic is not clear due to name, then likely same applies to function name

File: packages/runtime/container-runtime/src/dataStoreContext.ts [hunk 2]
```diff
@@ -676,7 +681,9 @@ export abstract class FluidDataStoreContext extends TypedEventEmitter<IFluidData
      * This method should not be used outside of the aliasing context.
      * It will be removed, as the source of truth for this flag will be the aliasing blob.
      */
-    public abstract setRoot(): void;
+     public setRoot(): void {
```
Comment (vladsud) [inline packages/runtime/container-runtime/src/dataStoreContext.ts:684]: Is this API is called only as result of aliasing? If so, maybe we should rename it to reflect it.

File: packages/runtime/container-runtime/src/dataStoreContext.ts [hunk 3]
```diff
@@ -860,7 +858,7 @@ export class LocalFluidDataStoreContextBase extends FluidDataStoreContext {
         );
 
         this.snapshotTree = props.snapshotTree;
-        this.isRootDataStore = props.isRootDataStore ?? false;
+        this.isLocalRootDataStore = props.isRootDataStore;
```
Comment (vladsud) [inline packages/runtime/container-runtime/src/dataStoreContext.ts:861]: I do not know if it will work, but can we
- call this.setRoot() if props.isRootDataStore === true here.
- remove this.isLocalRootDataStore altogether, and all the code that deals with it
   - createAttributes() below to use this.isAliased() (unfortunately it cannot call this.isRoot() due to async nature)
- getInitialSnapshotDetails() always return isRootDataStore: false
    - I believe it should not matter, because only user of it is isRoot() function that will already OR it with value of this.isAliasedDataStore set above
- remove setRoot() overwrite - parent implementation is enough

File: packages/runtime/container-runtime/src/dataStoreContext.ts (hunk 2 above)
Comment (tyler-cai-microsoft) [reply packages/runtime/container-runtime/src/dataStoreContext.ts:684]: No, it's not

File: packages/runtime/container-runtime/src/dataStoreContext.ts (hunk 3 above)
Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/dataStoreContext.ts:861]: This seems like a good plan. Local data stores only care about the if its alias or not. If its created as root, we still call it an alias which isn't exactly true but its okay. Remote data stores care about both initial snapshot state and aliasing.

File: packages/runtime/container-runtime/src/dataStoreContext.ts (hunk 2 above)
Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/dataStoreContext.ts:684]: Where else is it used?

Comment (tyler-cai-microsoft) [reply packages/runtime/container-runtime/src/dataStoreContext.ts:684]: Based on the comment below, it should be used when a local datastore is created

File: packages/runtime/container-runtime/src/dataStoreContext.ts [hunk 4]
```diff
@@ -926,15 +924,18 @@ export class LocalFluidDataStoreContextBase extends FluidDataStoreContext {
                 // If there is no isRootDataStore in the attributes blob, set it to true. This ensures that data
                 // stores in older documents are not garbage collected incorrectly. This may lead to additional
                 // roots in the document but they won't break.
-                this.isRootDataStore = this.isRootDataStore || (attributes.isRootDataStore ?? true);
+                this.isLocalRootDataStore = this.isLocalRootDataStore ||
```
Comment (tyler-cai-microsoft) [inline packages/runtime/container-runtime/src/dataStoreContext.ts:927]: How should this be handled? I was thinking this.setRoot if attributes.isRootDataStore ?? true

File: packages/runtime/container-runtime/src/dataStoreContext.ts (hunk 2 above)
Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/dataStoreContext.ts:684]: Okay. I was looking at existing usages. You can still call this `setAliased` or something like that. Like I mentioned in my other comment, this isn't exactly true since being root doesn't mean its aliased but its okay because it makes the code simpler and easier to reason about.

Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/dataStoreContext.ts:684]: The problem is there are 3 states that need to be handled:
1. root during creation.
2. Aliased.
3. root in initial snapshot.
For simplicity, we can combine 1 and 2. Also, local data stores only care about 1 and 2.
Alternatively, all 3 states can be tracked. Local data stores look at 1 and 2. Remote data stores look at all 3.

File: packages/runtime/container-runtime/src/dataStoreContext.ts (hunk 4 above)
Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/dataStoreContext.ts:927]: We should not be setting any state here. We should only be reading it. For local data stores, the state should be set during data store creation or when it is aliased and isRoot is called.

Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/dataStoreContext.ts:927]: Actually, that may not be true. Let me take a look at the code closely.

Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/dataStoreContext.ts:927]: Okay, so this has to go back to how it originally was. Basically if the root (or alias) state is already true, then use it, else use from attributes:
`this.isRootDataStore = this.isRootDataStore || (attributes.isRootDataStore ?? true);`

Comment (tyler-cai-microsoft) [reply packages/runtime/container-runtime/src/dataStoreContext.ts:927]: Ok, because I wanted to make the `this.isRootDataStore` variable private and thus not accessible to the child, in this case the `LocalFluidDataStoreContextBase`, I'll do something like `if(this.isAliased || (attributes.isRootDataStore ?? true)) this.setRoot/setAliased`.

Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/dataStoreContext.ts:927]: Sounds good. Although if its already aliased, you don't need to set it as root or aliased again.

File: packages/runtime/container-runtime/src/dataStoreContext.ts (hunk 1 above)
Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/dataStoreContext.ts:457]: Not sure if you are planning to address this or not but there are some inconsistencies in naming:
This variable for instance should be called isRootDataStore or the function it gets the value from should be called isRootOrAlias.
Similarly, setRoot sets isAliasedDataStore. Either the function should be called setAliasDataStore or the member should be called isRootDataStore (or isRootOrAlias).

**Review by agarwal-navin — APPROVED** [review]
