### PR TITLE
Emit dispose event on sub directory deletion

### LINKED ISSUE #9435: Add dispose event on deleted sub-directories in shared directory.
## Describe the bug
Add dispose event on deleted sub-directories in shared directory.

### PR DESCRIPTION
**Pull request by jatgarg**
Fixes: https://github.com/microsoft/FluidFramework/issues/9435
1.) Emit dispose event on sub directory which is deleted.
2.) Throw error on any access to disposed sub directory.

### CODE REVIEW

File: packages/dds/map/src/directory.ts [hunk 1]
```diff
@@ -1475,8 +1522,13 @@ class SubDirectory extends TypedEventEmitter<IDirectoryEvents> implements IDirec
      * @param op - The message if from a remote delete, or null if from a local delete
      */
     private deleteSubDirectoryCore(subdirName: string, local: boolean) {
+        const previousValue = this.getSubDirectory(subdirName);
         // This should make the subdirectory structure unreachable so it can be GC'd and won't appear in snapshots
         // Might want to consider cleaning out the structure more exhaustively though?
-        return this._subdirectories.delete(subdirName);
+        const successfullyRemoved = this._subdirectories.delete(subdirName);
+        if (previousValue !== undefined) {
+            (previousValue as SubDirectory).emit("dispose", local, previousValue);
```
Comment (vladsud) [inline packages/dds/map/src/directory.ts:1530]: This is not great pattern to raise events on other objects. It's implicit flow that is hard to track.
I'd suggest to add methods on internal interfaces and calling these methods instead.

**Comment by vladsud** [comment]
This is change in behavior, so breaking.md note is due.

**Comment by vladsud** [comment]
Also, this event needs to be recursively delivered to whole tree of sub-directories.

File: packages/dds/map/src/directory.ts (hunk 1 above)
Comment (jatgarg) [reply packages/dds/map/src/directory.ts]: Made changes.

**Comment by jatgarg** [comment]
> Also, this event needs to be recursively delivered to whole tree of sub-directories.

Add new issue for that.

File: packages/dds/map/src/test/directory.spec.ts [hunk 2]
```diff
@@ -136,6 +137,16 @@ describe("Directory", () => {
                 assert.equal(valueChangedExpected, false, "missing valueChangedExpected event");
                 assert.equal(containedValueChangedExpected, false, "missing containedValueChanged event");
 
+                // Test dispose on subdirectory delete
```
Comment (vladsud) [inline packages/dds/map/src/test/directory.spec.ts:140]: It would be great to add steps in this test that would (at the end of current test)
- create sub-directory with same name 
- Validate that newly created object works and one can set / reset keys on it and it's not disposed
- The old in-memory object stays disposed, and accessing any key on it throws exception

File: api-report/map.api.md [hunk 3]
```diff
@@ -65,6 +67,8 @@ export interface IDirectoryDataObject {
 export interface IDirectoryEvents extends IEvent {
     // (undocumented)
     (event: "containedValueChanged", listener: (changed: IValueChanged, local: boolean, target: IEventThisPlaceHolder) => void): any;
+    // (undocumented)
+    (event: "dispose", listener: (target: IEventThisPlaceHolder) => void): any;
```
Comment (vladsud) [inline api-report/map.api.md:71]: Is it dispose or disposed? Do we have interface that we can inherit to get proper signature, instead of defining it everywhere?

File: packages/dds/map/src/directory.ts [hunk 4]
```diff
@@ -338,6 +338,8 @@ export class DirectoryFactory {
  * @sealed
  */
 export class SharedDirectory extends SharedObject<ISharedDirectoryEvents> implements ISharedDirectory {
```
Comment (vladsud) [inline packages/dds/map/src/directory.ts:340]: Are we adding IDisposed somewhere to make sure compiler helps us ensure signatures are correct?

File: packages/dds/map/src/directory.ts [hunk 5]
```diff
@@ -338,6 +338,8 @@ export class DirectoryFactory {
...
+    private _dispose = false;
```
Comment (vladsud) [inline packages/dds/map/src/directory.ts:341]: Should handling of disposed be delegated fully to this.root? Otherwise it's half baked system - we set boolean on this object, but never check for it, which will be source of bugs...

File: packages/dds/map/src/interfaces.ts [hunk 6]
```diff
@@ -48,6 +48,16 @@ export interface IDirectory extends Map<string, any>, IEventProvider<IDirectoryE
      */
     set<T = any>(key: string, value: T): this;
 
+    /**
+     * Dispose the directory when it is deleted. 
+     */
+    dispose(): void;
```
Comment (heliocliu) [inline packages/dds/map/src/interfaces.ts:54]: there's the `IDisposable` interface that this should probably implement instead

**Review by heliocliu — DISMISSED** [review]
Blocking because this looks to contain breaking changes. Please rebase this against and merge into the `next` branch instead.

**Comment by vladsud** [comment]
@heliocliu, just want to check - I assume that there should be no need to block PRs like that - they simply should fail the build. Is it correct?

**Comment by heliocliu** [comment]
> @heliocliu, just want to check - I assume that there should be no need to block PRs like that - they simply should fail the build. Is it correct?

Not quite yet but that will be happening soon.  I wanted to block the existing PRs so things don't accidentally slip through in the meantime.

File: packages/dds/map/src/directory.ts (hunk 5 above)
Comment (jatgarg) [reply packages/dds/map/src/directory.ts]: Can you please explain what  do you mean by it? How will the root handle the dispose?

File: packages/dds/map/src/directory.ts (hunk 4 above)
Comment (jatgarg) [reply packages/dds/map/src/directory.ts]: Added to implement IDisposable interface.

**Comment by heliocliu** [comment]
> BTW, I'm not sure it contains breaking changes. In a sense that I think behavior was undefined for operations on deleted sub-directory object. It would be great to confirm what actually happened when (on local and remote machines) when operations were performed on such objects. If it was failing in some form, then it's a plus to not being afraid to change such behavior without impacting compatibility concerns.

This is considered breaking because the addition of the required `dispose` api is not forward compatible.  It may be that in practice this won't matter because of how it's used, and if you or Jatin think this is the case I'm fine with unblocking the PR.  But as this gets more automated I think there will be less room for these sorts of "exceptions" to exist even if they are not truly breaking.

**Comment by vladsud** [comment]
Addition of a method on existing object is definitely minor change, not major. And I believe we require only major changes to go to vNext.
Addition of a method on interface could be considered breaking, as some alternative implementation of this interface can exists outside of our repo. In practice, I think we can ignore / make exception to it.

File: BREAKING.md [hunk 7]
```diff
@@ -47,6 +47,7 @@ sometimes followed by a colon and an inner error message when applicable.
 - [Removing snapshot API from IRuntime](#Removing-snapshot-api-from-IRuntime)
 - [Remove Unused IFluidObject Augmentations](#Remove-Unused-IFluidObject-Augmentations)
 - [Duplicate extractLogSafeErrorProperties removed](#duplicate-extractlogsafeerrorproperties-removed)
+- [Disallowed access to deleted sub directory](#Disallowed-access-to-deleted-sub-directory)
```
Comment (heliocliu) [inline BREAKING.md:50]: move this out of 0.57 as relevant

**Review by heliocliu — COMMENTED** [review]
unblocking

File: packages/dds/map/src/test/directory.spec.ts (hunk 2 above)
Comment (jatgarg) [reply packages/dds/map/src/test/directory.spec.ts:140]: Can not add this scenario to test currently as with current implementation we return the same object on directory creation with same name. So previous one will not be disposed. This PR just add dispose event on explicitly deleting the directory.

File: api-report/map.api.md (hunk 3 above)
Comment (jatgarg) [reply api-report/map.api.md]: Changed to disposed and made the directory implement IDisposable interface.

File: packages/dds/map/src/directory.ts (hunk 5 above)
Comment (jatgarg) [reply packages/dds/map/src/directory.ts]: Deleted this from here and delegated to root.

File: BREAKING.md [hunk 8]
```diff
@@ -36,6 +37,10 @@ Previously, the fluidErrorCode value (a pascaleCased term) was often used as the
 Now all error messages can be expected to be easily-read sentences,
 sometimes followed by a colon and an inner error message when applicable.
 
+
+### Disallowed access to deleted sub directory
+Users will now be disallowed to do operations on a deleted directory. Users can subscribe to `dispose` event to know if a sub directory is deleted.
```
Comment (vladsud) [inline BREAKING.md:42]: might be worth to clarify what "disallow" actually means in practice

File: api-report/map.api.md [hunk 9]
```diff
@@ -65,6 +66,8 @@ export interface IDirectoryDataObject {
 export interface IDirectoryEvents extends IEvent {
     // (undocumented)
     (event: "containedValueChanged", listener: (changed: IValueChanged, local: boolean, target: IEventThisPlaceHolder) => void): any;
+    // (undocumented)
+    (event: "disposed", listener: (target: IEventThisPlaceHolder, error?: Error) => void): any;
```
Comment (vladsud) [inline api-report/map.api.md:70]: Fo we ever have an error object here? If not, feels like argument should not be here.

File: packages/dds/map/src/directory.ts [hunk 10]
```diff
@@ -1475,8 +1534,11 @@ class SubDirectory extends TypedEventEmitter<IDirectoryEvents> implements IDirec
      * @param op - The message if from a remote delete, or null if from a local delete
      */
     private deleteSubDirectoryCore(subdirName: string, local: boolean) {
+        const previousValue = this.getSubDirectory(subdirName);
         // This should make the subdirectory structure unreachable so it can be GC'd and won't appear in snapshots
         // Might want to consider cleaning out the structure more exhaustively though?
-        return this._subdirectories.delete(subdirName);
+        const successfullyRemoved = this._subdirectories.delete(subdirName);
+        (previousValue as SubDirectory)?.dispose();
```
Comment (vladsud) [inline packages/dds/map/src/directory.ts:1541]: This cast likely points to some problem. Is it that IDirectory should derive from IDisposed?

File: packages/dds/map/src/test/directory.spec.ts (hunk 2 above)
Comment (vladsud) [reply packages/dds/map/src/test/directory.spec.ts:140]: I think this is a bug. Once sub-directory is disposed, it should not be accessible from directory itself - it should be gone completely, and garbage-collected once users stop referencing it.

File: api-report/map.api.md (hunk 9 above)
Comment (jatgarg) [reply api-report/map.api.md]: not used today but left for future. Removing it for now as could be added later as it is not getting used currently.

File: packages/dds/map/src/test/directory.spec.ts (hunk 2 above)
Comment (jatgarg) [reply packages/dds/map/src/test/directory.spec.ts:162]: Sorry I got the test wrong what you were saying. added the mentioned suggested test.

File: BREAKING.md (hunk 8 above)
Comment (jatgarg) [reply BREAKING.md]: fixed.

File: packages/dds/map/src/test/directory.spec.ts [hunk 11]
```diff
@@ -142,6 +143,51 @@ describe("Directory", () => {
...
+
+                // Usage Error on accessing disposed directory.
+                let usageErrorExpected = true;
+                try {
+                    subDirectory.set("throw", "error");
+                } catch (error) {
+                    assert.strictEqual(error.errorType, "usageError", "Should throw usage error");
+                    usageErrorExpected = false;
+                }
+                assert(usageErrorExpected === false, "Should throw usage error");
```
Comment (vladsud) [inline packages/dds/map/src/test/directory.spec.ts:188]: You can get rid of usageErrorExpected altogether by addign assert(false) after line 183

**Comment by vladsud** [comment]
LGTM, but I want to see either an issue or a fix for recursive part of this story.

**Review by vladsud — APPROVED** [review]

**Comment by jatgarg** [comment]
> LGTM, but I want to see either an issue or a fix for recursive part of this story.

I already have an issue for the same:
https://github.com/microsoft/FluidFramework/issues/9106
