### PR TITLE
Fix for wip used routes set during summarize before GC is run

### LINKED ISSUE #4750: Fix wip used routes are set during summarize before GC is run
wipSerializedUsedRoutes are set in startSummary which is called before GC is run. This means that reference used routes will be incorrectly updated to the previous used routes.

### PR DESCRIPTION
**Pull request by agarwal-navin**
Fixes #4750.

- wip used routes was set in `startSummary` which is called before GC is run. So, the wip used routes was using old value of used routes from the previous GC run. It is now set in `updateUsedRoutes` which is always called before summarize.
- Changed the flag in `IContainerRuntimeOptions` that can be used to disable GC to leave it enabled by default.
- Added state in `SummarizeNodeWithGC` to know when GC is disabled so that it doesn't track GC state during summary. Some of the state was inconsistent earlier when GC was disabled.
- Added checks in `SummarizerNodeWithGC` to ensure that GC is run and used routes are set before summarize is called.

### CODE REVIEW

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 1]
```diff
@@ -217,8 +217,8 @@ export interface IContainerRuntimeOptions {
     // Delay before first attempt to spawn summarizing container
     initialSummarizerDelayMs?: number;
 
-    // Flag that enables running garbage collection to delete unused Fluid objects.
-    runGC?: boolean;
+    // Flag that will disable garbage collection if set to true.
+    disableGC?: true;
```
Comment (arinwt) [inline packages/runtime/container-runtime/src/containerRuntime.ts:221]: Is the typing intentionally `true` only here?  Right now the only values allowed are `undefined` (or leaving unset since option) or `true`. I think it will prevent passing false.

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 2]
```diff
@@ -1372,11 +1371,15 @@ export class ContainerRuntime extends TypedEventEmitter<IContainerRuntimeEvents>
...
 
-            if (this.runtimeOptions.runGC) {
+            if (!this.runtimeOptions.disableGC) {
                 // Get the container's GC data and run GC on the reference graph in it.
                 const gcData = await this.dataStores.getGCData();
                 const { referencedNodeIds } = runGarbageCollection(gcData.gcNodes, [ "/" ], this.logger);
 
+                // Update our summarizer node's used routes. Updating used routes in summarizer node before summarizing
+                // is required and asserted by the the summarizer node.
+                this.summarizerNode.updateUsedRoutes([""]);
```
Comment (arinwt) [inline packages/runtime/container-runtime/src/containerRuntime.ts:1381]: Just to clarify, this is [""] because the root is always referenced?

File: packages/runtime/runtime-utils/src/summarizerNode/summarizerNodeWithGc.ts [hunk 3]
```diff
@@ -100,6 +103,10 @@ export class SummarizerNodeWithGC extends SummarizerNode implements IRootSummari
             wipSummaryLogger,
         );
 
+        if (config.gcDisabled === true) {
+            this.gcDisabled = true;
+        }
```
Comment (arinwt) [inline packages/runtime/runtime-utils/src/summarizerNode/summarizerNodeWithGc.ts:108]:
```suggestion
        this.gcDisabled = config.gcDisabled;
```
Is this not equivalent since they are both `true | undefined` and it is readonly?

**Review by arinwt — APPROVED** [review]
Looks good! The only thing I thought was a little odd was the `gcDisabled` adding a little bit of overhead, but I guess being undefined 90% of the time saves some memory?
I didn't look too closely at the back-compat part.

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 1 above)
Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/containerRuntime.ts:221]: It is intentional. The idea is to set this flag only when you want to disable GC. Otherwise, don't pass it or leave it undefined. Do you think we should false as an option here?
Also, with the naming, it makes more sense to only have true as a value. disableGC: false is a double negation which seems unnecessary :-).

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 2 above)
Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/containerRuntime.ts:1381]: Yes, that's correct.

Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/containerRuntime.ts:1381]: I will add this to the comment there.

File: packages/runtime/runtime-utils/src/summarizerNode/summarizerNodeWithGc.ts (hunk 3 above)
Comment (agarwal-navin) [reply packages/runtime/runtime-utils/src/summarizerNode/summarizerNodeWithGc.ts:108]: Yes, it is. The only advantage we get out of the check first is that if its not there, the property is not set at all (even to undefined).

**Comment by agarwal-navin** [comment]
> Looks good! The only thing I thought was a little odd was the `gcDisabled` adding a little bit of overhead, but I guess being undefined 90% of the time saves some memory?
> I didn't look too closely at the back-compat part.

Yes, it will be undefined most of the times except if things go wrong and someone disables GC. It does add a little overhead but its temporary and is there as long as we have a switch to disable GC. Without this flag, its very hard to maintain the consistency of GC state in the summarizer node. Also, we cannot assert that GC is called before summarize if we don't have this.
For example, when summarize is called, we cannot assert that `wipSerializedUsedRoutes` is set if we don't know whether GC is disabled or not.

File: packages/runtime/runtime-utils/src/summarizerNode/summarizerNodeWithGc.ts (hunk 3 above)
Comment (agarwal-navin) [reply packages/runtime/runtime-utils/src/summarizerNode/summarizerNodeWithGc.ts:108]: Now that I am thinking about this, boolean makes the code clearer and more readable.

Comment (agarwal-navin) [reply packages/runtime/runtime-utils/src/summarizerNode/summarizerNodeWithGc.ts]: Changed to boolean.

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 1 above)
Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/containerRuntime.ts]: Changed to boolean for clarity and readability.

Comment (arinwt) [reply packages/runtime/container-runtime/src/containerRuntime.ts]: I think either way is fine, it's just some of the other code written around the typing seemed verbose.

**Comment by arinwt** [comment]
I think if you want to keep it `true | undefined`, you could add a simple getter somewhere that just does the trivial `=== undefined` to return a boolean.
