### PR TITLE
Summarization telemetry improvements

### LINKED ISSUE #6649: Improve summary failure logging
Based on https://github.com/microsoft/FluidFramework/issues/6555.
Feel free to break it into smaller issues, we could also distribute it across more people.

Here are key observations (crossed out are things I believe I addressed):
1. We should be consistent in how we log failure. There is SummaryAckWaitTimeout, SummaryOp, but there is no Nack event any more. We should either log all of them, or remove all of the and propagate relevant info into the rest of the flow (i.e. Summarize_[end|cancel] events).
   - I'm not sure there is a value in SummaryOp, and in tracking `submitOpDuration` on GenerateSummary event - the former tracks overall latency of connection, and later - latency of calling couple APIs?
2. It's very hard to say how many nacks are there. One can aggregate error property from fluid:telemetry:Summarizer:Running:Summarize_cancel and guess which ones are coming from ordering service ("Failed to summarize the document") and which are not ("disconnecte", "Error 404").
3. ~fluid:telemetry:Summarizer:Running:Summarize_cancel should have category = "error", not generic.~
4. ~There are fluid:telemetry:Summarizer:Running:Summarize_cancel events with empty error field. It's hard to say what these errors represent - would be great to figure out why that happens and how to address it.~
5. fluid:telemetry:Summarizer:Running:GenerateSummary is logging both failures and successes. Looking at stats, I believe we can drop this event on failure path, as fluid:telemetry:Summarizer:Running:Summarize_cancel duplicates it, though it does not log same data. Maybe it should be dropped altogether if Summarize_end & Summarize_cancel could convey same info? Not sure, need to look at how we report durations for various phases of summarization process.
   - Should we use exceptions for error paths (including expected errors)?
6. `timeWaiting` property is not very telling. I think it should be called `duration` on SummaryOp, and ackWaitDuration on  Summarize_end event.

Here are examples of payloads (relevant bits mostly, I removed some):

**GenerateSummary:**
"refSequenceNumber":"70418",
"opsSinceLastAttempt":"267",
"opsSinceLastSummary":"267",
"generateDuration":"3.9183210134506226",
"submitOpDuration":"0.06549999117851257",
"uploadDuration":"1097.4087789952755",

**Summarize_end**
"duration":"3775",
"sequenceNumber":"65519",
"summarySequenceNumber":"65518",
"reason":"maxTime",
"timeWaiting":"1475",
"timeSinceLastAttempt":"60639",
"timeSinceLastSummary":"60639",
"message":"summaryAck",

**Summarize_cancel**
"duration":"383",
"dmInitialSeqNumber":"45499",
"dmLastMsqSeqTimestamp":"1625638803886",
"dmLastKnownSeqNumber":"53696",
"dmLastMsqSeqClientId":"5a41c6c1-144a-43fd-a2dd-bdcba64c8d13",
"dmLastMsqSeqNumber":"53696",
"reason":"retry2",
"timeSinceLastAttempt":"120001",
"timeSinceLastSummary":"216331",
"error":"disconnected",
"message":"generateSummaryFailure",

**SummaryOp**
"summarySequenceNumber":"80051",
"refSequenceNumber":"80047",
"timeWaiting":"75",

### PR DESCRIPTION
**Pull request by pleath**
Implement logging improvements described in https://github.com/microsoft/FluidFramework/issues/6649.

### CODE REVIEW

**Comment by fluidgit** [comment]
<details><summary><b><span style="color: green">■</span> @fluidframework/base-host:</b> No change</summary><table><tr><th>Metric Name</th><th>Baseline Size</th><th>Compare Size</th><th>Size Diff</th></tr><tr>
    <td>main.js</td>
    <td>185.72 KB</td>
    <td>185.72 KB</td>
    <td><span style="color: green">■</span> No change</td>
  </tr><tr>
    <td>Total Size</td>
    <td>213.31 KB</td>
    <td>213.31 KB</td>
    <td><span style="color: green">■</span> No change</td>
  </tr></table></details><details><summary><b><span style="color: coral">⯅</span> @fluid-example/bundle-size-tests:</b> +32 Bytes</summary><table><tr><th>Metric Name</th><th>Baseline Size</th><th>Compare Size</th><th>Size Diff</th></tr><tr>
    <td>container.js</td>
    <td>163 KB</td>
    <td>163.03 KB</td>
    <td><span style="color: coral">⯅</span> +32 Bytes</td>
  </tr><tr>
    <td>map.js</td>
    <td>44.71 KB</td>
    <td>44.71 KB</td>
    <td><span style="color: green">■</span> No change</td>
  </tr><tr>
    <td>matrix.js</td>
    <td>143.51 KB</td>
    <td>143.51 KB</td>
    <td><span style="color: green">■</span> No change</td>
  </tr><tr>
    <td>odspDriver.js</td>
    <td>173.42 KB</td>
    <td>173.42 KB</td>
    <td><span style="color: green">■</span> No change</td>
  </tr><tr>
    <td>odspPrefetchSnapshot.js</td>
    <td>38.7 KB</td>
    <td>38.7 KB</td>
    <td><span style="color: green">■</span> No change</td>
  </tr><tr>
    <td>sharedString.js</td>
    <td>165.09 KB</td>
    <td>165.09 KB</td>
    <td><span style="color: green">■</span> No change</td>
  </tr><tr>
    <td>Total Size</td>
    <td>761.11 KB</td>
    <td>761.14 KB</td>
    <td><span style="color: coral">⯅</span> +32 Bytes</td>
  </tr></table></details><hr><p>Baseline commit: 92372ffdc273128113612545b3e0f99bbd266aee</p>
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0ec0d4e588502204d4c3053182c3a0b0d53d061d
</p>

File: packages/runtime/container-runtime/src/summaryGenerator.ts [hunk 1]
```diff
@@ -272,14 +272,16 @@ export class SummaryGenerator {
...
                     }
                 }
             }
 
-            logger.sendTelemetryEvent({ eventName: "GenerateSummary", ...generateTelemetryProps });
-            if (summaryData.stage !== "submit") {
+            if (summaryData.stage === "submit") {
+                logger.sendTelemetryEvent({ eventName: "GenerateSummary", ...generateTelemetryProps });
+            }
+            else {
```
Comment (andre4i) [inline packages/runtime/container-runtime/src/summaryGenerator.ts:283]: #nit This formatting is kind of inconsistent. What do you think about `} else {` ?

File: packages/runtime/container-runtime/src/summaryGenerator.ts [hunk 2]
```diff
@@ -272,14 +272,16 @@ export class SummaryGenerator {
...
+                // Log event here on summary success only, as Summarize_cancel duplicates failure logging.
```
Comment (andre4i) [inline packages/runtime/container-runtime/src/summaryGenerator.ts:284]: I'm confused about this comment. Is it referring to the next line? It doesn't seem to be logging an event (except maybe as a side effect).

**Comment by pleath** [comment]
Yeah, you’re right, the comment really belongs before the if.

— Paul
________________________________

**Comment by pleath** [comment]
No problem.

— Paul
________________________________

**Review by andre4i — APPROVED** [review]

File: packages/runtime/container-runtime/src/summaryGenerator.ts [hunk 3]
```diff
@@ -354,6 +354,7 @@ export class SummaryGenerator {
                 const retryAfterSeconds = summaryNack?.retryAfter;
 
                 const error = new LoggingError(`summaryNack: ${message}`, { retryAfterSeconds });
+                logger.sendTelemetryEvent({ eventName: "SummaryNack", ...generateTelemetryProps }, error);
```
Comment (vladsud) [inline packages/runtime/container-runtime/src/summaryGenerator.ts:357]: I do not think retryAfter[Seconds] is part of generateTelemetryProps, so it would be useful to add it to telemetry event.

**Review by vladsud — APPROVED** [review]
