### PR TITLE
Enable strictNullCheck for the map package (and fixes)

### LINKED ISSUE #4761: Enable strictNullCheck for map package.

### PR DESCRIPTION
**Pull request by curtisman**
Fix #4761 
Also
- Fix a bug in the dds-interceptor where getWorkingDirectory of a non-existent subdirectory throw instead of returning undefined. Test added.
- Add missing `clear` event signature for directory and map. (Related to #4594)
- Directory events are missing the "target" argument returning `this`
- Map events `target` should be the map itself, instead of the `MapKernel`
- Expanded local action events testing for map and dictionary

### CODE REVIEW

File: packages/dds/map/src/interfaces.ts [hunk 1]
```diff
@@ -234,8 +239,13 @@ export interface ISharedMapEvents extends ISharedObjectEvents {
     (event: "valueChanged", listener: (
         changed: IDirectoryValueChanged,
         local: boolean,
-        op: ISequencedDocumentMessage,
+        op: ISequencedDocumentMessage | null,
         target: IEventThisPlaceHolder) => void);
+    (event: "clear", listener: (
+        local: boolean,
+        op: ISequencedDocumentMessage | null,
+        target: IEventThisPlaceHolder
```
Comment (ChumpChief) [inline packages/dds/map/src/interfaces.ts:247]: Do we need the target arg?  Would probably prefer to omit unless we need it, to keep the signature simpler.  Both here and for other events.

File: packages/dds/map/src/directory.ts [hunk 2]
```diff
@@ -649,7 +650,10 @@ export class SharedDirectory extends SharedObject<ISharedDirectoryEvents> implem
     protected reSubmitCore(content: any, localOpMetadata: unknown) {
         const message = content as IDirectoryOperation;
         const handler = this.messageHandlers.get(message.type);
-        handler.submit(message, localOpMetadata);
+
+        // eslint-disable-next-line max-len
+        // eslint-disable-next-line @typescript-eslint/no-non-null-assertion, @typescript-eslint/no-unnecessary-type-assertion
+        handler!.submit(message, localOpMetadata);
```
Comment (ChumpChief) [inline packages/dds/map/src/directory.ts:656]: Would be nice to assert here rather than just a non-null assertion so that if we try the value type removal (thereby removing "act" type) then we can get a more descriptive error.
```typescript
assert(handler !== undefined, `Missing message handler for message type: ${message.type}`);
```

File: packages/dds/map/src/directory.ts [hunk 3]
```diff
@@ -739,7 +744,8 @@ export class SharedDirectory extends SharedObject<ISharedDirectoryEvents> implem
         if (message.type === MessageType.Operation) {
             const op: IDirectoryOperation = message.contents as IDirectoryOperation;
             if (this.messageHandlers.has(op.type)) {
```
Comment (ChumpChief) [inline packages/dds/map/src/directory.ts:746]: Similar here would be reasonable to switch to an assert

File: packages/dds/map/src/directory.ts [hunk 4]
```diff
@@ -980,21 +986,18 @@ class SubDirectory extends TypedEventEmitter<IDirectoryEvents> implements IDirec
...
-        return this._storage.get(key).value as T;
+    public get<T = any>(key: string): T | undefined {
+        return this._storage.get(key)?.value as T | undefined;
     }
 
     /**
      * {@inheritDoc IDirectory.wait}
      */
-    public async wait<T = any>(key: string): Promise<T> {
+    public async wait<T = any>(key: string): Promise<T | undefined> {
```
Comment (ChumpChief) [inline packages/dds/map/src/directory.ts:996]: This should only be `T` right?  Since the promise just won't resolve if the key isn't set.

File: packages/dds/map/src/interfaces.ts (hunk 1 above)
Comment (curtisman) [reply packages/dds/map/src/interfaces.ts:247]: This was added explicitly in 2019 in this [commit](https://github.com/microsoft/FluidFramework/commit/c7d52fc091981449fd4e1c1c404c2d1cdeb69dee) 
@anthony-murphy raise the original issue (back in the old github repo)

File: packages/dds/map/src/directory.ts (hunk 4 above)
Comment (curtisman) [reply packages/dds/map/src/directory.ts:996]: Yeah... I was debating in my head, since we are wait is listening on `valueChanged` and the `delete` action would also cause it.  But send we already check if doesn't exist up front, then only a `set` action would cause the `valueChanged`, and that means that we should just follow the user's type assertion here.  I will change.

File: packages/dds/map/src/directory.ts (hunk 3 above)
Comment (curtisman) [reply packages/dds/map/src/directory.ts]: done

File: packages/dds/map/src/directory.ts (hunk 2 above)
Comment (curtisman) [reply packages/dds/map/src/directory.ts]: done

File: packages/dds/map/src/interfaces.ts (hunk 1 above)
Comment (curtisman) [reply packages/dds/map/src/interfaces.ts:247]: The gist of the it is that without it, it will be difficult to create a generic event handler (e.g. without closure at the time of listener registration)

File: examples/data-objects/multiview/constellation-model/src/model.ts [hunk 5]
```diff
@@ -57,12 +57,14 @@ export class Constellation extends DataObject implements IConstellation {
     }
 
     private async updateStarsFromRoot() {
-        const starHandles = this.root.get<IFluidHandle<ICoordinate>[]>(starListKey);
+        // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
+        const starHandles = this.root.get<IFluidHandle<ICoordinate>[]>(starListKey)!;
```
Comment (tylerbutler) [inline examples/data-objects/multiview/constellation-model/src/model.ts:61]: Naive question: is this safe? Do we have some guarantees in the framework that this won't be null?

File: packages/dds/map/src/directory.ts [hunk 6]
```diff
@@ -1563,14 +1571,14 @@ class SubDirectory extends TypedEventEmitter<IDirectoryEvents> implements IDirec
...
      * @returns True if the key existed and was deleted, false if it did not exist
      */
-    private deleteCore(key: string, local: boolean, op: ISequencedDocumentMessage) {
+    private deleteCore(key: string, local: boolean, op: ISequencedDocumentMessage | null) {
         const previousValue = this.get(key);
         const successfullyRemoved = this._storage.delete(key);
         if (successfullyRemoved) {
             const event: IDirectoryValueChanged = { key, path: this.absolutePath, previousValue };
-            this.directory.emit("valueChanged", event, local, op);
+            this.directory.emit("valueChanged", event, local, op, this.directory);
```
Comment (tylerbutler) [inline packages/dds/map/src/directory.ts:1579]: ❤️

File: packages/dds/map/src/interfaces.ts (hunk 1 above)
Comment (tylerbutler) [reply packages/dds/map/src/interfaces.ts:247]: Nit: May be worth a comment in the code.

File: packages/dds/map/src/localValues.ts [hunk 7]
```diff
@@ -179,25 +179,32 @@ export class LocalValueMaker {
...
-            if (serializable.type === ValueType[ValueType.Shared]) {
-                serializable.type = ValueType[ValueType.Plain];
-                const handle: ISerializedHandle = {
-                    type: "__fluid_handle__",
-                    url: serializable.value as string,
-                };
-                serializable.value = handle;
-            }
+    public fromSerializable(serializable: ISerializableValue): ILocalValue {
+        // Migrate from old shared value to handles
```
Comment (tylerbutler) [inline packages/dds/map/src/localValues.ts:184]: Is this for backcompat?

File: packages/dds/map/src/test/directory.spec.ts [hunk 8]
```diff
@@ -80,16 +80,68 @@ describe("Directory", () => {
...
+                    assert.equal(target, directory, "target should be the directory for clear event");
+                });
+                directory.on("error", (error) => {
+                    // propagate error in the event handlers
+                    throw error;
+                });
+
+                // Test set
+                previousValue = undefined;
                 directory.set("dwyane", "johnson");
```
Comment (tylerbutler) [inline packages/dds/map/src/test/directory.spec.ts:89]: Nit: Dwayne is misspelled.

File: packages/dds/matrix/test/matrix.stress.spec.ts [hunk 9]
```diff
@@ -266,7 +266,7 @@ describe("Matrix", () => {
             it(`Stress (numClients=${numClients} numOps=${numOps} syncProbability=${syncProbability} disconnectProbability=${disconnectProbability} seed=0x${seed.toString(16).padStart(8, "0")})`,
                 // Note: Must use 'function' rather than arrow '() => { .. }' in order to set 'this.timeout(..)'
                 async function () {
-                    this.timeout(10000);
+                    this.timeout(15000);
```
Comment (tylerbutler) [inline packages/dds/matrix/test/matrix.stress.spec.ts:269]: Why the increase?

**Review by tylerbutler — APPROVED** [review]

File: packages/dds/map/src/directory.ts [hunk 10]
```diff
@@ -682,7 +684,8 @@ export class SharedDirectory extends SharedObject<ISharedDirectoryEvents> implem
         const stack: [SubDirectory, IDirectoryDataObject][] = [];
         stack.push([this.root, data]);
         while (stack.length > 0) {
-            const [currentSubDir, currentSubDirObject] = stack.pop();
+            // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
+            const [currentSubDir, currentSubDirObject] = stack.pop()!;
```
Comment (agarwal-navin) [inline packages/dds/map/src/directory.ts:688]: This is a generic question - Is it better to have no-null-assertion or explicitly assert that the value is not null? Whenever I have to add an eslint warning, I kind of assume that it may not be the right way to do it.

File: examples/data-objects/multiview/constellation-model/src/model.ts (hunk 5 above)
Comment (curtisman) [reply examples/data-objects/multiview/constellation-model/src/model.ts:61]: nope. non-null is a type assertion (it remove both undefined and null from the type)  It is same as `as`, which doesn't have any runtime code.

File: packages/dds/matrix/test/matrix.stress.spec.ts (hunk 9 above)
Comment (curtisman) [reply packages/dds/matrix/test/matrix.stress.spec.ts:269]: it took longer on different machine (and parallelism)

File: packages/dds/map/src/directory.ts (hunk 10 above)
Comment (curtisman) [reply packages/dds/map/src/directory.ts:688]: explicitly assert has runtime impact. in this case, we have check stack.length > 0, so pop can't be undefined. 
So a type assertion is fine in this case, because it is working around the limitation of the lint rule.

File: packages/dds/map/src/localValues.ts (hunk 7 above)
Comment (curtisman) [reply packages/dds/map/src/localValues.ts:184]: looks like it.    Conversion to handles from older format.

File: packages/dds/map/src/interfaces.ts (hunk 1 above)
Comment (curtisman) [reply packages/dds/map/src/interfaces.ts:247]: I think this is more a general api design guideline.  Would be pretty tedious to put that on all event handers declaration?

File: packages/dds/map/src/test/directory.spec.ts (hunk 8 above)
Comment (curtisman) [reply packages/dds/map/src/test/directory.spec.ts:89]: fixed.

File: packages/dds/map/src/directory.ts (hunk 10 above)
Comment (tylerbutler) [reply packages/dds/map/src/directory.ts:688]: This is why I love code review; I always learn!

File: packages/dds/map/src/interfaces.ts (hunk 1 above)
Comment (tylerbutler) [reply packages/dds/map/src/interfaces.ts:247]: Ahh, I see. Agreed, a comment is the wrong place for such a note.

**Comment by curtisman** [comment]
Related to #2358
