### PR TITLE
GC back compat - Add flag in summary to allow/disallow

### LINKED ISSUE #4948: GC back compat - do not do GC on "old" documents
Documents created prior to all data objects storing handle references should not have the GC reference check run against them, as it will incorrectly make objects as unreferenced.

### PR DESCRIPTION
**Pull request by arinwt**
Right now it works like so: the flag on the metadata (in the summary) will specify a preference whether or not GC is allowed. True to enable GC, false to disable it, or undefined to leave the decision totally up to the runtime.

Behavior is as follows (for now):
gcAllowed | gcFeature | disableGC | runGC
-|-|-|-
true | 1 | true | false ❌
true | 1 | false | true ✔
true | 1 | undefined | true ✔
false/undefined | 0 | true | false ❌
false/undefined | 0 | false | false ❌
false/undefined | 0 | undefined | false ❌

Right now there is no way to change this value after it is initially set.

For documents earlier than `summaryFormatVersion == 1` (i.e. if they don't have the metadata blob yet), then we assume `gcFeature` is explicitly `0` which means disallowed, and will never runGC.

To set it the first time, just pass the desired value in runtimeOptions as `gcAllowed`. If nothing is passed to this runtime option, then it defaults to `false` and will stay that way. When serialized `true -> 1` for allowed, and `false -> 0` for disallowed. In the future we may repurpose the 1+ to be an incrementing version for GC.

Fixes #4948

### CODE REVIEW

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 1]
```diff
@@ -521,12 +534,18 @@ export class ContainerRuntime extends TypedEventEmitter<IContainerRuntimeEvents>
         const chunks = await tryFetchBlob<[string, string[]][]>(chunksBlobName) ?? [];
         const metadata = await tryFetchBlob<IContainerRuntimeMetadata>(metadataBlobName);
 
+        // enableGC in metadata is introduced with v1 in the metadata blob. Force to false before that.
+        const documentEnableGC = gcEnabled(metadata);
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/containerRuntime.ts:538]: This will override the value in runtimeOptions (if any) right? Can you please add that to the comment.

File: packages/runtime/container-runtime/src/summaryFormat.ts [hunk 2]
```diff
@@ -98,6 +101,14 @@ export function rootHasIsolatedChannels(metadata: IContainerRuntimeMetadata | un
     return !!metadata && !metadata.disableIsolatedChannels;
 }
 
+export function gcEnabled(metadata: IContainerRuntimeMetadata | undefined): boolean | undefined {
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/summaryFormat.ts:104]: We should probably have an option to toggle this via localStorage for testing in real documents. Similar to this code here:
https://github.com/microsoft/FluidFramework/blob/8b917eac70fb641d9f9f453d7fe76b7b3211d679/packages/loader/driver-utils/src/blobAggregationStorage.ts#L33

Comment (arinwt) [reply packages/runtime/container-runtime/src/summaryFormat.ts:104]: Do you think it should override the existing flag in the metadata blob?

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 3]
```diff
@@ -214,21 +215,33 @@ const DefaultSummaryConfiguration: ISummaryConfiguration = {
...
 
-    // Flag that will bypass optimizations and generate GC data for all nodes irrespective of whether the node
-    // changed or not.
+    /**
+     * Flag representing the document's preference for enabling garbage collection.
+     * This is stored in the summary and unchangeable (for now).
+     * Currently if this is set to false, it will take priority and the document will
+     * never run GC.
+     */
+    documentEnableGC?: boolean;
```
Comment (anthony-murphy) [inline packages/runtime/container-runtime/src/containerRuntime.ts:236]: please don't use the word document

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 4]
```diff
@@ -214,21 +215,33 @@ const DefaultSummaryConfiguration: ISummaryConfiguration = {
...
+     */
     generateSummaries?: boolean;
 
-    // Delay before first attempt to spawn summarizing container
+    /* Delay before first attempt to spawn summarizing container. */
     initialSummarizerDelayMs?: number;
 
-    // Flag that will disable garbage collection if set to true.
+    /* Flag that will disable garbage collection if set to true. */
     disableGC?: boolean;
```
Comment (anthony-murphy) [inline packages/runtime/container-runtime/src/containerRuntime.ts:228]: can we put all the gc options into a sub-object, rather than having them all directly on IContainerRuntimeOptions. seems to be sprawling a bit

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 5]
```diff
@@ -1530,6 +1577,16 @@ export class ContainerRuntime extends TypedEventEmitter<IContainerRuntimeEvents>
         return summarizeResult as IChannelSummarizeResult;
     }
 
+    private shouldRunGC(): boolean {
+        // Can override with localStorage flag.
+        return localStorageEnableGC() ?? (
```
Comment (anthony-murphy) [inline packages/runtime/container-runtime/src/containerRuntime.ts:1582]: I don't like this as a member function of this class, and i don't like the value changing at runtime, we should use this data to build the initial configuration, and then only depend on the config, two sources of truth like this always leads to bugs

File: packages/runtime/container-runtime/src/summaryFormat.ts [hunk 6]
```diff
@@ -75,13 +75,16 @@ export interface IContainerRuntimeMetadata {
     readonly summaryFormatVersion: 1;
     /** True if channels are not isolated in .channels subtrees, otherwise isolated. */
     readonly disableIsolatedChannels?: true;
+    /** True to enable GC, false to disable GC, undefined to not specify a preference. */
+    readonly enableGC?: boolean;
```
Comment (anthony-murphy) [inline packages/runtime/container-runtime/src/summaryFormat.ts:79]: i don't like that enableGc means on thing here, and somethings else on the container, please unify the config names

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 3 above)
Comment (arinwt) [reply packages/runtime/container-runtime/src/containerRuntime.ts:236]: What term should I use here? Not sure the term for the "file" entity- i.e. the specific op log + summaries.

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 4 above)
Comment (arinwt) [reply packages/runtime/container-runtime/src/containerRuntime.ts:216]: I broke into `summaryOptions` and `gcOptions`. Let me know what you think.

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 5 above)
Comment (arinwt) [reply packages/runtime/container-runtime/src/containerRuntime.ts]: I agree with you.
I changed to readonly properties: `shouldRunGC` and `disableIsolatedChannels`. Now I no longer modify the passed in `runtimeOptions` for those.

I kept the `shouldWriteMetadata` getter, because it is a computed property using all readonly properties.

File: packages/runtime/container-runtime/src/summaryFormat.ts (hunk 6 above)
Comment (arinwt) [reply packages/runtime/container-runtime/src/summaryFormat.ts:79]: I don't know how much it would help, but maybe I can change to `summaryAllowGC` ?
`summary` - to indicate it is per document / stored in summary
`allow` - vs. enable to show that this is less of an option more of a restriction?

@agarwal-navin also thoughts?

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 3 above)
Comment (arinwt) [reply packages/runtime/container-runtime/src/containerRuntime.ts]: Changed to `summaryEnableGC` for now.. See other comment about changing again to something else.. like `summaryAllowGC` or otherwise.

File: packages/runtime/client-api/src/api/document.ts [hunk 7]
```diff
@@ -242,7 +242,7 @@ export async function load(
     urlResolver: IUrlResolver,
     options: ILoaderOptions = {},
     documentServiceFactory: IDocumentServiceFactory = defaultDocumentServiceFactory,
-    runtimeOptions: IContainerRuntimeOptions = { generateSummaries: false },
+    runtimeOptions: IContainerRuntimeOptions = {},
```
Comment (agarwal-navin) [inline packages/runtime/client-api/src/api/document.ts:245]: Shouldn't `generateSummaries: false` be added as summary options here?

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 8]
```diff
@@ -237,10 +250,33 @@ export interface IContainerRuntimeOptions {
     disableIsolatedChannels?: boolean;
 }
 
+/**
+ * Options for container runtime.
+ */
+export interface IContainerRuntimeOptions {
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/containerRuntime.ts:256]: Isn't this a breaking change? You should probably add this to breaking.md.

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 9]
```diff
@@ -684,27 +717,48 @@ export class ContainerRuntime extends TypedEventEmitter<IContainerRuntimeEvents>
...
         private readonly requestHandler?: (request: IRequest, runtime: IContainerRuntime) => Promise<IResponse>,
         private _storage?: IDocumentStorageService,
     ) {
         super();
 
-        this.runtimeOptions = {
-            ...{ disableIsolatedChannels: true },
-            ...runtimeOptions,
-        };
+        // enableGC in metadata is introduced with v1 in the metadata blob. Force to false before that.
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/containerRuntime.ts:745]: nit: Consider using /** */ block for bigger comments.

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 10]
```diff
@@ -684,27 +717,48 @@ export class ContainerRuntime extends TypedEventEmitter<IContainerRuntimeEvents>
...
+        // This will override the value in runtimeOptions if it is set (true/false). So setting it in
+        // runtimeOptions will only specify what to do if it has never been set before.
+        // Note that even leaving it undefined will force it to false if no metadata blob is written.
+        const prevSummaryEnableGC = context.baseSnapshot ? gcEnabled(metadata) : undefined;
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/containerRuntime.ts:749]: Is the check for context.baseSnapshot used to determine if this is a new or existing document? Can we simply say if (!context.existing) read this value from the runtime options, else get this value from the summary metdata?

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 11]
```diff
@@ -684,27 +717,48 @@ export class ContainerRuntime extends TypedEventEmitter<IContainerRuntimeEvents>
...
+        this.summaryEnableGC = prevSummaryEnableGC ?? this.runtimeOptions.gcOptions.summaryEnableGC;
+
+        // Can override with localStorage flag.
+        this.shouldRunGC = localStorageEnableGC() ?? (
+            // Must not be disabled permanently in summary.
+            (this.summaryEnableGC ?? true)
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/containerRuntime.ts:755]: If there is metadata blob but it does not have `enableGC` property in it, this will default to running GC right. I am wondering if that is the behavior we want.
What will happen in this scenario - A document is created before the "GC waterline" and it does not provide the `summaryEnableGC`  runtime option. But we write the metadata blob for it (maybe because of disableIsolatedChannels?) then we will end up running GC on this document right?

File: packages/runtime/container-runtime/src/summaryFormat.ts (hunk 6 above)
Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/summaryFormat.ts:79]: I am wondering if having both `enableGC / summaryEnableGC` and `disableGC` is a bit too much. It is confusing for sure. We can probably just have `enableGC` and the override (to disable it) can be done via the local storage or via loader options (which would be hidden).

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 8 above)
Comment (arinwt) [reply packages/runtime/container-runtime/src/containerRuntime.ts:256]: Added to BREAKING.md

File: packages/runtime/client-api/src/api/document.ts (hunk 7 above)
Comment (arinwt) [reply packages/runtime/client-api/src/api/document.ts:245]: Yep, good catch.

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 10 above)
Comment (arinwt) [reply packages/runtime/container-runtime/src/containerRuntime.ts:773]: What's the benefit of using `context.existing`? I'm thinking about it purely from loaded-from summary perspective.

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 11 above)
Comment (arinwt) [reply packages/runtime/container-runtime/src/containerRuntime.ts]: Yes I thought that was correct (since we are in v1+), but now I have changed it to always write `false` for now.

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 10 above)
Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/containerRuntime.ts:773]: I think they mean the same thing now. With detached container, existing documents that are loaded will always have a baseSnapshot.
The idea behind adding this functionality is - If you are creating a new Container, you can specify whether you want GC or not. After that, we will respect this choice whenever this container is loaded again and it cannot be changed.

So, we essentially want a check that says if this is a new container, try to get this information from runtime options. Else try to get it from the summary. I believe we use the `existing` flag to do this kind of distinction in our code.

**Comment by agarwal-navin** [comment]
We need tests to verify that we do enable / disable GC correctly based on different combination of these options.

We can probably add more combinations to the tests I have in this PR - https://github.com/microsoft/FluidFramework/pull/5539.

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 10 above)
Comment (arinwt) [reply packages/runtime/container-runtime/src/containerRuntime.ts]: Okay I went ahead and changed it.

**Comment by vladsud** [comment]
Couple mete-observations around GC and similar features:

1. Overall, I'd love to see a way for enabling new features for new files only, as a way of staging. I.e. if I want to roll new functionality, it's beneficial to leave existing files as is (either forever, or come back to enable feature later for them) and just enable for new files. This would require some property bag associated with a file (and easy access to it from any place in runtime, and ideally - driver as well), such that a feature could test property from that bag and determine if feature is enabled
   - Someone can use external logic (like partition based on SPO audience) to enable features on sub-set of files
   - Blob aggregation is great example of feature like that. Enabling it only for new files ensures that damage I can cause (in case something goes wrong) is rather small, and disabling it as a recovery mechanism will lose some number of files, but likely nothing that is already used in prod, which is great.
 
2. But when it comes to GC, boolean will not work. It's almost guaranteed that we will find bugs in GC (overall, let's say some component does not use handles). I.e. after we enabled it and set a flag, we may find ourselves in situation where files are not correctly represented in search index. I see couple outcomes
   1. Overall, we do not care, and just say - files created at GA+ are correct, everything else is best effort. In this case we do not care about boolean at all.
   2. We need not boolean, but counter / version. Every time we find that version X has a bug, we fix it, bump version and tell storage to ignore all files with <=X version.
   3. we use current approach. It's a mix of two approaches above, because I'm sure we will get it wrong and boolean will be just non-perfect filter, but GA (and files created at GA) would be the real test / filter.

Note that for GC, we would love to enable as much of GC pipeline as quickly as possible, so I think waiting enabling 2.3 is not great. I'd use 2.2 and maybe use runtime version (that created a file) as a poor man's indicator of GC versions. Storage may want to play this game with us, or maybe not and just index it all the time based on GC data, at which case it's 2.1, but we have our own telemetry to say "oh yes, that's an old file, it's expected it's not perfect when it comes to GC"

Note that if we find bugs after GA, having version in the file (that created a file) might be handy - we might write some scripts that run in storage, find these files and fix them. This is super expensive, so we will likely do it only if absolutely required, but we should leave this option available as a safety net.

**Comment by arinwt** [comment]
@vladsud - let me know if I got something wrong here. The suggestion is to include the runtime version in the metadata blob, and use it to map to "GC version", so we know which version of GC we are on, and thus which files we need to exclude/filter as "bad"? (2.2 above)

**Comment by arinwt** [comment]
I can also imagine the property bag you mention in 1, but it just has the version for each feature, or 0/null/undefined if it is disabled. And it is stored in the metadata blob.

`gcFeature: 0 | 1 | 2` - 0 is disabled, 1 is first version, 2 is second version, etc.
`blobAggregationFeature: 0 | 1` - 0 is disabled, 1 is enabled

**Comment by arinwt** [comment]
Hey @vladsud, after some discussion, I think we can switch to a 0/1 number type instead of a boolean, but keep everything else the same. It feels like the example of app using handles is more of an app-problem, and would have nothing to do with a GC version from the runtime's perspective. Let me know if you see any problem with this.

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 12]
```diff
@@ -212,25 +213,37 @@ const DefaultSummaryConfiguration: ISummaryConfiguration = {
...
-    // Flag that will bypass optimizations and generate GC data for all nodes irrespective of whether the node
-    // changed or not.
+    /**
+     * Flag representing the summary's preference for enabling garbage collection.
+     * This is stored in the summary and unchangeable (for now). So this runtime option
+     * only takes affect on new containers.
+     * Currently if this is set to false, it will take priority and any container will
+     * never run GC.
+     */
+    summaryEnableGC?: boolean;
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/containerRuntime.ts:227]: Based on out conversation around what this flag means, we might consider naming it something that indicates this container is GC-ready. The other flag controls whether GC is enabled or not. Maybe rename this to something like `isReadyForGC` or `canRunGC`?

File: BREAKING.md [hunk 13]
```diff
@@ -30,6 +31,22 @@ The previous format was just a property bag:
...
+### IContainerRuntimeOptions Format Change
+
+The runtime options passed into `ContainerRuntime` have been subdivided into nested objects, because all of them fall under two categories currently:
+
+-   `summaryOptions` - contains all summary/summarizer related options
+    -   `generateSummaries`
+    -   `initialSummarizerDelayMs`
+    -   `summaryConfigOverrides`
+    -   `disableIsolatedChannels`
+-   `gcOptions` - contains all GC related options
```
Comment (agarwal-navin) [inline BREAKING.md:43]: nit: Consider using `Garbage Collection` instead of `GC` in this sentence. It might not be apparent what GC is.

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 14]
```diff
@@ -686,27 +743,50 @@ export class ContainerRuntime extends TypedEventEmitter<IContainerRuntimeEvents>
...
         private readonly requestHandler?: (request: IRequest, runtime: IContainerRuntime) => Promise<IResponse>,
         private _storage?: IDocumentStorageService,
     ) {
         super();
 
-        this.runtimeOptions = {
-            ...{ disableIsolatedChannels: true },
-            ...runtimeOptions,
-        };
+        /* enableGC in metadata is introduced with v1 in the metadata blob. Force to false before that.
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/containerRuntime.ts:771]: nit: This comment pattern is inconsistent with the rest of the system.

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 15]
```diff
@@ -239,10 +252,33 @@ export interface IContainerRuntimeOptions {
...
+export interface IContainerRuntimeOptions {
+    summaryOptions?: ISummaryRuntimeOptions;
+    gcOptions?: IGCRuntimeOptions;
+}
+
 interface IRuntimeMessageMetadata {
     batch?: boolean;
 }
 
+function localStorageEnableGC(): boolean | undefined {
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/containerRuntime.ts:267]: nit: The local storage flag can both enable and disable GC. Consider a neutral name for this - `localStorageRunGC`?

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 14 above)
Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/containerRuntime.ts:771]: Also, `enableGC` in the comment is now outdated.

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 12 above)
Comment (arinwt) [reply packages/runtime/container-runtime/src/containerRuntime.ts:227]: What about `summaryAllowGC`?

File: packages/test/test-end-to-end-tests/src/test/flattenRuntimeOptions.ts [hunk 16]
```diff
@@ -0,0 +1,22 @@
+/*!
+ * Copyright (c) Microsoft Corporation. All rights reserved.
+ * Licensed under the MIT License.
+ */
+
+import { IContainerRuntimeOptions } from "@fluidframework/container-runtime";
+
+/** Temporary function to make backwards compatible runtime options. */
+export function flattenRuntimeOptions(
```
Comment (agarwal-navin) [inline packages/test/test-end-to-end-tests/src/test/flattenRuntimeOptions.ts:9]: This is to use when tests run against older container runtime?

Comment (arinwt) [reply packages/test/test-end-to-end-tests/src/test/flattenRuntimeOptions.ts:9]: Right

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 12 above)
Comment (arinwt) [reply packages/runtime/container-runtime/src/containerRuntime.ts]: Changed to `gcAllowed`.

**Review by agarwal-navin — APPROVED** [review]

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 17]
```diff
@@ -212,25 +213,37 @@ const DefaultSummaryConfiguration: ISummaryConfiguration = {
...
-
-    // Flag that will disable garbage collection if set to true.
+export interface IGCRuntimeOptions {
+    /* Flag that will disable garbage collection if set to true. */
     disableGC?: boolean;
 
-    // Flag that will bypass optimizations and generate GC data for all nodes irrespective of whether the node
-    // changed or not.
+    /**
+     * Flag representing the summary's preference for enabling garbage collection.
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/containerRuntime.ts:221]: nit: This comment need a small update to reflect the new name.

Comment (arinwt) [reply packages/runtime/container-runtime/src/containerRuntime.ts:221]: Fixed
