### PR TITLE
Throw when loading fails in SharedString

### LINKED ISSUE #4612: SequenceLoadFailed Doesn't fail loading
Seeing a case where the event `SequenceLoadFailed` is logged with `Error 404 from the server, msg = , type = cors`, but the loading of the sequence is failed e.g. the client seems to get the sequence even though it failed to load

### PR DESCRIPTION
**Pull request by anthony-murphy**
fixes #4612 
releated #4613

### CODE REVIEW

File: packages/dds/sequence/src/sequence.ts [hunk 1]
```diff
@@ -656,6 +656,7 @@ export abstract class SharedSegmentSequence<T extends MergeTree.ISegment>
             if (error) {
                 this.logger.sendErrorEvent({ eventName: "SequenceLoadFailed" }, error);
                 this.loadedDeferred.reject(error);
```
Comment (vladsud) [inline packages/dds/sequence/src/sequence.ts:658]: should we return this.loadedDeferred.promise at the bottom of the function instead?

**Review by vladsud — APPROVED** [review]

File: packages/dds/sequence/src/sequence.ts (hunk 1 above)
Comment (anthony-murphy) [reply packages/dds/sequence/src/sequence.ts:661]: there is a non-async usage of this function, returning the promise would make the function async. It technically wouldn't cause a problem, as that case is a non-error case, but i think i could introduce bugs if someone took advantage of the async-ness to do other things in the load finished method
