### PR TITLE
Regenerate GC and summary data when GC version changes

### LINKED ISSUE #6247: Re-summarize and re-generate GC data when GC version of the file changes
This is to handle scenarios where we find a bug with GC and increment the GC version of the file. We need to re-generate GC data and re-summarize the file so that it has updated (and correct) GC data from that point on. Basically, we will consider the GC data before this new version to be incorrect.

### PR DESCRIPTION
**Pull request by agarwal-navin**
Fixes #6247.

With this change, when the GC version of the container runtime changes, we regenerate the GC data and run a full tree summary the first time.

### CODE REVIEW

**Comment by agarwal-navin** [comment]
@arinwt I am looking into the scenario where we get a summary ACK for a summary which has a different GC version than the current.

**Comment by agarwal-navin** [comment]
@arinwt Added code to handle the scenario when an ack comes in with a different GC version and also added tests for it.

**Comment by agarwal-navin** [comment]
@vladsud @arinwt Ping. Can you guys please take a look at this PR :)

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 1]
```diff
@@ -198,6 +199,9 @@ const DefaultSummaryConfiguration: ISummaryConfiguration = {
     maxAckWaitTime: 120000,
 };
 
+// This is the current version of garbage collection.
+const GCVersion = 1;
```
Comment (arinwt) [inline packages/runtime/container-runtime/src/containerRuntime.ts:203]: nit: should this be camelCase?
```suggestion
const gcVersion = 1;
```

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 2]
```diff
@@ -753,8 +757,10 @@ export class ContainerRuntime extends TypedEventEmitter<IContainerRuntimeEvents>
 
     private readonly dataStores: DataStores;
 
-    // This is the source of truth for writing in the summary metadata blob.
-    private readonly summaryGCFeature: Required<IContainerRuntimeMetadata>["gcFeature"];
+    // The current GC version that this container is running.
+    private readonly currentGCVersion = GCVersion;
```
Comment (arinwt) [inline packages/runtime/container-runtime/src/containerRuntime.ts:761]: Do you really need this?

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 3]
```diff
@@ -1679,12 +1687,24 @@ export class ContainerRuntime extends TypedEventEmitter<IContainerRuntimeEvents>
...
 
+            // If the GC version that this container is loaded from differs from the current GC version that this
+            // container is running, we need to regenerate the GC data and run full summary. This is used to handle
+            // scenarios where we upgrade the GC version because we cannot trust the data from the previous GC version.
+            let forceRegenerateData = false;
+            if (this.summaryGCVersion !== this.currentGCVersion && this.summaryGCVersion > 0) {
+                forceRegenerateData = true;
+                // We will regenerate the GC data by running full GC as per the current GC version. Update the version
+                // of GC data written in the summary to the current GC version.
+                this.summaryGCVersion = this.currentGCVersion;
```
Comment (arinwt) [inline packages/runtime/container-runtime/src/containerRuntime.ts:1698]: I don't think this should be here.. if the summary is nacked we have prematurely set this flag, right?

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 4]
```diff
@@ -2003,17 +2023,41 @@ export class ContainerRuntime extends TypedEventEmitter<IContainerRuntimeEvents>
...
             summaryLogger,
         );
+
+        /**
+         * If the acked snapshot was downloaded by the summarizer node and the ack is for a summary that was not
+         * generated by this client, it's possible that it had a different GC version than the current. If so, update
+         * the summary GC version which will update the last successful summary that this client has seen. We will
+         * regenerate the summary and GC data in the next summary to make it up to date to the current version.
+         */
+         if (ackedSnapshotDownloaded && clientId !== this.clientId) {
```
Comment (arinwt) [inline packages/runtime/container-runtime/src/containerRuntime.ts:2053]: I think this code check is totally fine. I am planning to refactor this a bit in a different PR and I will update this part accordingly as well, but I just wanted to let you know the following _should_ be true:
1. All summaries submitted by this summarizer client should be put in SummarizerNode pending summaries
2. When this refresh is called for a summary submitted by this client, it should find the summary in the pending queue, _unless_ it is manually refreshing latest from storage which is also submitted by this client
3. When this refresh is called for a summary _not_ submitted by this client, it will always go down the `refreshLatestFromSnapshot` code path in SummarizerNode and actually download the summary tree, _unless_ it is a summary older than the latest ref seq # we already have.

So all that to say is, theoretically you shouldn't need to do the `clientId !== this.clientId` check, but I wouldn't worry about it for now.

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 5]
```diff
@@ -784,19 +789,20 @@ export class ContainerRuntime extends TypedEventEmitter<IContainerRuntimeEvents>
...
-         runtimeOptions will only specify what to do if it has never been set before.
-         Note that even leaving it undefined will force it to 0/disallowed if no metadata blob is written. */
-        const prevSummaryGCFeature = context.existing ? gcFeature(metadata) : undefined;
+         /**
+          * gcFeature in metadata is introduced with v1 in the metadata blob. Forced to 0/disallowed before that.
+          * For existing documents, we get this value from the metadata blob.
+          * For new documents, we get this value based on the gcAllowed flag in runtimeOptions.
+          */
+        const prevSummaryGCVersion = context.existing ? gcFeature(metadata) : undefined;
         // Default to false for now.
```
Comment (arinwt) [inline packages/runtime/container-runtime/src/containerRuntime.ts:798]: update this comment

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 6]
```diff
@@ -1082,14 +1088,14 @@ export class ContainerRuntime extends TypedEventEmitter<IContainerRuntimeEvents>
...
-        return !this.disableIsolatedChannels || (this.summaryGCFeature > 0);
+        return !this.disableIsolatedChannels || (this.summaryGCVersion > 0);
     }
 
     private formMetadata(): IContainerRuntimeMetadata {
         return {
             summaryFormatVersion: 1,
             disableIsolatedChannels: this.disableIsolatedChannels || undefined,
-            gcFeature: this.summaryGCFeature, // retain value, this is unchangeable for now
+            gcFeature: this.summaryGCVersion, // retain value, this is unchangeable for nown
```
Comment (arinwt) [inline packages/runtime/container-runtime/src/containerRuntime.ts:1098]:
```suggestion
            gcFeature: this.summaryGCVersion, // retain value, this is unchangeable for now
```
typo

**Review by arinwt — CHANGES_REQUESTED** [review]
Looks good mostly. The only part that needs to be fixed is that it shouldn't set summaryGCVersion in generateSummary, but rather in refresh latest (or somewhere in Summarizer on ack).

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 7]
```diff
@@ -2003,17 +2023,41 @@ export class ContainerRuntime extends TypedEventEmitter<IContainerRuntimeEvents>
...
+         * regenerate the summary and GC data in the next summary to make it up to date to the current version.
+         */
+         if (ackedSnapshotDownloaded && clientId !== this.clientId) {
+            const snapshot = await getSnapshotP;
+            const blobId = snapshot.blobs[metadataBlobName];
+            if (blobId) {
+                const metadata = await readAndParse<IContainerRuntimeMetadata>(this.storage, blobId);
+                this.summaryGCVersion = gcFeature(metadata);
+            }
+        }
```
Comment (arinwt) [inline packages/runtime/container-runtime/src/containerRuntime.ts:2060]: There could be another case where `clientId === this.clientId` and that triggers `this.summaryGCVersion = this.currentGCVersion` or something like that.

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 1 above)
Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/containerRuntime.ts:203]: Other globals in this file start with upper case so I kept that.

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 2 above)
Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/containerRuntime.ts:761]: Not really. I added this so I could update it in tests to simulate version updates. I can remove it if we can come up with other ways of testing :-).

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 4 above)
Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/containerRuntime.ts:2053]: That sounds like a good change that will make things clearer. Add me to that PR when it happens so I can get a better idea of this :-).

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 3 above)
Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/containerRuntime.ts]: I fixed this. This is now updated in `refreshLatestSummaryWithAck`. Can you please take a look.

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 7 above)
Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/containerRuntime.ts:2058]: Fixed it.

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 8]
```diff
@@ -2038,9 +2080,28 @@ export class ContainerRuntime extends TypedEventEmitter<IContainerRuntimeEvents>
             summaryLogger,
         );
 
+        /**
+         * Since the latest summary we are tracking is based off of the snapshot we just fetched, update the summary
+         * GC version to the GC version in this snapshot too.
+         */
+        if (this.gcEnabled) {
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/containerRuntime.ts:2087]: @arinwt I am not 100% sure if we need to update summaryGCVersion here. Is it possible that when we force a refresh while summarizing, the GC version of the downloaded snapshot is different from the `currentGCVersion`? From what I understand, it is possible but making sure.

Comment (arinwt) [reply packages/runtime/container-runtime/src/containerRuntime.ts:2103]: Yeah it is possible.

File: packages/runtime/runtime-utils/src/summarizerNode/summarizerNode.ts [hunk 9]
```diff
@@ -262,6 +268,7 @@ export class SummarizerNode implements IRootSummarizerNode {
             correlatedSummaryLogger,
             readAndParseBlob,
         );
+        return false;
```
Comment (arinwt) [inline packages/runtime/runtime-utils/src/summarizerNode/summarizerNode.ts:271]: Do we wanna short-circuit for oldest snapshots? sequence number comparison?

**Review by arinwt — APPROVED** [review]

File: packages/runtime/runtime-utils/src/summarizerNode/summarizerNode.ts (hunk 9 above)
Comment (arinwt) [reply packages/runtime/runtime-utils/src/summarizerNode/summarizerNode.ts:271]: That way `pendingSummary` can be set to true or something that bypasses downloading the snapshot..

Comment (agarwal-navin) [reply packages/runtime/runtime-utils/src/summarizerNode/summarizerNode.ts:271]: Doesn't that become a third case then? Basically, we did not have a pending summary but we didn't update the latest summary either.

Comment (agarwal-navin) [reply packages/runtime/runtime-utils/src/summarizerNode/summarizerNode.ts:271]: Maybe a better way would be for `refreshSummaryAck` in summarizer node to return whether this ack was used to update latest summary or not. If it was, then we download the snapshot and update `summaryGCVersion` based on the metadata blob. If it was not used, we simply ignore it.
Although its a little expensive because in the common case, for each ack, we will download the summary.

Comment (agarwal-navin) [reply packages/runtime/runtime-utils/src/summarizerNode/summarizerNode.ts]: @arinwt Updated this as per our conversation. Can you please take a look.

**Review by arinwt — APPROVED** [review]
