### PR TITLE
Reduce Signal Leader Election errors

### LINKED ISSUE #8125: Follow up to: Add Signals to Stress Test
## Work Item

- After reviewing the initial data, the time spent waiting for a new signal should be upped to 30 seconds.
- Additional logging should be added to determine the amount of time it takes to find a new leader.
- Move the `UnexpectedLeaderEventError` to a generic table.

### PR DESCRIPTION
**Pull request by tyler-cai-microsoft**
Resolves #8125 

The goal is to reduce/remove the Signal Leader Election Errors created by #7994

### CODE REVIEW

File: packages/test/test-service-load/src/leaderElection.ts [hunk 1]
```diff
@@ -38,13 +40,14 @@ export class LeaderElection {
     private runLeaderElection() {
         if (this.leaderId !== undefined && this.leaderId === this.dataStoreRuntime.clientId) {
             this.dataStoreRuntime.submitSignal("leaderMessage", "leaderMessage");
-            this.lastPinged = Date.now();
+            this.updateLastPinged();
         }else if(this.leaderId === undefined) {
             this.logger.sendErrorEvent({eventName: "LeaderUndefinedEventError"});
```
Comment (anthony-murphy) [inline packages/test/test-service-load/src/leaderElection.ts:45]: let me this to sendTelemetryEvent as well, to keep the test results clean as we have a chance to tune it

File: packages/test/test-service-load/src/leaderElection.ts [hunk 2]
```diff
@@ -9,12 +9,14 @@ import { ChildLogger, TelemetryLogger } from "@fluidframework/telemetry-utils";
...
     private readonly beatInEveryNSecs: number = 1000; // 1 secs
-    private readonly leaderWait: number = 5000; // 5 secs
+    private readonly leaderWait: number = 30000; // 30 secs
     private lastPinged: number | undefined;
     private readonly logger: TelemetryLogger;
+    private prevPing: number;
 
     constructor(private readonly dataStoreRuntime: IFluidDataStoreRuntime) {
         this.logger = ChildLogger.create(this.dataStoreRuntime.logger, "SignalLeaderElection");
+        this.prevPing = 0;
```
Comment (anthony-murphy) [inline packages/test/test-service-load/src/leaderElection.ts:19]: i don't think this should be initialize to 0. i'd rather it be undefined. 0 will lead to weird results for LeaderFound

File: packages/test/test-service-load/src/leaderElection.ts [hunk 3]
```diff
@@ -38,13 +39,14 @@ export class LeaderElection {
...
             this.dataStoreRuntime.submitSignal("leaderMessage", "leaderMessage");
-            this.lastPinged = Date.now();
+            this.updateLastPinged();
         }else if(this.leaderId === undefined) {
-            this.logger.sendErrorEvent({eventName: "LeaderUndefinedEventError"});
+            this.logger.sendTelemetryEvent({eventName: "LeaderUndefinedEventError"});
         }else {
             const current = Date.now();
             if(this.lastPinged !== undefined && current - this.lastPinged > this.leaderWait) {
                 this.logger.sendErrorEvent({eventName: "LeaderLostEventError"});
```
Comment (anthony-murphy) [inline packages/test/test-service-load/src/leaderElection.ts:48]:
```suggestion
                this.logger.sendTelemetryEvent({eventName: "LeaderLostEventError"});
```
rather promote after we see it clean

**Review by anthony-murphy — APPROVED** [review]
