### PR TITLE
Fix the issue #3982

### LINKED ISSUE #3982: Can not broadcast 'ops' in the same socket package while the 'ops' was received by the same socket package
## Describe the bug
When I in client A do something for DDSes, will sned those changes by 'submitOp', that content will be in the same socket package.
While in client B, I got two socket package, the first always contain 1 op and the others at the second package.

### To Reproduce
1. at client A, do some changes at DDSes, it will send 'submitOp' to the server
2. at client B, monitor WebSocket message, will see two 'op' message

### Some socket message:

**At client A, Some changes trigger out 8 ops**

Screen Shot 2020-10-19 at 5 28 13 PM

**At client B, we received two broadcasts message, The first with 1 op and the second with 7 ops**

Screen Shot 2020-10-19 at 5 28 29 PM
Screen Shot 2020-10-19 at 5 28 59 PM

### Expected behavior
broadcast 'ops' message in one socket package if they are submitted by 'submitOp'

### PR DESCRIPTION
**Pull request by qianfeiqianlan**
The [issue](https://github.com/microsoft/FluidFramework/issues/3982) seems cause by broadcast lambda.

It will be broadcast one message when '**sendPending**' called first, and broadcast others later.

### CODE REVIEW

**Comment by tanviraumi** [comment]
Thanks for your PR. Can you please give us some context on issue #3982? I am trying to understand why this one is considered as a bug. And whether we are breaking any invariance by chunking into two socket packages?

**Comment by qianfeiqianlan** [comment]
> Thanks for your PR. Can you please give us some context on issue #3982? I am trying to understand why this one is considered as a bug. And whether we are breaking any invariance by chunking into two socket packages?

Hi @tanviraumi , In my case, I wanner got the DDSes changes in the same transaction.

eg. At client A, I can modify some DDSes, and submit them in the same socket package by 'submitOp', and at client B, I can synchronously get those changes and apply the changes to my customized data structure.

I think 'sendPending()' in BroadcasterLambda is the intention to do it.

**Comment by tanviraumi** [comment]
Thanks for the clarification and apologize for the delayed response. Fluid does provide some basic transaction support but the guarantee is not on the socket level. In other words, the incoming messages may or may not show up in the same batch, but Fluid does not rely on that characteristics for supporting transaction. @DLehenbauer will provide more guidance on enabling transaction.

But your PR actually surfaces an interesting behavior: we always send one op separately and rests in a single batch. We will take a closer look into that and figure out the core issue soon. So please keep your PR open for now.

@ChumpChief who is also looking at the issue.

**Comment by DLehenbauer** [comment]
Hi @qianfeiqianlan - If you call `setFlushMode(FlushMode.Manual)` on the ContainerRuntime, Fluid will process ops generated within a single [JS-task](https://javascript.info/event-loop) as a group...  meaning the ops will never be interleaved with ops from other clients and will always be dispatched in a single JS-task (Issue #4048 describes the behavior in more detail.)

You can get the same guarantees for smaller regions using `orderSequentially()` (also on the ContainerRuntime).

**Comment by tanviraumi** [comment]
Hi @qianfeiqianlan, let us know your thoughts on the API and we can close your issue.

File: server/routerlicious/packages/lambdas/src/broadcaster/lambda.ts [hunk 1]
```diff
@@ -78,26 +78,23 @@ export class BroadcasterLambda implements IPartitionLambda {
...
             return;
         }
 
-        // Swap current and pending
-        const temp = this.current;
-        this.current = this.pending;
-        this.pending = temp;
-        const batchOffset = this.pendingOffset;
+        // Invoke the next send after a setImmediate to give IO time to create more batches
+        setImmediate(() => {
```
Comment (GaryWilber) [inline server/routerlicious/packages/lambdas/src/broadcaster/lambda.ts:86]: Could you save the `setImmediate` timer id to a property and make it so `sendPending` does nothing if there's an existing timer? Then in this callback, clear that timer id before calling `sendPending` again.

Otherwise this call would keep queueing up more of these callbacks. There's no need to queue up more than one of these since the callback will process/send the whole batch.

**Review by GaryWilber — CHANGES_REQUESTED** [review]
To clarify what's happening, here's why the issue occurs. After the client submits 8 ops:
1. The kafka consumer will read 8 ops and call the broadcaster lambda handler 8 times, within the same event loop (this is important!).
1. The first time the handler is called, it will call `sendPending`, which broadcasts the op.
1. The next 7 times the handler is called, it will also call `sendPending`, but `sendPending` will return immediately since there's a pending batch being sent.
1. After the event loop finishes, the `setImmediate` call started in `sendPending` will trigger, which processes the next batch (the 7 ops).

@qianfeiqianlan This PR would fix this issue. However with this current fix, it would end up calling `setImmediate` 8 times, one for each op. That is not really necessary because only the first `setImmediate` call would actually process the batch. The next 7 times the callback is called, it would not really do anything.

File: server/routerlicious/packages/lambdas/src/broadcaster/lambda.ts (hunk 1 above)
Comment (qianfeiqianlan) [reply server/routerlicious/packages/lambdas/src/broadcaster/lambda.ts:88]: @GaryWilber I fix it with an **isMessageSending** flag,  is this a graceful solution？

I try to fix it with timer id and **clearImmediate**, but I have no idea to determine whether a timer is cleared.

Comment (GaryWilber) [reply server/routerlicious/packages/lambdas/src/broadcaster/lambda.ts:88]: Yea looks like this will work.

**Review by GaryWilber — APPROVED** [review]

**Review by tanviraumi — APPROVED** [review]
