### PR TITLE
send blob attach op immediately upon uploading a blob

### LINKED ISSUE #5123: Blob upload should be repeated if we are unable to issue BlobAttach message in reasonable amount of time.
If blob was uploaded to storage, but we were not able to issue and see the ack for ContainerMessageType.BlobAttach within 36 hours, then blob has to be reuploaded again, as SPO already deleted it.
Referencing it in ops/snapshot will mean we have broken blob reference, which is not good.

Note that ideally this policy (36 hours) should be communicated from SPO.
I'm proposing that response for blob upload return that value in the header.
Note that we should start measuring time from the start of upload that succeeded. I.e. if we are offline, the timer does not start until we actually online and reached SPO with first byte (or rather - just a moment before that).

Also this is driver specific implementation (how it's returned in response), we should change upload blob API on the driver to return this info in driver-agnostic way.

### PR DESCRIPTION
**Pull request by wes-carlson**
fix #5123

### CODE REVIEW

File: packages/runtime/container-runtime/src/blobManager.ts [hunk 1]
```diff
@@ -77,20 +74,24 @@ export class BlobManager {
             `${BlobManager.basePath}/${response.id}`,
             this.routeContext,
             async () => this.getStorage().readBlob(response.id),
-            () => this.attachBlobCallback(response.id),
         );
 
         // Note - server will de-dup blobs, so we might get existing blobId!
         if (!this.blobIds.has(response.id)) {
```
Comment (vladsud) [inline packages/runtime/container-runtime/src/blobManager.ts:80]: For consistency, you likely want to call handle.attachGraph() in ELSE clause.
That said, we have a race condition here if we do so, if two same images gets uploaded at the same time.
Can BlobHandle instead of having attached property check with this.pendingBlobIds to determine if it is attached or not?

File: packages/runtime/container-runtime/src/blobManager.ts [hunk 2]
```diff
@@ -77,20 +74,24 @@ export class BlobManager {
...
+
+            // send blob attach op and wait until we see it to return the handle
+            this.attachBlobCallback(response.id);
+            await this.pendingBlobIds.get(response.id)?.promise;
         }
 
         return handle;
     }
 
     public addBlobId(blobId: string) {
```
Comment (vladsud) [inline packages/runtime/container-runtime/src/blobManager.ts:91]: Can we break it into two functions - one private addBlobCore() called from load() (that would only add to blobIds) and another - postBlobAttach() or something of similar name called from container runtime? It would be easier to follow intent. Also for the later, it should be unconditional, i.e. there has to be an entry for it in this.pendingBlobIds when it's called (if we handle concurrent uploads of same image correctly, see prior comment)

File: packages/test/test-end-to-end-tests/src/test/blobs.spec.ts [hunk 3]
```diff
@@ -69,16 +69,20 @@ describeFullCompat("blobs", (getTestObjectProvider) => {
...
+
+        const blob = await dataStore._runtime.uploadBlob(stringToBuffer("some random text", "utf-8"));
+
+        // this will send the blob attach op on < 0.41 runtime (otherwise it's sent at time of upload)
+        dataStore._root.set("my blob", blob);
+        await attachOpP;
+
         const snapshot1 = (container1 as any).context.runtime.blobManager.snapshot();
 
         // wait for summarize, then summary ack so the next container will load from snapshot
```
Comment (vladsud) [inline packages/test/test-end-to-end-tests/src/test/blobs.spec.ts:88]: It would be great to have concurrent upload of same blob (twice) and see how code reacts - some storages may dedup, some will not, but the test should not fail. Same for sequential upload of same content, if we do not have that coverage.

File: packages/runtime/container-runtime/src/blobManager.ts [hunk 4]
```diff
@@ -77,20 +74,24 @@ export class BlobManager {
...
         );
 
         // Note - server will de-dup blobs, so we might get existing blobId!
         if (!this.blobIds.has(response.id)) {
-            this.pendingBlobIds.add(response.id);
+            this.pendingBlobIds.set(response.id, new Deferred<void>());
+
+            // send blob attach op and wait until we see it to return the handle
+            this.attachBlobCallback(response.id);
+            await this.pendingBlobIds.get(response.id)?.promise;
```
Comment (vladsud) [inline packages/runtime/container-runtime/src/blobManager.ts:85]: Not sure if we want to do it in this PR, but we need to check the policy (returned as payload of upload API in ODSP) if blob op made it in time. If not, we would need to restart the uploads process. If not in this PR, can you please check we have an issue tracking it (and if not - open one)?
Also we should likely reject process (overall end-to-end) if container runtime was disposed.

Comment (wes-carlson) [reply packages/runtime/container-runtime/src/blobManager.ts:87]: #6469

Comment (vladsud) [reply packages/runtime/container-runtime/src/blobManager.ts:87]: What about rejection on container being disposed? That's missing and not covered in this issue.

**Review by vladsud — APPROVED** [review]

File: packages/runtime/container-runtime/src/blobManager.ts (hunk 4 above)
Comment (wes-carlson) [reply packages/runtime/container-runtime/src/blobManager.ts:87]: submit() will throw if the runtime is disposed and I added a check when uploadBlob() is called. Do we need more?

Comment (vladsud) [reply packages/runtime/container-runtime/src/blobManager.ts:87]: I think you refer to attachBlobCallback() callback calling submit and failing if container runtime is disposed at that moment.
This is not sufficient. The biggest gap - something somewhere needs to do this.pendingBlobIds.get(id).reject() when container runtime is disposed or we should have Promise.race() waiting for promise that gets rejected on disposition of container runtime.
The other part - failing before making a call to createBlob(). I've looked at ODSP implementation and we do not track dispose there, so it will be happy to create a blob in disposed state, which is not great (but less important than above)

**Review by vladsud — APPROVED** [review]
