### PR TITLE
Do not close container from reconnectOnError even if canRetry is false

### LINKED ISSUE #8570: A container will always reconnect and retry, even for non-retriable errors
[Original discussion](https://github.com/microsoft/FluidFramework/pull/7987#discussion_r765939797)

## Describe the bug

**Any** error coming from the driver will cause the container to reconnect and retry pending ops. This risks the container going into an endless loop of reconnects even for errors which should never be retried. 

For example, if the server rejects a payload for exceeding the payload size limitation (this is the particular error type which surfaced the issue in the aforementioned PR), the container will reconnect and will attempt to resend the large ops forever.

The issue seems to be rooted in the `createReconnectError` method will always ignore the `canRetry` property from the supplied error.
https://github.com/microsoft/FluidFramework/blob/f2ea99fe007f4f4e6da9543be203366a1765bc37/packages/loader/container-loader/src/connectionManager.ts#L81

The fix seems trivial at first sight; however, it risks breaking existing assumptions about how errors are handled at that layer. I believe the fix should be deeper and rethink our reconnection strategies.

### To Reproduce

- from the `DocumentDeltaConnection`, emit an error as:
```
this.emit("error", new NonRetryableError("Catastrophic", undefined, DriverErrorType.writeError));
```
- the container will still retry.

### Expected behavior
An error without the `canRetry` property set to `true` should not cause a reconnect and a retry.

cc @markfields

### PR DESCRIPTION
**Pull request by markfields**
Fixes #8570

There should be no behavior change with this PR.  But the flow/expectations are much clearer.

Previously, 2/3 codepaths entering `reconnectOnError` would stomp over `canRetry` with `true`, to avoid closing the container due to hiccup on the socket (assumption being, any fatal error state will cause container to close on reconnect attempt).  Now, rather than overwriting `canRetry`, I've let that stay as-is and updated `reconnectOnError` to simply log if `canRetry` is false.

The third codepath entering `reconnectOnError` (nack) has a case where `canRetry` is false, so in that case rather than leaning on `reconnectOnError` to close the container, I check `canRetry` first and close right away (then `reconnectOnError` will return early).

Note: My previous analysis that stated that `documentDeltaConnection`'s `disconnect` event could lead to this code path if raised during `odspDocumentDeltaConnection.initialize` was incorrect - at that point in time, `connectionManager` hasn't registered event listeners, of course, since the connection object is never successfully created/returned.

With this in mind (and given the refactor for the non-retryable nack), I don't actually expect the new log event `"reconnectingDespiteFatalError"` to ever be hit.  And even if it is, it's an expected/supported code path so I'm logging it as a generic event, not an error event.

### CODE REVIEW

File: packages/loader/container-loader/src/connectionManager.ts [hunk 1]
```diff
@@ -743,8 +740,8 @@ export class ConnectionManager implements IConnectionManager {
             return;
         }
 
-        const delayMs = error !== undefined ? getRetryDelayFromError(error) : undefined;
-        if (delayMs !== undefined) {
+        const delayMs = getRetryDelayFromError(error);
+        if (error !== undefined && delayMs !== undefined) {
```
Comment (andre4i) [inline packages/loader/container-loader/src/connectionManager.ts:744]: is `error !== undefined` redundant here?

**Comment by markfields** [comment]
The test failures are important, I'm taking a look.  I understand that this change will result in container closing immediately, rather than from `connectCore` where it awaits the promise returned from `initialize`.  That seems to be breaking some assumptions in these tests.

File: packages/loader/driver-utils/src/network.ts [hunk 2]
```diff
@@ -29,6 +29,18 @@ export function isOnline(): OnlineStatus {
...
 
+/**
+ * Interface describing errors and warnings raised by any driver code.
+ * errorType would be either DriverErrorType or the specific driver's specialized error type enum
+ */
+ export interface IAnyDriverError {
+    readonly errorType: string;
+    readonly message: string;
+    canRetry: boolean;
+    online?: string;
```
Comment (andre4i) [inline packages/loader/driver-utils/src/network.ts:40]: some comments here would be nice :) `online` doesn't say much about what it means.

File: packages/loader/container-loader/src/connectionManager.ts [hunk 3]
```diff
@@ -726,7 +723,7 @@ export class ConnectionManager implements IConnectionManager {
 
         this.disconnectFromDeltaStream(disconnectMessage);
 
-        const canRetry = error !== undefined ? canRetryOnError(error) : true;
+        const canRetry = (error === undefined) || canRetryOnError(error);
```
Comment (andre4i) [inline packages/loader/container-loader/src/connectionManager.ts:726]: Not saying this is wrong, considering the code being logically equivalent. But I'm curious why we'd retry on an undefined error. It seems like this method might be used for a generic reconnect without an error, which is slightly against the name of the method. Nothing actionable right now but something to keep in mind in case of a larger refactoring.

**Comment by andre4i** [comment]
> The test failures are important, I'm taking a look. I understand that this change will result in container closing immediately, rather than from connectCore where it awaits the promise returned from initialize. That seems to be breaking some assumptions in these tests.

Please see if you can add new tests to lock in the new behavior explicitly. I mean in case the existing tests aren't explicit about why they fail..

**Comment by markfields** [comment]
As discussed in the issue, I misunderstood the semantics here.  Will update the PR to restore the old behavior but make it more explicit/clear/consistent.

File: packages/loader/container-loader/src/connectionManager.ts (hunk 1 above)
Comment (markfields) [reply packages/loader/container-loader/src/connectionManager.ts:747]: Correct.  But without it this way, TypeScript can't figure out the type narrowing and complains that `error` could be `undefined` on the next line.  If you have a stronger opinion, I can do `error!` on the next line with a lint error suppression, but I prefer to avoid those myself.

**Comment by markfields** [comment]
@andre4i, @vladsud  -- Ready for review again.  I'm updating the title/original comment to explain the new approach, which is to leave canRetry as-is, but don't close if it's false.

**Review by andre4i — APPROVED** [review]

File: packages/loader/driver-utils/src/network.ts (hunk 2 above)
Comment (vladsud) [reply packages/loader/driver-utils/src/network.ts:40]: I'm not sure "Any" has a value.

Comment (markfields) [reply packages/loader/driver-utils/src/network.ts:40]: You'd prefer `IDriverError`?  I'm trying to articulate that this can be an error from the base/utils driver code, or from a specialized (e.g. ODSP) driver layer.

File: packages/loader/container-loader/src/connectionManager.ts [hunk 4]
```diff
@@ -68,6 +67,12 @@ const DefaultChunkSize = 16 * 1024;
 const fatalConnectErrorProp = { fatalConnectError: true };
 
 function getNackReconnectInfo(nackContent: INackContent) {
+    // check message.content for Back-compat with old service.
+    if (nackContent === undefined) {
```
Comment (vladsud) [inline packages/loader/container-loader/src/connectionManager.ts:71]: not sure what "old service" means in this context. Is this some kind of new thing?
If it's an old thing, how did code work before?

Comment (markfields) [reply packages/loader/container-loader/src/connectionManager.ts:71]: I just copied this block from below.  I bet we could remove it in a separate PR once we identified the back-compat scenario/timeline

File: packages/loader/container-loader/src/connectionManager.ts [hunk 5]
```diff
@@ -726,12 +724,7 @@ export class ConnectionManager implements IConnectionManager {
 
         this.disconnectFromDeltaStream(disconnectMessage);
 
-        const canRetry = error !== undefined ? canRetryOnError(error) : true;
-
-        // If reconnection is not an option, close the DeltaManager
-        if (!canRetry) {
-            this.props.closeHandler(normalizeError(error, { props: fatalConnectErrorProp }));
-        } else if (this.reconnectMode === ReconnectMode.Never) {
```
Comment (vladsud) [inline packages/loader/container-loader/src/connectionManager.ts:734]: not sure why canRetry handling is removed. Is this intentional?
I believe nackHandler() workflow can result in non-retryable error. I.e. getNackReconnectInfo() & nackContent.code !== 403.

Comment (markfields) [reply packages/loader/container-loader/src/connectionManager.ts:734]: Please read PR description

Comment (vladsud) [reply packages/loader/container-loader/src/connectionManager.ts:734]: Thanks! I'd suggest for nackHandler() to not even call this function in case of canRetry - false, and just add assert(canRetry, "all code paths reach here with retryable error") and remove any handling or events below - it feels clearly RE enforcing invariants and capturing any changes in workflows sooner.

Comment (markfields) [reply packages/loader/container-loader/src/connectionManager.ts:734]: Might not be true though.  See error handler in documentDeltaConnection

Comment (markfields) [reply packages/loader/container-loader/src/connectionManager.ts:734]:
```
const err = this.createErrorObject("error", error, error !== "Invalid namespace");
```

File: packages/loader/container-loader/src/connectionManager.ts (hunk 4 above)
Comment (vladsud) [reply packages/loader/container-loader/src/connectionManager.ts:71]: Got it, I did not see the code where it moved from :)

**Review by vladsud — APPROVED** [review]

File: packages/loader/container-loader/src/connectionManager.ts (hunk 5 above)
Comment (vladsud) [reply packages/loader/container-loader/src/connectionManager.ts:734]: If my memory serves right, this case will result in failed connection, not disconnect. It happens before we get connect_document_success. I did not retraced code again, but I believe all reconnection flows were always passing canRetry = true except for nack path, so even if this error can result in disconnect, we are not handling it correctly.

File: packages/loader/driver-utils/src/network.ts (hunk 2 above)
Comment (vladsud) [reply packages/loader/driver-utils/src/network.ts:40]: I get it, but same logic applies to any driver interfaces, and we do not put "any" anywhere.
Some other places use "IGenericDriverError". Not sure it's better.
You can also go with IDocumentServiceError - this seems like more concrete (one implication - it assumes it's used only by instance, not by driver factory).

I think the core issue here is that it's not part of interface, i.e., we need to move toward drivers returning errors, not throwing errors. Then it becomes a bit easier to name (and "any" would make even less sense there).

File: packages/loader/container-loader/src/connectionManager.ts (hunk 5 above)
Comment (markfields) [reply packages/loader/container-loader/src/connectionManager.ts:734]: I think you're right. I want to start with the log and see if it bears out, I can follow up later and switch to assert. Not going to open an issue, I don't think it is critical to ensure it happens.

File: packages/loader/driver-utils/src/network.ts (hunk 2 above)
Comment (markfields) [reply packages/loader/driver-utils/src/network.ts:40]: > we need to move toward drivers returning errors, not throwing errors

Yes that is the direction.  Trying to make tactical fixes with that future in mind.  This type will be replaced with a proper type (with strongly-typed errorType) that can account for driver-specific errors in a careful way.

Comment (markfields) [reply packages/loader/driver-utils/src/network.ts:40]: Leaving it named as-is with a comment explaining a bit better its shape and purpose

**Comment by markfields** [comment]
@andre4i, @vladsud  -- I added tests and made some trivial changes, feel free to leave further comments, I am opening a follow-up PR with some stuff anyway.
