### PR TITLE
Should not fallback to secondary get latest in case of snaphsotTooBig error

### LINKED ISSUE #4390: 413 errors (file too big) do not look right in telemetry
Query:

Office_Fluid_FluidRuntime_Error
| where Event_Time > ago(5d)
| where Data_error contains "413"
| summarize count() by Data_eventName, Data_message, Data_errorType

Result:

fluid:telemetry:Container:ContainerClose	Error 413 from the server, msg = , type = cors	263
fluid:telemetry:OdspDriver:TreeLatest_FallBackToGetRequest	Error 413 from the server, msg = , type = cors	17
fluid:telemetry:Container:ContainerWarning		3

Couple things that look wrong:
1. We should not do secondary getLatest request on 413 - this means file is too big and client does not want that big file (error is comming from "Microsoft Teams Web").
2, 413 should not show up that way in the error / message. It should map to errorType = OdspErrorType.snapshotTooBig  and show up in telemetry as Data_errorType = "snapshotTooBig", but this property is missing. I do not know what's best here
3. It should also never get to fluid:telemetry:Container:ContainerWarning. This is likely summarizer warning - summarizer should always load, no matter what's the size of summary.

### PR DESCRIPTION
**Pull request by jatgarg**
Fixes: https://github.com/microsoft/FluidFramework/issues/4390
1.) We should not do secondary getLatest request on 413. We were having double try/catch which was causing the issue.
2.) Summarizer client should always load so don't respect the size or timeout specified by host.

### CODE REVIEW

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts [hunk 1]
```diff
@@ -564,59 +564,53 @@ export class OdspDocumentStorageService implements IDocumentStorageService {
     }
 
     private async fetchSnapshot(snapshotOptions: ISnapshotOptions, tokenFetchOptions: TokenFetchOptions) {
+        assert(snapshotOptions.timeout !== undefined, "Timeout should be provided for setting a limit");
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:567]: Not sure if it's appropriate here (could result in explosion of types, and also can be clunky to use by callers), but consider creating new interface where timeout property is not optional, and thus have it compiler check at compilation time, then detecting bugs at runtime via asserts

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts [hunk 2]
```diff
@@ -564,59 +564,53 @@ export class OdspDocumentStorageService implements IDocumentStorageService {
...
-                abortController.abort();
-            },
-            snapshotOptions.timeout,
-        );
         try {
             const odspSnapshot = await this.fetchSnapshotCore(snapshotOptions, tokenFetchOptions, usePost, abortController);
             return odspSnapshot;
         } catch (error) {
+            const errorType = error.errorType;
+            if ((errorType === DriverErrorType.authorizationError || errorType === DriverErrorType.incorrectServerResponse) && tokenFetchOptions.refresh === false) {
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:590]: It would be great to add a comment for future readers of why this check and throw is here.
That said, I think tokenFetchOptions.refresh === false check should be removed - we should not try to post if it was second time we hit 401/403.

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts [hunk 3]
```diff
@@ -564,59 +564,53 @@ export class OdspDocumentStorageService implements IDocumentStorageService {
...
+                throw error;
+            }
             // If the snapshot size is too big and the host specified the size limitation, then don't try to fetch the snapshot again.
-            if (error.errorType === OdspErrorType.snapshotTooBig && this.hostPolicy.snapshotOptions?.mds !== undefined) {
+            if ((error.errorType === OdspErrorType.snapshotTooBig && this.hostPolicy.snapshotOptions?.mds !== undefined) && (this.hostPolicy.summarizerClient !== true)) {
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:594]: It's a bit hard to extract intention here.
First, why do we check for mds? If we got snapshotTooBig, we can assert that mds was provided (to check if storage does not return this error code for something unrelated), but really there is no need to check for it, as we have failure in our hands one way or another.

I think this block and next block should be under one big (and same) IF statement - checking for both snapshotTooBig or fetchTimeout. I.e. below we treat them interchangeably, not sure why here we do not do the same.

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts [hunk 4]
```diff
@@ -564,59 +564,53 @@ export class OdspDocumentStorageService implements IDocumentStorageService {
...
                 throw error;
             }
             // If the first snapshot request was with blobs and we either timed out or the size was too big, then try to fetch without blobs.
             if ((error.errorType === OdspErrorType.snapshotTooBig || error.errorType === OdspErrorType.fetchTimeout) && snapshotOptions.blobs) {
                 const snapshotOptionsWithoutBlobs: ISnapshotOptions = { ...snapshotOptions, blobs: 0, mds: undefined };
                 return this.fetchSnapshotCore(snapshotOptionsWithoutBlobs, tokenFetchOptions, usePost);
             }
+            if (usePost) {
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:602]: Can this condition be more scoped? I.e. can it be only for specific error code or something like that? How does service let us know that PUT is not supported / disabled? Is it some special error code? I just worry about double the request payload on service when service is struggling (let's say returns us 500 or 429) - we are essentially making it worse.

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts [hunk 5]
```diff
@@ -564,59 +564,53 @@ export class OdspDocumentStorageService implements IDocumentStorageService {
...
+            }
             throw error;
         }
     }
 
     private async fetchSnapshotCore(
         snapshotOptions: ISnapshotOptions,
         tokenFetchOptions: TokenFetchOptions,
-        usePost: boolean,
+        usePost: boolean | undefined,
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:613]: I'd rather keep it boolean and do const usePost = !!this.hostPolicy.usePostForTreesLatest above

Comment (jatgarg) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:613]: Modified.

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts (hunk 2 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:590]: Added comment and removed the second condition.

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts (hunk 4 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:602]: As I asked them, they return 400 in case it is not supported, so falling back only in that case.

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts (hunk 3 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:594]: This is because if we get snapshotTooBig error and if the host specified the mds limit, then we don't want to retry without blobs. This is for host perf scenario like Teams as you suggested.

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts (hunk 1 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:567]: Actually this is private api and we are definitely adding timeout by ourselves, so I can remove this assert with any issue. So removing it.

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts [hunk 6]
```diff
@@ -564,51 +564,47 @@ export class OdspDocumentStorageService implements IDocumentStorageService {
...
-            snapshotOptions.timeout,
-        );
         try {
             const odspSnapshot = await this.fetchSnapshotCore(snapshotOptions, tokenFetchOptions, usePost, abortController);
             return odspSnapshot;
         } catch (error) {
+            const errorType = error.errorType;
+            // If we have 401/403 error then we don't need to fallback to get call for Trees/Latest. Just throw so that we get a refreshed
+            // token for once.
+            if (errorType === DriverErrorType.authorizationError || errorType === DriverErrorType.incorrectServerResponse) {
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:591]: You should be able to remove this block of code - all the code below works only with specific error codes, so anything that is not covered below results in throwing error (default path).

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts [hunk 7]
```diff
@@ -564,51 +564,47 @@ export class OdspDocumentStorageService implements IDocumentStorageService {
...
             }
             // If the first snapshot request was with blobs and we either timed out or the size was too big, then try to fetch without blobs.
             if ((error.errorType === OdspErrorType.snapshotTooBig || error.errorType === OdspErrorType.fetchTimeout) && snapshotOptions.blobs) {
                 const snapshotOptionsWithoutBlobs: ISnapshotOptions = { ...snapshotOptions, blobs: 0, mds: undefined };
                 return this.fetchSnapshotCore(snapshotOptionsWithoutBlobs, tokenFetchOptions, usePost);
             }
+            // If we used the post request first time and got a 400 error from server, then try with a GET request.
+            if (usePost && error.statusCode === 400) {
+                this.logger.sendErrorEvent({ eventName: "TreeLatest_FallBackToGetRequest" }, error);
+                return this.fetchSnapshotCore(snapshotOptions, tokenFetchOptions, false);
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:606]: Are you sure this should not go through most of the logic of this function?
I.e. we can hit same OdspErrorType.snapshotTooBig when doing usePost = false and need to handle it the same way as this function does above, no?

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts (hunk 3 above)
Comment (vladsud) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:595]: I see - we are checking not snapshotOptions, but this.hostPolicy.snapshotOptions.
Maybe put some comments more clearly describing the difference (the original intention of the user).

In general, this is not good practice to use "global" state, it's better to pass both policies explicitly to a function, i.e. hostOptions (what is this.hostPolicy.snapshotOptions& driverOptions (what is snapshotOptions).
Or even better - if we can take logic around line 388 and just move it into this function, such that it only receives hostPolicy, but locally modified the values that it is about to use right here (I have not checked if it's easy / possible). That way code would be more readable / more localized

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts (hunk 7 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:601]: Actually it does go through all the logic of this function in case usePost is false. In try we pass value of usePost and not just true.

Comment (vladsud) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:601]: What I mean is that if we started with usePost = true, we may get 404, and then we call fetchSnapshotCore(). if we get OdspErrorType.snapshotTooBig there (in fetchSnapshotCore), we fail, and never run the logic above

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts (hunk 6 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts]: Yeah removed. Previously it should have been here because we had just usePost in if condition. But now because we added status code check, we can remove this. So removing.

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts [hunk 8]
```diff
@@ -563,52 +563,42 @@ export class OdspDocumentStorageService implements IDocumentStorageService {
...
-            snapshotOptions.timeout,
-        );
         try {
             const odspSnapshot = await this.fetchSnapshotCore(snapshotOptions, tokenFetchOptions, usePost, abortController);
             return odspSnapshot;
         } catch (error) {
+            const errorType = error.errorType;
             // If the snapshot size is too big and the host specified the size limitation, then don't try to fetch the snapshot again.
-            if (error.errorType === OdspErrorType.snapshotTooBig && this.hostPolicy.snapshotOptions?.mds !== undefined) {
+            if ((errorType === OdspErrorType.snapshotTooBig && this.hostPolicy.snapshotOptions?.mds !== undefined) && (this.hostPolicy.summarizerClient !== true)) {
```
Comment (vladsud) [inline packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts:589]: It would be nice to follow up with moving modification of original hostPolicy into this function (the other comment I had here)

**Review by vladsud — APPROVED** [review]

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts (hunk 3 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts]: Done as suggested. Now we pass the hostSnapshotOptions from above and separate them from driverSnapshotOptions.

File: packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts (hunk 8 above)
Comment (jatgarg) [reply packages/drivers/odsp-driver/src/odspDocumentStorageManager.ts]: Moved in this PR only.
