### PR TITLE
Fix blob attachment when using batches (Fixes #4166)

### LINKED ISSUE #4166: Blob attachments & batches do not work together
[1:21 PM] Daniel Lehenbauer
Discovered that Blob attachment does not work w/FlushMode.Manual or 'ordereSequentially'.  This is because ContainerRuntime.submit(..) clobbers the opMetadata with {​​​​​​​​ batch: true }​​​​​​​
Easy fix to merge instead of clobber, but I was wondering if blob attach could use localOpMetadata?

### PR DESCRIPTION
**Pull request by DLehenbauer**
When batching, the container runtime was clobbering the { blobId: * } metadata with { batch: true/false }.

### CODE REVIEW

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 1]
```diff
@@ -301,15 +301,15 @@ export class ScheduleManager {
                 return;
             }
 
-            // If only length one then clear
+            // If the batch contains only a single op, clear the batch flag.
             if (messages.length === 1) {
-                delete messages[0].metadata;
+                delete firstMessageMetadata.batch;
```
Comment (DLehenbauer) [inline packages/runtime/container-runtime/src/containerRuntime.ts:306]: First bug: should delete the 'batch: true' flag, not the entire message metadata.

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 2]
```diff
@@ -301,15 +301,15 @@ export class ScheduleManager {
...
                 return;
             }
 
             // Set the batch flag to false on the last message to indicate the end of the send batch
             const lastMessage = messages[messages.length - 1];
-            lastMessage.metadata = { ...lastMessage.metadata, ...{ batch: false } };
+            lastMessage.metadata = { ...lastMessage.metadata, batch: false };
```
Comment (DLehenbauer) [inline packages/runtime/container-runtime/src/containerRuntime.ts:312]: (Opportunistic cleanup...  not a bug.)

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 3]
```diff
@@ -571,7 +571,7 @@ export class ContainerRuntime extends TypedEventEmitter<IContainerRuntimeEvents>
         type: ContainerMessageType,
         content: any,
         localOpMetadata: unknown,
-        opMetaData: unknown,
+        opMetaData: Record<string, unknown> | undefined,
```
Comment (DLehenbauer) [inline packages/runtime/container-runtime/src/containerRuntime.ts:574]: Constraining 'opMetadata' to types that we can merge (i.e., can't be a number, a boolean, etc.)

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 4]
```diff
@@ -1892,9 +1893,9 @@ export class ContainerRuntime extends TypedEventEmitter<IContainerRuntimeEvents>
             const maxOpSize = this.context.deltaManager.maxMessageSize;
 
             // If in manual flush mode we will trigger a flush at the next turn break
-            let batchBegin = false;
             if (this.flushMode === FlushMode.Manual && !this.needsFlush) {
-                batchBegin = true;
+                // eslint-disable-next-line no-param-reassign
+                opMetadata = { ...opMetadata, batch: true };
                 this.needsFlush = true;
```
Comment (DLehenbauer) [inline packages/runtime/container-runtime/src/containerRuntime.ts:1899]: 'batchBegin' flag was only used to determine if we need to set { batch: true } below.

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 5]
```diff
@@ -571,7 +571,7 @@ export class ContainerRuntime extends TypedEventEmitter<IContainerRuntimeEvents>
         type: ContainerMessageType,
         content: any,
         localOpMetadata: unknown,
-        opMetaData: unknown,
+        opMetadata: Record<string, unknown> | undefined,
```
Comment (DLehenbauer) [inline packages/runtime/container-runtime/src/containerRuntime.ts:574]: 'opMetadata' must be constrained to "map-like objects" to ensure we can merge.

(Also, opMetaData -> opMetadata)

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 6]
```diff
@@ -1892,9 +1893,9 @@ export class ContainerRuntime extends TypedEventEmitter<IContainerRuntimeEvents>
             const maxOpSize = this.context.deltaManager.maxMessageSize;
 
             // If in manual flush mode we will trigger a flush at the next turn break
-            let batchBegin = false;
             if (this.flushMode === FlushMode.Manual && !this.needsFlush) {
-                batchBegin = true;
+                // eslint-disable-next-line no-param-reassign
+                opMetadata = { ...opMetadata, batch: true };
```
Comment (wes-carlson) [inline packages/runtime/container-runtime/src/containerRuntime.ts:1898]: Is it safe to merge this way? (we'll lose whatever "batch" might have been on the metadata passed in, right?)

**Review by wes-carlson — APPROVED** [review]

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 6 above)
Comment (DLehenbauer) [reply packages/runtime/container-runtime/src/containerRuntime.ts:1898]: It looks like container-level submit is private and that the publicly exposed submit methods do not pass 'opMetadata'.

**Comment by DLehenbauer** [comment]
Thanks, @wes-carlson !
