### PR TITLE
Close the container on errors from inside `ContainerRuntime.orderSequentially`

### LINKED ISSUE #8437: ContainerRuntime.orderSequentially() and exceptions from callback
Today, if exception is thrown from callback, we flush partial batch and continue.
This does not have clear semantics on what happens next (i.e. whoever runs such batch may close container, but likely he/she will not).
Even if container is closed, we still push partial batch out.
I think this is wrong and we should close container, similar how we do with any exception during op processing (DataCorruptionError, CreateProcessingError usages)

### PR DESCRIPTION
**Pull request by andre4i**
Closes https://github.com/microsoft/FluidFramework/issues/8437

### CODE REVIEW

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 1]
```diff
@@ -1651,10 +1653,12 @@ export class ContainerRuntime extends TypedEventEmitter<IContainerRuntimeEvents>
...
         try {
             this.trackOrderSequentiallyCalls(callback);
-        } finally {
-            this.flush();
-            this.setFlushMode(savedFlushMode);
+        } catch(error) {
+            this.closeFn(CreateProcessingError(error, "orderSequentially"));
         }
+
+        this.flush();
```
Comment (vladsud) [inline packages/runtime/container-runtime/src/containerRuntime.ts:1660]: Feels like these 2 statements can be inside of try body

**Review by vladsud — APPROVED** [review]
