### PR TITLE
hot fix: change compressSmallBlobs level to 2

### LINKED ISSUE #6917: Aggregated blobs: compressSmallBlobs() should change depth to 2
We need to find more robust way of doing it....

### PR DESCRIPTION
**Pull request by chensixx**
Fixes #6917 
In compressSmallBlobs, we are only aggregating data store trees, which has ".component" blobs. In this PR, we are checking this instead of depending on the packing level.
We will keep using the packing level to assert we are on the right level. and this is a new param for blobAggregationStorage constructor and .wrap(). this value is dependent on containerRuntime.disableIsolatedChannels. By default, disableIsolatedChannels is false, and there are .channel layers in the summary tree, so the packing level is 2. Otherwise it will be 1.
We also modified the blobAggregationStorage test so the summary tree has both .channels and .component. 
We may follow up to add another tree without .channels, but it was manually tested to be passing

### CODE REVIEW

File: packages/loader/driver-utils/src/blobAggregationStorage.ts [hunk 1]
```diff
@@ -312,7 +312,7 @@ export class BlobAggregationStorage extends SnapshotExtractor implements IDocume
             return summary;
         }
         // Only pack at data store level.
-        const startingLevel = level === 1;
+        const startingLevel = level === 2;
```
Comment (agarwal-navin) [inline packages/loader/driver-utils/src/blobAggregationStorage.ts:315]: Consider declaring a const called `dataStoreLevel` or similar and use that here and during unpacking so they are in sync.

File: packages/loader/driver-utils/src/test/blobAggregation.spec.ts [hunk 2]
```diff
@@ -172,15 +172,15 @@ describe("BlobAggregationStorage", () => {
         const { storage } = await prep(true, 2048);
 
         // Number of actual blobs in storage should be 2!
-        assert(storage.blobs.size === 3,
```
Comment (agarwal-navin) [inline packages/loader/driver-utils/src/test/blobAggregation.spec.ts:175]: This does not seem right. The `summaryTree` used in the test should be updated to reflect the new format with ".channels".

File: packages/loader/driver-utils/src/blobAggregationStorage.ts [hunk 3]
```diff
@@ -290,6 +290,7 @@ export class BlobAggregationStorage extends SnapshotExtractor implements IDocume
         return this.storage.uploadSummaryWithContext(summaryNew, context);
     }
 
+    static dataStoreLevel = 2;
```
Comment (agarwal-navin) [inline packages/loader/driver-utils/src/blobAggregationStorage.ts:293]: You can declare this as a const at the top of this file.

File: packages/loader/driver-utils/src/blobAggregationStorage.ts [hunk 4]
```diff
@@ -102,7 +102,7 @@ export abstract class SnapshotExtractor {
     public async unpackSnapshotCore(snapshot: ISnapshotTree, level = 0): Promise<void> {
         // for now only working at data store level, i.e.
         // .app/DataStore/...
-        if (level >= 3) {
+        if (level > BlobAggregationStorage.dataStoreLevel) {
```
Comment (agarwal-navin) [inline packages/loader/driver-utils/src/blobAggregationStorage.ts:105]: @vladsud @arinwt, ".channels" in the summary tree can be disabled by setting `disableIsolatedChannels` to true. We should account for that for the data store level while packing / unpacking right?

Comment (arinwt) [reply packages/loader/driver-utils/src/blobAggregationStorage.ts:105]: I'm not familiar with what exactly this code is doing, but for tracking the absolute depth level of a given datastore/dds within the summary tree, we do need to consider that .channels may or may not be there. If we are looking at an `ISnapshotTree`, we can identify if it will exist by looking at the .metadata blob (see code in ContainerRuntime for this).

For writing a summary tree, we use the `disableIsolatedChannels` property in ContainerRuntime to make that decision.

Comment (vladsud) [reply packages/loader/driver-utils/src/blobAggregationStorage.ts:105]: We can make unpacking unconditional (i.e. no checks) - there is not that much perf saving - scanning full tree does not take that long. For writing, we should rely on disableIsolatedChannels or better - some const that tells us the depth of data stores (i.e. exported by same package that exports disableIsolatedChannels )

File: packages/loader/driver-utils/src/blobAggregationStorage.ts [hunk 5]
```diff
@@ -312,7 +313,7 @@ export class BlobAggregationStorage extends SnapshotExtractor implements IDocume
             return summary;
         }
         // Only pack at data store level.
-        const startingLevel = level === 1;
+        const startingLevel = level === BlobAggregationStorage.dataStoreLevel;
```
Comment (vladsud) [inline packages/loader/driver-utils/src/blobAggregationStorage.ts:316]: What we can do also is instead of calculating this number based on disableIsolatedChannels, we can only enable it for trees that have .component blob. That way it would be more robust RE changes in depth. That said, it would now depend on structure of snapshots. So maybe doing both (asserting that it's one and the same) is best, because it would immediately warn us if depth or structured changed and we can adjust it before cutting release.

File: packages/loader/driver-utils/src/blobAggregationStorage.ts [hunk 6]
```diff
@@ -311,21 +315,23 @@ export class BlobAggregationStorage extends SnapshotExtractor implements IDocume
...
             return summary;
         }
-        // Only pack at data store level.
-        const startingLevel = level === 1;
+
+        let shouldCompress: boolean = false;
 
         let aggregator = aggregatorArg;
-        if (startingLevel) {
+        if (Object.keys(summary.tree).includes(".component")) {
```
Comment (agarwal-navin) [inline packages/loader/driver-utils/src/blobAggregationStorage.ts:322]: Add a comment explaining what we are doing here.

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 7]
```diff
@@ -538,7 +538,7 @@ export class ContainerRuntime extends TypedEventEmitter<IContainerRuntimeEvents>
                 runtimeVersion: pkgVersion,
             },
         });
-
+        const packingLevel = runtimeOptions?.summaryOptions?.disableIsolatedChannels ? 1 : 2;
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/containerRuntime.ts:541]: You should move the `combinedRuntimeOptions` generated below to here and use it instead. It doesn't matter today but if we add more default options, this may become incorrect.

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 8]
```diff
@@ -626,7 +626,8 @@ export class ContainerRuntime extends TypedEventEmitter<IContainerRuntimeEvents>
         // So once we release 0.40 container-defn package we can remove this check.
         if (!this._storage && this.context.storage) {
             // Note: BlobAggregationStorage is smart enough for double-wrapping to be no-op
-            this._storage = BlobAggregationStorage.wrap(this.context.storage, this.logger);
+            this._storage = BlobAggregationStorage.wrap(this.context.storage, this.logger,
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/containerRuntime.ts:629]: Add a comment why disableIsolatedChannels changes the value of packing level passed to BlobAggregateStorage.

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 7 above)
Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/containerRuntime.ts:541]: Also, add a comment why disableIsolatedChannels changes the value of packing level passed to BlobAggregateStorage.

File: packages/loader/driver-utils/src/test/blobAggregation.spec.ts [hunk 9]
```diff
@@ -156,16 +176,16 @@ describe("BlobAggregationStorage", () => {
         const { storage } = await prep(false, 2048);
 
         // NUmber of actual blobs in storage should be 4 - no aggregation!
```
Comment (agarwal-navin) [inline packages/loader/driver-utils/src/test/blobAggregation.spec.ts:178]: Update comment. Also fix NUmber -> Number

File: packages/loader/driver-utils/src/test/blobAggregation.spec.ts [hunk 10]
```diff
@@ -156,16 +176,16 @@ describe("BlobAggregationStorage", () => {
...
-        assert(storage.blobs.size === 5,
-            `Unexpected blob storage size: ${storage.blobs.size} vs expected 5`);
+        assert(storage.blobs.size === 7,
+            `Unexpected blob storage size: ${storage.blobs.size} vs expected 7`);
     });
 
     it("Noop aggregation (driver does not know about aggregation", async () => {
         const { storage } = await prep(true, undefined);
 
         // NUmber of actual blobs in storage should be 4 - no aggregation!
```
Comment (agarwal-navin) [inline packages/loader/driver-utils/src/test/blobAggregation.spec.ts:186]: Fix comment.

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 11]
```diff
@@ -550,7 +550,7 @@ export class ContainerRuntime extends TypedEventEmitter<IContainerRuntimeEvents>
                 // IContainerContext storage api return type still has undefined in 0.39 package version.
                 // So once we release 0.40 container-defn package we can remove this check.
                 assert(context.storage !== undefined, 0x1f4 /* "Attached state should have storage" */);
-                const aggrStorage = BlobAggregationStorage.wrap(context.storage, logger);
+                const aggrStorage = BlobAggregationStorage.wrap(context.storage, logger, undefined, packingLevel);
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/containerRuntime.ts:553]: Add /* allowPacking */ after undefined. See other places where we use /* */ after parameters.

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 12]
```diff
@@ -626,7 +626,8 @@ export class ContainerRuntime extends TypedEventEmitter<IContainerRuntimeEvents>
         // So once we release 0.40 container-defn package we can remove this check.
         if (!this._storage && this.context.storage) {
             // Note: BlobAggregationStorage is smart enough for double-wrapping to be no-op
-            this._storage = BlobAggregationStorage.wrap(this.context.storage, this.logger);
+            this._storage = BlobAggregationStorage.wrap(this.context.storage, this.logger,
+                undefined, this.disableIsolatedChannels ? 1 : 2);
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/containerRuntime.ts:630]: Add /* allowPacking / after undefined. See other places where we use / */ after parameters.

File: packages/loader/driver-utils/src/blobAggregationStorage.ts [hunk 13]
```diff
@@ -188,15 +182,16 @@ export class BlobAggregationStorage extends SnapshotExtractor implements IDocume
 
     protected virtualBlobs = new Map<string, ArrayBufferLike>();
 
-    static wrap(storage: IDocumentStorageService, logger: ITelemetryLogger, allowPacking = gatesAllowPacking()) {
+    static wrap(storage: IDocumentStorageService, logger: ITelemetryLogger, allowPacking = gatesAllowPacking(),
```
Comment (agarwal-navin) [inline packages/loader/driver-utils/src/blobAggregationStorage.ts:185]: nit: Please use proper formatting when parameters extend beyond 120 chars:
```
static wrap(
    storage: IDocumentStorageService,
    logger: ITelemetryLogger,
    allowPacking = gatesAllowPacking(),
    packingLevel = 2,
) {
```

File: packages/loader/driver-utils/src/blobAggregationStorage.ts [hunk 14]
```diff
@@ -311,21 +307,24 @@ export class BlobAggregationStorage extends SnapshotExtractor implements IDocume
...
             return summary;
         }
-        // Only pack at data store level.
-        const startingLevel = level === 1;
+
+        let shouldCompress: boolean = false;
 
         let aggregator = aggregatorArg;
-        if (startingLevel) {
+        // checking if this is a dataStore tree
```
Comment (agarwal-navin) [inline packages/loader/driver-utils/src/blobAggregationStorage.ts:314]: nit: Consider adding that we only compress at data store level

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 15]
```diff
@@ -539,6 +539,16 @@ export class ContainerRuntime extends TypedEventEmitter<IContainerRuntimeEvents>
             },
         });
 
+        const backCompatRuntimeOptions = getBackCompatRuntimeOptions(runtimeOptions);
+        const defaultRuntimeOptions: Required<IContainerRuntimeOptions> = {
+            summaryOptions: { generateSummaries: true },
+            gcOptions: {},
+        };
+        const combinedRuntimeOptions = { ...defaultRuntimeOptions, ...backCompatRuntimeOptions };
+        // if isolated channels are disabled, then there are no .channel layers, we pack at level 1,
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/containerRuntime.ts:548]: Add that we pack at data store level only. if isolated channels are disabled, then there are no .channel layers, so data stores at level 1 else at level2

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 16]
```diff
@@ -550,21 +560,15 @@ export class ContainerRuntime extends TypedEventEmitter<IContainerRuntimeEvents>
                 // IContainerContext storage api return type still has undefined in 0.39 package version.
                 // So once we release 0.40 container-defn package we can remove this check.
                 assert(context.storage !== undefined, 0x1f4 /* "Attached state should have storage" */);
-                const aggrStorage = BlobAggregationStorage.wrap(context.storage, logger);
+                const aggrStorage = BlobAggregationStorage.wrap(context.storage, logger,
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/containerRuntime.ts:563]: nit: fix formatting:
```
const aggrStorage = BlobAggregationStorage.wrap(
    context.storage,
    logger,
    undefined /* allowPacking */,
    packingLevel,
);
```

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 17]
```diff
@@ -626,7 +630,10 @@ export class ContainerRuntime extends TypedEventEmitter<IContainerRuntimeEvents>
         // So once we release 0.40 container-defn package we can remove this check.
         if (!this._storage && this.context.storage) {
             // Note: BlobAggregationStorage is smart enough for double-wrapping to be no-op
-            this._storage = BlobAggregationStorage.wrap(this.context.storage, this.logger);
+            // If isolated channels are disabled, then there are no .channel layers, we pack at level 1,
+            // otherwise we pack at level 2
+            this._storage = BlobAggregationStorage.wrap(this.context.storage, this.logger,
+                undefined /* allowPacking */, this.disableIsolatedChannels ? 1 : 2);
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/containerRuntime.ts:636]: Fix formatting and update comment as per my other comment.

File: packages/loader/driver-utils/src/blobAggregationStorage.ts [hunk 18]
```diff
@@ -311,21 +311,24 @@ export class BlobAggregationStorage extends SnapshotExtractor implements IDocume
...
 
         let aggregator = aggregatorArg;
-        if (startingLevel) {
+        // checking if this is a dataStore tree, since we only pack at data store level
+        if (Object.keys(summary.tree).includes(".component")) {
             assert(aggregator === undefined, 0x0fb /* "logic err with aggregator" */);
+            assert(level === this.packingLevel, "we are not packing at the right level");
             aggregator = new BlobAggregator();
+            shouldCompress = true;
         }
```
Comment (vladsud) [inline packages/loader/driver-utils/src/blobAggregationStorage.ts:324]: would be great to have reverse check as well i.e.
} else {
    assert(level !== this.packingLevel);
}

File: packages/loader/driver-utils/src/blobAggregationStorage.ts [hunk 19]
```diff
@@ -188,15 +182,20 @@ export class BlobAggregationStorage extends SnapshotExtractor implements IDocume
 
     protected virtualBlobs = new Map<string, ArrayBufferLike>();
 
-    static wrap(storage: IDocumentStorageService, logger: ITelemetryLogger, allowPacking = gatesAllowPacking()) {
+    static wrap(
+        storage: IDocumentStorageService,
+        logger: ITelemetryLogger,
+        allowPacking = gatesAllowPacking(),
+        packingLevel = 2,
```
Comment (vladsud) [inline packages/loader/driver-utils/src/blobAggregationStorage.ts:189]: It feels like it needs to be required argument, not optional

**Review by vladsud — APPROVED** [review]

File: packages/loader/driver-utils/src/blobAggregationStorage.ts (hunk 19 above)
Comment (chensixx) [reply packages/loader/driver-utils/src/blobAggregationStorage.ts:189]: it's optional during one use by fetch tool...

**Review by agarwal-navin — APPROVED** [review]
