### PR TITLE
Fix ODSP driver data store ID issue and Loader.request() test

### LINKED ISSUE #5359: ODSP driver does not correctly handle data store IDs
Calling `Container.getAbsoluteUrl()` when using ODSP driver results in URLs like the following:
```
"https://[subdomain].sharepoint.com/default?driveId=[driveId]&itemId=[itemId]&path=%2F&containerPackageName=loaderRequestTestPackage"
"https://[subdomain].sharepoint.com/0a252f54-dec1-497b-9606-384a31ee398c?driveId=[driveId]&itemId=[itemId]+&path=%2F&containerPackageName=loaderRequestTestPackage"
```
Note that the data store ID follows the URL domain and the `path` query param is `/` in both cases. Passing this URL to `Loader.request()`, it calls `urlResolver.resolve()` and then parses the returned `IFluidResolvedUrl.url`:
```
"fluid-odsp://placeholder/placeholder/[docId]/?driveId=[driveId]&itemId=[itemId]&path=%2F&containerPackageName=loaderRequestTestPackage"
"fluid-odsp://placeholder/placeholder/[docId]/?driveId=[driveId]&itemId=[itemId]&path=%2F&containerPackageName=loaderRequestTestPackage"
```
The data store ID is absent in these URLs, causing the request to always be routed to the default data store.

cf. `LocalResolver` which produces absolute URLs like this:
```
"http://localhost:3000/ed3c944f-abb8-449b-b72b-2ce29891f78d/default"
"http://localhost:3000/ed3c944f-abb8-449b-b72b-2ce29891f78d/4da1d8b4-93bc-4562-9e3c-4b12808f2d1e"
```
and `IFluidResolvedUrl.url`s like this:
```
"fluid-test://localhost:3000/tenantId/ed3c944f-abb8-449b-b72b-2ce29891f78d/default"
"fluid-test://localhost:3000/tenantId/ed3c944f-abb8-449b-b72b-2ce29891f78d/4da1d8b4-93bc-4562-9e3c-4b12808f2d1e"
```
which are correctly routed to the appropriate data store.

### PR DESCRIPTION
**Pull request by wes-carlson**
Fix #5359 and fix Loader.request() test running against ODSP.

### CODE REVIEW

**Comment by jatgarg** [comment]
I think you need to fix some trivial unit tests in odsp driver based on this change.

File: packages/drivers/odsp-driver/src/odspDriverUrlResolver.ts [hunk 1]
```diff
@@ -140,7 +140,7 @@ export class OdspDriverUrlResolver implements IUrlResolver {
         }
         const odspResolvedUrl = resolvedUrl as IOdspResolvedUrl;
         let odspUrl = `${odspResolvedUrl.siteUrl}/${url}?driveId=${encodeURIComponent(odspResolvedUrl.driveId,
-            )}&itemId=${encodeURIComponent(odspResolvedUrl.itemId)}&path=${encodeURIComponent("/")}`;
+            )}&itemId=${encodeURIComponent(odspResolvedUrl.itemId)}&path=${encodeURIComponent(url)}`;
```
Comment (agarwal-navin) [inline packages/drivers/odsp-driver/src/odspDriverUrlResolver.ts:143]: `url` is encoded twice in odspUrl now. What is `path` supposed to have?

Comment (jatgarg) [reply packages/drivers/odsp-driver/src/odspDriverUrlResolver.ts:143]: Path is the data store path.

Comment (agarwal-navin) [reply packages/drivers/odsp-driver/src/odspDriverUrlResolver.ts:143]: It can be "any" path that needs to be passed to the Container right; doesn't have to be a data store path. I am a little concerned that it is now part of the osdpUrl twice. Can we see a real example of what this URL looks like for a fluid document?

Comment (agarwal-navin) [reply packages/drivers/odsp-driver/src/odspDriverUrlResolver.ts:143]: Also, we should add tests that covers the changes here.

Comment (jatgarg) [reply packages/drivers/odsp-driver/src/odspDriverUrlResolver.ts:143]: Sorry what other path would it be if not the data store path?

Comment (agarwal-navin) [reply packages/drivers/odsp-driver/src/odspDriverUrlResolver.ts:143]: It can be anything that the app wants to pass to the container. You can register request handlers to process any request. For example, path to a blob, initial configs, etc.

Comment (jatgarg) [reply packages/drivers/odsp-driver/src/odspDriverUrlResolver.ts:143]: @wes-carlson So url is already there in odspurl, why do we need to add it twice?

Comment (wes-carlson) [reply packages/drivers/odsp-driver/src/odspDriverUrlResolver.ts:143]: I originally tried changing `resolve()` to consume the path from the url pathname where `getAbsoluteUrl()` puts it currently, but this caused other unit tests to fail:
```
fluid url does not match

      + expected - actual

      -fluid-odsp://placeholder/placeholder/iNKF5NbXkQ9HFHj62PjIkOuQxDamm0zbffgsz8gigBA%3D/_api/v2.1/drives/randomDrive/items/randomItem/?driveId=randomDrive&itemId=randomItem&path=
      +fluid-odsp://placeholder/placeholder/iNKF5NbXkQ9HFHj62PjIkOuQxDamm0zbffgsz8gigBA%3D/?driveId=randomDrive&itemId=randomItem&path=
```

These seem more like "real" test failures than the ones that are currently failing, since I don't think `_api/v2.1/drives/randomDrive/items/randomItem` should be in the url.

Comment (jatgarg) [reply packages/drivers/odsp-driver/src/odspDriverUrlResolver.ts:143]: Yes instead of "_api/v2.1/drives/randomDrive/items/randomItem", I think it should be the path?

Comment (agarwal-navin) [reply packages/drivers/odsp-driver/src/odspDriverUrlResolver.ts:143]: I think we should discuss with ODSP folks as to what the expected behavior here is. If we return an incorrect url here, everything will fail!

Comment (jatgarg) [reply packages/drivers/odsp-driver/src/odspDriverUrlResolver.ts:143]: @wes-carlson We are already adding the relative path passed in getAbsoluteUrl api to the returned URL.  Does it create wrong urls where we are not able to correctly route the request to apt datastore?

Comment (jatgarg) [reply packages/drivers/odsp-driver/src/odspDriverUrlResolver.ts:143]: So I think the relative path that we are passing to getAbsoluteUrl is wrong, as per your example?

Comment (wes-carlson) [reply packages/drivers/odsp-driver/src/odspDriverUrlResolver.ts:143]: > Does it create wrong urls where we are not able to correctly route the request to apt datastore?

Yes, there's more detail in the linked issue (#5359), but `resolve()` puts the pathname of the url into `siteUrl` but not `url`, which is used by loader.

> So I think the relative path that we are passing to getAbsoluteUrl is wrong, as per your example?

Not sure what you mean, where are we doing that?

**Comment by jatgarg** [comment]
> 

So we do correctly add path here in document url which will be used by loader.request to resolve the request.

---
Refers to: packages/drivers/odsp-driver/src/odspDriverUrlResolver.ts:99 in 23ba502. [](commit_id = 23ba5022cdac368ea563532560d770e1ca4c8785, deletion_comment = False)

**Comment by jatgarg** [comment]
>         let documentUrl = `fluid-odsp://placeholder/placeholder/${hashedDocumentId}/${removeBeginningSlash(path)}`;

We do add the path correctly here in fluid url. So we need to fix the path supplied in abs url. 
So if you see here: [https://github.com/microsoft/FluidFramework/blob/81d0e131b3a9cae4b2afad1a49eabcda68afca50/packages/drivers/odsp-driver/src/odspDriverUrlResolverForShareLink.ts#L195](https://github.com/microsoft/FluidFramework/blob/81d0e131b3a9cae4b2afad1a49eabcda68afca50/packages/drivers/odsp-driver/src/odspDriverUrlResolverForShareLink.ts#L195)
we do add the relative path in dataStorePath and then use that in resolve to then add it as path in createOdspUrl. So your change is correct.

---
Refers to: packages/drivers/odsp-driver/src/odspDriverUrlResolver.ts:98 in 23ba502. [](commit_id = 23ba5022cdac368ea563532560d770e1ca4c8785, deletion_comment = False)

File: packages/runtime/test-runtime-utils/src/insecureUrlResolver.ts [hunk 2]
```diff
@@ -55,8 +55,8 @@ export class InsecureUrlResolver implements IUrlResolver {
         // If hosts match then we use the local tenant information. Otherwise we make a REST call out to the hosting
         // service using our bearer token.
         if (this.isForNodeTest) {
-            const documentId = parsedUrl.pathname.substr(1).split("/")[1];
-            return this.resolveHelper(documentId, "");
+            const [, documentId, relativePath] = parsedUrl.pathname.substr(1).split("/");
+            return this.resolveHelper(documentId, `/${relativePath}`, parsedUrl.search);
```
Comment (jatgarg) [inline packages/runtime/test-runtime-utils/src/insecureUrlResolver.ts:59]: You can relative path without "/" here and then in resolve helper make sure  if it does not have slash then prefix "/". So in that way user can pass anything for relative path with or without slash.

File: packages/drivers/odsp-driver/src/odspDriverUrlResolver.ts [hunk 3]
```diff
@@ -139,8 +139,8 @@ export class OdspDriverUrlResolver implements IUrlResolver {
             url = url.substr(1);
         }
         const odspResolvedUrl = resolvedUrl as IOdspResolvedUrl;
-        let odspUrl = `${odspResolvedUrl.siteUrl}/${url}?driveId=${encodeURIComponent(odspResolvedUrl.driveId,
-            )}&itemId=${encodeURIComponent(odspResolvedUrl.itemId)}&path=${encodeURIComponent("/")}`;
+        let odspUrl = `${odspResolvedUrl.siteUrl}/?driveId=${encodeURIComponent(odspResolvedUrl.driveId,
+            )}&itemId=${encodeURIComponent(odspResolvedUrl.itemId)}&path=${encodeURIComponent(url)}`;
```
Comment (anthony-murphy) [inline packages/drivers/odsp-driver/src/odspDriverUrlResolver.ts:143]: change this to use createOdspUrl

**Comment by anthony-murphy** [comment]
>         const resolvedUrl = await resolver.resolve(request);

for all the resolves here can you add validation to the resolvedrUrl, specificly assert.stringDeepEquals(resovledUlr, {...the expected object})

---
Refers to: packages/drivers/odsp-driver/src/test/odspDriverResolverTest.spec.ts:85 in 5df0e27. [](commit_id = 5df0e275cc2b547f0b07ed0b35a16c9689c448bb, deletion_comment = False)

**Review by jatgarg — APPROVED** [review]
