### PR TITLE
Get IFrame-Host working again

### LINKED ISSUE #4013: Get iframe-host working again
Currently starting iframe-host package doesn't work as expected and has a bunch of errors.  The package hasn't been updated to support the updates the past few months and needs to be fixed.

### PR DESCRIPTION
**Pull request by heliocliu**
Fixes #4013 
-fix comlink import warnings
-use Comlink.proxy on non-transferrable proxy members
-some interface type refactoring
-load code from a static import instead of through the cdn because the cdn is no longer updated

### CODE REVIEW

File: examples/hosts/iframe-host/src/outer.ts [hunk 1]
```diff
@@ -2,35 +2,25 @@
...
+import { InsecureTinyliciousUrlResolver } from "@fluidframework/get-tinylicious-container";
 import {
     RouterliciousDocumentServiceFactory,
 } from "@fluidframework/routerlicious-driver";
-import { IFluidCodeDetails } from "@fluidframework/container-definitions";
-import { BaseHost } from "@fluidframework/base-host";
-import { IRequest } from "@fluidframework/core-interfaces";
-import { InsecureUrlResolver } from "@fluidframework/test-runtime-utils";
-import { SemVerCdnCodeResolver } from "@fluidframework/web-code-loader";
+// import { InsecureUrlResolver } from "@fluidframework/test-runtime-utils";
```
Comment (heliocliu) [inline examples/hosts/iframe-host/src/outer.ts:14]: cleaned this up

File: examples/hosts/iframe-host/src/outer.ts [hunk 2]
```diff
@@ -71,31 +67,32 @@ async function getFluidObjectAndRender(baseHost: BaseHost, url: string, div: HTM
...
     };
 
-    const baseHost = new BaseHost(
-        {
-            codeResolver: new SemVerCdnCodeResolver(),
-            documentServiceFactory,
-            urlResolver,
-            options: {},
-        });
+    const module = { fluidExport: TodoContainer };
```
Comment (heliocliu) [inline examples/hosts/iframe-host/src/outer.ts:80]: This stuff can probably be refactored into another IFrameHost class similar to base-host (base-host expects to use the WebCodeLoader internally which isn't how the data object is being loaded here)

File: examples/utils/get-tinylicious-container/src/getTinyliciousContainer.ts [hunk 3]
```diff
@@ -25,7 +25,7 @@ import { getContainer } from "./getContainer";
  * URL shape, so it expects the request url to have this format (as opposed to a more traditional URL):
  * documentId/containerRelativePathing
  */
-class InsecureTinyliciousUrlResolver implements IUrlResolver {
+export class InsecureTinyliciousUrlResolver implements IUrlResolver {
```
Comment (ChumpChief) [inline examples/utils/get-tinylicious-container/src/getTinyliciousContainer.ts:28]: TBH I'm a little worried about the proliferation of these utilities.  I created `getTinyliciousContainer` as a bandaid originally because working with the url resolver is painful and not necessary for most scenarios, and so I intentionally did not expose it.  So if working with the url resolver is necessary for a scenario, then perhaps it would be better to step away from these utils and do something more legit.  I think this might slowly devolve back into the original `InsecureUrlResolver` otherwise.

I wouldn't object to the change necessarily, but I think it's more evidence that we need a better permanent solution sooner than later.

File: examples/hosts/iframe-host/src/outer.ts [hunk 4]
```diff
@@ -2,35 +2,25 @@
...
-const getTinyliciousResolver =
-    () => new InsecureUrlResolver(
-        "http://localhost:3000",
-        "http://localhost:3000",
-        "http://localhost:3000",
-        "tinylicious",
-        "12345",
-        { id: "userid0" },
-        "bearer");
+const documentId = `testdoc${Math.floor(Math.random() * 10000)}`;
```
Comment (ChumpChief) [inline examples/hosts/iframe-host/src/outer.ts:18]: The random here makes it so the doc is lost when refreshing the page and could theoretically have name collisions (although rare) - consider doing something like in the app-integration samples using a timestamp or other predictably-unique ID, plus putting it in the page URL so page refresh works.

Comment (ChumpChief) [reply examples/hosts/iframe-host/src/outer.ts:18]: Playing with it a bit, looks like this will expose some bugs in the refresh scenario that also need ironed out.

Comment (heliocliu) [reply examples/hosts/iframe-host/src/outer.ts:18]: there's the issue with how outer doesn't handle the refresh that i need to cover with the host refactoring, were there any other issues that you saw?

Comment (ChumpChief) [reply examples/hosts/iframe-host/src/outer.ts:18]: I didn't look super hard, just made the small change to see if it would magically work or not :)  I think that's probably what I was seeing though, I think the inner was working correctly if I remember right

File: examples/utils/get-tinylicious-container/src/getTinyliciousContainer.ts (hunk 3 above)
Comment (heliocliu) [reply examples/utils/get-tinylicious-container/src/getTinyliciousContainer.ts:28]: I was having some trouble with the plain `InsecureUrlResolver` with tinylicious information that was there before, but that appears to be because I just constructed the request wrongly, so it can keep using that.  It's still _very_ similar to what's happening here, though I'm not sure that contributes further to needing the better permanent solution then?

Comment (heliocliu) [reply examples/utils/get-tinylicious-container/src/getTinyliciousContainer.ts]: Ended up being able to use `getTinyliciousContainer` for one spot, and kept the old `getTinyliciousResolver` for the other (though the existing `getTinyliciousResolver` is basically a dupe of `InsecureTinyliciousUrlResolver`)

File: examples/hosts/iframe-host/README.md [hunk 5]
```diff
@@ -1,3 +1,7 @@
 # @fluid-example/iframe-host
 
-_Coming soon..._
+Experimental host to test isolating containers in IFrames.
```
Comment (tylerbutler) [inline examples/hosts/iframe-host/README.md:3]:
```suggestion
An experimental host to test isolating containers in IFrames.
```

File: examples/hosts/iframe-host/src/inner.ts [hunk 6]
```diff
@@ -21,27 +27,23 @@ async function getFluidObjectAndRender(baseHost: BaseHost, url: string, div: HTM
...
+
+    const loader = new Loader({
+        urlResolver: documentServiceFactory.urlResolver,
+        documentServiceFactory,
+        codeLoader,
+    });
 
     const url = documentServiceFactory.resolvedUrl.url;
-    const container = await baseHost.initializeContainer(url, pkg);
+    const documentId = decodeURIComponent(url.replace("fluid://localhost:3000/tinylicious/", ""));
```
Comment (anthony-murphy) [inline examples/hosts/iframe-host/src/inner.ts:41]: > const documentId = decodeURIComponent(url.replace("fluid://localhost:3000/tinylicious/", "")); [](start = 3, length = 95)

can't think come from the resolve url above?

**Review by anthony-murphy — CHANGES_REQUESTED** [review]
:clock1:

**Review by anthony-murphy — APPROVED** [review]
:shipit:

**Comment by anthony-murphy** [comment]
looks good as a first step to get it working again

File: examples/hosts/iframe-host/src/inner.ts (hunk 6 above)
Comment (heliocliu) [reply examples/hosts/iframe-host/src/inner.ts:41]: Nothing in `IFluidResolvedUrl` equal to this (copied this from the insecuretinyliciousurlresolver 🤔)

**Comment by curtisman** [comment]
Closing and reopening to trigger build

**Review by ChumpChief — APPROVED** [review]
I see a console error due to `getAbsoluteUrl` not implemented in `InnerUrlResolver` that might be worth taking a look at (looks like it's tracked by #2109), but it doesn't seem to prevent the demo from functioning.  Definitely good to see this working :)

**Comment by heliocliu** [comment]
> 
> 
> I see a console error due to `getAbsoluteUrl` not implemented in `InnerUrlResolver` that might be worth taking a look at (looks like it's tracked by #2109), but it doesn't seem to prevent the demo from functioning. Definitely good to see this working :)

I think I saw that too, but it was the resolver from inside the todo component instead of the iframe host?  I'll take a look again next time i see it but if it's from the data object then i doubt it will really cause problems
