### PR TITLE
Fix issue #2724 and forceReadonly API while connected

### LINKED ISSUE #2724: Avoid multiple dirty->clean->dirty transition event sent on processing ops after reconnection
Currently, when we reconnect and we have pending ops, we clean the dirty flags (in case we don't need to resend anything) causing extra transitions.  We should avoid those event since logically, the document didn't really get saved in between.

### PR DESCRIPTION
**Pull request by curtisman**
- Improve readability of documentDirty tests
- Add assert that we only get event when state changes (i.e. no double dirty or double save event)
- Fix issue #2724 by making the disable emitting the event while replay.
- forceReadonly(true) can't be set when it is connected.  So the API will implicit disconnect and reconnect if it was connected.
- Added test with forceReadonly, replay and document dirty state.  Identified and fixed replay op on changing force read only mode
    - There was an issue that documentDirty bit is clear but not being replayed when we transitioning to force read only mode.  
        - The fix is only to "clear" the flags if we are going to replay.
    - replay is different transition out of force readonly mode, where we don't clear the dirty flag first. So if there is a DDS that might cancel a pending up while replaying ops, we will not clear the dirty flag.  
        - The fix is reuse the same function in both case so they have the same behavior.

### CODE REVIEW

File: packages/loader/container-loader/src/deltaManager.ts [hunk 1]
```diff
@@ -325,12 +325,30 @@ export class DeltaManager
...
+     * there are pending in the outbound queue, it will stop sending until force readonly is
+     * cleared.
+     *
+     * @param readonly - set or clear force readonly.
      */
     public forceReadonly(readonly: boolean) {
         const oldValue = this.readonly;
         this._forceReadonly = readonly;
         if (oldValue !== this.readonly) {
+            let reconnect = false;
```
Comment (vladsud) [inline packages/loader/container-loader/src/deltaManager.ts:340]: I'm not certain reconnection is right flow.
We might be already connected as "read"
Also re-connecting as "read" can still give you "write" connection - server is free to give you more.

Also this._reconnectMode might be ReconnectMode.Never or ReconnectMode.Disabled, in such case we should not reconnect (this is checked in reconnectOnError(), which probably should be duplicated via assert connectCore(), but it also likely point out that we are better off using reconnectOnError() flow vs. manually disconnecting and reconnecting.

I'd rather either scope the usage of this API to disconnected state, OR not touch connection, but operate only with readonly property. Latter is simpler and feels better, but it breaks the assumption that we somewhat ride on here - that connection properties (like permissions, read-only, etc.) are changed only on granularity of connections.

File: packages/loader/container-loader/src/deltaManager.ts [hunk 2]
```diff
@@ -472,7 +490,22 @@ export class DeltaManager
...
+     * Start the connection. Any error should result in container being close.
+     * And report the error if it excape for any reason.
+     * @param args - The connection arguments
+     */
+    private triggerConnect(args: IConnectionArgs) {
+        this.connectCore(args).catch((err) => {
+            // Errors are raised as "error" event and close container.
+            // Have a catch-all case in case we missed something
+            if (!this.closed) {
+                this.logger.sendErrorEvent({ eventName: "ConnectException" }, err);
```
Comment (vladsud) [inline packages/loader/container-loader/src/deltaManager.ts:503]: I'd not log anything (and ideally make connectCore void, i.e. fire and forget).
DeltaManager already reports properly all the errors.
The only reason connectCore() returns anything is to support deprecated creation-on-connection flow that should be removed from code base.

Comment (vladsud) [reply packages/loader/container-loader/src/deltaManager.ts:503]: Ah, it's moved code...

File: packages/runtime/container-runtime/src/containerRuntime.ts [hunk 3]
```diff
@@ -1111,22 +1110,36 @@ export class ContainerRuntime extends TypedEventEmitter<IContainerRuntimeEvents>
         return { snapshot, state };
     }
 
+    private replayPendingStates() {
+        // We need to be able to send ops to replay states
+        if (!this.canSendOps()) { return; }
+
+        // Save the old state, reset to false, disable event emit
```
Comment (vladsud) [inline packages/runtime/container-runtime/src/containerRuntime.ts:1117]: Some comments on the reasons for all this state management would be great.
Also should we use helper classes to make sure right stuff happens if exception is thrown from here?

File: packages/test/end-to-end-tests/src/test/documentDirty.spec.ts [hunk 4]
```diff
@@ -44,7 +44,13 @@ describe("Document Dirty", () => {
      */
     async function waitForContainerReconnection(c: Container): Promise<void> {
         assert.equal(c.connected, false);
-        await new Promise((resolve) => c.once("connected", () => resolve()));
+        return new Promise((resolve) => c.once("connected", () => resolve()));
+    }
+
+    async function ensureForContainerConnected(c: Container): Promise<void> {
```
Comment (vladsud) [inline packages/test/end-to-end-tests/src/test/documentDirty.spec.ts:50]: maybe waitForContainerConnected?
or ensureContainerConnected?

File: packages/test/end-to-end-tests/src/test/documentDirty.spec.ts [hunk 5]
```diff
@@ -284,98 +249,104 @@ describe("Document Dirty", () => {
...
+    });
+
+    describe("Force readonly", () => {
+        it(`sets operations when force readonly and then turn off force readonly to process them`, async () => {
+            container.forceReadonly(true);
+            await ensureForContainerConnected(container);
 
-            assert.equal(wasMarkedDirtyCount, 1,
-                `Document will not increment the dirty count as it was already dirty`);
+            // Set values in DDSes in disconnected state.
```
Comment (vladsud) [inline packages/test/end-to-end-tests/src/test/documentDirty.spec.ts:304]: Comment does not match call above

File: packages/test/end-to-end-tests/src/test/documentDirty.spec.ts [hunk 6]
```diff
@@ -284,98 +249,104 @@ describe("Document Dirty", () => {
...
 
-            // Wait for the Container to get reconnected.
-            await waitForContainerReconnection(container);
+            // Document should have been marked dirty again due to pending DDS ops
+            checkDirtyState("after value set while force readonly", true, 0);
 
-            // Document will have been marked clean on reconnection
-            assert.equal(wasMarkedCleanCount, 1,
-                "Document will have been marked clean on reconnection");
+            container.forceReadonly(false);
```
Comment (vladsud) [inline packages/test/end-to-end-tests/src/test/documentDirty.spec.ts:312]: not sure if you check anywhere, if not, can you please check that container is actually in read-only state after flipping true and is not after false?
The best way to validate it is to have a component that reports last seen "readonly" event on datastore runtime (I think)

File: packages/loader/container-loader/src/deltaManager.ts (hunk 1 above)
Comment (curtisman) [reply packages/loader/container-loader/src/deltaManager.ts:340]: I would only reconnect if we switch from write to read, and it really does matter what permission the server give us.  We don't rely on that to stop sending ops to the server, but explicity depend on the readonly flag.

Not touching the connection is where we have problems with the assert in the readonly event handler, because we can't replay the ops after we reconnect on the same connection.

Logically, this is an internal disconnect reconnect, not auto reconnect which I thought the reconnectMode is supposed to control.  What is the usage of reconnectMode?

File: packages/loader/container-loader/src/deltaManager.ts (hunk 2 above)
Comment (curtisman) [reply packages/loader/container-loader/src/deltaManager.ts:503]: yep... we can't clean it up later, but I am reusing existing code.

**Review by agarwal-navin — APPROVED** [review]
The document dirty event part looks good to me.

File: packages/loader/container-loader/src/deltaManager.ts (hunk 1 above)
Comment (vladsud) [reply packages/loader/container-loader/src/deltaManager.ts:340]: It makes sense. One thing to consider though - this is not fully invisible to users. For example, if that functionality would have been applied to summarizing container, then it would puke, because it notices disconnects and stops.
But I guess we can leave with it.

**Review by vladsud — APPROVED** [review]

File: packages/loader/container-loader/src/deltaManager.ts (hunk 1 above)
Comment (curtisman) [reply packages/loader/container-loader/src/deltaManager.ts:340]: True..... may be we can disable this API for summarizing clients?   I will leave it for now.

File: packages/runtime/container-runtime/src/containerRuntime.ts (hunk 3 above)
Comment (curtisman) [reply packages/runtime/container-runtime/src/containerRuntime.ts:1121]: added.

File: packages/test/end-to-end-tests/src/test/documentDirty.spec.ts (hunk 6 above)
Comment (curtisman) [reply packages/test/end-to-end-tests/src/test/documentDirty.spec.ts:312]: @vladris has a PR for some forceReadonly specific test.  I will leave it to be added there.
