### PR TITLE
Fix for GC test mode assert not taking local storage flag into account

### LINKED ISSUE #6064: Fix: assert in `DataStores::deleteUnusedRoutes` is incorrect
It asserts that we the gcOptions have `runGCInTestMode`. However, GC test mode can be enabled via local storage flag too.

### PR DESCRIPTION
**Pull request by agarwal-navin**
Fixes #6064.

The assert in `DataStores::deleteUnusedRoutes` asserts that we the gcOptions have runGCInTestMode. However, GC test mode can be enabled via local storage flag too.
Fixed it to check for both.

### CODE REVIEW

File: packages/runtime/container-runtime/src/localStorageFeatureGates.ts [hunk 1]
```diff
@@ -0,0 +1,32 @@
+/*!
+ * Copyright (c) Microsoft Corporation and contributors. All rights reserved.
+ * Licensed under the MIT License.
+ */
+
+// Local storage key to turn GC on / off.
+export const runGCKey = "FluidRunGC";
```
Comment (vladsud) [inline packages/runtime/container-runtime/src/localStorageFeatureGates.ts:7]: I'd move these two keys out of this file to more appropriate place (ideally they stay only in container runtime and data stores does not need to know about them)

**Review by vladsud — APPROVED** [review]

File: packages/runtime/container-runtime/src/localStorageFeatureGates.ts (hunk 1 above)
Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/localStorageFeatureGates.ts:7]: The `DataStores` class needs to know about the gc test mode key to validate that we don't delete data stores if we are not in this mode.

Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/localStorageFeatureGates.ts]: @vladsud I added a method to ContainerRuntime that tells whether its in GC test mode and DataStores calls it. Movded these keys to ContainerRuntime. Do you think this is better?

**Review by vladsud — APPROVED** [review]
