### PR TITLE
Fix broken Container error log

### LINKED ISSUE #5093: Add "op timestamp" to "messageClientIdShouldHaveLeft" error thrown in Container
Once we get this error, the container is closed. However, the document is not in an unreliable / corrupted state. The op that causes this can come back and fail at somewhere down the stack.
Adding "op timestamp" will give an indication of when this document was corrupted. Also, investigate and add other fields that can help debugging this issue.

### PR DESCRIPTION
**Pull request by markfields**
Fixes #5093 and #5095

This is a minimal fix.  See [this branch](https://github.com/microsoft/FluidFramework/compare/main...markfields:container-error?expand=1) for some additional refactoring we may consider in this space, that @ksbrar and I paired on.

### CODE REVIEW

File: packages/loader/container-loader/src/container.ts [hunk 1]
```diff
@@ -1619,11 +1619,13 @@ export class Container extends EventEmitterWithErrorHandling<IContainerEvents> i
             if (errorMsg !== undefined) {
                 const error = new GenericError(
                     errorMsg,
+                    undefined,
                     {
                         clientId: this._clientId,
                         messageClientId: message.clientId,
                         sequenceNumber: message.sequenceNumber,
                         clientSequenceNumber: message.clientSequenceNumber,
+                        opTimestamp: message.timestamp,
```
Comment (agarwal-navin) [inline packages/loader/container-loader/src/container.ts:1628]: messageTimestamp may be more appropriate and more in line with messageClientId above.

**Review by ksbrar — APPROVED** [review]
Still weird that for a GenericError, the "error" paramater in the constructor is essentially ignored - but to be addressed later.

File: packages/loader/container-utils/src/error.ts [hunk 2]
```diff
@@ -30,8 +30,9 @@ export class GenericError extends LoggingError implements IGenericError {
     constructor(
         errorMessage: string,
         readonly error: any,
+        props?: ITelemetryProperties,
     ) {
-        super(errorMessage);
```
Comment (anthony-murphy) [inline packages/loader/container-utils/src/error.ts:34]: can you add a quick ut here. should be easy given the tests @ksbrar added

File: packages/loader/container-loader/src/container.ts [hunk 3]
```diff
@@ -1619,11 +1619,13 @@ export class Container extends EventEmitterWithErrorHandling<IContainerEvents> i
             if (errorMsg !== undefined) {
                 const error = new GenericError(
                     errorMsg,
+                    undefined,
                     {
                         clientId: this._clientId,
                         messageClientId: message.clientId,
                         sequenceNumber: message.sequenceNumber,
                         clientSequenceNumber: message.clientSequenceNumber,
+                        messageTimestamp: message.timestamp,
```
Comment (anthony-murphy) [inline packages/loader/container-loader/src/container.ts:1628]: I'm fine with this, but i think we might actually want to just add a bunch of this information directly to the logger at the container level, so these field are always avaialbe, but maybe it's overkill. or maybe only add them for errors

File: packages/loader/container-loader/src/container.ts [hunk 4]
```diff
@@ -1619,11 +1619,13 @@ export class Container extends EventEmitterWithErrorHandling<IContainerEvents> i
             if (errorMsg !== undefined) {
                 const error = new GenericError(
```
Comment (anthony-murphy) [inline packages/loader/container-loader/src/container.ts:1620]: want to make this a datacorruption as part of #4663 while you are here?

File: packages/loader/container-loader/src/container.ts (hunk 3 above)
Comment (agarwal-navin) [reply packages/loader/container-loader/src/container.ts:1628]: +1 to that. I feel like we should always log certain things like clientId and timestamp.

File: packages/loader/container-loader/src/container.ts [hunk 5]
```diff
@@ -1619,11 +1619,13 @@ export class Container extends EventEmitterWithErrorHandling<IContainerEvents> i
...
                     errorMsg,
+                    undefined,
```
Comment (agarwal-navin) [inline packages/loader/container-loader/src/container.ts:1622]: nit: Add a msg what this is: something like `undefined /* error */` so looking at the call we can tell what we are passing as undefined.

**Comment by agarwal-navin** [comment]
I know this is not related to this change, but we rename the two events for this is fired to - `clientMissingFromQuorum` and `clientShouldHaveLeftQuorum`.
`messageClientIdMissingFromQuorum` and `messageClientIdShouldHaveLeft` does not really tell me what the problem is.

**Review by agarwal-navin — APPROVED** [review]

File: packages/loader/container-loader/src/container.ts (hunk 3 above)
Comment (markfields) [inline packages/loader/container-loader/src/container.ts:1628]: @anthony-murphy , @agarwal-navin  - How helpful would it be if I converted this to a human readable datetime format rather than just the Unix epoch format?

File: packages/loader/container-loader/src/container.ts (hunk 5 above)
Comment (markfields) [reply packages/loader/container-loader/src/container.ts:1622]:
```suggestion
                    undefined /* error */,
```

File: packages/loader/container-loader/src/container.ts (hunk 3 above)
Comment (markfields) [reply packages/loader/container-loader/src/container.ts:1628]: #5121 

Good idea.

File: packages/loader/container-utils/src/error.ts (hunk 2 above)
Comment (markfields) [reply packages/loader/container-utils/src/error.ts:34]: Yay someone asked for a test!  I just pushed one and was going to rag on everyone for not asking :P

File: packages/loader/container-loader/src/container.ts (hunk 4 above)
Comment (markfields) [reply packages/loader/container-loader/src/container.ts:1620]: Ah yes of course!  I'll leave in the changes to `GenericError` even though they're not used now, since I went to the trouble of writing that test ;)

File: packages/loader/container-loader/src/container.ts (hunk 3 above)
Comment (agarwal-navin) [reply packages/loader/container-loader/src/container.ts:1627]: I am not sure that will help. We have a lot of telemetry where message timestamp is in Unix epoch format. Also, server logs, console logs, op stream, etc. would have it in that format. I would rather keep the same format so that its consistent.

**Review by anthony-murphy — APPROVED** [review]

File: packages/loader/container-loader/src/container.ts (hunk 3 above)
Comment (anthony-murphy) [reply packages/loader/container-loader/src/container.ts:1627]: I'm fine with the epoch

**Comment by markfields** [comment]
> I know this is not related to this change, but we rename the two events for this is fired to - `clientMissingFromQuorum` and `clientShouldHaveLeftQuorum`.
> `messageClientIdMissingFromQuorum` and `messageClientIdShouldHaveLeft` does not really tell me what the problem is.

Decided not to do this now for simplicity, but I agree that's a good change next time someone is in the file/code.

File: packages/loader/container-loader/src/container.ts (hunk 3 above)
Comment (vladsud) [reply packages/loader/container-loader/src/container.ts:1627]: Note: As a general rule, we try not to add info that already exists in telemetry. clientId (not message clientID, but current known to container) is already in the logs. There is pros & cons to either approach (each event is self-contained vs. not), but I spent some time analyzing cost of logging (Kusto has reports for that) and things like clientID are unfortunately rather expensive when repeated despite compression (i.e. that's the reason I removed it from being on all events).
In this case it's likely not a big deal (error handling - rare events), so mostly FYI for future.
