### PR TITLE
9946 Improve last summary flow

### LINKED ISSUE #9946: Improve last summary flow
## Goal
Reduce number of trailing ops in files at rest.
Ideal (unachievable outcome at the moment) - there are no trailing ops in files at rest.

## Suggested work
1. Pass SummarizerStopReason to shouldRunLastSummary()
2. Add telemetry event in shouldRunLastSummary() to log opsSinceLastAck & this.minOpsForAttemptOnClose & SummarizerStopReason
3. Make shouldRunLastSummary() return false if reason is not "parentNotConnected".
4. Change default value for minOpsForAttemptOnClose from 50 to 10
5. Change logic in getShouldSummarizeState() - reorder first two cases (parentNotConnected & parentShouldNotSummarize)
6. RunningSummarizer.trySummarize() should only do one iteration (see attempts array) when summarizeReason == "lastSummary"
7. Expose minOpsForAttemptOnClose on ISummaryConfiguration (and move default to DefaultSummaryConfiguration. Such settings should not be buried deep in the code, and specific scenario (i.e., app) should be able to change them easily
   - I'd prefer it to be a separate PR, this is lower priority compared to other items.

## Description

There are only 2.5K last summaries out of 6M of summaries - that's very low number!

> union Office_Fluid_FluidRuntime_*
| where Data_eventName == "fluid:telemetry:Summarizer:Running:SummaryOp"
| summarize count() by Data_summarizeReason

Last summary is the process that runs to summarize a file when main client is closed. It was originally built as a recovery mechanism for corrupted files (files that have over 10K unsummarized ops, and thus can't be edited unless new summary is posted).

At the same time, there are 3.6M summary sessions, some of them do not log the following event (as tab is closed), but most do:
> union Office_Fluid_FluidRuntime_*
| where Data_eventName contains "StoppingSummarizer"
| where Data_clientType != "interactive"
| summarize count() by Data_reason

Data_reason | count_
-- | --
parentShouldNotSummarize | 2,119,619
parentNotConnected | 299,577
summarizerClientDisconnected | 45,086
failToSummarize | 58
summarizerException | 5

Top 2 lines can run last summary (allowLastSummary = true in waiStop()) today but they do not due to too high minOpsForAttemptOnClose.
That's a bummer as we can leverage that to reduce number of cases where we have trailing ops!

reason = "summarizerClientDisconnected" should translate to allowLastSummary = false, the bottom 2 reasons probably should never try to do last summary, that said not sure how much we care. parentShouldNotSummarize is questionable whether we want to run a summary, as it means there is another summarizer client that is booting in parallel, so running last summary here risks having two summarizers, and thus we should avoid running last summary.

But parentNotConnected indicates that parent is disconnected. In original design that was equivalent to parentShouldNotSummarize, but with recent Paul's changes a summarizer client that stays afloat is considered to be elected, and should proceed to last summary.
For that reason, I believe the order of getShouldSummarizeState() should be changed - we should first check if client is condition for parentShouldNotSummarize is satisfied - this is stronger signal. We should also likely rename it, as it has less to do with parent nowadays. This change (reorder) will make this logic independent on how decisions for elected summarizer is made (as with today's logic we are essentially overwriting such logic in getShouldSummarizeState() by saying that parent connectivity is included in this logic, while it might be not true).

We might go with allow-list here, and shouldRunLastSummary() can only return true for first two reasons.

### PR DESCRIPTION
**Pull request by kian-thompson**
#9946 
[AB#129](https://dev.azure.com/fluidframework/235294da-091d-4c29-84fc-cdfc3d90890b/_workitems/edit/129)

### CODE REVIEW

File: packages/runtime/container-runtime/src/summarizerHeuristics.ts [hunk 1]
```diff
@@ -81,9 +88,22 @@ export class SummarizeHeuristicRunner implements ISummarizeHeuristicRunner {
         }
     }
 
-    public shouldRunLastSummary(): boolean {
+    public shouldRunLastSummary(stopReason: SummarizerStopReason): boolean {
+        if (stopReason === "parentNotConnected") {
```
Comment (vladsud) [inline packages/runtime/container-runtime/src/summarizerHeuristics.ts:92]: I think this should be !== 
Would be great to add tests for this (if possible).

File: packages/runtime/container-runtime/src/summaryManager.ts [hunk 2]
```diff
@@ -141,12 +141,12 @@ export class SummaryManager implements IDisposable {
...
-        if (!this.connectedState.connected) {
-            return { shouldSummarize: false, stopReason: "parentNotConnected" };
-        } else if (this.connectedState.clientId !== this.clientElection.electedParentId ||
+        if (this.connectedState.clientId !== this.clientElection.electedParentId ||
             (this.state !== SummaryManagerState.Running &&
                 this.connectedState.clientId !== this.clientElection.electedClientId)) {
             return { shouldSummarize: false, stopReason: "parentShouldNotSummarize" };
+        } else if (!this.connectedState.connected) {
+            return { shouldSummarize: false, stopReason: "parentNotConnected" };
         } else if (this.disposed) {
```
Comment (vladsud) [inline packages/runtime/container-runtime/src/summaryManager.ts:150]: @agarwal-navin can you please double check my logic in #9946? You already looked at it, but I want to make sure the reasoning is solid on why this change is correct and preferred.

**Comment by vladsud** [comment]
Looks good, but I'd definitely run through local stress test before merging it.
See packages\test\test-service-load\readme.md
You would need to get secrets installed first on your box, then you should be able to run a test.
It will spew some errors, but number of them should be low and nothing related to summarization. I can help with looking at results. It's very useful tool, so worth the time to get through the hoops.

**Comment by vladsud** [comment]
Oh, I'd probably split it into two PRs. I'd change the actual number of ops (from 50 to 10) only after @NicholasCouri is done with his PR, as I expect this to have a hit on Whiteboard that I can't estimate. So, I really want to given them an escape valve here - they can use old settings and find the values that work for them (same with any other workload that does not like defaults). I assume it will need to go to _next_ because of it.

The rest can go in as is (I think) to main.

**Review by vladsud — APPROVED** [review]

File: packages/runtime/container-runtime/src/summarizerHeuristics.ts [hunk 3]
```diff
@@ -56,7 +62,8 @@ export class SummarizeHeuristicRunner implements ISummarizeHeuristicRunner {
         private readonly heuristicData: ISummarizeHeuristicData,
         private readonly configuration: ISummaryConfiguration,
         private readonly trySummarize: (reason: SummarizeReason) => void,
-        private readonly minOpsForAttemptOnClose = 50,
+        private readonly logger: ITelemetryLogger,
+        private readonly minOpsForAttemptOnClose = 10,
```
Comment (NicholasCouri) [inline packages/runtime/container-runtime/src/summarizerHeuristics.ts:66]: >10, [](http://example.com/codeflow?start=51&length=3)

We might wait for my PR so this default will not be here anymore - I could change on my PR but for history purposes it might be better for us to change later.

File: packages/runtime/container-runtime/src/summaryManager.ts [hunk 4]
```diff
@@ -141,12 +141,12 @@ export class SummaryManager implements IDisposable {
         // enforce connectedState.clientId === clientElection.electedClientId. But once we're Running, we should
         // only transition to Stopping when the electedParentId changes. Stopping the summarizer without
         // changing the electedParent will just cause us to transition to Starting again.
-        if (!this.connectedState.connected) {
-            return { shouldSummarize: false, stopReason: "parentNotConnected" };
-        } else if (this.connectedState.clientId !== this.clientElection.electedParentId ||
+        if (this.connectedState.clientId !== this.clientElection.electedParentId ||
```
[the remark this answers is not in the document]
Comment (vladsud) [reply packages/runtime/container-runtime/src/summaryManager.ts:144]: clientId is never undefined after first connection is established, even on disconnect. It always tracks either current connection ID, or previous one (such that we can continue properly account acks for our own ops on reconnect). In other words, clientId switched to reflect new value only when we are 100% sure all previously sent ops either are accounted (we observed them sequenced and received them) or 100% sure that they are lost and would never make it into a file.
Only then we switch clientId and allow this connection to send new ops.

**Review by NicholasCouri — APPROVED** [review]

File: packages/runtime/container-runtime/src/summaryManager.ts (hunk 2 above)
Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/summaryManager.ts:150]: Taking a look. What's the reason for re-ordering the first 2 conditions though?

File: packages/runtime/container-runtime/src/summarizerHeuristics.ts [hunk 5]
```diff
@@ -56,6 +62,7 @@ export class SummarizeHeuristicRunner implements ISummarizeHeuristicRunner {
         private readonly heuristicData: ISummarizeHeuristicData,
         private readonly configuration: ISummaryConfiguration,
         private readonly trySummarize: (reason: SummarizeReason) => void,
+        private readonly logger: ITelemetryLogger,
         private readonly minOpsForAttemptOnClose = 50,
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/summarizerHeuristics.ts:66]: Shouldn't this be changed to 10 as per #9946?

File: packages/runtime/container-runtime/src/summaryManager.ts [hunk 6]
```diff
@@ -141,12 +141,12 @@ export class SummaryManager implements IDisposable {
         // enforce connectedState.clientId === clientElection.electedClientId. But once we're Running, we should
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/summaryManager.ts:141]: This comment needs to be updated to clearly describe why the "parentShouldNotSummarize" condition is needed. Can you please create an issue for this? I meant to change this comment but it slips my mind.

Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/summaryManager.ts:141]: Also, these stop reasons need to be renamed. I don't think the names convey what they mean. You can probably add this to the same issue.

File: packages/runtime/container-runtime/src/summarizerHeuristics.ts [hunk 7]
```diff
@@ -81,9 +88,22 @@ export class SummarizeHeuristicRunner implements ISummarizeHeuristicRunner {
...
+        const minOpsForAttemptOnClose = this.minOpsForAttemptOnClose;
+
+        this.logger.sendTelemetryEvent({
+            eventName: "ShouldRunLastSummary",
+            stopReason,
+            opsSinceLastAck,
+            minOpsForAttemptOnClose,
+        });
+
+        return opsSinceLastAck > minOpsForAttemptOnClose;
```
Comment (agarwal-navin) [inline packages/runtime/container-runtime/src/summarizerHeuristics.ts:106]: This should probably be >=. Not a big deal but the name "minOpsForAttemptOnClose" would suggest that we would summarize it we hit this number.

File: packages/runtime/container-runtime/src/summaryManager.ts (hunk 2 above)
Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/summaryManager.ts:150]: Looks reasonable. My only questions is the one I asked above. This one is not clear to me.

File: packages/runtime/container-runtime/src/summarizerHeuristics.ts (hunk 5 above)
Comment (agarwal-navin) [reply packages/runtime/container-runtime/src/summarizerHeuristics.ts:66]: This has already be addressed in other comments. Please ignore it :)

File: packages/runtime/container-runtime/src/summarizerHeuristics.ts [hunk 8]
```diff
@@ -81,9 +88,22 @@ export class SummarizeHeuristicRunner implements ISummarizeHeuristicRunner {
         }
     }
 
-    public shouldRunLastSummary(): boolean {
+    public shouldRunLastSummary(stopReason: SummarizerStopReason): boolean {
+        if (stopReason !== "parentNotConnected") {
```
Comment (kian-thompson) [inline packages/runtime/container-runtime/src/summarizerHeuristics.ts:92]: @vladsud Thinking about this case a bit more, does it even make sense to have the logic at this level? For example, we have the `allowLastSummary` parameter on the `RunningSummarizer.waitStop(...)` method. But our value for `allowLastSummary` may not matter because of this stop reason check. I think it makes more sense for the caller of `RunningSummarizer.waitStop(...)` to make this decision on a specific stop reason not allowing summarization.

Comment (vladsud) [reply packages/runtime/container-runtime/src/summarizerHeuristics.ts:92]: Sure, we can move decision up the stack.

File: packages/runtime/container-runtime/src/summaryManager.ts (hunk 6 above)
Comment (kian-thompson) [reply packages/runtime/container-runtime/src/summaryManager.ts:141]: #10105

**Comment by kian-thompson** [comment]
> Looks good, but I'd definitely run through local stress test before merging it. See packages\test\test-service-load\readme.md You would need to get secrets installed first on your box, then you should be able to run a test. It will spew some errors, but number of them should be low and nothing related to summarization. I can help with looking at results. It's very useful tool, so worth the time to get through the hoops.

I ran some local stress tests and there seem to be some errors around summarization. However, I also ran the local stress tests on the `next` branch and saw very similar errors. So, I believe the failures are already pre-existing prior to this change and may be related to some unrelated issues with ODSP (403, 404, and summary nacks).
