### PR TITLE
correctly handle simultaneous upload of identical blob

### LINKED ISSUE #9702: Data processing error 0x1f8 can occur on duplicate blob upload
## Describe the bug

I found this issue while writing fuzz tests for the legacy tree DDS. I believe I've debugged enough to provide a description of the problem, but I also have a concrete tests case (albeit convoluted since it is generated stochastically) which demonstrates it, in case my description is inaccurate. The state machine around `pendingBlobId`s breaks down a bit on server deduplication of blobs with identical content, causing [this assert](https://github.com/microsoft/FluidFramework/blob/611d86d2bae3cf01eb927b5c24ac590c706aee42/packages/runtime/container-runtime/src/blobManager.ts#L150) to fire.

### To Reproduce

steps to reproduce the behavior:
1. Connect two clients to a local server (issue may repro on other servers as well, depending on blobId generation strategy--if this is deterministic, I'd expect it to repro)
2. On each client, upload a blob containing the same contents. These two operations should be concurrent.
3. Wait for sequencing of ops to occur. Whichever BlobAttach op gets sequenced first will cause both entries from `pendingBlobId`s to be removed, and when the second BlobAttach op is sequenced on the client that submitted it, it will hit the 0x1f8 assert.

image

### Expected behavior

No failure.

### PR DESCRIPTION
**Pull request by wes-carlson**
Fix #9702
Correctly handle the case where multiple containers upload the same blob and submit blobAttach ops with identical blob IDs due to blob de-duping. In this case, BlobManager should only resolve the deferred promise when it sees its own op.

### CODE REVIEW

File: packages/runtime/container-runtime/src/blobManager.ts [hunk 1]
```diff
@@ -147,9 +147,12 @@ export class BlobManager {
     }
 
     public processBlobAttachOp(blobId: string, local: boolean) {
-        assert(!local || this.pendingBlobIds.has(blobId), 0x1f8 /* "local BlobAttach op with no pending blob" */);
-        this.pendingBlobIds.get(blobId)?.resolve();
-        this.pendingBlobIds.delete(blobId);
+        if (local) {
```
Comment (vladsud) [inline packages/runtime/container-runtime/src/blobManager.ts:150]: Your code looks correct, but I wonder why you chose this design over using first op?
I.e. I think you can leave the code as is, but remove assert. We lose a bit of validation that way.
Either way, it's probably does not matter :)

Curios, how did we find this bug in the first place?

**Review by vladsud — APPROVED** [review]

File: packages/runtime/container-runtime/src/blobManager.ts (hunk 1 above)
Comment (wes-carlson) [reply packages/runtime/container-runtime/src/blobManager.ts:150]: It seemed simpler this way and I would guess it's possible to hit this in normal usage but very unlikely so like you say it probably doesn't matter

Comment (Abe27342) [reply packages/runtime/container-runtime/src/blobManager.ts:150]: issue was discovered by writing a fuzz tester for the tree DDS whiteboard uses ahead of shipping the op/summary compression work. The 0.1.1 format with history involves a strategy for chunking edits into blobs which are uploaded. There's assumption that all clients agree on the chunk boundaries which is partially enforced via quorum, but in certain scenarios chunks can get uploaded twice. For example if the leader elected to upload blobs leaves the session immediately after submitting an edit chunk, and the newly elected leader starts uploading yet-un-uploaded blobs before blob attach op gets broadcast to it.

It should actually be a rare scenario in practice.
