### PR TITLE
Fix wrapError for better errors analysis in telemetry

### LINKED ISSUE #8954: Improve semantics of wrapError
Today, `wrapError` does this:

* Generates a new error object with a new errorType, and often a new fluidErrorCode
* Typically takes the original error's errorMessage
* The original stack is used
* A new errorInstanceId is generated, and the logs include a link between the inner (if existing) to outer
* Optionally log via `wrapErrorAndLog`

Problems here include:

* The inner error's message may contain PII or variable data, but we're stamping it on one of "our" errors. This is counter to the goals we have for our errors' messages
* Furthermore, with the deprecation of fluidErrorCode, if we preserve the incoming message we have few options for adding on a meaningful message/description of the wrapping error from our code's POV.
* Stitching together via inner/outer errorInstanceId is prohibitively difficult
* The original error object is discarded, which could hamper debugging

New plan (exact prop names TBD):

* Generate a new error object with a new errorType and message
* At runtime, stick the original error on as innerError. 
* Add a tagged telemetry prop innerErrorMessage which is the inner error's message
* Reuse errorInstanceId between the two
  * If innerError has it, use it. Otherwise generate it.
  * If not, do best effort (in try-catch) to stamp the id on the innerError as well
  * Include it in the log in the case of `wrapErrorAndLog`
* Continue to reuse the stack... Or log it as innerErrorStack?

As we go through current/new usages of `wrapError`, we can adjust this, but I think it's the right way to iterate from here.

### PR DESCRIPTION
**Pull request by markfields**
Fixes #8954 

Here are the changes to `wrapError`:

* Reuse `errorInstanceId` as discussed above (but also leave current props for ease of transition in queries)
* Properly set `untrustedOrigin` telemetry prop, to reflect whether the original error was external, even after being normalized and/or wrapped, possibly multiple times.

See discussion in issue #8954 for additional context.

### CODE REVIEW

File: packages/loader/container-utils/src/error.ts [hunk 1]
```diff
@@ -165,21 +166,18 @@ export class DataProcessingError extends LoggingError implements IErrorBase, IFl
 
         const normalizedError = normalizeError(originalError, { props });
 
-        // Check for errors that originated externally to our code before being normalized.
```
Comment (markfields) [inline packages/loader/container-utils/src/error.ts:168]: This diff looks crazy.  All I did was update the if statement to use the new `isExternalError` helper, and invert it to do early return and reduce nesting

File: packages/utils/telemetry-utils/src/test/errorLogging.spec.ts [hunk 2]
```diff
@@ -614,14 +632,32 @@ describe("normalizeError", () => {
...
             const annotations = annotationCases[annotationCase];
+            let doneOnceForThisAnnotationCase = false;
             for (const caseName of Object.keys(untrustedInputs)) {
                 const getTestCase = untrustedInputs[caseName];
-                it(`Normalize untrusted error: ${caseName} (${annotationCase})`, () => {
+                if (!doneOnceForThisAnnotationCase) {
+                    doneOnceForThisAnnotationCase = true;
+                    // Each test case only differs by what stack/error are.  Test the rest only once per annotation case.
+                    it(`Normalize untrusted error full validation: (${annotationCase})`, () => {
+                        // Arrange
```
Comment (andre4i) [inline packages/utils/telemetry-utils/src/test/errorLogging.spec.ts:645]: #nit not a big fan of the `Arrange`/`Act' comments. I feel they're sort of redundant.

File: packages/utils/telemetry-utils/src/test/errorLogging.spec.ts [hunk 3]
```diff
@@ -662,6 +717,56 @@ describe("wrapErrorAndLog", () => {
     assert(mockLogger.matchEvents([{
         eventName: "WrapError",
         wrappedByErrorInstanceId: newError.errorInstanceId,
+        errorInstanceId: newError.errorInstanceId,
         error: "hello",
      }]), "Expected the 'WrapError' event to be logged");
 });
+
+describe.only("Error Discovery", () => {
```
Comment (andre4i) [inline packages/utils/telemetry-utils/src/test/errorLogging.spec.ts:725]: Is this `only` intentional?

**Review by andre4i — APPROVED** [review]
Looks good. Take a look at my comment about the test

File: packages/utils/telemetry-utils/src/test/errorLogging.spec.ts (hunk 3 above)
Comment (markfields) [reply packages/utils/telemetry-utils/src/test/errorLogging.spec.ts:725]: You win a cookie for catching this!  Embarrassed I let this slip in.  Not my first time doing so...  :(

File: packages/utils/telemetry-utils/src/test/errorLogging.spec.ts (hunk 2 above)
Comment (markfields) [reply packages/utils/telemetry-utils/src/test/errorLogging.spec.ts:645]: Yeah, it can be.  I think I like the "Act" block most of all because it draws attention to what behavior is actually under test.  But 🤷‍♂️
