### PR TITLE
Throw Processing Error on Summary Load Failures

### LINKED ISSUE #5674: Mark exception in Summary flow as DataProcessing Issues
## Work Item
We've instrumented the message processing flow with DataProcessing issues, we should do the same thing with the summary loading flow.

### PR DESCRIPTION
**Pull request by anthony-murphy**
fixes #5674

### CODE REVIEW

File: packages/runtime/container-runtime/src/dataStoreContext.ts [hunk 1]
```diff
@@ -280,7 +281,7 @@ export abstract class FluidDataStoreContext extends TypedEventEmitter<IFluidData
         if (!this.channelDeferred) {
             this.channelDeferred = new Deferred<IFluidDataStoreChannel>();
             this.realizeCore().catch((error) => {
-                this.channelDeferred?.reject(error);
+                    this.channelDeferred?.reject(CreateProcessingError(error, undefined));
```
Comment (anthony-murphy) [inline packages/runtime/container-runtime/src/dataStoreContext.ts:284]:
```suggestion
                this.channelDeferred?.reject(CreateProcessingError(error, undefined));
```

File: packages/runtime/container-runtime/src/dataStoreContext.ts [hunk 2]
```diff
@@ -280,7 +281,7 @@ export abstract class FluidDataStoreContext extends TypedEventEmitter<IFluidData
         if (!this.channelDeferred) {
             this.channelDeferred = new Deferred<IFluidDataStoreChannel>();
             this.realizeCore().catch((error) => {
-                this.channelDeferred?.reject(error);
+                this.channelDeferred?.reject(CreateProcessingError(error, undefined));
```
Comment (vladsud) [inline packages/runtime/container-runtime/src/dataStoreContext.ts:284]: Can you please add comment, i.e.
, undefined /* message */);

**Comment by vladsud** [comment]
Couple thoughts on the direction:
1. We are basically trying to do something in shipping code that we usually do in post-processing of telemetry - hit bucketing (mostly based on stack). Doing it in non-shipping code has huge advantages - we can change bucketing rules based on learnings very quickly. We had discussions before on improving stack analyzes - feels like that needs to happen no matter what.
2. CreateProcessingError() (and overall flow) is a bit weird. In a sense that if some logging error is thrown (let's say storage error), then it would be preserved (i.e. it would not be "processing error". But if we hit runtime error (referencing null), then it becomes processing error. There is really no difference from one angle (can't load / summarize), and huge difference from another (reason for failure), to it feels like really what we want is to add a property to an error object (error during loading / processing ops), but also leave the old one in place such that different kind of analyzes can be done (i.e. ensure it's logging object, and then add error.processingError = true to it). Stack analyzes would allow both types of filtration of data, so this approach is really a poor mans implementation of that.

**Comment by anthony-murphy** [comment]
1. As a platform i don't think we can or do own post-processing, and i'm not sure we can ever trust stack given how common things like webpack, and bable are for rewriting much of the code. so we will have to have more structures logs, such that it is easier for consumers to deal with, and likely give back to us
2. I'm not against switching from a rows to columns eg. errorType=dataProcessing to dataProcessing = true, but it will make some things harder for consumers. Right now only unknown errors will ever have errorType=dataProcessing, so they can pretty effiecently bucket those as needing follow up. If we just tack it on to all logging error they will need to do more complex things to seperate expect errors, like network errors, for unexpected errors. This is probably more flexible for us, but could be harder for consumers.

File: packages/runtime/container-runtime/src/dataStoreContext.ts (hunk 2 above)
Comment (anthony-murphy) [reply packages/runtime/container-runtime/src/dataStoreContext.ts:284]: yes. something i didn't do here, but am considering is storing the details (seq, refSeq, timestamp,...) of the last message a channel receives in it's attributes such that we can provide it here, a give a context to the error. Timestamp is especially important for alerting, as it allows us to differentiated old broken documents for new incidents breaking documents. this would however impact blob deduping. curious your thoughts on that?

Comment (markfields) [inline packages/runtime/container-runtime/src/dataStoreContext.ts:284]: Do you also want to do the same in the catch block inside `bindRuntime`?

Comment (markfields) [reply packages/runtime/container-runtime/src/dataStoreContext.ts:284]: For now maybe just make that param optional...?

**Review by markfields — APPROVED** [review]
I can't confidently say whether you've covered all the right codepaths for what you're trying to accomplish, but it seems like a fine change given our overall approach here.  I do see Vlad's point that we're awkwardly "marking up" the error based on what functions are in the stack, which is good food for thought for me as I'm thinking broadly in this space.

🎂 Signing off, but left a few comments for you to look at before merging.

File: packages/runtime/container-runtime/src/dataStoreContext.ts (hunk 2 above)
Comment (anthony-murphy) [reply packages/runtime/container-runtime/src/dataStoreContext.ts:284]: i don't think so. i'm really just looking to cover cases where we are processing the snapshot. bind runtime does do some op processing, but that will be caught in the channel handler which was added previously to cover op processing

File: packages/runtime/container-runtime/src/dataStoreContext.ts [hunk 3]
```diff
@@ -268,7 +269,7 @@ export abstract class FluidDataStoreContext extends TypedEventEmitter<IFluidData
...
```
Comment (anthony-murphy) [inline packages/runtime/container-runtime/src/dataStoreContext.ts:272]:
```suggestion
                this.channelDeferred?.reject(CreateProcessingError(error, undefined /* message */));
```
