### PR TITLE
Fix logging in runWithRetry when aborted

### LINKED ISSUE #8309: Prod: fluid:telemetry:OdspDriver:createNewFile_cancel: Need better back off & progress reporting / cancelation.
There are a lot of fluid:telemetry:OdspDriver:createNewFile_cancel errors in telemetry.
Looking closer, I see that most of them are concentrated in 10 sessions, with top one probably have 30% of all events (2109 hits in that session alone!)

I believe it works as it was designed (i.e. we keep retrying if user is offline), but
- should it do so in such tight loop? It looks like there is no delay / back off, just straight retry
- should it do so long? I know we went back and forth on it, and allowed (before) to fail and do retry by host.
   - probably better question to ask - can we start propagating IProgress through API and use this flow as a first guinea pig  for flashing out cancelation / progress reporting API?

> union Office_Fluid_FluidRuntime_*
| where Data_containerId == "2316b2db-5472-454b-bc4e-a1138393a477"
| project Event_Sequence, Event_Time, Data_eventName, Data_errorType, Data_error, Data_reason
| order by Event_Time asc

### PR DESCRIPTION
**Pull request by chensixx**
Fixes #8309 
Fixed how the error is logged and thrown in runWithRetry when it's aborted

### CODE REVIEW

File: packages/loader/driver-utils/src/runWithRetry.ts [hunk 1]
```diff
@@ -66,10 +66,15 @@ export async function runWithRetry<T>(
...
             if (progress.cancel?.aborted === true) {
+                logger.sendTelemetryEvent({
+                    eventName: `${fetchCallName}_runWithRetryAborted`,
+                    retry: numRetries,
+                    duration: performance.now() - startTime,
+                }, err);
                 throw new NonRetryableError(
-                    "runWithRetryAborted",
+                    "runWithRetry was Aborted",
                     OdspErrorType.fetchTimeout,
```
Comment (markfields) [inline packages/loader/driver-utils/src/runWithRetry.ts:76]: I still don't understand why this errorType is used here, but if you and Vlad agreed on it I'm okay.  Do you have a follow-up issue opened to move this (or whatever the final correct errorType is) to base driver ErrorType and use it here?

Comment (chensixx) [reply packages/loader/driver-utils/src/runWithRetry.ts:76]: yeah #8488

**Review by markfields — APPROVED** [review]
🎂 Thanks for the quick follow-up!

File: packages/loader/driver-utils/src/runWithRetry.ts [hunk 2]
```diff
@@ -66,10 +66,15 @@ export async function runWithRetry<T>(
...
-                    { eventName: `runWithRetryAborted_${fetchCallName}`, driverVersion: pkgVersion },
+                    { driverVersion: pkgVersion },
```
Comment (vladsud) [inline packages/loader/driver-utils/src/runWithRetry.ts:77]: I'd add fetchCallName as a property, may make it easier to debug such events in the future.

Comment (markfields) [reply packages/loader/driver-utils/src/runWithRetry.ts:77]: Here and the other two logs in this function

**Review by vladsud — APPROVED** [review]

File: packages/loader/driver-utils/src/runWithRetry.ts (hunk 2 above)
Comment (markfields) [reply packages/loader/driver-utils/src/runWithRetry.ts:77]: And if you're making changes, I'd update the eventName to `..._abort` or `...aborted` (more concise)

File: packages/loader/driver-utils/src/runWithRetry.ts (hunk 1 above)
Comment (chensixx) [reply packages/loader/driver-utils/src/runWithRetry.ts:76]: i can also change it to generic now and then use the final correct type later

File: packages/loader/driver-utils/src/runWithRetry.ts (hunk 2 above)
Comment (chensixx) [reply packages/loader/driver-utils/src/runWithRetry.ts:77]: do you mean just on the error, not on the events?

File: packages/loader/driver-utils/src/runWithRetry.ts (hunk 1 above)
Comment (markfields) [reply packages/loader/driver-utils/src/runWithRetry.ts:76]: Hmmm I guess I would prefer that since then you could remove the dependency on ODSP driver packages from here.  And you can call out this case in that issue so we don't forget to update it too.  Honestly I don't feel too strongly so you can decide either way.

**Comment by chensixx** [comment]
the _runwithRetryAborted events are not making it to logs, need to investigate more
