### PR TITLE
Prevent duplicate create container calls

### LINKED ISSUE #8514: Throw an error creating a second container with TestObjectProvider
> A thing to note is that the test object provider does not support creating multiple containers. When you do it, it does unexpected things... We should probably throw an error or something when a second container is created.

### PR DESCRIPTION
**Pull request by tyler-cai-microsoft**
Resolves #8514 

Throws an error when createContainer is done once. Currently designed to allow for multiple documentIds to be used in the future as well.

### CODE REVIEW

File: packages/test/test-utils/src/testObjectProvider.ts [hunk 1]
```diff
@@ -137,6 +137,7 @@ export class TestObjectProvider {
     private _urlResolver: IUrlResolver | undefined;
     private _logger: ITelemetryBaseLogger | undefined;
     private readonly _documentIdStrategy: IDocumentIdStrategy;
+    private readonly _usedDocumentIds: Set<string>;
```
Comment (agarwal-navin) [inline packages/test/test-utils/src/testObjectProvider.ts:140]: A set is not needed as the test provider only supports one documentId at a time. A flag should be enough for this which is set when a container is created.
Maybe it can be built into documentIdStrategy but I don't see a simple way to do this.

Comment (agarwal-navin) [reply packages/test/test-utils/src/testObjectProvider.ts:140]: Also, this state has to be reset when `reset` is called on the test provider.

File: packages/test/test-utils/src/testObjectProvider.ts [hunk 2]
```diff
@@ -137,6 +137,7 @@ export class TestObjectProvider {
     private _urlResolver: IUrlResolver | undefined;
     private _logger: ITelemetryBaseLogger | undefined;
     private readonly _documentIdStrategy: IDocumentIdStrategy;
+    private _usedDocumentId: boolean;
```
Comment (agarwal-navin) [inline packages/test/test-utils/src/testObjectProvider.ts:140]: `usedDocumentId` does not seem like the right name for this. We are limiting the number of documents or number of create container calls to 1. So, the name should be something like documentCreated or containerCreated.
You should also add a comment here about this limit.

File: packages/test/test-utils/src/testObjectProvider.ts [hunk 3]
```diff
@@ -149,6 +150,7 @@ export class TestObjectProvider {
         public readonly createFluidEntryPoint: (testContainerConfig?: ITestContainerConfig) => fluidEntryPoint,
     ) {
         this._documentIdStrategy = getDocumentIdStrategy(driver.type);
+        this._usedDocumentId = false;
```
Comment (agarwal-navin) [inline packages/test/test-utils/src/testObjectProvider.ts:153]: nit: You can initialize this where the member is declared.

File: packages/test/test-utils/src/testObjectProvider.ts [hunk 4]
```diff
@@ -235,11 +237,15 @@ export class TestObjectProvider {
      */
     public async createContainer(entryPoint: fluidEntryPoint, options?: ITestLoaderOptions) {
         const loader = this.createLoader([[defaultCodeDetails, entryPoint]], options);
+        if (this._usedDocumentId) {
```
Comment (agarwal-navin) [inline packages/test/test-utils/src/testObjectProvider.ts:240]: Move this before creating the loader.

File: packages/test/test-utils/src/testObjectProvider.ts [hunk 5]
```diff
@@ -235,11 +237,15 @@ export class TestObjectProvider {
...
+            throw new Error("createContainer can only be called once! Use loadContainer");
```
Comment (agarwal-navin) [inline packages/test/test-utils/src/testObjectProvider.ts:241]: The error should probably say only a single container / document can be created. To load the container / document use loadContainer. Similar for the other place where this error is thrown.

**Review by agarwal-navin — APPROVED** [review]
