### PR TITLE
Retain actual error while throwing in resolvewrapper in fetch tool

### LINKED ISSUE #5309: Fetch-tool failed with "Cannot read property 'push' of undefined"
Got this error while running fluid-fetch tool on random file.
It worked (same bits) a moment before on another file, and I do not have any changes related to driver / tool:

Error calling getVersions
ERROR: Error: Fail to connect to ODSP server
Error Response:
TypeError: Cannot read property 'push' of undefined
    at Object.resolveWrapper (E:\Git\FluidFramework\packages\tools\fetch-tool\dist\fluidFetchSharePoint.js:38:31)
    at async Function.timedExecAsync (E:\Git\FluidFramework\packages\utils\telemetry-utils\dist\logger.js:308:25)
    at async E:\Git\FluidFramework\packages\drivers\odsp-driver\dist\odspDocumentStorageManager.js:472:34
    at async reportErrors (E:\Git\FluidFramework\packages\tools\fetch-tool\dist\fluidFetchSnapshot.js:194:16)
    at async Object.fluidFetchSnapshot (E:\Git\FluidFramework\packages\tools\fetch-tool\dist\fluidFetchSnapshot.js:214:22)
    at async fluidFetchOneFile (E:\Git\FluidFramework\packages\tools\fetch-tool\dist\fluidFetch.js:32:5)

ResolveWrapper in fluidFetchSharePoint.ts should not eat error and rethrow as is!

Actual error:
ERROR: TypeError: Cannot read property 'push' of undefined
    at Object.get (E:\FluidFramework\packages\utils\tool-utils\dist\odspTokenManager.js:207:89)
    at async OdspTokenManager.getTokenFromCache (E:\FluidFramework\packages\utils\tool-utils\dist\odspTokenManager.js:70:27)
    at async OdspTokenManager.getTokens (E:\FluidFramework\packages\utils\tool-utils\dist\odspTokenManager.js:84:37)
    at async Object.resolveWrapper (E:\FluidFramework\packages\tools\fetch-tool\dist\fluidFetchSharePoint.js:20:24)

rc.tokens is undefined in odspTokensCache.get()

Using --forceTokenReauth fixed the problem.

### PR DESCRIPTION
**Pull request by jatgarg**
Fixes: https://github.com/microsoft/FluidFramework/issues/5309

### CODE REVIEW

File: packages/tools/fetch-tool/src/fluidFetchSharePoint.ts [hunk 1]
```diff
@@ -61,7 +61,8 @@ export async function resolveWrapper<T>(
             // Re-auth
             return resolveWrapper<T>(callback, server, clientConfig, true, forToken);
         }
-        return Promise.reject(new Error(`Fail to connect to ODSP server\nError Response:\n${e}`));
+        e.message = `Fail to connect to ODSP server\nError Response:\n${e.message}`;
+        return Promise.reject(e);
```
Comment (markfields) [inline packages/tools/fetch-tool/src/fluidFetchSharePoint.ts:65]: Couple nits - I don't like the existing "Error Response" term, maybe just drop that line. It may not be an error about the server response.  And just use `throw` not `return Promise.reject`.

**Review by markfields — APPROVED** [review]
🎂 feel free to ignore my nit-picking and merge as-is :)

File: packages/tools/fetch-tool/src/fluidFetchSharePoint.ts (hunk 1 above)
Comment (jatgarg) [reply packages/tools/fetch-tool/src/fluidFetchSharePoint.ts]: Removed Promsie.reject and used throw. Also removed the word Response.

File: packages/tools/fetch-tool/src/fluidFetchSharePoint.ts [hunk 2]
```diff
@@ -61,7 +61,8 @@ export async function resolveWrapper<T>(
             // Re-auth
             return resolveWrapper<T>(callback, server, clientConfig, true, forToken);
         }
-        return Promise.reject(new Error(`Fail to connect to ODSP server\nError Response:\n${e}`));
+        e.message = `Fail to connect to ODSP server\nError:\n${e.message}`;
```
Comment (vladsud) [inline packages/tools/fetch-tool/src/fluidFetchSharePoint.ts:64]: This code would be only valid if you know entity of the object. It may not be Error object.
