### PR TITLE
Account for gaps in the LocalReference array when packing segments

### LINKED ISSUE #9564: Intervals appear to change position after typing and syncing
### To Reproduce
In Scriptor, the repro looks like this:

1. In client 1, type "abcdef".
2. Add an interval at {2,2}.
3. Go to offset 0 and type "abcdef".
4. Add an interval at {6,6}.
5. After syncing, client 1 correctly shows the text "abcdefabcdef" and intervals at {8,8} and {6,6}.
6. But client 2 shows intervals at {7,7} and {6,6}.

Note that the issue seems to be timing-dependent. Hitting breakpoints during typing or creating intervals hides the bug.

### PR DESCRIPTION
**Pull request by pleath**
When Zamboni combines TextSegment's, it needs to update LocalReference's that refer to the segments. It wasn't doing this correctly in the case where, say, a reference is found at position 0, then some number of segments without references were appended, then a segment containing a reference was appended. The text corresponding to the segments without references wasn't accounted in the final segment. A gap needs to be introduced in the LocalReference array to make the references correct.

### CODE REVIEW

File: packages/dds/merge-tree/src/localReference.ts [hunk 1]
```diff
@@ -132,6 +132,10 @@ export class LocalReferenceCollection {
         if (seg2.localRefs && !seg2.localRefs.empty) {
             if (!seg1.localRefs) {
                 seg1.localRefs = new LocalReferenceCollection(seg1);
+            } else if (seg1.cachedLength > seg1.localRefs.refsByOffset.length) {
```
Comment (anthony-murphy) [inline packages/dds/merge-tree/src/localReference.ts:135]: the goal was to always have refsByOffset.length === cachedLength. I see how we are diverging, but i'm a bit worried about late binding the fixup here, as there are a lot of places, we enumerate refsByOffset.length.

Comment (pleath) [reply packages/dds/merge-tree/src/localReference.ts:135]: We could instead bump the length every time we append a segment with no references to a segment that already has a non-empty LocalReferenceCollection.

Comment (anthony-murphy) [reply packages/dds/merge-tree/src/localReference.ts:135]:
```
    public static append(seg1: ISegment, seg2: ISegment) {
        if (seg2.localRefs && !seg2.localRefs.empty) {
            if (!seg1.localRefs) {
                seg1.localRefs = new LocalReferenceCollection(seg1);
            } 
            seg1.localRefs.append(seg2.localRefs);
        }else{
                if(seg1.localRefe){
                        seg1.refsByOffset.length += seg2.cachedLength
                }
        }
    }
```

Comment (anthony-murphy) [reply packages/dds/merge-tree/src/localReference.ts:135]: i would even be ok adding an assert in the condition before we increment that `seg1.refsByOffset.length === seg1.cachedLength`

**Review by anthony-murphy — APPROVED** [review]
